#!/usr/bin/env sh
# ==============================================================================
# تشغيل تحقّق المرحلة 6 كاملاً من نسخة نظيفة من المستودع.
# لا يعتمد على أي ملفّ موجود مسبقاً في /tmp — كل مصدر تنفيذي داخل المستودع،
# و/tmp تُستعمل لمخرجات التشغيل المؤقّتة فقط. يعمل من أي مجلّد عمل.
#
#   sh tests/phase6/run_all.sh            # كل شيء عدا المتصفّح الحقيقي
#   sh tests/phase6/run_all.sh --browser  # مع Chromium عبر Playwright
# ==============================================================================
set -e
HERE=$(cd "$(dirname "$0")" && pwd)
ROOT=$(cd "$HERE/../.." && pwd)
cd "$ROOT"
FAIL=0
step() { printf '\n=== %s ===\n' "$1"; }
guard() { if [ "$1" -ne 0 ]; then FAIL=1; fi }

step "0 · Python syntax and imports"
python3 -m py_compile acs_*.py && echo "py_compile: OK"
python3 - <<'PY'
import importlib
mods = ["acs_arch", "acs_struct", "acs_mep", "acs_fls", "acs_coord", "acs_visual",
        "acs_runtime", "acs_authoring", "acs_workspace"]
for m in mods:
    importlib.import_module(m)
print("imports: OK (%d modules)" % len(mods))
PY
guard $?

step "1 · regenerate every browser layer from the canonical specifications"
python3 "$ROOT/tools/build_runtime_browser.py"; guard $?
python3 "$ROOT/tools/build_authoring_browser.py"; guard $?
python3 "$ROOT/tools/build_workspace_ui.py"; guard $?

step "2 · the generated blocks are idempotent (running twice changes nothing)"
python3 "$ROOT/tools/build_workspace_ui.py" >/dev/null
python3 - <<'PY'
# بعد F-09 صارت public/index.html قشرة: العلامة فيها، والشيفرة في وحدات
# public/app/، والأنماط في public/app/styles/app.css. التسليم هو الثلاثة معاً،
# فالعدّ يجري عليه كلّه — لا على الصفحة وحدها.
import os
import sys
sys.path.insert(0, os.path.join(os.getcwd(), 'tools'))
import app_source as A
page = A.shell() + '\n' + A.app_text() + '\n' + A.css_text()
marks = [
    '/* ===== ACS WORKSPACE UI (generated by tools/build_workspace_ui.py) ===== */',
    '/* ===== END ACS WORKSPACE UI ===== */',
    '<!-- ===== ACS WORKSPACE DOM (generated) ===== -->',
    '<!-- ===== END ACS WORKSPACE DOM ===== -->',
    '/* ===== ACS WORKSPACE STYLES (generated) ===== */',
    '/* ===== END ACS WORKSPACE STYLES ===== */',
]
bad = [m for m in marks if page.count(m) != 1]
if bad:
    raise SystemExit('duplicated or missing generated marker: %s' % bad)
print('generated blocks: exactly one of each (%d markers)' % len(marks))
# وأشدّ من العدّ: كل كتلة شيفرة مولَّدة يجب أن تحملها وحدة واحدة بعينها،
# وأن تكون تلك الوحدة مستوردة فعلاً من public/app/main.js — فلا تمرّ كتلة
# صحيحة الوسم لكنها في ملفّ يتيم لا يُحمَّل.
_imported = set(A.order())
_mods = A.modules()
for _m in [m for m in marks if m.startswith('/*') and 'STYLES' not in m]:
    _owners = [f for f in _mods if _mods[f].count(_m) == 1]
    if len(_owners) != 1 or _owners[0] not in _imported:
        raise SystemExit('generated block is not carried by exactly one module '
                         'imported by public/app/main.js: %r -> %s' % (_m, _owners))
print('every generated code block is carried by one imported module')
PY
guard $?

step "3 · workspace contract, state boundaries and view models"
node "$ROOT/tests/lib/run.js" "$HERE/test_workspace.js"; guard $?

step "4 · the complete product workflow through the public API"
node "$ROOT/tests/lib/run.js" "$HERE/test_workflow.js"; guard $?

step "5 · the real interface in a real DOM (declares NOT VERIFIED without one)"
node "$ROOT/tests/lib/run.js" "$HERE/test_dom.js"; guard $?

step "6 · workspace security: malicious names, labels, imports, references, assistant"
node "$ROOT/tests/lib/run.js" "$HERE/test_security.js"; guard $?

step "7 · Python <-> JavaScript workspace parity"
node "$HERE/test_parity.js"; guard $?

step "8 · backend and configuration security"
python3 "$ROOT/tests/security/test_security.py"; guard $?

step "9 · Phase 5 regression (authoring must not weaken)"
sh "$ROOT/tests/phase5/run_all.sh" "$1"; guard $?

step "10 · deterministic workspace benchmarks (no FPS, no GPU, no pixel claim)"
node "$ROOT/tests/lib/run.js" "$HERE/benchmark_workspace.js"
python3 "$HERE/benchmark_workspace.py"

if [ "$1" = "--browser" ]; then
  step "11 · real Chromium: the interface, security and responsive layout"
  node "$ROOT/tests/phase3/lib/run_browser.js" "$HERE/test_dom.js"; guard $?
  node "$ROOT/tests/phase3/lib/run_browser.js" "$HERE/test_security.js"; guard $?
  node "$HERE/test_responsive.js"; guard $?
  step "12 · the complete product walkthrough in real Chromium"
  node "$HERE/walkthrough.js"; guard $?
else
  printf '\n=== 11 · real Chromium ===\nSKIPPED (pass --browser to run). '
  printf 'Without it: NOT VERIFIED — CHROMIUM ENVIRONMENT UNAVAILABLE\n'
fi

printf '\n==============================================\n'
if [ "$FAIL" -eq 0 ]; then
  echo "PHASE 6 VERIFICATION: all executed suites passed"
else
  echo "PHASE 6 VERIFICATION: FAILURES PRESENT"
  exit 1
fi
