import http from 'node:http';
import {readFile} from 'node:fs/promises';
import {extname,normalize} from 'node:path';
const PORT=Number(process.env.PORT||10000);
const ROOT=new URL('./public/',import.meta.url);
const SUPA=(process.env.JANA_SUPABASE_URL||'').replace(/\/$/,'');
const KEY=process.env.JANA_SUPABASE_KEY||'';
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.json':'application/json; charset=utf-8','.webmanifest':'application/manifest+json'};
const send=(res,status,body)=>{res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'});res.end(JSON.stringify(body))};
async function readJson(req){const chunks=[];for await(const c of req)chunks.push(c);if(!chunks.length)return{};return JSON.parse(Buffer.concat(chunks).toString('utf8'))}
async function rpc(name,args={}){const r=await fetch(`${SUPA}/rest/v1/rpc/${name}`,{method:'POST',headers:{apikey:KEY,authorization:`Bearer ${KEY}`,'content-type':'application/json'},body:JSON.stringify(args)});const t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok){const e=new Error(d?.message||`db_${r.status}`);e.status=r.status;throw e}return d}
const tok=req=>{const h=req.headers.authorization||'';return h.startsWith('Bearer ')?h.slice(7).trim():''};
function mapErr(e){const m=String(e?.message||'request_failed');const known=['invalid_email','invalid_name','weak_password','email_exists','invalid_credentials','unauthorized','invalid_address','invalid_coordinates','invalid_cart','slot_unavailable','zone_unavailable','outside_zone','below_minimum','insufficient_stock','insufficient_lot_stock','quote_not_found','quote_expired'];const code=known.includes(m)?m:'request_failed';const status=code==='unauthorized'||code==='invalid_credentials'?401:code==='email_exists'?409:['slot_unavailable','insufficient_stock','insufficient_lot_stock','quote_expired'].includes(code)?409:code==='request_failed'?500:400;return{code,status}}
async function api(req,res,u){try{const p=u.pathname.replace(/^\/api/,'')||'/';if(req.method==='GET'&&p==='/health')return send(res,200,{ok:true,service:'jana-live-api',version:1});if(req.method==='GET'&&p==='/config')return send(res,200,{brand:'جَنى',currency:'SAR',timezone:'Asia/Riyadh',cod:true});if(req.method==='GET'&&p==='/catalog')return send(res,200,await rpc('jana_public_catalog'));if(req.method==='GET'&&p==='/slots')return send(res,200,await rpc('jana_public_slots'));if(req.method==='POST'&&p==='/auth/register'){const b=await readJson(req);return send(res,201,await rpc('jana_register',{p_email:b.email,p_name:b.name,p_password:b.password,p_phone:b.phone||null}))}if(req.method==='POST'&&p==='/auth/login'){const b=await readJson(req);return send(res,200,await rpc('jana_login',{p_email:b.email,p_password:b.password}))}if(req.method==='GET'&&p==='/me')return send(res,200,await rpc('jana_me',{p_token:tok(req)}));if(req.method==='GET'&&p==='/addresses')return send(res,200,await rpc('jana_list_addresses',{p_token:tok(req)}));if(req.method==='POST'&&p==='/addresses'){const b=await readJson(req);return send(res,201,await rpc('jana_add_address',{p_token:tok(req),p_label:b.label||'المنزل',p_details:b.details,p_latitude:String(b.latitude||''),p_longitude:String(b.longitude||''),p_recipient_name:b.recipient_name||'',p_recipient_phone:b.recipient_phone||'',p_default:b.is_default!==false}))}if(req.method==='POST'&&p==='/quotes'){const b=await readJson(req);return send(res,201,await rpc('jana_create_quote',{p_token:tok(req),p_slot_id:b.slot_id,p_address_id:b.address_id,p_items:b.items}))}const m=p.match(/^\/quotes\/([^/]+)\/confirm$/);if(req.method==='POST'&&m)return send(res,201,await rpc('jana_confirm_order',{p_token:tok(req),p_quote_id:m[1]}));if(req.method==='GET'&&p==='/orders')return send(res,200,await rpc('jana_my_orders',{p_token:tok(req)}));return send(res,404,{error:'not_found'})}catch(e){console.error('api',e?.message||e);const x=mapErr(e);return send(res,x.status,{error:x.code})}}
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost');if(u.pathname==='/health'||u.pathname==='/ready')return send(res,200,{ok:true,service:'jana-live'});if(u.pathname.startsWith('/api/'))return api(req,res,u);let path=u.pathname==='/'?'index.html':u.pathname.replace(/^\//,'');path=normalize(path).replace(/^\.\.(\/|\\|$)/,'');const data=await readFile(new URL(path,ROOT));res.writeHead(200,{'content-type':mime[extname(path)]||'application/octet-stream','x-content-type-options':'nosniff','referrer-policy':'strict-origin-when-cross-origin','content-security-policy':"default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; frame-ancestors 'none'; base-uri 'self'; object-src 'none'"});res.end(data)}catch(e){console.error('gateway',e?.message||e);send(res,404,{error:'not_found'})}});
server.listen(PORT,'0.0.0.0',async()=>{console.log('JANA live on',PORT);try{const cat=await rpc('jana_public_catalog');const slots=await rpc('jana_public_slots');console.log('JANA_RPC_SELFTEST',JSON.stringify({catalog_count:Array.isArray(cat)?cat.length:null,slot_count:Array.isArray(slots)?slots.length:null,supabase:Boolean(SUPA&&KEY)}))}catch(e){console.error('JANA_RPC_SELFTEST_FAIL',e?.message||e)}});
