#!/usr/bin/env sh
# ==============================================================================
# تشغيل تحقّق المرحلة 9 كاملاً من نسخة نظيفة من المستودع.
#   sh tests/phase9/run_all.sh            # كل شيء عدا المتصفّح الحقيقي
#   sh tests/phase9/run_all.sh --browser  # مع Chromium عبر Playwright
# ==============================================================================
set -e
HERE=$(cd "$(dirname "$0")" && pwd)
ROOT=$(cd "$HERE/../.." && pwd)
cd "$ROOT"
FAIL=0
step() { printf '\n=== %s ===\n' "$1"; }
guard() { if [ "$1" -ne 0 ]; then FAIL=1; fi }

step "0 · Python syntax and imports"
python3 -m py_compile acs_*.py && echo "py_compile: OK"
python3 - <<'PY'
import importlib
mods = ["acs_visual", "acs_runtime", "acs_authoring", "acs_workspace",
        "acs_render", "acs_bim", "acs_docs"]
for m in mods:
    importlib.import_module(m)
print("imports: OK (%d modules)" % len(mods))
PY
guard $?

step "1 · regenerate every browser layer from the canonical specifications"
python3 "$ROOT/tools/build_runtime_browser.py"; guard $?
python3 "$ROOT/tools/build_authoring_browser.py"; guard $?
python3 "$ROOT/tools/build_workspace_ui.py"; guard $?
python3 "$ROOT/tools/build_render_browser.py"; guard $?
python3 "$ROOT/tools/build_bim_browser.py"; guard $?
python3 "$ROOT/tools/build_docs_browser.py"; guard $?

step "2 · the generated blocks are idempotent"
python3 "$ROOT/tools/build_docs_browser.py" >/dev/null
python3 - <<'PY'
page = open('public/index.html', encoding='utf-8').read()
marks = [
    '/* ===== ACS DOCUMENTATION (generated by tools/build_docs_browser.py) ===== */',
    '/* ===== END ACS DOCUMENTATION ===== */',
    '<!-- ===== ACS DOCS DOM (generated) ===== -->',
    '<!-- ===== END ACS DOCS DOM ===== -->',
    '/* ===== ACS DOCS STYLES (generated) ===== */',
    '/* ===== END ACS DOCS STYLES ===== */',
]
bad = [m for m in marks if page.count(m) != 1]
if bad:
    raise SystemExit('duplicated or missing generated marker: %s' % bad)
print('generated documentation blocks: exactly one of each (%d markers)' % len(marks))
PY
guard $?

step "3 · documentation contract and tests A to N"
python3 "$HERE/test_docs.py"; guard $?

step "4 · Python <-> JavaScript documentation parity"
node "$HERE/test_parity.js"; guard $?

step "5 · the documentation panel (Node scope)"
node "$ROOT/tests/lib/run.js" "$HERE/test_docs_browser.js"; guard $?

step "6 · backend and configuration security, including malformed documentation"
python3 "$ROOT/tests/security/test_security.py"; guard $?

step "7 · deployment closure for every canonical file"
sh "$ROOT/tests/deploy/verify_deploy.sh"; guard $?

step "8 · Phase 8 regression (BIM, render, workspace and every earlier phase)"
sh "$ROOT/tests/phase8/run_all.sh" "$1"; guard $?

step "9 · deterministic documentation benchmarks (no FPS, no GPU)"
python3 "$HERE/benchmark_docs.py"

step "10 · produce the real documentation artifacts and their manifest"
python3 "$HERE/make_outputs.py"; guard $?

if [ "$1" = "--browser" ]; then
  step "11 · real Chromium: the documentation workspace end to end"
  node "$ROOT/tests/phase3/lib/run_browser.js" "$HERE/test_docs_browser.js"; guard $?
else
  printf '\n=== 11 · real Chromium ===\nSKIPPED (pass --browser to run). '
  printf 'Without it: NOT VERIFIED — CHROMIUM ENVIRONMENT UNAVAILABLE\n'
fi

printf '\n==============================================\n'
if [ "$FAIL" -eq 0 ]; then
  echo "PHASE 9 VERIFICATION: all executed suites passed"
else
  echo "PHASE 9 VERIFICATION: FAILURES PRESENT"
  exit 1
fi
