#!/usr/bin/env sh
# ==============================================================================
# تشغيل تحقّق المرحلة 9.1 كاملاً من نسخة نظيفة من المستودع.
#   sh tests/phase9_1/run_all.sh            # كل شيء عدا المتصفّح الحقيقي
#   sh tests/phase9_1/run_all.sh --browser  # مع Chromium عبر Playwright
# ==============================================================================
set -e
HERE=$(cd "$(dirname "$0")" && pwd)
ROOT=$(cd "$HERE/../.." && pwd)
cd "$ROOT"
FAIL=0
step() { printf '\n=== %s ===\n' "$1"; }
guard() { if [ "$1" -ne 0 ]; then FAIL=1; fi }

step "0 · Python syntax and imports"
python3 -m py_compile acs_*.py && echo "py_compile: OK"
python3 - <<'PY'
import importlib
mods = ["acs_visual", "acs_runtime", "acs_authoring", "acs_workspace",
        "acs_render", "acs_bim", "acs_docs", "acs_pbr"]
for m in mods:
    importlib.import_module(m)
print("imports: OK (%d modules)" % len(mods))
PY
guard $?

step "1 · regenerate the visual quality browser layer from the specification"
python3 "$ROOT/tools/build_pbr_browser.py"; guard $?

step "2 · the generated quality blocks are idempotent"
python3 "$ROOT/tools/build_pbr_browser.py" >/dev/null
python3 - <<'PY'
# بعد F-09 صارت public/index.html قشرة: العلامة فيها، والشيفرة في وحدات
# public/app/، والأنماط في public/app/styles/app.css. التسليم هو الثلاثة معاً،
# فالعدّ يجري عليه كلّه — لا على الصفحة وحدها.
import os
import sys
sys.path.insert(0, os.path.join(os.getcwd(), 'tools'))
import app_source as A
page = A.shell() + '\n' + A.app_text() + '\n' + A.css_text()
marks = [
    '/* ===== ACS PBR QUALITY (generated by tools/build_pbr_browser.py) ===== */',
    '/* ===== END ACS PBR QUALITY ===== */',
    '<!-- ===== ACS PBR DOM (generated) ===== -->',
    '<!-- ===== END ACS PBR DOM ===== -->',
    '/* ===== ACS PBR STYLES (generated) ===== */',
    '/* ===== END ACS PBR STYLES ===== */',
    '/* ===== ACS PBR BRIDGE (module scope) ===== */',
    '/* ===== END ACS PBR BRIDGE ===== */',
]
bad = [m for m in marks if page.count(m) != 1]
if bad:
    raise SystemExit('duplicated or missing generated marker: %s' % bad)
if page.count('window.__ACS_PQ__&&window.__ACS_PQ__.composer') != 1:
    raise SystemExit('render loop dispatcher is not exactly once')
if 'else{renderer.render(scene,camera);}' not in page:
    raise SystemExit('render loop fallback branch is missing')
print('generated quality blocks: exactly one of each (%d markers), '
      'dispatcher single, fallback present' % len(marks))
# وأشدّ من العدّ: كل كتلة شيفرة مولَّدة يجب أن تحملها وحدة واحدة بعينها،
# وأن تكون تلك الوحدة مستوردة فعلاً من public/app/main.js — فلا تمرّ كتلة
# صحيحة الوسم لكنها في ملفّ يتيم لا يُحمَّل.
_imported = set(A.order())
_mods = A.modules()
for _m in [m for m in marks if m.startswith('/*') and 'STYLES' not in m]:
    _owners = [f for f in _mods if _mods[f].count(_m) == 1]
    if len(_owners) != 1 or _owners[0] not in _imported:
        raise SystemExit('generated block is not carried by exactly one module '
                         'imported by public/app/main.js: %r -> %s' % (_m, _owners))
print('every generated code block is carried by one imported module')
PY
guard $?

step "3 · the visual quality contract (materials, lighting, shadows, cameras, immutability)"
python3 "$HERE/test_pbr.py"; guard $?

step "4 · Python <-> JavaScript quality-layer parity"
node "$HERE/test_parity.js"; guard $?

step "5 · the quality panel (Node scope)"
node "$ROOT/tests/lib/run.js" "$HERE/test_pbr_browser.js"; guard $?

step "6 · backend and configuration security, including the presentation layer"
python3 "$ROOT/tests/security/test_security.py"; guard $?

step "7 · deployment closure for every canonical file"
sh "$ROOT/tests/deploy/verify_deploy.sh"; guard $?

step "8 · Phase 9 regression (documentation, BIM and every earlier phase)"
sh "$ROOT/tests/phase9/run_all.sh" "$1"; guard $?

step "9 · deterministic quality-layer benchmark (no FPS, no GPU, no WebGL)"
python3 "$HERE/benchmark_pbr.py"

step "10 · §25 reference captures (needs a networked machine with vendored Three.js)"
node "$HERE/capture_reference.js" || {
  rc=$?
  if [ "$rc" -eq 2 ]; then
    echo "reference captures: NOT VERIFIED — EXTERNAL ENVIRONMENT REQUIRED (exit 2, not a test failure)"
  else
    guard "$rc"
  fi
}

if [ "$1" = "--browser" ]; then
  step "11 · real Chromium: the quality panel and shipped page end to end"
  node "$ROOT/tests/phase3/lib/run_browser.js" "$HERE/test_pbr_browser.js"; guard $?
else
  printf '\n=== 11 · real Chromium ===\nSKIPPED (pass --browser to run). '
  printf 'Without it: NOT VERIFIED — CHROMIUM ENVIRONMENT UNAVAILABLE\n'
fi

printf '\n==============================================\n'
if [ "$FAIL" -eq 0 ]; then
  echo "PHASE 9.1 VERIFICATION: all executed suites passed"
else
  echo "PHASE 9.1 VERIFICATION: FAILURES PRESENT"
  exit 1
fi
