import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { understand, briefIssues, generate, validate, totals, clone, propose, resolvePreview, commitPreview, parseCommand, createHistory, pushHistory, current, exportEnvelope, importEnvelope, assertModel, assertHistory, parseDXF, exportDXF, uid, designMetrics, createAlternatives, requirementStatus, impactSummary, touchesGardenEdge, distanceToEntry } from '../shared/model.js';
import { planSVG, escapeHTML, sceneBoxes, exportOBJ } from '../shared/geometry.js';
const fixture = () => generate(understand('أرض 20×25 ثلاثة أدوار خمس غرف نوم الشارع جنوب'));
const errorIssues = m => validate(m).filter(i => i.status === 'error');
test('Arabic and Persian numerals, spelled-out floors, explicit sources', () => { const b = understand('أرض ٢٠×۲۵ ثلاثة أدوار خمس غرف نوم الشارع شمال'); assert.equal(b.width, 20); assert.equal(b.depth, 25); assert.equal(b.floors, 3); assert.equal(b.bedrooms, 5); assert.equal(b.street, 'شمال'); assert.equal(b.sources.width, 'requested'); });
test('Unknown decisions remain marked as assumptions; original text preserved', () => { const text = 'منزل عائلي هادئ'; const b = understand(text); assert.equal(b.prompt, text); assert.equal(b.sources.width, 'assumed'); assert.equal(b.sources.street, 'assumed'); });
test('Requested zero floors is not silently changed into two floors', () => { const b = understand('0 أدوار'); assert.equal(b.floors, 0); assert.throws(() => generate(b)); });
test('Elevator and pool requests produce explicit conceptual elements and remain engineering-unchecked', () => { const b = understand('فيلا ثلاثة أدوار مع مصعد ومسبح'); assert.equal(b.elevator, true); assert.equal(b.pool, true); const m = generate(b); assert.equal(m.levels.every(l => l.rooms.some(r => r.kind === 'elevator')), true); assert.equal(m.site.features.some(f => f.type === 'pool'), true); assert.deepEqual(errorIssues(m), []); for (const r of m.requirements.filter(r => r.type === 'feature')) { const rs = requirementStatus(m, r); assert.equal(rs.measurable, true); assert.equal(rs.satisfied, true); } assert.equal(validate(m).find(i => i.id === 'elevator-design').status, 'unchecked'); assert.equal(validate(m).find(i => i.id === 'pool-design').status, 'unchecked'); });
test('Negative pool intent is respected', () => { const b = understand('شاليه بدون مسبح وبدون مصعد'); assert.equal(b.pool, false); assert.equal(b.elevator, false); });
test('Out-of-bounds generation rejects instead of clamping', () => { const b = understand('أرض 5×9 عشرة أدوار'); assert.throws(() => generate(b)); });
for (let floors = 1; floors <= 6; floors++)
    for (let bedrooms = 1; bedrooms <= 12; bedrooms++)
        for (const street of ['جنوب', 'شمال', 'شرق', 'غرب'])
            test(`generation f${floors} b${bedrooms} street ${street}`, () => { const m = generate(understand(`أرض 20×25 ${floors} أدوار ${bedrooms} غرف نوم الشارع ${street}`)); assert.equal(m.levels.length, floors); assert.equal(totals(m).bedrooms, bedrooms); assert.deepEqual(errorIssues(m), []); assert.equal(m.site.width, 20); assert.equal(m.site.depth, 25); const door = m.levels[0].rooms.find(r => r.kind === 'hall').doors[0]; assert.equal(door.side, { جنوب: 'south', شمال: 'north', شرق: 'east', غرب: 'west' }[street]); });
for (const [w, d] of [[12, 15], [12, 100], [80, 15], [80, 100], [16.5, 21.75], [23.3, 31.7]])
    for (const street of ['جنوب', 'شرق'])
        test(`dimension boundary ${w}x${d} ${street}`, () => { const m = generate(understand(`أرض ${w}×${d} ثلاثة أدوار خمس غرف نوم الشارع ${street}`)); assert.deepEqual(errorIssues(m), []); assert.equal(m.site.width, w); assert.equal(m.site.depth, d); });
test('Floor-area calculation is exact for the rectangular conceptual footprint', () => { const m = fixture(); assert.equal(totals(m).floorArea, 912); assert.equal(totals(m).footprint, 304); });
test('Preview is immutable, cancel has no side effects, commit changes intended room', () => { const m = fixture(), before = JSON.stringify(m), id = m.levels[0].rooms[0].id, p = propose(m, { type: 'rename', roomId: id, name: 'مجلس العائلة' }); assert.equal(JSON.stringify(m), before); assert.equal(p.changes.length, 1); assert.equal(p.blockers.length, 0); const next = commitPreview(m, p); assert.equal(next.levels[0].rooms[0].name, 'مجلس العائلة'); assert.equal(JSON.stringify(m), before); });
test('A stale preview cannot overwrite a newer version', () => { const m = fixture(), id = m.levels[0].rooms[0].id, p = propose(m, { type: 'rename', roomId: id, name: 'نسخة أخرى' }); m.title = 'new version'; assert.throws(() => commitPreview(m, p), /تغيّر/); });
test('New overlap is blocked at preview and commit', () => { const m = fixture(), r = m.levels[0].rooms[0], p = propose(m, { type: 'resize', roomId: r.id, w: r.w + 1 }); assert.ok(p.blockers.length); assert.throws(() => commitPreview(m, p)); });
test('Locked stair refuses geometry changes but allows harmless name edit', () => { const m = fixture(), r = m.levels[0].rooms.find(r => r.kind === 'stairs'); assert.throws(() => propose(m, { type: 'move', roomId: r.id, x: r.x + 1 }), /مثبّت/); assert.doesNotThrow(() => propose(m, { type: 'rename', roomId: r.id, name: 'درج ثابت' })); });
test('Blocked resize can produce an explicit safe reflow that preserves locked stair geometry', () => { const m=fixture(), bath=m.levels[0].rooms.find(r=>r.kind==='bath'), stair=m.levels[0].rooms.find(r=>r.kind==='stairs'), service=m.levels[0].rooms.find(r=>r.kind==='service'), stairBefore=JSON.stringify({x:stair.x,y:stair.y,w:stair.w,d:stair.d}), serviceArea=service.w*service.d; const p=propose(m,{type:'resize',roomId:bath.id,d:bath.d+1}); assert.ok(p.blockers.some(i=>i.id.startsWith('overlap-'))); const solved=resolvePreview(m,p); assert.ok(solved); assert.equal(solved.blockers.length,0); assert.equal(JSON.stringify({x:solved.candidate.levels[0].rooms.find(r=>r.id===stair.id).x,y:solved.candidate.levels[0].rooms.find(r=>r.id===stair.id).y,w:solved.candidate.levels[0].rooms.find(r=>r.id===stair.id).w,d:solved.candidate.levels[0].rooms.find(r=>r.id===stair.id).d}),stairBefore); const newBath=solved.candidate.levels[0].rooms.find(r=>r.id===bath.id), newService=solved.candidate.levels[0].rooms.find(r=>r.id===service.id); assert.equal(newBath.d,bath.d+1); assert.ok(newService.w*newService.d < serviceArea); assert.ok(solved.resolutionNotes.some(n=>n.includes('دون تحريك'))); assert.doesNotThrow(()=>commitPreview(m,solved)); });
test('Commit revalidates even if a preview object was tampered with', () => { const m = fixture(), r = m.levels[0].rooms[0], p = propose(m, { type: 'rename', roomId: r.id, name: 'س' }); p.candidate.levels[0].rooms[0].w = 100; p.blockers = []; assert.throws(() => commitPreview(m, p)); });
test('Disconnected room receives a focused issue', () => { const m = fixture(), r = m.levels[0].rooms[0]; r.doors = []; assert.ok(errorIssues(m).some(i => i.id === 'access-' + r.id)); });
test('Door width cannot overflow its host wall', () => { const m = fixture(), r = m.levels[0].rooms[0], p = propose(m, { type: 'door', roomId: r.id, side: 'east', width: 5, offset: .05 }); assert.ok(p.blockers.some(i => i.id.startsWith('door-fit'))); });
test('Moving stair breaks vertical connectivity and stays visible', () => { const m = fixture(), r = m.levels[1].rooms.find(r => r.kind === 'stairs'); r.x += .5; assert.ok(errorIssues(m).some(i => i.id === 'stair-' + r.id)); });
test('Swapping rooms keeps counts, IDs and comments associated with the room', () => { const m = fixture(), a = m.levels[0].rooms[0], b = m.levels[0].rooms[2]; m.comments.push({ id: uid(), roomId: a.id, text: 'ملاحظة', author: 'المراجع', at: new Date().toISOString(), resolved: false }); const p = propose(m, { type: 'swap', roomId: a.id, targetId: b.id }); assert.equal(p.blockers.length, 0); const n = commitPreview(m, p); assert.equal(n.comments[0].roomId, a.id); assert.equal(totals(n).bedrooms, 5); assert.equal(p.changes.length, 2); });
test('All geometry and numeric inputs must be finite', () => { for (const n of [NaN, Infinity, -Infinity]) {
    const m = fixture();
    m.levels[0].rooms[0].w = n;
    assert.throws(() => assertModel(m));
} });
test('Duplicate entity IDs are rejected', () => { const m = fixture(); m.levels[0].rooms[1].id = m.levels[0].rooms[0].id; assert.throws(() => assertModel(m)); });
test('Invalid kind and forged unknown document versions are rejected', () => { const m = fixture(); m.levels[0].rooms[0].kind = '__proto__'; assert.throws(() => assertModel(m)); m.schemaVersion = 9; assert.throws(() => assertModel(m)); });
test('Append-only revision list preserves branches after undo then edit', () => { const m = fixture(), h = createHistory(m), a = clone(m); a.title = 'A'; const h1 = pushHistory(h, a, 'A'), b = clone(a); b.title = 'B'; const h2 = pushHistory(h1, b, 'B'); h2.cursor = 0; const c = clone(m); c.title = 'C'; const h3 = pushHistory(h2, c, 'C'); assert.equal(h3.revisions.length, 4); assert.equal(h3.revisions[2].model.title, 'B'); assert.equal(h3.revisions[3].parentIndex, 0); assert.equal(h.revisions.length, 1); });
test('Project export/import exactly restores all data', () => { const h = createHistory(fixture()); assert.deepEqual(importEnvelope(JSON.stringify(exportEnvelope(h))), h); });
test('Import rejects excessive size and malformed history', () => { assert.throws(() => importEnvelope('x'.repeat(8000001))); const h = createHistory(fixture()); h.cursor = 3; assert.throws(() => assertHistory(h)); });
test('Deterministic parser works with Arabic dimensions and refuses unknown prose', () => { const m = fixture(), id = m.levels[0].rooms[0].id; assert.equal(parseCommand('العرض ٥', m, id).w, 5); assert.equal(parseCommand('انقل 1 متر شمال', m, id).y, 4); assert.throws(() => parseCommand('حوله لقصر فاخر', m, id), /غير واضح/); });
test('Selected scope is required when a natural-language target is ambiguous', () => { const m = fixture(); assert.throws(() => parseCommand('غير العرض 5', m, null)); });
test('Display compilation and every export never mutate canonical data', () => { const m = fixture(), before = JSON.stringify(m); sceneBoxes(m, { all: true }); planSVG(m, 'l0'); exportDXF(m, 'l0'); exportOBJ(m); validate(m); assert.equal(JSON.stringify(m), before); });
test('2D measurement overlay is presentation-only and reports Euclidean metres', () => { const m=fixture(), before=JSON.stringify(m), svg=planSVG(m,'l0',{measurement:{active:true,a:{x:2,y:3},b:{x:5,y:7}}}); assert.ok(svg.includes('measure-overlay')); assert.ok(svg.includes('5 m')); assert.equal(JSON.stringify(m),before); });
test('SVG escapes hostile labels and uses no executable event handlers', () => { const m = fixture(); m.levels[0].rooms[0].name = '<img src=x onerror=alert(1)>'; const svg = planSVG(m, 'l0'); assert.ok(svg.includes('&lt;img')); assert.ok(!svg.includes('<img')); assert.ok(!svg.includes('<script')); assert.equal(escapeHTML('"&<>'), '&quot;&amp;&lt;&gt;'); });
test('DXF export yields real closed polylines and round-trips current world-metre geometry', () => { const m = fixture(), first=m.levels[0].rooms[0], text = exportDXF(m, 'l0'), lines = parseDXF(text); assert.equal(lines.length, m.levels[0].rooms.length * 4); const expected=[first.x,first.y,first.x+first.w,first.y].map(x=>Math.round(x*1000)/1000); assert.deepEqual(lines[0], expected); assert.deepEqual(parseDXF(text, .001)[0], expected.map(x=>Math.round(x*.001*1000)/1000)); });
test('Unsupported CAD data is explicitly rejected', () => { assert.throws(() => parseDXF('not a DXF file')); assert.throws(() => parseDXF('x'.repeat(2000001))); });
test('OBJ output contains actual vertices and faces with limitations stated', () => { const obj = exportOBJ(fixture()); assert.ok(obj.includes('\nv ')); assert.ok(obj.includes('\nf ')); assert.ok(obj.includes('DISPLAY assumptions')); });
test('Engineering and code checks remain UNCHECKED, never falsely pass', () => { const issues = validate(fixture()); assert.equal(issues.find(i => i.id === 'structure').status, 'unchecked'); assert.equal(issues.find(i => i.id === 'regulatory').status, 'unchecked'); });
test('Product generators cover office, warehouse, retail and eight-floor residential without geometry errors', () => { for (const q of ['مكاتب 30×40 ثمانية أدوار 20 مكتب الشارع شرق','مستودع 40×60 دور واحد الشارع جنوب','محل تجاري 24×36 دورين الشارع غرب','فيلا 24×32 ثمانية أدوار 16 غرف نوم الشارع شمال']) { const b=understand(q), m=generate(b); if (/ثمانية/.test(q)) assert.equal(b.floors,8); assert.deepEqual(errorIssues(m),[]); assert.doesNotThrow(()=>assertModel(m)); } });
test('Relational parser understands entry/garden and directional expansion with explicit amount', () => { const m=fixture(), maj=m.levels[0].rooms.find(r=>r.kind==='majlis'); assert.deepEqual(parseCommand('انقل المجلس قرب المدخل',m,maj.id),{type:'near',roomId:maj.id,target:'entry'}); assert.deepEqual(parseCommand('وسع المجلس 2 متر شمال',m,maj.id),{type:'expand',roomId:maj.id,amount:2,direction:'north'}); assert.equal(parseCommand('وسع المجلس متر باتجاه الحديقة',m,maj.id).direction,'garden'); });
test('Impact summary is deterministic and reports score/geometry changes without mutating source', () => { const m=fixture(), before=JSON.stringify(m), r=m.levels[0].rooms[0], p=propose(m,{type:'rename',roomId:r.id,name:'مجلس جديد'}), impact=impactSummary(m,p.candidate); assert.equal(JSON.stringify(m),before); assert.equal(impact.affectedIds.includes(r.id),true); assert.equal(Number.isFinite(impact.scoreDelta),true); assert.deepEqual(impact.beforeMetrics,designMetrics(m)); });
test('Four alternatives preserve locked geometry and all are valid conceptual models', () => { const m=fixture(), locked=m.levels[0].rooms.find(r=>r.kind==='stairs'), base=JSON.stringify({x:locked.x,y:locked.y,w:locked.w,d:locked.d}), alts=createAlternatives(m); assert.equal(alts.length,4); for(const a of alts){assert.doesNotThrow(()=>assertModel(a.model));assert.deepEqual(errorIssues(a.model),[]);const r=a.model.levels[0].rooms.find(x=>x.id===locked.id);assert.equal(JSON.stringify({x:r.x,y:r.y,w:r.w,d:r.d}),base);assert.ok(a.metrics.overall>=0&&a.metrics.overall<=100);} });
test('Validation distinguishes checked model facts from explicitly unchecked engineering disciplines', () => { const issues=validate(fixture()); assert.ok(issues.some(i=>i.status==='checked'&&i.category==='model-check')); assert.equal(issues.find(i=>i.id==='structure').status,'unchecked'); assert.equal(issues.find(i=>i.id==='regulatory').status,'unchecked'); });
test('Requested adjacency becomes a measurable requirement instead of disappearing into prompt text', () => { const m=generate(understand('فيلا 20×25 دورين 4 غرف نوم والمجلس قريب من المدخل الشارع جنوب')); const req=m.requirements.find(r=>r.type==='adjacency'&&r.value?.type==='near-entry'); assert.ok(req); const rs=requirementStatus(m,req); assert.equal(rs.measurable,true); assert.equal(typeof rs.satisfied,'boolean'); });
test('Bundled HTML script bytes exactly match its CSP hash', async () => { const html = await readFile(new URL('../dist/index.html', import.meta.url), 'utf8'), script = html.match(/<script>([\s\S]*?)<\/script>/)[1], hash = createHash('sha256').update(script).digest('base64'); assert.ok(html.includes(`sha256-${hash}`)); assert.equal(script, await readFile(new URL('../dist/app.bundle.js', import.meta.url), 'utf8')); });
test('Fractional floor counts are preserved for rejection, not truncated', () => { const b = understand('أرض 20×25 وعدد 3.5 أدوار'); assert.equal(b.floors, 3.5); assert.ok(briefIssues(b).length); });
test('Negative dimensions and room counts are never silently made positive', () => { const b = understand('أرض -20×25 و-3 غرف نوم'); assert.equal(b.width, -20); assert.equal(b.bedrooms, -3); assert.ok(briefIssues(b).length); });
test('Imported revision cannot point to itself or an invalid parent', () => { const h = createHistory(generate(understand('أرض 20×25'))); h.revisions[0].parentIndex = 0; assert.throws(() => assertHistory(h)); });
