#!/usr/bin/env sh
# ==============================================================================
# تشغيل تحقّق المرحلة 8 كاملاً من نسخة نظيفة من المستودع.
#   sh tests/phase8/run_all.sh            # كل شيء عدا المتصفّح الحقيقي
#   sh tests/phase8/run_all.sh --browser  # مع Chromium عبر Playwright
# ==============================================================================
set -e
HERE=$(cd "$(dirname "$0")" && pwd)
ROOT=$(cd "$HERE/../.." && pwd)
cd "$ROOT"
FAIL=0
step() { printf '\n=== %s ===\n' "$1"; }
guard() { if [ "$1" -ne 0 ]; then FAIL=1; fi }

step "0 · Python syntax and imports"
python3 -m py_compile acs_*.py && echo "py_compile: OK"
python3 - <<'PY'
import importlib
mods = ["acs_visual", "acs_runtime", "acs_authoring", "acs_workspace",
        "acs_render", "acs_bim"]
for m in mods:
    importlib.import_module(m)
print("imports: OK (%d modules)" % len(mods))
PY
guard $?

step "1 · regenerate every browser layer from the canonical specifications"
python3 "$ROOT/tools/build_runtime_browser.py"; guard $?
python3 "$ROOT/tools/build_authoring_browser.py"; guard $?
python3 "$ROOT/tools/build_workspace_ui.py"; guard $?
python3 "$ROOT/tools/build_render_browser.py"; guard $?
python3 "$ROOT/tools/build_bim_browser.py"; guard $?

step "2 · the generated blocks are idempotent"
python3 "$ROOT/tools/build_bim_browser.py" >/dev/null
python3 - <<'PY'
page = open('public/index.html', encoding='utf-8').read()
marks = [
    '/* ===== ACS BIM EXCHANGE (generated by tools/build_bim_browser.py) ===== */',
    '/* ===== END ACS BIM EXCHANGE ===== */',
    '<!-- ===== ACS BIM DOM (generated) ===== -->',
    '<!-- ===== END ACS BIM DOM ===== -->',
    '/* ===== ACS BIM STYLES (generated) ===== */',
    '/* ===== END ACS BIM STYLES ===== */',
]
bad = [m for m in marks if page.count(m) != 1]
if bad:
    raise SystemExit('duplicated or missing generated marker: %s' % bad)
print('generated BIM blocks: exactly one of each (%d markers)' % len(marks))
PY
guard $?

step "3 · regenerate the phase 8 fixtures from real IFC files"
python3 "$HERE/fixture_generator.py"; guard $?

step "4 · BIM contract, export, parse, staging, diff, proposals and commit"
python3 "$HERE/test_bim.py"; guard $?

step "5 · Python <-> JavaScript exchange parity"
node "$HERE/test_parity.js"; guard $?

step "6 · the BIM workspace panel (Node scope)"
node "$ROOT/tests/lib/run.js" "$HERE/test_bim_browser.js"; guard $?

step "7 · backend and configuration security, including malformed BIM payloads"
python3 "$ROOT/tests/security/test_security.py"; guard $?

step "8 · Phase 7 regression (render, workspace and every earlier phase)"
sh "$ROOT/tests/phase7/run_all.sh" "$1"; guard $?

step "9 · deterministic exchange benchmarks (no FPS, no GPU, no pixel claim)"
python3 "$HERE/benchmark_bim.py"

step "10 · produce the real BIM artifacts and their manifests"
python3 "$HERE/make_outputs.py"; guard $?

if [ "$1" = "--browser" ]; then
  step "11 · real Chromium: the exchange panel, hostile imports and language switch"
  node "$ROOT/tests/phase3/lib/run_browser.js" "$HERE/test_bim_browser.js"; guard $?
else
  printf '\n=== 11 · real Chromium ===\nSKIPPED (pass --browser to run). '
  printf 'Without it: NOT VERIFIED — CHROMIUM ENVIRONMENT UNAVAILABLE\n'
fi

printf '\n==============================================\n'
if [ "$FAIL" -eq 0 ]; then
  echo "PHASE 8 VERIFICATION: all executed suites passed"
else
  echo "PHASE 8 VERIFICATION: FAILURES PRESENT"
  exit 1
fi
