import { COLORS, area, doorPoint, windowPoint, roomPolygon, pointInPolygon, centroid, round } from './model.js';
import { deriveWalls, deriveOpenings } from './building.js';
export const escapeHTML = s => String(s ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const fmt = n => Number(n).toLocaleString('en-US', { maximumFractionDigits: 1 });
const qkey=n=>String(round(n));
function floorCells(r){
    if(!r.footprint) return [{x:r.x,y:r.y,w:r.w,d:r.d}];
    const poly=roomPolygon(r), xs=[...new Set(poly.map(p=>qkey(p[0])))].map(Number).sort((a,b)=>a-b), ys=[...new Set(poly.map(p=>qkey(p[1])))].map(Number).sort((a,b)=>a-b), cells=[];
    for(let xi=1;xi<xs.length;xi++) for(let yi=1;yi<ys.length;yi++) { const x=xs[xi-1],y=ys[yi-1],w=xs[xi]-x,d=ys[yi]-y; if(w>.001&&d>.001&&pointInPolygon([x+w/2,y+d/2],poly,false)) cells.push({x,y,w,d}); }
    return cells;
}
function openingInterval(o,w){ const along=w.axis==='v'?o.y:o.x; return [along-o.width/2,along+o.width/2]; }
function boxForWall(w,a,b,z,h){ const t=w.thickness||.12; return {x:w.axis==='v'?w.coord-t/2:a,y:w.axis==='v'?a:w.coord-t/2,z,w:w.axis==='v'?t:b-a,d:w.axis==='v'?b-a:t,h,color:w.external?'#ded9cf':'#ebe7de',kind:'wall',wallId:w.id,displayOnly:true}; }
/** Presentation geometry derived from authoring walls/openings. It never mutates model facts. */
export function wallBoxes(model, levelId, displayHeight=2.75){
    const level=model.levels.find(l=>l.id===levelId)||model.levels[0], walls=deriveWalls(model).filter(w=>w.levelId===level.id), openings=deriveOpenings(model).filter(o=>o.levelId===level.id&&o.hostWallId), boxes=[];
    for(const w of walls){ const hosted=openings.filter(o=>o.hostWallId===w.id), points=[w.start,w.end]; for(const o of hosted){const [a,b]=openingInterval(o,w);points.push(Math.max(w.start,a),Math.min(w.end,b));} const cuts=[...new Set(points.map(qkey))].map(Number).sort((a,b)=>a-b);
        for(let i=1;i<cuts.length;i++){const a=cuts[i-1],b=cuts[i],mid=(a+b)/2;if(b-a<=.001)continue;const o=hosted.find(x=>{const [s,e]=openingInterval(x,w);return mid>s+.001&&mid<e-.001;});
            if(!o){boxes.push(boxForWall(w,a,b,level.elevation,displayHeight));continue;}
            if(o.type==='door'){const bottom=Math.min(displayHeight,o.height||2.15),h=displayHeight-bottom;if(h>.001)boxes.push(boxForWall(w,a,b,level.elevation+bottom,h));}
            else {const sill=Math.max(0,Math.min(displayHeight,o.sill||0)),top=Math.max(sill,Math.min(displayHeight,sill+(o.height||1.2)));if(sill>.001)boxes.push(boxForWall(w,a,b,level.elevation,sill));if(displayHeight-top>.001)boxes.push(boxForWall(w,a,b,level.elevation+top,displayHeight-top));}
        }
    }
    return boxes;
}
export function sceneBoxes(model,{levelId=model.levels[0].id,all=false,selectedId=null,furniture=true,cutaway=true,issues=[]}={}){
    const W=model.site.width,D=model.site.depth,bad=new Set(issues.filter(i=>i.status==='error').flatMap(i=>i.targets)),warn=new Set(issues.filter(i=>i.status==='warning').flatMap(i=>i.targets)),boxes=[{x:-.7,y:-.7,z:-.28,w:W+1.4,d:D+1.4,h:.25,color:'#b9c7aa',kind:'ground',displayOnly:true},{x:1.5,y:2.5,z:-.035,w:W-3,d:D-5,h:.04,color:'#e5e0d4',kind:'paving',displayOnly:true}];
    for(const f of model.site.features||[]){if(f.type==='pool')boxes.push({x:f.x,y:f.y,z:-.09,w:f.w,d:f.d,h:.08,color:'#78b8c3',kind:'pool',displayOnly:true});else boxes.push({x:f.x,y:f.y,z:-.01,w:f.w,d:f.d,h:.04,color:'#c8d2be',kind:f.type,displayOnly:true});}
    const levels=all?model.levels:model.levels.filter(l=>l.id===levelId), derivedOpenings=deriveOpenings(model);
    for(const level of levels){const elev=all?level.elevation:0,delta=elev-level.elevation;
        for(const r of level.rooms){const color=r.id===selectedId?'#68c8ad':bad.has(r.id)?'#cf7f70':warn.has(r.id)?'#d6b26e':COLORS[r.kind];for(const c of floorCells(r))boxes.push({...c,z:elev,h:.075,color,kind:'floor',roomId:r.id});
            if(furniture&&!r.footprint){const ox=r.x+.5,oy=r.y+.45,ww=Math.min(r.w-1,2),dd=Math.min(r.d-1,2.1);if(r.kind==='bedroom'&&ww>.8&&dd>1){boxes.push({x:ox,y:oy,z:elev+.1,w:ww,d:dd,h:.38,color:'#f4f0e7',displayOnly:true},{x:ox,y:oy,z:elev+.5,w:ww,d:.2,h:.35,color:'#a49a89',displayOnly:true});}if(['living','majlis'].includes(r.kind)&&r.w>2&&r.d>2)boxes.push({x:ox,y:oy,z:elev+.1,w:Math.min(3,r.w-1),d:.8,h:.55,color:'#f3eee4',displayOnly:true},{x:ox+.45,y:oy+1.3,z:elev+.1,w:Math.min(1.5,r.w-1),d:.8,h:.32,color:'#987e60',displayOnly:true});if(['dining','kitchen','office'].includes(r.kind)&&r.w>2&&r.d>2)boxes.push({x:r.x+r.w*.28,y:r.y+r.d*.3,z:elev+.08,w:r.w*.42,d:Math.min(1.6,r.d*.4),h:.85,color:r.kind==='kitchen'?'#ddd6c9':'#9c8264',displayOnly:true});if(r.kind==='stairs')for(let i=0;i<12;i++)boxes.push({x:r.x+.15,y:r.y+.2+i*(r.d-.4)/12,z:elev,w:r.w-.3,d:(r.d-.4)/12,h:.08+i*.19,color:'#b3a895',displayOnly:true});}
        }
        const h=cutaway?(all?1.1:1.35):2.75;for(const b of wallBoxes(model,level.id,h))boxes.push({...b,z:b.z+delta});
        for(const o of derivedOpenings.filter(o=>o.levelId===level.id&&o.type==='window')){const vertical=['east','west'].includes(o.side),t=.025;boxes.push({x:vertical?o.x-t:o.x-o.width/2,y:vertical?o.y-o.width/2:o.y-t,z:elev+(o.sill||0),w:vertical?t*2:o.width,d:vertical?o.width:t*2,h:o.height||1.2,color:'#8fcbd0',kind:'window',openingId:o.id,displayOnly:true});}
    }
    for(let i=0;i<Math.min(7,Math.floor(D/3));i++){boxes.push({x:.25,y:1+i*3,z:0,w:.9,d:.9,h:.7,color:'#7f9a71',displayOnly:true});boxes.push({x:W-1.1,y:1+i*3,z:0,w:.8,d:.8,h:.6,color:'#8ca57e',displayOnly:true});}
    return boxes;
}
function furnitureSVG(r){if(r.footprint)return '';const x=r.x,y=r.y,w=r.w,d=r.d;if(w<2||d<2)return '';let s='';if(r.kind==='bedroom'){const bw=Math.min(1.8,w-.8),bd=Math.min(2,d-.8);s=`<rect x="${x+.45}" y="${y+.45}" width="${bw}" height="${bd}" rx=".09"/><path d="M${x+.45} ${y+.9}h${bw}"/>`;}else if(['living','majlis'].includes(r.kind))s=`<rect x="${x+.4}" y="${y+.4}" width="${Math.min(3,w-.8)}" height=".8" rx=".15"/><rect x="${x+.9}" y="${y+1.5}" width="${Math.min(1.5,w-1.4)}" height=".8" rx=".1"/>`;else if(r.kind==='stairs'){for(let i=0;i<12;i++)s+=`<path d="M${x+.25} ${y+.2+i*(d-.4)/12}h${w-.5}"/>`;}else if(r.kind==='kitchen')s=`<path d="M${x+.3} ${y+d-.3}h${w-.6}v-.7H${x+1}V${y+.3}h-.7Z"/>`;else if(r.kind==='dining')s=`<rect x="${x+w*.25}" y="${y+d*.3}" width="${w*.5}" height="${d*.4}" rx=".2"/>`;return `<g fill="none" stroke="#777367" stroke-width=".045" opacity=".55" pointer-events="none">${s}</g>`;}
function roomShape(r,attrs){if(!r.footprint)return `<rect x="${r.x}" y="${r.y}" width="${r.w}" height="${r.d}" ${attrs}/>`;return `<polygon points="${roomPolygon(r).map(p=>p.join(',')).join(' ')}" ${attrs}/>`;}
export function planSVG(model,levelId,{selectedId=null,issues=[],dimensions=true,furniture=true,preview=null,measurement=null,interactive=true}={}){
    const l=model.levels.find(l=>l.id===levelId)||model.levels[0],W=model.site.width,D=model.site.depth,bad=new Set(issues.filter(i=>i.status==='error').flatMap(i=>i.targets)),warn=new Set(issues.filter(i=>i.status==='warning').flatMap(i=>i.targets)),checked=new Set(issues.filter(i=>i.status==='checked'&&i.category==='model-check').flatMap(i=>i.targets));let svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="-2.5 -2.5 ${W+5} ${D+5}" class="floorplan" role="img" aria-label="مخطط ${escapeHTML(l.name)}. أبعاد بالمتر. تصميم مفاهيمي." preserveAspectRatio="xMidYMid meet"><defs><pattern id="plan-grid" width="1" height="1" patternUnits="userSpaceOnUse"><path d="M1 0H0V1" fill="none" stroke="#d6ddd5" stroke-width=".02"/></pattern></defs><rect x="-2.5" y="-2.5" width="${W+5}" height="${D+5}" fill="#f4f6f0"/><g transform="translate(0 ${D}) scale(1 -1)"><rect width="${W}" height="${D}" fill="#e2e8d9" rx=".2"/><rect width="${W}" height="${D}" fill="url(#plan-grid)"/><rect width="${W}" height="${D}" fill="none" stroke="#879785" stroke-width=".08" stroke-dasharray=".3 .18"/>`;
    for(const f of model.site.features||[]){const fill=f.type==='pool'?'#78b8c3':'#c8d2be',stroke=f.type==='pool'?'#3f7f88':'#71836c';svg+=`<g aria-label="${escapeHTML(f.name)}"><rect x="${f.x}" y="${f.y}" width="${f.w}" height="${f.d}" rx=".12" fill="${fill}" fill-opacity=".78" stroke="${stroke}" stroke-width=".07"/></g>`;}
    for(const ref of model.references||[])for(const line of ref.lines)svg+=`<path d="M${line[0]} ${line[1]}L${line[2]} ${line[3]}" stroke="#54a2a1" stroke-width=".055" fill="none" opacity=".6"/>`;
    for(const r of l.rooms){const issue=bad.has(r.id),warning=warn.has(r.id),ok=checked.has(r.id),sel=r.id===selectedId,fill=sel?'#b0d9ca':issue?'#eed0c9':warning?'#eee0bc':COLORS[r.kind],[cx,cy]=centroid(r),status=issue?'، توجد مشكلة':warning?'، يوجد تنبيه':ok?'، فُحص ضمن نموذج مسار':'';const dot=issue?'#b74d3c':warning?'#b4873f':ok?'#4e9167':null;const attrs=`fill="${fill}" stroke="${issue?'#bd624d':warning?'#a98445':sel?'#176653':'#676c62'}" stroke-width="${sel?.16:.09}"`;
        svg+=`<g ${interactive?`data-room-id="${escapeHTML(r.id)}" tabindex="0" role="button"`:''} aria-label="${escapeHTML(r.name)}، ${fmt(area(r))} متر مربع${status}${r.locked?'، مثبت':''}" class="room">${roomShape(r,attrs)}${furniture?furnitureSVG(r):''}<g transform="translate(${cx} ${cy}) scale(1 -1)" text-anchor="middle" pointer-events="none"><text y="-.08" font-size="${Math.min(.52,r.w*.16)}" font-family="Tahoma,Arial,sans-serif" fill="#253c35" font-weight="600">${escapeHTML(r.name)}</text><text y=".48" font-size=".38" fill="#58675e" font-family="Arial,sans-serif" direction="ltr">${fmt(area(r))} m²${r.locked?' •':''}</text>${dimensions&&!['stairs','elevator'].includes(r.kind)?`<text y=".9" font-size=".33" fill="#617065" font-family="Arial,sans-serif" direction="ltr">${r.footprint?'غير مستطيل · bbox ':''}${fmt(r.w)} × ${fmt(r.d)} m</text>`:''}</g>${dot?`<circle cx="${r.x+r.w-.3}" cy="${r.y+r.d-.3}" r=".16" fill="${dot}"/>`:''}</g>`;}
    for(const r of l.rooms){for(const d of r.doors){const[x,y]=doorPoint(r,d),vertical=['east','west'].includes(d.side),w=d.width;svg+=`<path d="M${vertical?x:x-w/2} ${vertical?y-w/2:y}${vertical?'v':'h'}${w}" fill="none" stroke="#f5f4e9" stroke-width=".15"/><path d="M${vertical?x:x-w/2} ${vertical?y-w/2:y}l${vertical?w:0} ${vertical?0:w}" stroke="#718171" stroke-width=".035" fill="none"/>`;}
        for(const w of r.windows||[]){const[x,y]=windowPoint(r,w),vertical=['east','west'].includes(w.side),half=w.width/2;svg+=`<path d="M${vertical?x:x-half} ${vertical?y-half:y}${vertical?'v':'h'}${w.width}" stroke="#2b8790" stroke-width=".09" fill="none"/><path d="M${vertical?x+(w.side==='east'?-.07:.07):x-half} ${vertical?y-half:y+(w.side==='north'?-.07:.07)}${vertical?'v':'h'}${w.width}" stroke="#91cbd0" stroke-width=".045" fill="none"/>`;}}
    if(preview)for(const c of preview.changes){const r=c.before;if(!r||![r.x,r.y,r.w,r.d].every(Number.isFinite))continue;svg+=roomShape(r,'fill="none" stroke="#b77642" stroke-width=".10" stroke-dasharray=".25 .16" pointer-events="none"');}
    svg+='</g>';
    if(measurement?.a){const a=measurement.a,b=measurement.b||measurement.a,ay=D-a.y,by=D-b.y,distance=Math.hypot(b.x-a.x,b.y-a.y),mx=(a.x+b.x)/2,my=(ay+by)/2;svg+=`<g class="measure-overlay" pointer-events="none"><line x1="${a.x}" y1="${ay}" x2="${b.x}" y2="${by}" stroke="#176653" stroke-width=".11" stroke-dasharray=".2 .12"/><circle cx="${a.x}" cy="${ay}" r=".16" fill="#176653"/><circle cx="${b.x}" cy="${by}" r=".16" fill="#176653"/>${measurement.b?`<g transform="translate(${mx} ${my})"><rect x="-1.05" y="-.34" width="2.1" height=".68" rx=".18" fill="#fffdf7" stroke="#176653" stroke-width=".04"/><text y=".15" text-anchor="middle" font-size=".4" font-family="Arial,sans-serif" fill="#174f42" direction="ltr">${fmt(distance)} m</text></g>`:''}</g>`;}
    svg+=`<g stroke="#7a887f" stroke-width=".04" fill="none"><path d="M0 -1H${W} M0 -1.25v.5 M${W} -1.25v.5"/><path d="M${W+1} 0V${D} M${W+.75} 0h.5 M${W+.75} ${D}h.5"/></g><g fill="#5a6c61" font-size=".42" font-family="Arial,sans-serif" direction="ltr" text-anchor="middle"><text x="${W/2}" y="-1.3">${fmt(W)} m</text><text transform="translate(${W+1.65} ${D/2}) rotate(90)">${fmt(D)} m</text><text x="${W/2}" y="${D+1.3}" font-family="Tahoma,Arial,sans-serif">الشارع: ${escapeHTML(model.site.street)} · ارتدادات افتراضية تحتاج مراجعة</text></g><g transform="translate(-1.4 .4)"><path d="M0 1V-1M-.2-.6 0-1l.2.4" fill="none" stroke="#3b6452" stroke-width=".06"/><text y="-1.25" text-anchor="middle" fill="#3b6452" font-size=".45">N</text></g></svg>`;return svg;
}
export function exportOBJ(model){const boxes=model.levels.flatMap(l=>[...l.rooms.flatMap(r=>floorCells(r).map(c=>({...c,z:l.elevation,h:.08}))),...wallBoxes(model,l.id)]);let o='# MASAR authoring coordination model. Metres, Z up. NOT FOR CONSTRUCTION.\n# DISPLAY assumptions: wall boxes use declared conceptual authoring wall thickness; polygon floors are cell-decomposed presentation geometry.\n',index=1;for(const b of boxes){const{x,y,z,w,d,h}=b;for(const[dx,dy,dz]of[[0,0,0],[w,0,0],[w,d,0],[0,d,0],[0,0,h],[w,0,h],[w,d,h],[0,d,h]])o+=`v ${round(x+dx)} ${round(y+dy)} ${round(z+dz)}\n`;for(const f of[[0,3,2,1],[4,5,6,7],[0,1,5,4],[1,2,6,5],[2,3,7,6],[3,0,4,7]])o+=`f ${f.map(v=>v+index).join(' ')}\n`;index+=8;}return o;}
