#!/usr/bin/env sh
# ==============================================================================
# تشغيل تحقّق المرحلة 7 كاملاً من نسخة نظيفة من المستودع.
#   sh tests/phase7/run_all.sh            # كل شيء عدا المتصفّح الحقيقي
#   sh tests/phase7/run_all.sh --browser  # مع Chromium عبر Playwright
# ==============================================================================
set -e
HERE=$(cd "$(dirname "$0")" && pwd)
ROOT=$(cd "$HERE/../.." && pwd)
cd "$ROOT"
FAIL=0
step() { printf '\n=== %s ===\n' "$1"; }
guard() { if [ "$1" -ne 0 ]; then FAIL=1; fi }

step "0 · Python syntax and imports"
python3 -m py_compile acs_*.py && echo "py_compile: OK"
python3 - <<'PY'
import importlib
mods = ["acs_visual", "acs_runtime", "acs_authoring", "acs_workspace", "acs_render"]
for m in mods:
    importlib.import_module(m)
print("imports: OK (%d modules)" % len(mods))
PY
guard $?

step "1 · regenerate every browser layer from the canonical specifications"
python3 "$ROOT/tools/build_runtime_browser.py"; guard $?
python3 "$ROOT/tools/build_authoring_browser.py"; guard $?
python3 "$ROOT/tools/build_workspace_ui.py"; guard $?
python3 "$ROOT/tools/build_render_browser.py"; guard $?

step "2 · the generated blocks are idempotent"
python3 "$ROOT/tools/build_render_browser.py" >/dev/null
python3 - <<'PY'
# بعد F-09 صارت public/index.html قشرة: العلامة فيها، والشيفرة في وحدات
# public/app/، والأنماط في public/app/styles/app.css. التسليم هو الثلاثة معاً،
# فالعدّ يجري عليه كلّه — لا على الصفحة وحدها.
import os
import sys
sys.path.insert(0, os.path.join(os.getcwd(), 'tools'))
import app_source as A
page = A.shell() + '\n' + A.app_text() + '\n' + A.css_text()
marks = [
    '/* ===== ACS RENDER ENGINE (generated by tools/build_render_browser.py) ===== */',
    '/* ===== END ACS RENDER ENGINE ===== */',
    '<!-- ===== ACS RENDER DOM (generated) ===== -->',
    '<!-- ===== END ACS RENDER DOM ===== -->',
    '/* ===== ACS RENDER STYLES (generated) ===== */',
    '/* ===== END ACS RENDER STYLES ===== */',
]
bad = [m for m in marks if page.count(m) != 1]
if bad:
    raise SystemExit('duplicated or missing generated marker: %s' % bad)
print('generated render blocks: exactly one of each (%d markers)' % len(marks))
# وأشدّ من العدّ: كل كتلة شيفرة مولَّدة يجب أن تحملها وحدة واحدة بعينها،
# وأن تكون تلك الوحدة مستوردة فعلاً من public/app/main.js — فلا تمرّ كتلة
# صحيحة الوسم لكنها في ملفّ يتيم لا يُحمَّل.
_imported = set(A.order())
_mods = A.modules()
for _m in [m for m in marks if m.startswith('/*') and 'STYLES' not in m]:
    _owners = [f for f in _mods if _mods[f].count(_m) == 1]
    if len(_owners) != 1 or _owners[0] not in _imported:
        raise SystemExit('generated block is not carried by exactly one module '
                         'imported by public/app/main.js: %r -> %s' % (_m, _owners))
print('every generated code block is carried by one imported module')
PY
guard $?

step "3 · regenerate the phase 7 fixtures from the repository fixtures"
node "$HERE/fixture_generator.js"; guard $?

step "4 · render contract, materials, cameras, drawings, buffers and drift"
node "$ROOT/tests/lib/run.js" "$HERE/test_render.js"; guard $?

step "5 · produced targets and the named tests A to L"
node "$ROOT/tests/lib/run.js" "$HERE/test_targets.js"; guard $?

step "6 · render security: hostile references, prompts, assets and secrets"
node "$ROOT/tests/lib/run.js" "$HERE/test_security.js"; guard $?

step "7 · Python <-> JavaScript render parity"
node "$HERE/test_parity.js"; guard $?

step "8 · backend and configuration security"
python3 "$ROOT/tests/security/test_security.py"; guard $?

step "9 · Phase 6 regression (workspace and every earlier phase)"
sh "$ROOT/tests/phase6/run_all.sh" "$1"; guard $?

step "10 · deterministic render benchmarks (no FPS, no GPU, no pixel claim)"
node "$ROOT/tests/lib/run.js" "$HERE/benchmark_render.js"

step "11 · produce the real presentation outputs"
node "$ROOT/tests/lib/run.js" "$HERE/make_outputs.js"; guard $?

if [ "$1" = "--browser" ]; then
  step "12 · real Chromium: the visualisation panel and render security"
  node "$ROOT/tests/phase3/lib/run_browser.js" "$HERE/test_security.js"; guard $?
else
  printf '\n=== 12 · real Chromium ===\nSKIPPED (pass --browser to run). '
  printf 'Without it: NOT VERIFIED — CHROMIUM ENVIRONMENT UNAVAILABLE\n'
fi

printf '\n==============================================\n'
if [ "$FAIL" -eq 0 ]; then
  echo "PHASE 7 VERIFICATION: all executed suites passed"
else
  echo "PHASE 7 VERIFICATION: FAILURES PRESENT"
  exit 1
fi
