#!/usr/bin/env sh
# ==============================================================================
# تشغيل تحقّق المرحلة 9.2 كاملاً من نسخة نظيفة من المستودع.
#   sh tests/phase9_2/run_all.sh            # كل شيء عدا المتصفّح الحقيقي
#   sh tests/phase9_2/run_all.sh --browser  # مع Chromium عبر Playwright
# ==============================================================================
set -e
HERE=$(cd "$(dirname "$0")" && pwd)
ROOT=$(cd "$HERE/../.." && pwd)
cd "$ROOT"
FAIL=0
step() { printf '\n=== %s ===\n' "$1"; }
guard() { if [ "$1" -ne 0 ]; then FAIL=1; fi }

step "0 · Python syntax and imports"
python3 -m py_compile acs_*.py && echo "py_compile: OK"
python3 - <<'PY'
import importlib
mods = ["acs_visual", "acs_runtime", "acs_authoring", "acs_workspace",
        "acs_render", "acs_bim", "acs_docs", "acs_pbr", "acs_archdetail"]
for m in mods:
    importlib.import_module(m)
print("imports: OK (%d modules)" % len(mods))
PY
guard $?

step "0b · layer integration (one viewport contract everywhere)"
python3 "$ROOT/tools/check_integration.py" "$ROOT"; guard $?

step "1 · regenerate the architectural detail browser layer"
python3 "$ROOT/tools/build_archdetail_browser.py"; guard $?

step "2 · the generated architectural blocks are idempotent"
python3 "$ROOT/tools/build_archdetail_browser.py" >/dev/null
python3 - <<'PY'
page = open('public/index.html', encoding='utf-8').read()
marks = [
    '/* ===== ACS ARCH DETAIL '
    '(generated by tools/build_archdetail_browser.py) ===== */',
    '/* ===== END ACS ARCH DETAIL ===== */',
    '<!-- ===== ACS ARCH DETAIL DOM (generated) ===== -->',
    '<!-- ===== END ACS ARCH DETAIL DOM ===== -->',
    '/* ===== ACS ARCH DETAIL STYLES (generated) ===== */',
    '/* ===== END ACS ARCH DETAIL STYLES ===== */',
    '/* ===== ACS ARCH DETAIL BRIDGE (module scope) ===== */',
    '/* ===== END ACS ARCH DETAIL BRIDGE ===== */',
]
bad = [m for m in marks if page.count(m) != 1]
if bad:
    raise SystemExit('duplicated or missing generated marker: %s' % bad)
if page.count('window.__ACS_PQ__&&window.__ACS_PQ__.composer') != 1:
    raise SystemExit('the 9.1 render loop dispatcher must stay single')
print('generated architectural blocks: exactly one of each (%d markers), '
      'no second dispatcher' % len(marks))
PY
guard $?

step "3 · the architectural fidelity contract (materials, facade, windows, objects, immutability)"
python3 "$HERE/test_archdetail.py"; guard $?

step "4 · Python <-> JavaScript architectural-layer parity"
node "$HERE/test_parity.js"; guard $?

step "5 · the architectural panel (Node scope)"
node "$ROOT/tests/lib/run.js" "$HERE/test_archdetail_browser.js"; guard $?

step "6 · backend and configuration security, including the architectural layer"
python3 "$ROOT/tests/security/test_security.py"; guard $?

step "7 · deployment closure for every canonical file"
sh "$ROOT/tests/deploy/verify_deploy.sh"; guard $?

step "7a · the black-viewport regression (bounds, clip, frustum, fail-open)"
python3 "$HERE/test_black_viewport.py"; guard $?

step "7a2 · the transform and alignment regression (roof, racks, levels, axis)"
python3 "$HERE/test_alignment.py"; guard $?

step "7b · the viewport pixel analyser (positive and negative fixtures)"
node "$ROOT/tests/deploy/test_viewport_pixels.js"; guard $?

step "7c · the application page guard and real boot check"
python3 "$ROOT/tools/check_index_guard.py" "$ROOT/public/index.html"; guard $?
node "$ROOT/tests/deploy/verify_page_boot.js" || {
  rc=$?
  if [ "$rc" -eq 2 ]; then
    echo "page boot: NOT VERIFIED — EXTERNAL ENVIRONMENT REQUIRED (exit 2, not a test failure)"
  else
    guard "$rc"
  fi
}

step "8 · Phase 9.1 regression (visual quality and every earlier phase)"
sh "$ROOT/tests/phase9_1/run_all.sh" "$1"; guard $?

step "9 · §48 reference captures (needs a networked machine with vendored Three.js)"
node "$HERE/capture_reference_92.js" || {
  rc=$?
  if [ "$rc" -eq 2 ]; then
    echo "reference captures: NOT VERIFIED — EXTERNAL ENVIRONMENT REQUIRED (exit 2, not a test failure)"
  else
    guard "$rc"
  fi
}

if [ "$1" = "--browser" ]; then
  step "10 · real Chromium: the architectural panel and shipped page end to end"
  node "$ROOT/tests/phase3/lib/run_browser.js" "$HERE/test_archdetail_browser.js"; guard $?
else
  printf '\n=== 10 · real Chromium ===\nSKIPPED (pass --browser to run). '
  printf 'Without it: NOT VERIFIED — CHROMIUM ENVIRONMENT UNAVAILABLE\n'
fi

printf '\n==============================================\n'
if [ "$FAIL" -eq 0 ]; then
  echo "PHASE 9.2 VERIFICATION: all executed suites passed"
else
  echo "PHASE 9.2 VERIFICATION: FAILURES PRESENT"
  exit 1
fi
