#!/usr/bin/env python3
"""One-shot source transform for durable mobile generation jobs.
Run from repo root. It edits the API, browser wiring and transport regression test.
"""
from pathlib import Path


def replace_once(path, old, new):
    p=Path(path); s=p.read_text(encoding='utf-8')
    if old not in s: raise SystemExit('marker not found: '+path+' :: '+old[:80])
    if s.count(old)!=1: raise SystemExit('marker not unique: '+path+' :: '+str(s.count(old)))
    p.write_text(s.replace(old,new,1),encoding='utf-8')

# API: durable in-process registry wraps the existing cancellable process runner.
p='acs_understand_api.py'
replace_once(p,'import concurrent.futures\n','import concurrent.futures\nimport uuid\n')
replace_once(p,'_JOBS = JOBS.default_runner()\n','''_JOBS = JOBS.default_runner()\n\n# Durable HTTP generation jobs: the expensive provider call is no longer tied to\n# one Safari/HTTP connection. The existing JOBS runner still owns process isolation,\n# capacity and hard cancellation; this registry only owns HTTP-visible state/result.\nASYNC_JOB_TTL_S = env_int("ACS_ASYNC_JOB_TTL_S", 1800)\n_ASYNC_JOBS = {}\n_ASYNC_JOBS_LOCK = threading.Lock()\n\ndef _async_prune(now=None):\n    now = float(now or time.time())\n    with _ASYNC_JOBS_LOCK:\n        dead = [jid for jid,j in _ASYNC_JOBS.items()\n                if j.get("finished_at") and now-j["finished_at"] > ASYNC_JOB_TTL_S]\n        for jid in dead: _ASYNC_JOBS.pop(jid, None)\n\ndef _async_public(j):\n    out={"ok":True,"job_id":j["id"],"state":j["state"],\n         "request_id":j["request_id"],"created_at":j["created_at"],\n         "started_at":j.get("started_at"),"finished_at":j.get("finished_at")}\n    if j["state"]==JOBS.STATE_SUCCEEDED: out["result"]=j.get("result")\n    if j["state"]==JOBS.STATE_FAILED: out["error"]=j.get("error")\n    return out\n\ndef _async_start(kwargs, rid):\n    _async_prune()\n    jid="httpjob_"+uuid.uuid4().hex[:20]\n    job={"id":jid,"state":JOBS.STATE_PENDING,"request_id":rid,\n         "created_at":time.time(),"started_at":None,"finished_at":None,\n         "result":None,"error":None}\n    with _ASYNC_JOBS_LOCK: _ASYNC_JOBS[jid]=job\n    def worker():\n        with _ASYNC_JOBS_LOCK:\n            job["state"]=JOBS.STATE_RUNNING; job["started_at"]=time.time()\n        try:\n            building=_JOBS.run(TARGET_UNDERSTAND, kwargs, timeout_s=REQUEST_TIMEOUT_S,\n                               request_id=rid)\n            # Payload assembly uses CPU pool and is async; execute it on a private loop\n            # in this background thread after generation succeeds.\n            payload=asyncio.run(_understand_payload(building))\n            with _ASYNC_JOBS_LOCK:\n                job["result"]=payload; job["state"]=JOBS.STATE_SUCCEEDED\n                job["finished_at"]=time.time()\n        except E.AcsApiError as exc:\n            with _ASYNC_JOBS_LOCK:\n                job["state"]=JOBS.STATE_FAILED; job["finished_at"]=time.time()\n                job["error"]=exc.envelope(rid).get("error")\n        except Exception as exc:\n            err=E.classify_upstream(exc, provider=_resolved_provider())\n            with _ASYNC_JOBS_LOCK:\n                job["state"]=JOBS.STATE_FAILED; job["finished_at"]=time.time()\n                job["error"]=err.envelope(rid).get("error")\n    threading.Thread(target=worker,name="acs-http-"+jid[-8:],daemon=True).start()\n    return job\n''')

old='''@app.post("/v1/understand")\nasync def understand(req: UnderstandReq, request: Request):\n'''
new='''@app.post("/v1/understand/jobs", status_code=202)\nasync def understand_job_submit(req: UnderstandReq, request: Request):\n    if not req.text.strip():\n        raise E.AcsApiError(E.ACS_BAD_REQUEST, "النص فارغ.")\n    _cap(req.text); guard(request, "gen")\n    rid=request_id_of(request); text=req.text; hints=[]\n    if req.site_w and req.site_d:\n        hints.append("أبعاد الأرض/مسطح البناء: العرض %.1f م (محور X) × العمق %.1f م (محور Z)."\n                     % (float(req.site_w),float(req.site_d)))\n    if req.floors: hints.append("عدد الأدوار: %d." % int(req.floors))\n    if hints: text="[معطيات الموقع من العميل] "+" ".join(hints)+"\\n"+text\n    bt=req.btype if (req.btype and req.btype != "auto") else None\n    kwargs=dict(description=text,model=_safe_model(req.model),deep=req.deep,\n                strict=bool(req.strict),btype=bt,site_w=req.site_w,site_d=req.site_d,\n                floors=req.floors)\n    job=_async_start(kwargs,rid)\n    return _async_public(job)\n\n@app.get("/v1/understand/jobs/{job_id}")\nasync def understand_job_status(job_id: str, request: Request):\n    _async_prune()\n    with _ASYNC_JOBS_LOCK: job=_ASYNC_JOBS.get(job_id)\n    if not job: raise E.AcsApiError(E.ACS_NOT_FOUND,"مهمة التوليد غير موجودة أو انتهت مدة الاحتفاظ بها.")\n    return _async_public(job)\n\n@app.post("/v1/understand")\nasync def understand(req: UnderstandReq, request: Request):\n'''
replace_once(p,old,new)
replace_once(p,'"endpoints": ["/v1/understand", "/v1/edit",','"endpoints": ["/v1/understand", "/v1/understand/jobs", "/v1/edit",')

# Browser: short submit + polling; no long-lived paid-generation HTTP request.
p='public/app/ui/workspace-ui-wiring.js'
old='''  const res=await __ACS_SHARED.acsFetchJSON('/v1/understand',{method:'POST',\n    headers:{'Content-Type':'application/json'},\n    body:JSON.stringify({text:txt,\n      btype:((document.getElementById('bType')||{}).value||'auto'),\n      strict:!!(document.getElementById('strictMode')||{}).checked,\n      site_w:(+document.getElementById('siteW').value||null),\n      site_d:(+document.getElementById('siteD').value||null),\n      floors:(+document.getElementById('nFloors').value||null)})}, 900000);\n\n  // A superseded response must not repaint the current request's status.\n  if(_seq!==ACS_APPLY_SEQ) return;\n'''
new='''  const requestBody={text:txt,\n      btype:((document.getElementById('bType')||{}).value||'auto'),\n      strict:!!(document.getElementById('strictMode')||{}).checked,\n      site_w:(+document.getElementById('siteW').value||null),\n      site_d:(+document.getElementById('siteD').value||null),\n      floors:(+document.getElementById('nFloors').value||null)};\n  let res=await __ACS_SHARED.acsFetchJSON('/v1/understand/jobs',{method:'POST',\n    headers:{'Content-Type':'application/json'},body:JSON.stringify(requestBody)},30000);\n  if(_seq!==ACS_APPLY_SEQ) return;\n  if(res.status===ACS_NET.SUCCESS){\n    const accepted=res.body||{}, jobId=accepted.job_id;\n    if(!jobId){ res={status:ACS_NET.INVALID_JSON,http:res.http,request_id:res.request_id,\n      message:'الخادم قبل الطلب لكن لم يُعد معرّف مهمة.'}; }\n    else {\n      statusEl.textContent='✓ استلم الخادم الطلب — جارٍ بناء النموذج. يمكنك إبقاء الصفحة مفتوحة.';\n      const deadline=Date.now()+900000;\n      while(_seq===ACS_APPLY_SEQ && Date.now()<deadline){\n        await new Promise(resolve=>setTimeout(resolve,2000));\n        const poll=await __ACS_SHARED.acsFetchJSON('/v1/understand/jobs/'+encodeURIComponent(jobId),\n          {method:'GET'},15000);\n        if(_seq!==ACS_APPLY_SEQ) return;\n        if(poll.status!==ACS_NET.SUCCESS){\n          // A transient mobile-network failure must not create a second paid job.\n          if(poll.status===ACS_NET.ERROR||poll.status===ACS_NET.TIMEOUT||poll.status===ACS_NET.OFFLINE){\n            statusEl.textContent='… التوليد مستمر على الخادم — جارٍ إعادة الاتصال بالمهمة '+jobId;\n            continue;\n          }\n          res=poll; break;\n        }\n        const j=poll.body||{};\n        if(j.state==='SUCCEEDED'){\n          res={status:ACS_NET.SUCCESS,http:poll.http,request_id:j.request_id||poll.request_id,\n               body:j.result}; break;\n        }\n        if(j.state==='FAILED'||j.state==='TIMED_OUT'||j.state==='CANCELLED'||j.state==='REJECTED'){\n          const er=j.error||{}; res={status:ACS_NET.API_ERROR,http:poll.http,\n            request_id:er.request_id||j.request_id||poll.request_id,code:er.code||'',\n            message:er.message||('فشلت مهمة التوليد: '+j.state),retryable:!!er.retryable}; break;\n        }\n        statusEl.textContent='🤖 التوليد مستمر على الخادم — '+(j.state||'RUNNING')+'…';\n      }\n      if(Date.now()>=deadline && (!res.body||!res.body.building))\n        res={status:ACS_NET.TIMEOUT,request_id:accepted.request_id||res.request_id,\n             message:'انتهت مهلة انتظار الواجهة، والمهمة لم تُنشئ طلب توليد ثانياً.'};\n    }\n  }\n\n  // A superseded response must not repaint the current request's status.\n  if(_seq!==ACS_APPLY_SEQ) return;\n'''
replace_once(p,old,new)

# Add source-level regression assertions without rewriting existing harness assumptions.
p='tests/remediation/test_transport_errors.js'
old='''  console.log(`TRANSPORT UNIT: ${passed} passed, 0 failed (Node, no browser or paid calls)`);\n'''
new='''  await test('generation uses short submit plus job polling instead of one long HTTP request',async()=>{\n    const src=fs.readFileSync(path.join(ROOT,'public/app/ui/workspace-ui-wiring.js'),'utf8');\n    assert.ok(src.includes("acsFetchJSON('/v1/understand/jobs'"));\n    assert.ok(src.includes("'/v1/understand/jobs/'+encodeURIComponent(jobId)"));\n    assert.ok(src.includes('A transient mobile-network failure must not create a second paid job.'));\n    assert.ok(!src.includes("acsFetchJSON('/v1/understand',{method:'POST'"));\n  });\n  console.log(`TRANSPORT UNIT: ${passed} passed, 0 failed (Node, no browser or paid calls)`);\n'''
replace_once(p,old,new)
print('async generation transform applied')
