# -*- coding: utf-8 -*-
"""يحقن مساحة عمل المنتج في public/index.html بين علامات صريحة.

التشغيل مرّتين يستبدل الكتل ولا يكرّرها. تُحقن شيفرة الواجهة بعد كتلة التأليف
كي لا يمحو أي مولّد كتلة الآخر. المواصفة تُنسخ حرفاً بحرف من acs_workspace.json.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SPEC_PATH = os.path.join(ROOT, "acs_workspace.json")
PAGE = os.path.join(ROOT, "public", "index.html")

JS_BEGIN = "/* ===== ACS WORKSPACE UI (generated by tools/build_workspace_ui.py) ===== */"
JS_END = "/* ===== END ACS WORKSPACE UI ===== */"
JS_ANCHOR = "/* ===== END ACS AUTHORING LAYER ===== */"

CSS_BEGIN = "/* ===== ACS WORKSPACE STYLES (generated) ===== */"
CSS_END = "/* ===== END ACS WORKSPACE STYLES ===== */"
CSS_ANCHOR = "</style>"

DOM_BEGIN = "<!-- ===== ACS WORKSPACE DOM (generated) ===== -->"
DOM_END = "<!-- ===== END ACS WORKSPACE DOM ===== -->"
DOM_ANCHOR = "</body>"

CSS = r""":root{
  --ws-bg:#0e1116; --ws-panel:#151a21; --ws-panel2:#1b212a; --ws-line:#252c37;
  --ws-txt:#e6eaf0; --ws-dim:#9aa5b4; --ws-accent:#4a9eff; --ws-accent2:#7c5cff;
  --ws-ok:#22c55e; --ws-warn:#f59e0b; --ws-err:#ef4444; --ws-info:#38bdf8;
  --ws-edit:#f59e0b; --ws-topbar:52px; --ws-status:34px; --ws-tree:264px;
  --ws-insp:340px; --ws-hit:44px;
}
#acsWorkspace{position:fixed;inset:0;display:none;grid-template-rows:var(--ws-topbar) 1fr var(--ws-status);
  background:var(--ws-bg);color:var(--ws-txt);font:13px/1.5 system-ui,-apple-system,"Segoe UI",Tahoma,sans-serif;
  z-index:40;overflow:hidden;max-width:100vw}
#acsWorkspace.on{display:grid}
#acsWorkspace *{box-sizing:border-box}
#acsWorkspace button{font:inherit;color:inherit}
#acsWorkspace :focus-visible{outline:2px solid var(--ws-accent);outline-offset:2px}
.ws-top{grid-row:1;display:flex;align-items:center;gap:8px;padding:0 10px;
  background:var(--ws-panel);border-bottom:1px solid var(--ws-line);min-width:0;overflow-x:auto}
.ws-brand{font-weight:800;letter-spacing:.3px;white-space:nowrap}
.ws-proj{font-weight:600;max-width:26vw;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.ws-rev{font:11px/1 ui-monospace,SFMono-Regular,Menlo,monospace;color:var(--ws-dim);
  background:var(--ws-panel2);border:1px solid var(--ws-line);border-radius:6px;padding:4px 7px;white-space:nowrap}
.ws-sp{flex:1 1 auto;min-width:4px}
.ws-btn{min-height:34px;min-width:34px;padding:6px 10px;border-radius:8px;border:1px solid var(--ws-line);
  background:var(--ws-panel2);cursor:pointer;display:inline-flex;align-items:center;gap:6px;white-space:nowrap}
.ws-btn:hover{border-color:var(--ws-accent)}
.ws-btn[disabled]{opacity:.45;cursor:not-allowed}
.ws-btn.pri{background:var(--ws-accent);border-color:var(--ws-accent);color:#04121f;font-weight:700}
.ws-btn.danger{background:#3a1517;border-color:#5b2126;color:#fecaca}
.ws-btn.on{background:var(--ws-edit);border-color:var(--ws-edit);color:#1a1206;font-weight:700}
.ws-main{grid-row:2;display:grid;grid-template-columns:var(--ws-tree) minmax(0,1fr) var(--ws-insp);min-height:0;min-width:0}
.ws-pane{background:var(--ws-panel);border-inline-end:1px solid var(--ws-line);
  display:flex;flex-direction:column;min-height:0;min-width:0;overflow:hidden}
.ws-pane.right{border-inline-end:0;border-inline-start:1px solid var(--ws-line)}
.ws-pane h3{margin:0;padding:9px 12px;font-size:11px;letter-spacing:.10em;text-transform:uppercase;
  color:var(--ws-dim);border-bottom:1px solid var(--ws-line);display:flex;align-items:center;gap:8px}
.ws-scroll{overflow:auto;flex:1;min-height:0;-webkit-overflow-scrolling:touch}
.ws-view{position:relative;background:#0a0d12;min-width:0;min-height:0;overflow:hidden}
.ws-view-host{position:absolute;inset:0}
.ws-filters{display:flex;flex-wrap:wrap;gap:4px;padding:6px 8px;border-bottom:1px solid var(--ws-line)}
.ws-chip{font-size:11px;padding:4px 8px;border-radius:999px;border:1px solid var(--ws-line);
  background:var(--ws-panel2);cursor:pointer;min-height:26px}
.ws-chip.on{background:var(--ws-accent);border-color:var(--ws-accent);color:#04121f;font-weight:700}
.ws-row{display:flex;align-items:center;gap:6px;padding:5px 8px;cursor:pointer;
  border-inline-start:2px solid transparent;min-height:30px}
.ws-row:hover{background:var(--ws-panel2)}
.ws-row.sel{background:#12314f;border-inline-start-color:var(--ws-accent)}
.ws-row .tw{width:14px;text-align:center;color:var(--ws-dim);flex:0 0 14px}
.ws-row .nm{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;flex:1}
.ws-row .kd{font-size:10px;color:var(--ws-dim);flex:0 0 auto}
.ws-sec{padding:8px 12px;border-bottom:1px solid var(--ws-line)}
.ws-sec h4{margin:0 0 6px;font-size:11px;letter-spacing:.08em;text-transform:uppercase;color:var(--ws-dim)}
.ws-f{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1.1fr);gap:6px;align-items:center;padding:3px 0}
.ws-f .k{color:var(--ws-dim);font-size:12px;overflow:hidden;text-overflow:ellipsis}
.ws-f .v{display:flex;align-items:center;gap:6px;min-width:0}
.ws-f .v span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.ws-f input{width:100%;min-height:30px;background:var(--ws-panel2);border:1px solid var(--ws-line);
  border-radius:6px;color:var(--ws-txt);padding:3px 7px;font:inherit}
.ws-tag{font-size:9px;padding:2px 5px;border-radius:4px;border:1px solid var(--ws-line);
  color:var(--ws-dim);flex:0 0 auto;white-space:nowrap}
.ws-tag.derived{border-color:#3b3f7a;color:#a5b4fc}
.ws-tag.unknown{border-color:#5b4a1f;color:#fcd34d}
.ws-tag.display{border-color:#3f5b4a;color:#86efac}
.ws-tag.readonly{border-color:#4a4f5b;color:#cbd5e1}
.ws-tag.editable{border-color:#1f4a5b;color:#7dd3fc}
.ws-unknown{color:#fcd34d;font-style:italic}
.ws-status{grid-row:3;display:flex;align-items:center;gap:10px;padding:0 10px;background:var(--ws-panel);
  border-top:1px solid var(--ws-line);font-size:11px;color:var(--ws-dim);overflow-x:auto;white-space:nowrap}
.ws-status b{color:var(--ws-txt);font-weight:600}
.ws-status i{font-style:normal}
.ws-pill{padding:2px 7px;border-radius:999px;border:1px solid var(--ws-line);background:var(--ws-panel2)}
.ws-pill.err{border-color:#5b2126;color:#fca5a5}
.ws-pill.warn{border-color:#5b4a1f;color:#fcd34d}
.ws-pill.info{border-color:#1f4a5b;color:#7dd3fc}
.ws-pill.edit{border-color:var(--ws-edit);color:var(--ws-edit)}
.ws-modal{position:fixed;inset:0;background:rgba(4,7,11,.72);display:none;align-items:center;
  justify-content:center;z-index:60;padding:14px}
.ws-modal.on{display:flex}
.ws-card{background:var(--ws-panel);border:1px solid var(--ws-line);border-radius:12px;
  max-width:min(620px,96vw);width:100%;max-height:88vh;overflow:auto;padding:16px}
.ws-card h2{margin:0 0 4px;font-size:16px}
.ws-card .sub{color:var(--ws-dim);font-size:12px;margin-bottom:12px}
.ws-card label{display:block;font-size:11px;color:var(--ws-dim);margin:8px 0 3px}
.ws-card input,.ws-card textarea,.ws-card select{width:100%;background:var(--ws-panel2);
  border:1px solid var(--ws-line);border-radius:8px;color:var(--ws-txt);padding:8px 10px;font:inherit;min-height:38px}
.ws-card textarea{min-height:120px;resize:vertical}
.ws-actions{display:flex;gap:8px;margin-top:14px;flex-wrap:wrap}
.ws-actions .ws-btn{min-height:var(--ws-hit)}
.ws-drawer{position:absolute;inset-block:0;inset-inline-start:0;width:min(84vw,300px);background:var(--ws-panel);
  border-inline-end:1px solid var(--ws-line);transform:translateX(-104%);transition:transform .18s;z-index:12;
  display:flex;flex-direction:column}
[dir="rtl"] .ws-drawer{transform:translateX(104%)}
.ws-drawer.on{transform:none}
.ws-sheet{position:absolute;inset-inline:0;bottom:0;max-height:62%;background:var(--ws-panel);
  border-top:1px solid var(--ws-line);border-radius:14px 14px 0 0;transform:translateY(104%);
  transition:transform .18s;z-index:12;display:flex;flex-direction:column}
.ws-sheet.on{transform:none}
.ws-grab{width:38px;height:4px;border-radius:2px;background:var(--ws-line);margin:8px auto 2px;flex:0 0 auto}
.ws-toasts{position:fixed;inset-block-end:calc(var(--ws-status) + 10px);inset-inline-end:12px;
  display:flex;flex-direction:column;gap:6px;z-index:70;pointer-events:none;max-width:min(92vw,340px)}
.ws-toast{background:var(--ws-panel2);border:1px solid var(--ws-line);border-radius:9px;padding:8px 11px;
  font-size:12px;box-shadow:0 6px 18px rgba(0,0,0,.42)}
.ws-toast.ok{border-color:#1f5b34}.ws-toast.err{border-color:#5b2126}
.ws-issue{padding:7px 10px;border-bottom:1px solid var(--ws-line);cursor:pointer;min-height:34px}
.ws-issue:hover{background:var(--ws-panel2)}
.ws-issue .c{font-size:10px;color:var(--ws-dim);letter-spacing:.05em}
.ws-issue .d{font-size:12px}
.ws-empty{padding:22px 14px;text-align:center;color:var(--ws-dim);font-size:12px}
.ws-degraded{position:absolute;inset:0;display:none;align-items:center;justify-content:center;
  padding:20px;text-align:center;background:#161013;color:#fecaca;font-size:13px;z-index:8}
.ws-degraded.on{display:flex}
.ws-loading{position:absolute;inset:0;display:none;align-items:center;justify-content:center;
  background:rgba(10,13,18,.86);color:var(--ws-dim);z-index:7;font-size:12px}
.ws-loading.on{display:flex}
.ws-tabs{display:flex;gap:2px;padding:6px 8px 0;border-bottom:1px solid var(--ws-line);overflow-x:auto}
.ws-tab{padding:6px 10px;border-radius:8px 8px 0 0;border:1px solid transparent;cursor:pointer;
  font-size:11px;color:var(--ws-dim);background:transparent;min-height:32px;white-space:nowrap}
.ws-tab.on{background:var(--ws-panel2);border-color:var(--ws-line);border-bottom-color:var(--ws-panel2);color:var(--ws-txt)}
.ws-ref{display:flex;gap:8px;align-items:center;padding:7px 10px;border-bottom:1px solid var(--ws-line)}
.ws-ref img{width:46px;height:46px;object-fit:cover;border-radius:6px;background:var(--ws-panel2)}
.ws-diff{font:11px/1.6 ui-monospace,SFMono-Regular,Menlo,monospace;padding:7px 10px}
.ws-diff .a{color:#fca5a5}.ws-diff .b{color:#86efac}
.ws-preview-badge{position:absolute;inset-block-start:10px;inset-inline-start:10px;background:var(--ws-edit);
  color:#1a1206;font-weight:800;font-size:11px;padding:4px 9px;border-radius:999px;z-index:6;display:none}
.ws-preview-badge.on{display:block}
@media (max-width:1023px){
  .ws-main{grid-template-columns:minmax(0,1fr)}
  .ws-pane.left,.ws-pane.right{position:absolute;z-index:12}
  .ws-pane.left{inset-block:0;inset-inline-start:0;width:min(84vw,300px);transform:translateX(-104%);
    transition:transform .18s;border-inline-end:1px solid var(--ws-line)}
  [dir="rtl"] .ws-pane.left{transform:translateX(104%)}
  .ws-pane.left.on{transform:none}
  .ws-pane.right{inset-inline:0;bottom:0;max-height:62%;border-radius:14px 14px 0 0;
    border-top:1px solid var(--ws-line);transform:translateY(104%);transition:transform .18s}
  .ws-pane.right.on{transform:none}
  .ws-main{position:relative}
}
@media (max-width:767px){
  /* رقم المراجعة معروض في شريط الحالة أصلاً، فإخفاؤه هنا يقصّر شريط الأدوات
     دون أن تختفي أي معلومة. الأزرار العشرة بمقاس لمس 44px لا تتّسع في 390px،
     فالشريط يبقى قابلاً للتمرير أفقياً — لا يُخفى منه زرّ ولا يُقصّ. */
  .ws-rev{display:none}
  .ws-proj{max-width:34vw}
  .ws-btn{min-height:var(--ws-hit);min-width:var(--ws-hit)}
  .ws-top{gap:6px}
  .ws-row{min-height:var(--ws-hit)}
}
"""

DOM = r"""<div id="acsWorkspace" role="application" aria-label="AI Construction Studio workspace">
  <div class="ws-top" role="toolbar" aria-label="Workspace toolbar">
    <span class="ws-brand">ACS</span>
    <span class="ws-proj" id="wsProjName" data-ws="project-name">—</span>
    <span class="ws-rev" id="wsRev" data-ws="revision" title="Current revision">—</span>
    <span class="ws-sp"></span>
    <button class="ws-btn" id="wsBtnTree" aria-label="Toggle project tree" title="Project tree (B)">☰</button>
    <button class="ws-btn" id="wsBtnMode" aria-label="Toggle edit mode" title="View / Edit mode (E)"
      aria-pressed="false" data-ws="mode-toggle">👁 <span id="wsModeLbl">VIEW</span></button>
    <button class="ws-btn" id="wsBtnUndo" aria-label="Undo" title="Undo (Ctrl+Z)" disabled>↶</button>
    <button class="ws-btn" id="wsBtnRedo" aria-label="Redo" title="Redo (Ctrl+Shift+Z)" disabled>↷</button>
    <button class="ws-btn" id="wsBtnHistory" aria-label="Revision history" title="Revision history">⏱</button>
    <button class="ws-btn" id="wsBtnIssues" aria-label="Issue center" title="Issue center">⚠ <span id="wsIssueN">0</span></button>
    <button class="ws-btn" id="wsBtnAI" aria-label="Assistant" title="Assistant">✦</button>
    <button class="ws-btn" id="wsBtnExport" aria-label="Export center" title="Export">⤓</button>
    <button class="ws-btn" id="wsBtnLang" aria-label="Switch language" title="Language">ع/EN</button>
    <button class="ws-btn" id="wsBtnInsp" aria-label="Toggle inspector" title="Inspector (I)">▤</button>
  </div>

  <div class="ws-main">
    <aside class="ws-pane left" id="wsTreePane" aria-label="Project tree">
      <h3 id="wsTreeTitle">Project</h3>
      <div class="ws-filters" id="wsTreeFilters" role="group" aria-label="Discipline filters"></div>
      <div class="ws-scroll" id="wsTree" role="tree" aria-label="Project structure" tabindex="0"></div>
    </aside>

    <section class="ws-view" id="wsViewport" aria-label="3D viewport">
      <div class="ws-view-host" id="wsViewHost"></div>
      <div class="ws-preview-badge" id="wsPreviewBadge">PREVIEW</div>
      <div class="ws-loading" id="wsLoading">…</div>
      <div class="ws-degraded" id="wsDegraded">
        <div><b id="wsDegradedTitle">3D engine unavailable</b><br>
        <span id="wsDegradedBody">The project data, tree, inspector, issues and history stay usable.</span></div>
      </div>
    </section>

    <aside class="ws-pane right" id="wsInspPane" aria-label="Inspector">
      <div class="ws-grab" aria-hidden="true"></div>
      <h3 id="wsInspTitle">Inspector</h3>
      <div class="ws-scroll" id="wsInsp"></div>
    </aside>
  </div>

  <div class="ws-status" role="status" aria-live="polite">
    <span data-ws="status-rev"><i id="wsLblRev">rev</i> <b id="wsStRev">—</b></span>
    <span data-ws="status-level"><i id="wsLblLevel">level</i> <b id="wsStLevel">All</b></span>
    <span data-ws="status-mode"><i id="wsLblMode">mode</i> <b id="wsStMode">VIEW</b></span>
    <span data-ws="status-nav"><i id="wsLblNav">nav</i> <b id="wsStNav">ORBIT</b></span>
    <span class="ws-pill" id="wsStSaved">unsaved</span>
    <span class="ws-pill err" id="wsStErr">0 errors</span>
    <span class="ws-pill warn" id="wsStWarn">0 warnings</span>
    <span class="ws-pill info" id="wsStInfo">0 info</span>
    <span class="ws-pill" id="wsStPreview">no preview</span>
    <span class="ws-sp"></span>
    <span data-ws="compliance"><i id="wsLblCompliance">compliance</i> <b id="wsStCompliance">NOT_EVALUATED</b></span>
  </div>
</div>

<div class="ws-modal" id="wsModal" role="dialog" aria-modal="true" aria-labelledby="wsModalTitle">
  <div class="ws-card">
    <h2 id="wsModalTitle">—</h2>
    <div class="sub" id="wsModalSub"></div>
    <div id="wsModalBody"></div>
    <div class="ws-actions" id="wsModalActions"></div>
  </div>
</div>
<div class="ws-toasts" id="wsToasts" aria-live="polite" aria-atomic="false"></div>
"""

BODY = r"""const ACS_WORKSPACE_SPEC = __SPEC__;
const WS_SCHEMA = ACS_WORKSPACE_SPEC.schema;
const WS_VERSION = ACS_WORKSPACE_SPEC.version;
const WS_STATE_CLASSES = ACS_WORKSPACE_SPEC.state_classes;
const WS_STATE_OWNERSHIP = ACS_WORKSPACE_SPEC.state_ownership;
const WS_PANELS = ACS_WORKSPACE_SPEC.panels;
const WS_BREAKPOINTS = ACS_WORKSPACE_SPEC.breakpoints;
const WS_TREE_KINDS = ACS_WORKSPACE_SPEC.tree_node_kinds;
const WS_TREE_DISCIPLINES = ACS_WORKSPACE_SPEC.tree_disciplines;
const WS_EDITABILITY = ACS_WORKSPACE_SPEC.editability_classes;
const WS_UNKNOWN_LABEL = ACS_WORKSPACE_SPEC.unknown_label;
const WS_PROVENANCE = ACS_WORKSPACE_SPEC.provenance_labels;
const WS_FORBIDDEN_PROV = ACS_WORKSPACE_SPEC.forbidden_provenance_labels;
const WS_UI_MODES = ACS_WORKSPACE_SPEC.ui_modes;
const WS_ELEMENT_OPS = ACS_WORKSPACE_SPEC.element_operations;
const WS_ISSUE_CATEGORIES = ACS_WORKSPACE_SPEC.issue_categories;
const WS_ISSUE_SEVERITIES = ACS_WORKSPACE_SPEC.issue_severities;
const WS_RULE_STATUSES = ACS_WORKSPACE_SPEC.rule_statuses;
const WS_FORBIDDEN_STATUS = ACS_WORKSPACE_SPEC.forbidden_status_words;
const WS_REQUIREMENT_CLASSES = ACS_WORKSPACE_SPEC.requirement_classes;
const WS_EXPORT_KINDS = ACS_WORKSPACE_SPEC.export_kinds;
const WS_EXPORT_SOURCES = ACS_WORKSPACE_SPEC.export_sources;
const WS_REFERENCE_KINDS = ACS_WORKSPACE_SPEC.reference_kinds;
const WS_REFERENCE_SCOPES = ACS_WORKSPACE_SPEC.reference_scopes;
const WS_VISUAL_INTENT_FIELDS = ACS_WORKSPACE_SPEC.visual_intent_fields;
const WS_ASSISTANT_CAPS = ACS_WORKSPACE_SPEC.assistant_capabilities;
const WS_CLAIM_CLASSES = ACS_WORKSPACE_SPEC.assistant_claim_classes;
const WS_CAMERA_PRESETS = ACS_WORKSPACE_SPEC.camera_presets;
const WS_MEASUREMENT_KINDS = ACS_WORKSPACE_SPEC.measurement_kinds;
const WS_DISPLAY_UNITS = ACS_WORKSPACE_SPEC.display_units;
const WS_CANONICAL_UNIT = ACS_WORKSPACE_SPEC.canonical_unit;
const WS_LANGUAGES = ACS_WORKSPACE_SPEC.languages;
const WS_REFERENCE_UNSAFE = ACS_WORKSPACE_SPEC.reference_unsafe_patterns;
/* مصدر مرجع أو تعليقه لا حاجة فيه لوسم أو شيفرة — يُرفض صراحةً */
function _wsAllowedRefUri(v){
  /* مصدر مرجع مقبول بقائمة سماح. أي مخطّط آخر مرفوض افتراضاً، فلا ننتظر
     إضافة نمط هجوم جديد إلى قائمة حظر قبل أن نرفضه. */
  if(typeof v!=='string'||!v) return false;
  const low=v.trim().toLowerCase();
  if(_wsUnsafeRef(low)) return false;
  if(low.indexOf('https:')===0||low.indexOf('http:')===0||low.indexOf('blob:')===0)
    return true;
  if(low.indexOf('data:')===0)
    return low.indexOf('data:image/')===0&&low.indexOf(';base64,')>=0
      &&low.split(',')[0].indexOf('svg')<0;
  if(low.split('/')[0].indexOf(':')>=0) return false;
  return /^[a-z0-9._~/-]+$/.test(low); }
function _wsUnsafeRef(){ const j=Array.prototype.slice.call(arguments)
  .map(v=>String(v===null||v===undefined?'':v)).join(' ').toLowerCase();
  return WS_REFERENCE_UNSAFE.some(p=>j.indexOf(String(p).toLowerCase())>=0); }
const WS_SHORTCUTS = ACS_WORKSPACE_SPEC.shortcuts;
const WS_NOT_SPECIFIED = 'NOT_SPECIFIED';

/* ------------------------------------------------------------ أدوات --- */
function _wsCopy(v){ return (v&&typeof v==='object')?JSON.parse(JSON.stringify(v)):v; }
/* قراءة قيمة من مسار مسطّح مثل floors.g.rooms[0].name — للعرض فقط */
function _wsAtPath(obj,path){ let cur=obj;
  String(path).split('.').forEach(seg=>{
    if(cur===undefined||cur===null) return;
    const m=/^([^\[]*)((\[\d+\])*)$/.exec(seg);
    if(!m){ cur=undefined; return; }
    if(m[1]) cur=cur[m[1]];
    const idx=(m[2]||'').match(/\d+/g)||[];
    idx.forEach(i=>{ cur=(cur===undefined||cur===null)?undefined:cur[Number(i)]; }); });
  return cur; }
function _wsNum(v){ return _auNum(v); }
function wsLabel(key,lang){
  const lg=(WS_LANGUAGES.indexOf(lang)>=0)?lang:'en';
  const e=WS_PROVENANCE[key];
  return e?e[lg]:WS_PROVENANCE.unknown[lg]; }
function wsIsForbiddenLabel(t){
  const s=String(t).trim().toLowerCase();
  return WS_FORBIDDEN_PROV.some(f=>String(f).trim().toLowerCase()===s); }
function wsResolveProvenanceLabel(source,lang){
  const s=String(source===null||source===undefined?'':source).trim().toLowerCase();
  const map={imported:'imported',user:'user',stated:'user',ai:'ai_inference',
    ai_inference:'ai_inference',llm:'ai_inference',inferred:'geometry_inference',
    geometry:'geometry_inference',derived:'derived',system_default:'system_default',
    'default':'system_default',unknown:'unknown'};
  const key=Object.prototype.hasOwnProperty.call(map,s)?map[s]:'unknown';
  const out=wsLabel(key,lang);
  return wsIsForbiddenLabel(out)?wsLabel('unknown',lang):out; }
/* String في جافاسكربت تنتج صيغة أسّية عند 1e21 فما فوق ("1e+21") بينما
   str(int(...)) في بايثون تنتج التوسّع العشري الكامل، فينحرف نصّ العرض بين
   التطبيقين عند القيم الضخمة. BigInt تعطي نفس توسّع بايثون بالضبط. */
function _wsIntStr(n){
  if(Math.abs(n)>=1e21){ try{ return BigInt(n).toString(); }catch(e){ return String(n); } }
  return String(n); }
function _wsFormat(v){
  if(typeof v==='boolean') return v?'true':'false';
  if(typeof v==='number'){ const n=_wsNum(v);
    if(n===null) return String(v);
    return Number.isInteger(n)?_wsIntStr(n)
      :n.toFixed(Number(ACS_WORKSPACE_SPEC.display_decimals)); }
  if(v&&typeof v==='object') return JSON.stringify(v);
  return String(v); }
function wsDisplayValue(value,editability,lang){
  const lg=(WS_LANGUAGES.indexOf(lang)>=0)?lang:'en';
  if(value===null||value===undefined||value===WS_NOT_SPECIFIED||editability==='UNKNOWN')
    return {text:WS_UNKNOWN_LABEL[lg],known:false,editability:editability,raw:null};
  return {text:_wsFormat(value),known:true,editability:editability,raw:value}; }
function wsConvertDisplay(valueM,unit){
  const n=_wsNum(valueM);
  if(n===null||WS_DISPLAY_UNITS.indexOf(unit)<0)
    return {value:null,unit:WS_CANONICAL_UNIT,converted:false,writes_to_model:false};
  let out=n;
  if(unit==='METRIC_CM') out=n*100;
  else if(unit==='IMPERIAL_FT') out=n/0.3048;
  return {value:_pyRound(out,6),unit:unit,canonical_m:n,
    converted:unit!==WS_CANONICAL_UNIT,writes_to_model:false}; }

/* ------------------------------------------------------ شجرة المشروع - */
function wsProjectTree(project,arch,coordination,lang){
  const model=project.model, bid=project.building_id||'bld_0';
  /* أسماء المجموعات نصّ واجهة لا بيانات نموذج، فتُترجَم من المواصفة وحدها؛
     أسماء المستعمل (اسم المشروع، اسم الفراغ) تبقى كما كتبها هو */
  const _L=k=>{ const e=ACS_WORKSPACE_SPEC.ui_labels[k];
    return e[(WS_LANGUAGES.indexOf(lang)>=0)?lang:ACS_WORKSPACE_SPEC.default_language]; };
  const levels=(model.levels||[]).slice().sort((a,b)=>{
    const ai=(a.index===null||a.index===undefined)?1e9:a.index;
    const bi=(b.index===null||b.index===undefined)?1e9:b.index;
    return ai-bi; });
  const byT={};
  _auAllRooms(model).forEach(p=>{ if(!byT[p[0]]) byT[p[0]]=[]; byT[p[0]].push(p[1]); });
  const node=(nid,kind,name,disc,children,meta)=>({node_id:nid,kind:kind,name:name,
    discipline:(disc===undefined)?null:disc,children:children||[],
    selectable:['SPACE','DOOR','WINDOW','OBJECT','LEVEL','SITE','BUILDING'].indexOf(kind)>=0,
    meta:meta||{}});
  const levelNodes=[];
  levels.forEach(lv=>{
    const tmpl=lv.template, idx=lv.index;
    const rooms=(byT[tmpl]||[]).slice().sort((a,b)=>_scmp(String(a.id),String(b.id)));
    const sp=[],dr=[],wn=[],ob=[];
    rooms.forEach(r=>{
      const rid=String(r.id);
      sp.push(node(bid+'.'+tmpl+'.'+rid,'SPACE',r.name||rid,'ARCHITECTURE',null,
        {template:tmpl,level_index:idx,space_id:rid}));
      (r.doors||[]).forEach((op,j)=>dr.push(node(bid+'.'+tmpl+'.'+rid+'.door_'+j,'DOOR',
        rid+' · '+_L('t_door')+' '+j,'ARCHITECTURE',null,
        {space_id:rid,level_index:idx,edge:op.edge})));
      (r.windows||[]).forEach((op,j)=>wn.push(node(bid+'.'+tmpl+'.'+rid+'.window_'+j,'WINDOW',
        rid+' · '+_L('t_window')+' '+j,'ARCHITECTURE',null,
        {space_id:rid,level_index:idx,edge:op.edge})));
      (r.objects||[]).forEach((o,j)=>ob.push(node(tmpl+'.'+rid+'.obj_'+j,'OBJECT',
        rid+' · '+o.kind,'ARCHITECTURE',null,
        {space_id:rid,level_index:idx,object_kind:o.kind}))); });
    const groups=[];
    if(sp.length) groups.push(node(bid+'.flr_'+idx+'.spaces','GROUP',_L('t_spaces'),
      'ARCHITECTURE',sp,{count:sp.length}));
    if(dr.length) groups.push(node(bid+'.flr_'+idx+'.doors','GROUP',_L('t_doors'),
      'ARCHITECTURE',dr,{count:dr.length}));
    if(wn.length) groups.push(node(bid+'.flr_'+idx+'.windows','GROUP',_L('t_windows'),
      'ARCHITECTURE',wn,{count:wn.length}));
    if(ob.length) groups.push(node(bid+'.flr_'+idx+'.objects','GROUP',_L('t_objects'),
      'ARCHITECTURE',ob,{count:ob.length}));
    levelNodes.push(node(bid+'.flr_'+idx,'LEVEL',lv.name||(_L('t_level')+' '+idx),
      'ARCHITECTURE',groups,{level_index:idx,template:tmpl})); });
  const discGroups=[];
  if(arch){ const walls=arch.walls||[];
    if(walls.length) discGroups.push(node(bid+'.derived.walls','GROUP',_L('t_walls_derived'),
      'ARCHITECTURE',[],{count:walls.length,derived:true})); }
  /* المفتاح القانوني للإنشاء في هذا النموذج هو structural؛ يُقبل الاسمان */
  [[['structural','structure'],'STRUCTURE_GROUP','STRUCTURE','t_structure'],
   [['mep'],'MEP_GROUP','MEP','t_mep'],
   [['fls'],'FLS_GROUP','FLS','t_fls']].forEach(e=>{
    const key=e[0].filter(k=>model[k])[0]||e[0][0];
    const present=model[key];
    if(present){ let count=0;
      if(present&&typeof present==='object'&&!Array.isArray(present))
        Object.keys(present).forEach(k=>{ if(Array.isArray(present[k])) count+=present[k].length; });
      discGroups.push(node(bid+'.'+key,e[1],_L(e[3]),e[2],[],
        {count:count,authorable:false})); } });
  if(coordination){
    const f=(coordination.clashes||[]).concat(coordination.penetrations||[])
      .concat(coordination.clearance_issues||[]).concat(coordination.semantic_conflicts||[]);
    discGroups.push(node(bid+'.coordination','COORDINATION_GROUP',_L('t_coordination'),
      'COORDINATION',[],{count:f.length,derived:true})); }
  const building=node(bid,'BUILDING',((model.meta||{}).name)||bid,null,
    levelNodes.concat(discGroups),{levels:levels.length});
  const site=node('site','SITE',_L('t_site'),'ARCHITECTURE',[building],
    {w:(model.site||{}).w,d:(model.site||{}).d});
  const root=node('project','PROJECT',((model.meta||{}).name)||_L('t_project'),null,[site],
    {revision:project.current_revision,model_hash:String(project.model_hash).slice(0,24)});
  const count=n=>1+n.children.reduce((s,c)=>s+count(c),0);
  const total=count(root);
  return {schema:WS_SCHEMA,root:root,node_count:total,
    /* مفتاح غائب في جافاسكربت يختفي من JSON؛ بايثون تكتب null. الشكل واحد */
    levels:levels.map(lv=>({index:(lv.index===undefined)?null:lv.index,
      name:(lv.name===undefined)?null:lv.name,
      template:(lv.template===undefined)?null:lv.template})),
    disciplines:WS_TREE_DISCIPLINES.slice(),
    virtualise:total>Number(ACS_WORKSPACE_SPEC.tree_virtualisation_threshold),
    writes_to_model:false,
    note:'every node carries a real identifier from the canonical model or a compiler '+
         'output; there is no placeholder node'}; }

function wsFlattenTree(tree,expanded,disciplineFilter,levelFilter){
  const exp=new Set(expanded||[]);
  const rows=[];
  const walk=(n,depth,visible)=>{
    const discOk=(!disciplineFilter||!disciplineFilter.length||n.discipline===null
      ||disciplineFilter.indexOf(n.discipline)>=0);
    const lvl=n.meta.level_index;
    const levelOk=(levelFilter===null||levelFilter===undefined
      ||lvl===null||lvl===undefined||lvl===levelFilter);
    const show=visible&&discOk&&levelOk;
    if(show) rows.push({node_id:n.node_id,kind:n.kind,name:n.name,depth:depth,
      discipline:n.discipline,has_children:n.children.length>0,
      expanded:exp.has(n.node_id),selectable:n.selectable});
    const childVisible=show&&(exp.has(n.node_id)||depth===0);
    n.children.forEach(c=>walk(c,depth+1,childVisible)); };
  walk(tree.root,0,true);
  return {rows:rows,row_count:rows.length,writes_to_model:false}; }

/* ------------------------------------------------------------ الفاحص - */
function _wsDisciplineOf(kind){
  if(['SPACE','DOOR','WINDOW','OBJECT','LEVEL','WALL'].indexOf(kind)>=0) return 'ARCHITECTURE';
  if(['SITE','BUILDING'].indexOf(kind)>=0) return 'SITE';
  return null; }
function _wsLevelOf(res,model){
  if(res.kind==='LEVEL') return res.level_index;
  const t=res.template;
  if(t===null||t===undefined) return null;
  let out=null;
  (model.levels||[]).forEach(lv=>{ if(lv.template===t&&out===null) out=lv.index; });
  return out; }
function _wsRelationships(model,res,arch,bid){
  const out=[]; const kind=res.kind;
  if(kind==='SPACE'){
    const room=_auFindRoom(model,res.template,res.room_id);
    [['doors','HOSTS_DOOR','door'],['windows','HOSTS_WINDOW','window'],
     ['objects','CONTAINS_OBJECT','obj']].forEach(e=>{
      (room[e[0]]||[]).forEach((x,j)=>{
        const nid=(e[0]==='objects')?(res.template+'.'+res.room_id+'.obj_'+j)
          :(bid+'.'+res.template+'.'+res.room_id+'.'+e[2]+'_'+j);
        out.push({relation:e[1],target_id:nid,resolved:true}); }); });
  } else if(kind==='DOOR'||kind==='WINDOW'){
    out.push({relation:'HOSTED_BY_SPACE',
      target_id:bid+'.'+res.template+'.'+res.room_id,resolved:true});
    let host=null;
    if(arch) (arch.openings||[]).forEach(op=>{
      if(host===null&&String(op.space_id||'').slice(-res.room_id.length)===res.room_id)
        host=op.host_wall_id; });
    out.push({relation:'HOSTED_BY_WALL',target_id:host,resolved:host!==null});
  } else if(kind==='OBJECT'){
    out.push({relation:'CONTAINED_BY_SPACE',
      target_id:bid+'.'+res.template+'.'+res.room_id,resolved:true}); }
  return out; }
function _wsElementIssues(project,targetId,res,coordination,bid){
  const out=[];
  const integ=auValidateModelIntegrity(project.model,bid);
  let key=null;
  if(res.kind==='SPACE') key=res.template+'.'+res.room_id;
  else if(res.kind==='DOOR'||res.kind==='WINDOW')
    key=res.template+'.'+res.room_id+'.'+res.kind.toLowerCase()+'_'+res.opening_index;
  integ.issues.forEach(i=>{
    if(key&&String(i.subject===null?'':i.subject).indexOf(key)===0)
      out.push({category:'MODEL_INTEGRITY',code:i.code,severity:i.severity,
        detail:i.detail}); });
  if(coordination&&key) (coordination.clashes||[]).forEach(c=>{
    if(targetId===c.element_a||targetId===c.element_b)
      out.push({category:'COORDINATION',code:c.type,
        severity:c.severity||'WARNING',detail:c.note}); });
  return out; }

function wsAvailableOperations(kind,locked){
  const ops=(WS_ELEMENT_OPS[kind]||['INSPECT']).slice();
  return ops.map(op=>{
    if(op==='INSPECT') return {operation:op,enabled:true,reason:null,command_type:null};
    let enabled=true, reason=null;
    if(locked){ enabled=false; reason='TARGET_LOCKED'; }
    else if(AU_IMPLEMENTED.indexOf(op)<0){ enabled=false; reason='COMMAND_NOT_IMPLEMENTED'; }
    return {operation:op,enabled:enabled,reason:reason,
      command_type:(AU_COMMAND_TYPES.indexOf(op)>=0)?op:null}; }); }

const _WS_GEOM_KEYS=['rect','offset','edge','x','z','area_m2','width_m','height_m',
  'sill_m','position','rotation_deg','w','d','start','end','length_m','axis','elevation_m'];
function wsInspectorModel(project,targetId,arch,visualScene,coordination,lang){
  const model=project.model, bid=project.building_id||'bld_0';
  const props=auEditableProperties(model,targetId,bid);
  if(!props.valid||!props.properties)
    return {valid:false,issues:props.issues,target_id:targetId,sections:null,
      note:'the target does not resolve to an inspectable element'};
  const p=props.properties;
  const res=auResolveTarget(model,targetId,bid);
  const fields=p.fields.map(f=>{
    const dv=wsDisplayValue(f.value===WS_NOT_SPECIFIED?null:f.value,f.editability,lang);
    return {field:f.field,editability:f.editability,source:f.source,
      provenance_label:wsResolveProvenanceLabel(f.source,lang),display:dv,
      constraints:f.constraints,
      editable:f.editability==='EDITABLE'&&!p.locked}; });
  const identity={id:targetId,kind:p.kind,discipline:_wsDisciplineOf(p.kind),
    level:_wsLevelOf(res,model),locked:p.locked,lock_reason:p.lock_reason};
  const isGeom=f=>_WS_GEOM_KEYS.indexOf(f.field.split('.').pop())>=0;
  return {valid:true,target_id:targetId,identity:identity,
    sections:{IDENTITY:identity,
      GEOMETRY:fields.filter(isGeom),
      PROPERTIES:fields.filter(f=>!isGeom(f)),
      RELATIONSHIPS:_wsRelationships(model,res,arch,bid),
      ISSUES:_wsElementIssues(project,targetId,res,coordination,bid),
      PROVENANCE:fields.map(f=>({field:f.field,source:f.source,
        label:f.provenance_label}))},
    operations:wsAvailableOperations(p.kind,p.locked),
    editable_count:fields.filter(f=>f.editable).length,
    unknown_count:fields.filter(f=>!f.display.known).length,
    derived_count:fields.filter(f=>f.editability==='DERIVED').length,
    writes_to_model:false,compliance:'NOT_EVALUATED',
    note:'an unknown value is reported as not specified and never replaced by a default; '+
         'a derived value is read-only and changes only through its source; a display-only '+
         'value is presentation and never engineering data'}; }

/* -------------------------------------------------- مركز الملاحظات --- */
function wsIssueCenter(project,arch,coordination,runtimeScene,ruleResults,bid){
  const b=bid||project.building_id||'bld_0';
  const cats={}; WS_ISSUE_CATEGORIES.forEach(c=>{cats[c]=[];});
  auValidateModelIntegrity(project.model,b).issues.forEach(i=>{
    cats.MODEL_INTEGRITY.push({code:i.code,severity:i.severity,subject:i.subject,
      detail:i.detail,targets:i.subject?[i.subject]:[]}); });
  if(coordination){
    (coordination.clashes||[]).forEach(c=>{
      cats.COORDINATION.push({code:c.type,severity:c.severity||'WARNING',subject:c.id,
        detail:c.note,targets:[c.element_a,c.element_b].filter(Boolean),
        discipline_pair:[c.discipline_a,c.discipline_b],status:c.status}); });
    (coordination.semantic_conflicts||[]).forEach(c=>{
      cats.UNRESOLVED_RELATIONSHIP.push({code:c.type,severity:c.severity||'WARNING',
        subject:c.id,detail:c.note,
        targets:[c.element_a,c.element_b].filter(Boolean)}); }); }
  if(arch) (arch.openings||[]).forEach(op=>{
    if(op.host_status&&op.host_status!=='resolved')
      cats.UNRESOLVED_RELATIONSHIP.push({code:'OPENING_HOST_UNRESOLVED',
        severity:'WARNING',subject:op.id,detail:op.host_note,targets:[op.id]}); });
  if(runtimeScene){
    const u=((runtimeScene.counts||{}).portals_unresolved)||0;
    if(u) cats.NAVIGATION.push({code:'PORTAL_CONNECTIVITY_UNRESOLVED',severity:'WARNING',
      subject:'walkability.portals',targets:[],
      detail:u+' portal(s) could not have their connectivity derived'}); }
  [[['structural','structure'],'STRUCTURAL_DATA'],[['mep'],'MEP_DATA'],
   [['fls'],'FLS_DATA']].forEach(e=>{
    if(!e[0].some(k=>project.model[k]))
      cats[e[1]].push({code:'DISCIPLINE_NOT_PRESENT',severity:'INFO',subject:e[0][0],
        targets:[],detail:'the model carries no '+e[0][0]+' data'}); });
  if(ruleResults) (ruleResults||[]).forEach(r=>{
    cats.RULE_EVALUATION.push({code:r.rule_id,severity:'INFO',subject:r.rule_id,
      targets:r.targets||[],detail:r.note,
      rule_status:(WS_RULE_STATUSES.indexOf(r.status)>=0)?r.status:'NOT_EVALUATED'}); });
  const counts={};
  WS_ISSUE_CATEGORIES.forEach(c=>{ counts[c]={total:cats[c].length};
    WS_ISSUE_SEVERITIES.forEach(s=>{
      counts[c][s]=cats[c].filter(x=>x.severity===s).length; }); });
  let total=0; WS_ISSUE_CATEGORIES.forEach(c=>{ total+=cats[c].length; });
  return {schema:WS_SCHEMA,categories:cats,counts:counts,total:total,
    rule_evaluation_status:ruleResults?'EVALUATED_SEPARATELY':'NOT_EVALUATED',
    compliance:'NOT_EVALUATED',writes_to_model:false,
    note:'categories are kept apart because they mean different things; severity and '+
         'regulatory status are separate axes and no status here means safe, compliant '+
         'or approved'}; }
function wsIssueTargets(issue){
  const t=(issue.targets||[]).filter(x=>typeof x==='string'&&x);
  return {targets:t,focusable:t.length>0,writes_to_model:false}; }

/* --------------------------------------------- تغطية المتطلّبات ------ */
function wsRequirementCoverage(report,lang){
  const classes={}; WS_REQUIREMENT_CLASSES.forEach(c=>{classes[c]=[];});
  let items=[];
  if(Array.isArray(report)) items=report;
  else if(report&&typeof report==='object') items=report.items||report.requirements||[];
  items.forEach(it=>{
    if(!it||typeof it!=='object'||Array.isArray(it)) return;
    let cls=String(it.status||it['class']||'UNRESOLVED').toUpperCase();
    if(WS_REQUIREMENT_CLASSES.indexOf(cls)<0) cls='UNRESOLVED';
    /* المفتاح الغائب في جافاسكربت يختفي من JSON بينما بايثون تكتب null،
       فالشكل المُعاد يجب أن يكون null صراحةً لا undefined */
    const _n=v=>(v===undefined)?null:v;
    classes[cls].push({text:_n(it.text||it.label),evidence:_n(it.evidence),
      target_ids:it.target_ids||[]}); });
  const counts={}; let total=0;
  WS_REQUIREMENT_CLASSES.forEach(c=>{ counts[c]=classes[c].length; total+=counts[c]; });
  return {classes:classes,counts:counts,total:total,
    unresolved:counts.UNRESOLVED+counts.EXCLUDED,claims_full_coverage:false,
    writes_to_model:false,
    note:'requirements are reported per class. Nothing here states that every requested '+
         'item was implemented; unresolved and excluded items are listed and counted '+
         'separately.'}; }

/* --------------------------------------------- المراجع البصرية ------- */
function wsPresentationContext(project){
  return {schema:WS_SCHEMA,references:[],visual_intent:{},
    project_revision:(project||{}).current_revision,
    is_engineering_data:false,writes_to_model:false,
    note:'visual references and visual intent are presentation context. They are never '+
         'engineering geometry and never enter a model hash.'}; }
function wsAttachReference(context,kind,scope,scopeId,uri,provenance,caption){
  const issues=[];
  const k=(typeof kind==='string')?kind.toUpperCase():null;
  const s=(typeof scope==='string')?scope.toUpperCase():null;
  if(WS_REFERENCE_KINDS.indexOf(k)<0) issues.push({code:'INVALID_PARAMETER',
    severity:'ERROR',subject:kind,detail:'unknown reference kind'});
  if(WS_REFERENCE_SCOPES.indexOf(s)<0) issues.push({code:'INVALID_PARAMETER',
    severity:'ERROR',subject:scope,detail:'unknown reference scope'});
  if(typeof uri!=='string'||!uri) issues.push({code:'INVALID_PARAMETER',severity:'ERROR',
    subject:'uri',detail:'a reference needs a source'});
  else if(_auScan({uri:uri,caption:caption},0,'reference').length
          ||_wsUnsafeRef(uri,caption)||!_wsAllowedRefUri(uri))
    issues.push({code:'PAYLOAD_REJECTED',severity:'ERROR',subject:'uri',
      detail:'the reference carries an unsafe or executable value'});
  if(issues.length) return {valid:false,issues:issues,context:context,reference:null};
  const ref={reference_id:'ref:'+_auSha16({kind:k,scope:s,scope_id:scopeId,uri:uri}),
    kind:k,scope:s,scope_id:scopeId,uri:uri,
    caption:(typeof caption==='string')?caption:null,
    provenance:(typeof provenance==='string')?provenance:'user',
    is_engineering_data:false,affects_geometry:false,
    note:'visual context only; no dimension is inferred from this image'};
  const ctx=_wsCopy(context);
  ctx.references=(ctx.references||[]).concat([ref]);
  return {valid:true,issues:[],context:ctx,reference:ref}; }
function wsSetVisualIntent(context,field,value){
  if(WS_VISUAL_INTENT_FIELDS.indexOf(field)<0)
    return {valid:false,context:context,issues:[{code:'INVALID_PARAMETER',
      severity:'ERROR',subject:field,detail:'unknown visual intent field'}]};
  const probe={}; probe[field]=value;
  if(_auScan(probe,0,'intent').length)
    return {valid:false,context:context,issues:[{code:'PAYLOAD_REJECTED',
      severity:'ERROR',subject:field,detail:'unsafe value'}]};
  const ctx=_wsCopy(context);
  if(!ctx.visual_intent) ctx.visual_intent={};
  ctx.visual_intent[field]=value;
  return {valid:true,context:ctx,issues:[],is_engineering_data:false}; }

/* ---------------------------------------------- حدّ حالة الواجهة ----- */
function wsClassifyStateKey(key){
  return Object.prototype.hasOwnProperty.call(WS_STATE_OWNERSHIP,key)
    ?WS_STATE_OWNERSHIP[key]:null; }
function wsUiStateDefault(){
  return {selected_id:null,hovered_id:null,tree_expanded:[],
    active_panel:ACS_WORKSPACE_SPEC.default_panel,
    language:ACS_WORKSPACE_SPEC.default_language,theme:'dark',
    ui_mode:ACS_WORKSPACE_SPEC.default_ui_mode,level_filter:null,
    discipline_filter:[],issue_filter:null,reference_panel_open:false,
    display_unit:WS_CANONICAL_UNIT,writes_to_model:false}; }
function wsModelHashOf(project){
  return auModelHash(project.model,'building',project.building_id||'bld_0'); }
function wsAssertUiStateExcluded(project,uiState){
  const before=wsModelHashOf(project);
  const leaked=[];
  Object.keys(uiState).sort(_scmp).forEach(k=>{
    const owner=wsClassifyStateKey(k);
    if(['UI_STATE','RUNTIME_STATE','PRESENTATION_OUTPUT'].indexOf(owner)>=0
       &&Object.prototype.hasOwnProperty.call(project.model,k)) leaked.push(k); });
  const after=wsModelHashOf(project);
  return {model_hash_before:before,model_hash_after:after,unchanged:before===after,
    leaked_keys:leaked,clean:before===after&&leaked.length===0}; }

/* ------------------------------------------------------------ التصدير */
function wsExportDescriptor(project,kind,source,view,createdAt){
  const issues=[];
  const k=(typeof kind==='string')?kind.toUpperCase():null;
  const s=(typeof source==='string')?source.toUpperCase():'COMMITTED';
  if(WS_EXPORT_KINDS.indexOf(k)<0) issues.push({code:'INVALID_PARAMETER',
    severity:'ERROR',subject:kind,detail:'unknown export kind'});
  if(WS_EXPORT_SOURCES.indexOf(s)<0) issues.push({code:'INVALID_PARAMETER',
    severity:'ERROR',subject:source,detail:'unknown export source'});
  if(issues.length) return {valid:false,issues:issues,descriptor:null};
  const name=String(((project.model.meta||{}).name)||'project');
  let safe=''; for(const ch of name){ if(/[A-Za-z0-9_-]/.test(ch)) safe+=ch; }
  if(!safe) safe='project';
  const rev=String(project.current_revision||'').replace(/:/g,'_');
  const prefix=(s==='PREVIEW')?'PREVIEW_':'';
  const ext={PROJECT_JSON:'json',GLB:'glb',SNAPSHOT_PNG:'png',
    REVISION_HISTORY_JSON:'json',ISSUE_REPORT_JSON:'json'}[k];
  return {valid:true,issues:[],descriptor:{kind:k,source:s,is_preview:s==='PREVIEW',
    filename:prefix+safe+'_'+rev+'.'+ext,
    metadata:{project_name:name,revision_id:project.current_revision,
      model_hash:project.model_hash,view:(view===undefined)?null:view,source:s,
      created_at:(createdAt===undefined)?null:createdAt},
    certifies_nothing:true,
    note:'an export is a presentation output taken from the named revision. It implies '+
         'no certification, approval or compliance.'}}; }

/* ------------------------------------------------------ مساعد المنتج */
function wsAssistantClaim(kind,text,evidence){
  let k=(typeof kind==='string')?kind.toUpperCase():null;
  if(WS_CLAIM_CLASSES.indexOf(k)<0) k='UNKNOWN';
  return {claim_class:k,text:text,evidence:(evidence===undefined)?null:evidence,
    is_engineering_authority:false,
    note:'a claim class states what kind of statement this is; an inference is never '+
         'presented as a model fact'}; }
function wsAssistantProposeEdit(project,phrase,command,rationale){
  const bid=project.building_id||'bld_0';
  const target=phrase?auResolveNlTarget(project.model,phrase,bid):null;
  if(target&&!target.valid)
    return {valid:false,issues:target.issues,candidates:target.candidates||[],
      proposal:null,committed:false,
      note:'target resolution did not produce a single element; the user must choose. '+
           'Nothing is guessed and nothing is committed.'};
  const prop=auProposeCommand(command,rationale,null);
  return {valid:prop.valid,issues:prop.issues,
    candidates:(target||{}).candidates||[],proposal:prop.proposal||null,
    committed:false,requires_explicit_confirmation:true,
    note:'a proposal is not a commit; applying it still passes the full authoring '+
         'validation, revision guard and explicit confirmation'}; }

function wsWorkspaceSummary(project,uiState,tree,issues){
  const ui=uiState||wsUiStateDefault();
  return {schema:WS_SCHEMA,version:WS_VERSION,
    ui_version:ACS_WORKSPACE_SPEC.compiler_version,
    project_name:(project.model.meta||{}).name,
    current_revision:project.current_revision,
    model_hash:String(project.model_hash).slice(0,24),
    revisions:(project.history||[]).length,
    ui_mode:ui.ui_mode,language:ui.language,selected_id:ui.selected_id,
    tree_nodes:(tree||{}).node_count,issue_total:(issues||{}).total,
    compliance:'NOT_EVALUATED',ui_writes_to_model:false,
    runtime_writes_to_model:false,
    note:'the workspace reads engine outputs and calls canonical APIs; it performs no '+
         'engineering calculation of its own'}; }

/* ============================================================================
   وحدة تحكّم مساحة العمل — تقرأ نماذج العرض أعلاه وتستدعي واجهات المرحلة 5.
   لا حساب هندسي هنا، ولا كتابة في النموذج، ولا تجاوز لأي بوّابة.
   ========================================================================== */
const WS = (function(){
  const S = {project:null, ui:null, tree:null, issues:null, arch:null,
             coordination:null, runtimeScene:null, visualScene:null,
             presentation:null, preview:null, previewCommand:null,
             exported:true, degraded:false, ready:false};
  const $ = id => (typeof document!=='undefined')?document.getElementById(id):null;
  /* جدول النصوص مصدره المواصفة القانونية وحدها — لا جدول ثانٍ داخل الواجهة،
     كي لا ينحرف النصّ العربي عن الإنجليزي (§16/§88/§89) */
  const T = (function(){
    const out={}; WS_LANGUAGES.forEach(lg=>{ out[lg]={}; });
    Object.keys(ACS_WORKSPACE_SPEC.ui_labels).forEach(k=>{
      const e=ACS_WORKSPACE_SPEC.ui_labels[k];
      WS_LANGUAGES.forEach(lg=>{ out[lg][k]=e[lg]; }); });
    return out; })();
  const t = k => (T[(S.ui&&S.ui.language)||ACS_WORKSPACE_SPEC.default_language]
                  ||T[ACS_WORKSPACE_SPEC.default_language])[k]||k;
  const esc = s => String(s===null||s===undefined?'':s)
    .replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')
    .replace(/"/g,'&quot;').replace(/'/g,'&#39;');

  /* ------------------------------------------------------------ توست - */
  function toast(kind,msg){
    const host=$('wsToasts'); if(!host) return;
    const d=document.createElement('div');
    d.className='ws-toast'+(kind==='COMMAND_REJECTED'?' err':' ok');
    d.textContent=msg; d.setAttribute('data-ws-toast',kind);
    host.appendChild(d);
    setTimeout(()=>{ if(d.parentNode) d.parentNode.removeChild(d); },4200); }

  /* --------------------------------------------------------- الحوارات */
  function modal(title,sub,bodyHtml,actions){
    const m=$('wsModal'); if(!m) return;
    $('wsModalTitle').textContent=title;
    $('wsModalSub').textContent=sub||'';
    $('wsModalBody').innerHTML=bodyHtml||'';
    const a=$('wsModalActions'); a.innerHTML='';
    (actions||[]).forEach(act=>{
      const b=document.createElement('button');
      b.className='ws-btn'+(act.primary?' pri':'')+(act.danger?' danger':'');
      b.textContent=act.label;
      if(act.id) b.id=act.id;
      b.setAttribute('data-ws-action',act.key||act.label);
      b.onclick=()=>{ try{ act.run&&act.run(); }catch(e){ toast('COMMAND_REJECTED',
        String(e&&e.message||e)); } };
      a.appendChild(b); });
    m.classList.add('on'); }
  function closeModal(){ const m=$('wsModal'); if(m) m.classList.remove('on'); }

  /* --------------------------------------------------- إعادة الاشتقاق */
  function rederive(){
    if(!S.project) return;
    const model=S.project.model, bid=S.project.building_id||'bld_0';
    try{ S.arch=compileArchitecture(_wsCopy(model),bid,null,0); }catch(e){ S.arch=null; }
    try{
      const st=compileStructure(_wsCopy(model),bid,null,0,S.arch);
      const mep=compileMep(_wsCopy(model),bid,null,0,S.arch);
      const fls=compileFls(_wsCopy(model),bid,null,0,S.arch,mep);
      S.coordination=compileCoordination(_wsCopy(model),bid,null,0,S.arch,st,mep,fls,null);
    }catch(e){ S.coordination=null; }
    try{ S.visualScene=compileVisualScene(_wsCopy(model),bid,null,0,{mode:'ENGINEERING'});
      S.runtimeScene=compileRuntimeScene(S.visualScene,null);
    }catch(e){ S.visualScene=null; S.runtimeScene=null; }
    S.tree=wsProjectTree(S.project,S.arch,S.coordination,S.ui.language);
    S.issues=wsIssueCenter(S.project,S.arch,S.coordination,S.runtimeScene,null,bid); }

  /* --------------------------------------------------------- التقديم - */
  function renderAll(){ renderChrome(); renderTop(); renderTree();
                       renderInspector(); renderStatus(); }

  /* §16/§88/§89 — نصوص الهيكل الثابت تُترجَم أيضاً، فلا تبقى كلمات إنجليزية
     داخل واجهة عربية ولا العكس. رموز التعداد (VIEW/ORBIT/NOT_EVALUATED)
     تبقى رموزاً في اللغتين لأنها قيم مواصفة لا نثر. */
  function renderChrome(){
    const set=(id,txt)=>{ const e=$(id); if(e) e.textContent=txt; };
    const attr=(id,a,v)=>{ const e=$(id); if(e) e.setAttribute(a,v); };
    set('wsTreeTitle',t('project'));
    set('wsInspTitle',t('inspector'));
    set('wsLblRev',t('rev'));
    set('wsLblLevel',t('level'));
    set('wsLblMode',t('mode'));
    set('wsLblNav',t('nav'));
    set('wsLblCompliance',t('compliance'));
    set('wsPreviewBadge',t('preview'));
    set('wsLoading',t('loading'));
    set('wsDegradedTitle',t('degraded'));
    set('wsDegradedBody',t('degraded_body'));
    attr('wsBtnTree','aria-label',t('tree_toggle'));
    attr('wsBtnTree','title',t('tree_toggle'));
    attr('wsBtnInsp','aria-label',t('insp_toggle'));
    attr('wsBtnInsp','title',t('insp_toggle'));
    attr('wsBtnUndo','aria-label',t('undo'));
    attr('wsBtnUndo','title',t('undo'));
    attr('wsBtnRedo','aria-label',t('redo'));
    attr('wsBtnRedo','title',t('redo'));
    attr('wsBtnHistory','aria-label',t('history'));
    attr('wsBtnHistory','title',t('history'));
    attr('wsBtnIssues','aria-label',t('issues'));
    attr('wsBtnIssues','title',t('issues'));
    attr('wsBtnAI','aria-label',t('assistant'));
    attr('wsBtnAI','title',t('assistant'));
    attr('wsBtnExport','aria-label',t('exportc'));
    attr('wsBtnExport','title',t('exportc'));
    attr('wsBtnLang','aria-label',t('language'));
    attr('wsBtnLang','title',t('language')); }

  function renderTop(){
    if(!$('wsProjName')) return;
    const name=S.project?((S.project.model.meta||{}).name||'Project'):t('noproject');
    $('wsProjName').textContent=name;
    $('wsRev').textContent=S.project?String(S.project.current_revision||'—'):'—';
    $('wsIssueN').textContent=S.issues?String(S.issues.total):'0';
    const mode=(S.ui&&S.ui.ui_mode)||'VIEW';
    $('wsModeLbl').textContent=mode;
    const mb=$('wsBtnMode');
    mb.classList.toggle('on',mode==='EDIT');
    mb.setAttribute('aria-pressed',mode==='EDIT'?'true':'false');
    const canUndo=!!(S.project&&(S.project.history||[]).length>1);
    $('wsBtnUndo').disabled=!canUndo;
    const cur=S.project?(S.project.history||[]).filter(r=>
      r.revision_id===S.project.current_revision)[0]:null;
    $('wsBtnRedo').disabled=!(cur&&cur.reverts_revision_id); }

  function renderTree(){
    const host=$('wsTree'); if(!host) return;
    if(!S.project){ host.innerHTML='<div class="ws-empty">'+esc(t('noproject'))+'</div>';
      return; }
    const flat=wsFlattenTree(S.tree,S.ui.tree_expanded,S.ui.discipline_filter,
      S.ui.level_filter);
    const parts=[];
    flat.rows.forEach(r=>{
      const sel=(r.node_id===S.ui.selected_id)?' sel':'';
      const tw=r.has_children?(r.expanded?'▾':'▸'):'';
      parts.push('<div class="ws-row'+sel+'" role="treeitem" tabindex="-1"'+
        ' data-ws-node="'+esc(r.node_id)+'" data-ws-kind="'+esc(r.kind)+'"'+
        ' aria-selected="'+(sel?'true':'false')+'"'+
        ' style="padding-inline-start:'+(6+r.depth*13)+'px">'+
        '<span class="tw">'+tw+'</span>'+
        '<span class="nm">'+esc(r.name)+'</span>'+
        '<span class="kd">'+esc(r.kind)+'</span></div>'); });
    host.innerHTML=parts.join('');
    Array.prototype.forEach.call(host.querySelectorAll('[data-ws-node]'),el=>{
      el.onclick=()=>{ const id=el.getAttribute('data-ws-node');
        if(el.querySelector('.tw').textContent) toggleNode(id);
        select(id); }; });
    const ft=$('wsTreeFilters');
    if(ft&&!ft.getAttribute('data-built')){
      ft.setAttribute('data-built','1');
      WS_TREE_DISCIPLINES.forEach(d=>{
        const b=document.createElement('button');
        b.className='ws-chip'; b.textContent=d; b.setAttribute('data-ws-filter',d);
        b.setAttribute('aria-pressed','false');
        b.onclick=()=>{ const i=S.ui.discipline_filter.indexOf(d);
          if(i>=0) S.ui.discipline_filter.splice(i,1);
          else S.ui.discipline_filter.push(d);
          b.classList.toggle('on'); b.setAttribute('aria-pressed',
            b.classList.contains('on')?'true':'false');
          renderTree(); };
        ft.appendChild(b); }); } }

  function toggleNode(id){
    const i=S.ui.tree_expanded.indexOf(id);
    if(i>=0) S.ui.tree_expanded.splice(i,1); else S.ui.tree_expanded.push(id); }

  function fieldRow(f){
    const cls={EDITABLE:'editable',DERIVED:'derived',UNKNOWN:'unknown',
      DISPLAY_ONLY:'display',READ_ONLY:'readonly'}[f.editability]||'readonly';
    const lbl={EDITABLE:t('editable'),DERIVED:t('derived'),UNKNOWN:t('unknown'),
      DISPLAY_ONLY:t('display'),READ_ONLY:t('readonly')}[f.editability]||'';
    const val=f.display.known?esc(f.display.text)
      :'<span class="ws-unknown" data-ws-unknown="1">'+esc(f.display.text)+'</span>';
    return '<div class="ws-f" data-ws-field="'+esc(f.field)+'"'+
      ' data-ws-editability="'+esc(f.editability)+'">'+
      '<span class="k">'+esc(f.field)+'</span>'+
      '<span class="v"><span>'+val+'</span>'+
      '<span class="ws-tag '+cls+'">'+esc(lbl)+'</span></span></div>'; }

  function renderInspector(){
    const host=$('wsInsp'); if(!host) return;
    if(!S.project||!S.ui.selected_id){
      host.innerHTML='<div class="ws-empty">'+esc(t('empty'))+'</div>'; return; }
    const m=wsInspectorModel(S.project,S.ui.selected_id,S.arch,S.visualScene,
      S.coordination,S.ui.language);
    if(!m.valid){
      host.innerHTML='<div class="ws-empty">'+esc(t('empty'))+'</div>'; return; }
    const p=[];
    p.push('<div class="ws-sec" data-ws-section="IDENTITY"><h4>IDENTITY</h4>');
    Object.keys(m.identity).forEach(k=>{
      const v=m.identity[k];
      p.push('<div class="ws-f"><span class="k">'+esc(k)+'</span><span class="v"><span>'+
        (v===null||v===undefined
          ?'<span class="ws-unknown" data-ws-unknown="1">'+esc(t('unknown'))+'</span>'
          :esc(String(v)))+'</span></span></div>'); });
    p.push('</div>');
    ['GEOMETRY','PROPERTIES'].forEach(sec=>{
      const list=m.sections[sec]||[];
      if(!list.length) return;
      p.push('<div class="ws-sec" data-ws-section="'+sec+'"><h4>'+sec+'</h4>');
      list.forEach(f=>p.push(fieldRow(f)));
      p.push('</div>'); });
    const rel=m.sections.RELATIONSHIPS||[];
    if(rel.length){
      p.push('<div class="ws-sec" data-ws-section="RELATIONSHIPS"><h4>RELATIONSHIPS</h4>');
      rel.forEach(r=>p.push('<div class="ws-f"><span class="k">'+esc(r.relation)+
        '</span><span class="v"><span>'+(r.resolved?esc(String(r.target_id))
          :'<span class="ws-unknown" data-ws-unknown="1">'+esc(t('unknown'))+'</span>')+
        '</span></span></div>'));
      p.push('</div>'); }
    const iss=m.sections.ISSUES||[];
    p.push('<div class="ws-sec" data-ws-section="ISSUES"><h4>ISSUES ('+iss.length+')</h4>');
    if(!iss.length) p.push('<div class="k" style="color:var(--ws-dim)">—</div>');
    iss.forEach(i=>p.push('<div class="ws-f"><span class="k">'+esc(i.category)+
      '</span><span class="v"><span>'+esc(i.code)+' · '+esc(i.severity)+
      '</span></span></div>'));
    p.push('</div>');
    p.push('<div class="ws-sec" data-ws-section="PROVENANCE"><h4>PROVENANCE</h4>');
    (m.sections.PROVENANCE||[]).slice(0,14).forEach(x=>p.push(
      '<div class="ws-f"><span class="k">'+esc(x.field)+'</span>'+
      '<span class="v"><span data-ws-provenance="1">'+esc(x.label)+'</span></span></div>'));
    p.push('</div>');
    if(S.ui.ui_mode==='EDIT'){
      p.push('<div class="ws-sec" data-ws-section="OPERATIONS"><h4>OPERATIONS</h4>');
      m.operations.forEach(op=>{
        if(op.operation==='INSPECT') return;
        p.push('<button class="ws-btn" style="width:100%;margin:3px 0"'+
          ' data-ws-op="'+esc(op.operation)+'"'+(op.enabled?'':' disabled')+
          ' title="'+esc(op.reason||'')+'">'+esc(op.operation)+'</button>'); });
      p.push('</div>'); }
    /* نصوص الإفصاح التعاقدي تُعرض بالإنجليزية القانونية في اللغتين ولا تُترجَم:
       ترجمتها قد تُزحزح معناها الهندسي. تُوسَم صراحةً كي لا تُحسب خلطاً لغوياً. */
    p.push('<div class="ws-sec"><div class="k" data-ws-note="canonical" lang="en"'+
      ' style="color:var(--ws-dim);font-size:11px">'+esc(m.note)+'</div></div>');
    host.innerHTML=p.join('');
    Array.prototype.forEach.call(host.querySelectorAll('[data-ws-op]'),el=>{
      el.onclick=()=>startOperation(el.getAttribute('data-ws-op')); }); }

  function renderStatus(){
    if(!$('wsStRev')) return;
    $('wsStRev').textContent=S.project?String(S.project.current_revision||'—'):'—';
    $('wsStLevel').textContent=(S.ui.level_filter===null||S.ui.level_filter===undefined)
      ?t('all'):String(S.ui.level_filter);
    $('wsStMode').textContent=S.ui.ui_mode;
    $('wsStNav').textContent=(S.runtimeScene&&S.runtimeScene.defaults)
      ?S.runtimeScene.defaults.navigation_mode:'ORBIT';
    $('wsStSaved').textContent=S.exported?t('exported'):t('unsaved');
    let e=0,w=0,i=0;
    if(S.issues) WS_ISSUE_CATEGORIES.forEach(c=>{
      e+=S.issues.counts[c].ERROR; w+=S.issues.counts[c].WARNING;
      i+=S.issues.counts[c].INFO; });
    $('wsStErr').textContent=e+' '+t('errors');
    $('wsStWarn').textContent=w+' '+t('warnings');
    $('wsStInfo').textContent=i+' '+t('info');
    $('wsStPreview').textContent=S.preview?t('preview_active'):t('no_preview');
    const badge=$('wsPreviewBadge');
    if(badge) badge.classList.toggle('on',!!S.preview); }

  /* ---------------------------------------------------------- التحديد */
  function select(id){
    S.ui.selected_id=id;                       /* UI_STATE — لا يمسّ النموذج */
    renderTree(); renderInspector(); renderStatus();
    if(typeof window!=='undefined'&&window.__ACS_ON_SELECT)
      try{ window.__ACS_ON_SELECT(id); }catch(e){}
    return id; }

  /* ------------------------------------------------------ وضع التحرير */
  function setMode(mode){
    const m=(WS_UI_MODES.indexOf(mode)>=0)?mode:'VIEW';
    S.ui.ui_mode=m;                            /* UI_STATE فقط */
    renderTop(); renderInspector(); renderStatus();
    return m; }
  function toggleMode(){ return setMode(S.ui.ui_mode==='EDIT'?'VIEW':'EDIT'); }

  /* --------------------------------------------- بدء عملية تحرير ---- */
  function startOperation(op){
    if(!S.project||!S.ui.selected_id) return null;
    if(S.ui.ui_mode!=='EDIT'){ toast('COMMAND_REJECTED','EDIT mode required'); return null; }
    const id=S.ui.selected_id;
    const res=auResolveTarget(S.project.model,id,S.project.building_id||'bld_0');
    if(op==='RENAME_SPACE'){
      const room=_auFindRoom(S.project.model,res.template,res.room_id)||{};
      modal(op,id,'<label>name</label><input id="wsIn1" value="'+esc(room.name||'')+'">',
        [{label:t('preview'),primary:true,key:'preview',run:()=>{
            beginPreview({type:'RENAME_SPACE',target_id:id,
              parameters:{name:$('wsIn1').value}}); }},
         {label:t('cancel'),key:'cancel',run:closeModal}]);
    } else if(op==='RESIZE_SPACE'){
      const room=_auFindRoom(S.project.model,res.template,res.room_id)||{};
      const r=room.rect||[0,0,0,0];
      modal(op,id,'<label>width (m)</label><input id="wsIn1" type="number" step="0.1" value="'+
        esc(r[2])+'"><label>depth (m)</label><input id="wsIn2" type="number" step="0.1" value="'+
        esc(r[3])+'">',
        [{label:t('preview'),primary:true,key:'preview',run:()=>{
            beginPreview({type:'RESIZE_SPACE',target_id:id,
              parameters:{w:Number($('wsIn1').value),d:Number($('wsIn2').value)}}); }},
         {label:t('cancel'),key:'cancel',run:closeModal}]);
    } else if(op==='MOVE_DOOR'||op==='MOVE_WINDOW'){
      const room=_auFindRoom(S.project.model,res.template,res.room_id)||{};
      const op0=((room[res.opening_key]||[])[res.opening_index])||{};
      modal(op,id,'<label>offset (m)</label><input id="wsIn1" type="number" step="0.05" value="'+
        esc(op0.offset)+'">',
        [{label:t('preview'),primary:true,key:'preview',run:()=>{
            beginPreview({type:op,target_id:id,
              parameters:{offset:Number($('wsIn1').value)}}); }},
         {label:t('cancel'),key:'cancel',run:closeModal}]);
    } else if(op==='MOVE_WALL'){
      hostedStrategyDialog(id);
    } else if(op&&op.indexOf('DELETE')===0){
      confirmDelete(op,id);
    } else if(op==='MOVE_OBJECT'||op==='MOVE_STAIR'){
      modal(op,id,'<label>x (m)</label><input id="wsIn1" type="number" step="0.1" value="0">'+
        '<label>z (m)</label><input id="wsIn2" type="number" step="0.1" value="0">',
        [{label:t('preview'),primary:true,key:'preview',run:()=>{
            beginPreview({type:op,target_id:id,
              parameters:{x:Number($('wsIn1').value),z:Number($('wsIn2').value)}}); }},
         {label:t('cancel'),key:'cancel',run:closeModal}]);
    } else {
      modal(op,id,'<div class="k">'+esc(op)+'</div>',
        [{label:t('cancel'),key:'cancel',run:closeModal}]); }
    return op; }

  /* -------------------------- §19 استراتيجية الفتحات — بلا خيار مسبق */
  function hostedStrategyDialog(id){
    modal(t('strategy'),id,
      '<label>delta (m)</label><input id="wsIn1" type="number" step="0.05" value="0.25">'+
      '<label>strategy</label><select id="wsIn2" data-ws="hosted-strategy">'+
      '<option value="">—</option>'+
      '<option value="KEEP_RELATIVE_POSITION">'+esc(t('keeprel'))+'</option>'+
      '<option value="KEEP_WORLD_POSITION">'+esc(t('keepworld'))+'</option>'+
      '<option value="CANCEL_IF_HOSTED">'+esc(t('cancelif'))+'</option></select>',
      [{label:t('preview'),primary:true,key:'preview',run:()=>{
          const st=$('wsIn2').value;
          const params={delta_m:Number($('wsIn1').value)};
          if(st) params.hosted_strategy=st;
          beginPreview({type:'MOVE_WALL',target_id:id,parameters:params}); }},
       {label:t('cancel'),key:'cancel',run:closeModal}]); }

  /* --------------------------- §18 حذف: الاعتماديات بالاسم لا بالعموم */
  function confirmDelete(op,id){
    const cmd={type:op,target_id:id,parameters:{}};
    const v=auValidateTransaction(S.project,[cmd],S.project.building_id||'bld_0');
    const txn=v.transaction||{};
    const deps=(txn.dependency_breaking&&txn.dependency_breaking.length)
      ?txn.dependency_breaking:(txn.dependencies||[]);
    const rows=deps.map(d=>'<div class="ws-f"><span class="k">'+esc(d)+
      '</span><span class="v"><span>affected</span></span></div>').join('')
      ||'<div class="k">—</div>';
    const bad=v.issues.filter(i=>i.severity==='ERROR');
    modal(op,id,
      '<div class="ws-sec" data-ws-section="DEPENDENCIES"><h4>'+esc(t('deps'))+
      ' ('+deps.length+')</h4>'+rows+'</div>'+
      (bad.length?'<div class="ws-sec"><h4>ERRORS</h4>'+bad.map(i=>
        '<div class="ws-f"><span class="k">'+esc(i.code)+'</span><span class="v"><span>'+
        esc(i.detail||'')+'</span></span></div>').join('')+'</div>':''),
      [{label:t('commit'),primary:true,danger:true,key:'commit',
        run:()=>{ doCommit([cmd],txn.confirmation_digest,true); }},
       {label:t('cancel'),key:'cancel',run:closeModal}]); }

  /* ------------------------------------------ §16/§17 معاينة حيّة --- */
  function beginPreview(command){
    if(!S.project) return null;
    const bid=S.project.building_id||'bld_0';
    const before=wsModelHashOf(S.project);
    const r=auPreviewCommand(S.project.model,command,null,bid,null,null);
    S.previewCommand=command;
    if(!r.valid){
      S.preview=null;
      showRejection(r.issues);
      renderStatus();
      return r; }
    S.preview=r;
    const txn=auValidateTransaction(S.project,[command],bid);
    const tx=txn.transaction||{};
    const parts=[];
    parts.push('<div class="ws-sec" data-ws-section="SUMMARY"><h4>'+esc(t('preview'))+
      '</h4><div class="ws-f"><span class="k">command</span><span class="v"><span>'+
      esc(command.type)+'</span></span></div>'+
      '<div class="ws-f"><span class="k">base hash</span><span class="v"><span>'+
      esc(String(r.preview.base_model_hash).slice(0,16))+'</span></span></div>'+
      '<div class="ws-f"><span class="k">candidate hash</span><span class="v"><span>'+
      esc(String(r.preview.candidate_model_hash).slice(0,16))+'</span></span></div></div>');
    parts.push('<div class="ws-sec" data-ws-section="AFFECTED"><h4>'+esc(t('affected'))+
      ' ('+r.preview.changed_paths.length+')</h4>'+
      (r.preview.changed_paths.map(p=>'<div class="ws-f"><span class="k">'+esc(p)+
        '</span><span class="v"><span>changed</span></span></div>').join('')||
       '<div class="k">—</div>')+'</div>');
    parts.push('<div class="ws-sec" data-ws-section="DEPENDENCIES"><h4>'+esc(t('deps'))+
      ' ('+r.preview.dependencies.length+')</h4>'+
      (r.preview.dependencies.map(p=>'<div class="ws-f"><span class="k">'+esc(p)+
        '</span><span class="v"><span>affected</span></span></div>').join('')||
       '<div class="k">—</div>')+'</div>');
    const before_c=coordKeys(S.coordination);
    let after_c=[];
    try{
      const a2=compileArchitecture(_wsCopy(r.candidate),bid,null,0);
      const s2=compileStructure(_wsCopy(r.candidate),bid,null,0,a2);
      const m2=compileMep(_wsCopy(r.candidate),bid,null,0,a2);
      const f2=compileFls(_wsCopy(r.candidate),bid,null,0,a2,m2);
      after_c=coordKeys(compileCoordination(_wsCopy(r.candidate),bid,null,0,a2,s2,m2,f2,null));
    }catch(e){ after_c=before_c.slice(); }
    const NEW=after_c.filter(x=>before_c.indexOf(x)<0);
    const RESOLVED=before_c.filter(x=>after_c.indexOf(x)<0);
    parts.push('<div class="ws-sec" data-ws-section="COORDINATION"><h4>'+esc(t('warn'))+
      ' '+NEW.length+' · '+esc(t('resolved'))+' '+RESOLVED.length+'</h4>'+
      '<div class="ws-f"><span class="k">NEW</span><span class="v"><span>'+NEW.length+
      '</span></span></div><div class="ws-f"><span class="k">RESOLVED_BY_CHANGE</span>'+
      '<span class="v"><span>'+RESOLVED.length+'</span></span></div>'+
      '<div class="ws-f"><span class="k">PERSISTING</span><span class="v"><span>'+
      (before_c.length-RESOLVED.length)+'</span></span></div></div>');
    const integ=auValidateModelIntegrity(r.candidate,bid);
    parts.push('<div class="ws-sec" data-ws-section="INTEGRITY"><h4>'+esc(t('integrity'))+
      '</h4><div class="ws-f"><span class="k">status</span><span class="v"><span>'+
      (integ.valid?'COHERENT':'FAILED')+'</span></span></div>'+
      '<div class="ws-f"><span class="k">compliance</span><span class="v"><span>'+
      'NOT_EVALUATED</span></span></div></div>');
    const needsAck=r.issues.some(i=>i.severity==='WARNING');
    if(needsAck) parts.push('<label><input type="checkbox" id="wsAck" data-ws="ack"> '+
      esc(t('ack'))+'</label>');
    if(tx.requires_confirmation) parts.push('<div class="ws-sec"><span class="k">'+
      esc(t('confirm'))+'</span></div>');
    modal(t('preview'),command.type+' · '+String(command.target_id||''),parts.join(''),
      [{label:t('commit'),primary:true,key:'commit',id:'wsCommitBtn',run:()=>{
          const ack=$('wsAck')?$('wsAck').checked:true;
          doCommit([command],tx.confirmation_digest,ack); }},
       {label:t('cancel'),key:'cancel',id:'wsCancelBtn',run:cancelPreview}]);
    renderStatus();
    if(wsModelHashOf(S.project)!==before)
      throw new Error('preview changed the canonical model');
    return r; }

  function coordKeys(co){
    if(!co) return [];
    return (co.clashes||[]).concat(co.penetrations||[])
      .concat(co.clearance_issues||[]).concat(co.semantic_conflicts||[])
      .map(x=>x.id||x.clash_id).filter(Boolean).sort(); }

  function cancelPreview(){
    S.preview=null; S.previewCommand=null;
    if(S.project) auCancelPreview(S.project);
    closeModal(); renderStatus();
    toast('PREVIEW_CANCELLED',t('cancel'));
    return {state:'IDLE'}; }

  function showRejection(issues){
    const rows=(issues||[]).map(i=>
      '<div class="ws-sec" data-ws-section="ERROR">'+
      '<div class="ws-f"><span class="k">code</span><span class="v"><span data-ws-code="1">'+
      esc(i.code)+'</span></span></div>'+
      '<div class="ws-f"><span class="k">target</span><span class="v"><span>'+
      esc(i.subject===null?'—':i.subject)+'</span></span></div>'+
      '<div class="ws-f"><span class="k">explanation</span><span class="v"><span>'+
      esc(i.detail||'')+'</span></span></div></div>').join('');
    modal('COMMAND_REJECTED','',rows||'<div class="k">—</div>',
      [{label:t('cancel'),key:'close',run:closeModal}]);
    toast('COMMAND_REJECTED',(issues&&issues[0])?issues[0].code:'rejected'); }

  /* ------------------------------------------------------ §12 الإيداع */
  function doCommit(commands,confirm,ack){
    if(!S.project) return null;
    const before=wsModelHashOf(S.project);
    const r=auCommitTransaction(S.project,commands,
      {confirm:confirm,acknowledge_warnings:!!ack});
    if(!r.committed){ showRejection(r.issues); renderStatus();
      if(wsModelHashOf(S.project)!==before)
        throw new Error('a rejected commit changed the canonical model');
      return r; }
    S.project=r.project; S.preview=null; S.previewCommand=null; S.exported=false;
    rederive(); closeModal(); renderAll();
    toast('REVISION_COMMITTED',r.revision);
    return r; }

  /* -------------------------------------------------- §20 تراجع/إعادة */
  function undo(){
    if(!S.project) return null;
    const r=auUndo(S.project,undefined,null,S.project.building_id||'bld_0');
    if(!r.valid){ showRejection(r.issues); return r; }
    S.project=r.project; rederive(); renderAll();
    toast('REVISION_COMMITTED',r.revision); return r; }
  function redo(){
    if(!S.project) return null;
    const r=auRedo(S.project,undefined,null,S.project.building_id||'bld_0');
    if(!r.valid){ showRejection(r.issues); return r; }
    S.project=r.project; rederive(); renderAll();
    toast('REVISION_COMMITTED',r.revision); return r; }

  /* --------------------------------------------- §21/§22 المراجعات -- */
  function historyPanel(){
    if(!S.project) return null;
    const h=S.project.history||[];
    const rows=h.slice().reverse().map(r=>
      '<div class="ws-issue" data-ws-rev="'+esc(r.revision_id)+'">'+
      '<div class="c">'+esc(r.revision_id)+' · '+esc(r.authoring_source)+
      ' · '+esc(r.created_at||'—')+'</div>'+
      '<div class="d">'+esc(r.summary||'')+'</div>'+
      '<div class="c">'+esc((r.changed_paths||[]).slice(0,3).join(', ')||'—')+
      '</div></div>').join('');
    modal(t('history'),String(h.length)+' revisions',
      '<div data-ws-section="HISTORY">'+(rows||'<div class="k">—</div>')+'</div>',
      [{label:t('cancel'),key:'close',run:closeModal}]);
    Array.prototype.forEach.call(
      document.querySelectorAll('#wsModalBody [data-ws-rev]'),el=>{
        el.onclick=()=>showDiff(el.getAttribute('data-ws-rev')); });
    return h; }

  function showDiff(revId){
    if(!S.project) return null;
    const snaps=S.project.revision_models||{};
    const h=S.project.history||[];
    let idx=-1; h.forEach((r,i)=>{ if(r.revision_id===revId) idx=i; });
    if(idx<=0){ toast('COMMAND_REJECTED','no parent revision'); return null; }
    const before=snaps[h[idx-1].revision_id], after=snaps[revId];
    if(!before||!after){ toast('COMMAND_REJECTED','revision model unavailable');
      return null; }
    const d=auRevisionDiff(before,after);
    /* الفرق يعرض المضاف والمحذوف كما يعرض المتغيّر — وإلا بدت إعادة تسمية بلا أثر */
    const rows=d.property_changes.slice(0,40).map(c=>
      '<div class="ws-diff" data-ws-diff="1">'+esc(c.path)+'<br>'+
      '<span class="a">'+esc(JSON.stringify(c.before))+'</span> → '+
      '<span class="b">'+esc(JSON.stringify(c.after))+'</span></div>').join('')
      +d.added_paths.slice(0,20).map(pth=>
      '<div class="ws-diff" data-ws-diff="1">'+esc(pth)+'<br>'+
      '<span class="a">—</span> → <span class="b">'+
      esc(JSON.stringify(_wsAtPath(after,pth)))+'</span></div>').join('')
      +d.removed_paths.slice(0,20).map(pth=>
      '<div class="ws-diff" data-ws-diff="1">'+esc(pth)+'<br>'+
      '<span class="a">'+esc(JSON.stringify(_wsAtPath(before,pth)))+
      '</span> → <span class="b">—</span></div>').join('');
    modal('DIFF',revId,
      '<div class="ws-sec"><h4>changed '+d.counts.changed+' · added '+d.counts.added+
      ' · removed '+d.counts.removed+'</h4></div>'+(rows||'<div class="k">—</div>'),
      [{label:t('cancel'),key:'close',run:closeModal}]);
    return d; }

  /* -------------------------------------------- §24/§26 مركز الملاحظات */
  function issuePanel(){
    if(!S.issues) return null;
    const parts=[];
    WS_ISSUE_CATEGORIES.forEach(c=>{
      const list=S.issues.categories[c];
      parts.push('<div class="ws-sec" data-ws-issue-cat="'+esc(c)+'"><h4>'+esc(c)+
        ' ('+list.length+')</h4>');
      if(!list.length) parts.push('<div class="k">—</div>');
      list.slice(0,40).forEach((i,n)=>{
        parts.push('<div class="ws-issue" data-ws-issue="'+esc(c)+':'+n+'"'+
          ' data-ws-severity="'+esc(i.severity)+'">'+
          '<div class="c">'+esc(i.code)+' · '+esc(i.severity)+
          (i.rule_status?(' · '+esc(i.rule_status)):'')+'</div>'+
          '<div class="d">'+esc(i.detail||i.subject||'')+'</div></div>'); });
      parts.push('</div>'); });
    modal(t('issues'),String(S.issues.total)+' · compliance NOT_EVALUATED',
      parts.join(''),[{label:t('cancel'),key:'close',run:closeModal}]);
    Array.prototype.forEach.call(
      document.querySelectorAll('#wsModalBody [data-ws-issue]'),el=>{
        el.onclick=()=>{
          const ref=el.getAttribute('data-ws-issue').split(':');
          const issue=S.issues.categories[ref[0]][Number(ref[1])];
          focusIssue(issue); }; });
    return S.issues; }

  function focusIssue(issue){
    const tg=wsIssueTargets(issue);
    closeModal();
    if(tg.focusable){
      const first=tg.targets[0];
      const res=auResolveTarget(S.project.model,first,S.project.building_id||'bld_0');
      if(res.kind!==null&&res.kind!==undefined) select(first);
      else select(S.ui.selected_id);
      if(typeof window!=='undefined'&&window.__ACS_ON_FOCUS)
        try{ window.__ACS_ON_FOCUS(tg.targets); }catch(e){} }
    return tg; }

  /* ------------------------------------------------ §46/§47 حفظ/فتح - */
  function saveProject(){
    if(!S.project) return null;
    const d=wsExportDescriptor(S.project,'PROJECT_JSON','COMMITTED',null,null);
    const blob=auSerialiseProject(S.project,true,true);
    S.exported=true; renderStatus();
    toast('PROJECT_EXPORTED',d.descriptor.filename);
    return {descriptor:d.descriptor,payload:blob}; }

  function loadProject(payload){
    const r=auLoadProject(payload,'bld_0');
    if(!r.valid){ showRejection(r.issues); return r; }
    S.project=r.project;
    S.ui=S.ui||wsUiStateDefault();
    S.ui.selected_id=null;
    S.preview=null; S.exported=true;
    rederive(); renderAll();
    toast('PROJECT_LOADED',S.project.current_revision);
    return r; }

  /* ------------------------------------------------------ §48 التصدير */
  function exportPanel(){
    if(!S.project) return null;
    const rows=WS_EXPORT_KINDS.map(k=>{
      const d=wsExportDescriptor(S.project,k,'COMMITTED',null,null).descriptor;
      return '<div class="ws-f"><span class="k">'+esc(k)+'</span>'+
        '<span class="v"><button class="ws-btn" data-ws-export="'+esc(k)+'">'+
        esc(d.filename)+'</button></span></div>'; }).join('');
    modal(t('exportc'),'source COMMITTED · certifies nothing',
      '<div class="ws-sec" data-ws-section="EXPORT">'+rows+'</div>'+
      '<div class="ws-sec"><span class="k">a preview export is labelled PREVIEW in both '+
      'the filename and the metadata</span></div>',
      [{label:t('cancel'),key:'close',run:closeModal}]);
    Array.prototype.forEach.call(
      document.querySelectorAll('#wsModalBody [data-ws-export]'),el=>{
        el.onclick=()=>doExport(el.getAttribute('data-ws-export'),'COMMITTED'); });
    return true; }

  function doExport(kind,source){
    if(!S.project) return null;
    const d=wsExportDescriptor(S.project,kind,source||'COMMITTED',null,null);
    if(!d.valid){ showRejection(d.issues); return d; }
    if(kind==='PROJECT_JSON') S.exported=true;
    renderStatus();
    toast('PROJECT_EXPORTED',d.descriptor.filename);
    return d; }

  /* ------------------------------------------ §51-§54 مساعد المنتج -- */
  function assistantPanel(){
    modal(t('assistant'),'proposals only — no write authority',
      '<label>message</label><input id="wsAIIn" placeholder="وسّع المجلس نصف متر">'+
      '<div class="ws-sec" data-ws-section="AI_CAPS">'+
      WS_ASSISTANT_CAPS.map(c=>'<div class="ws-f"><span class="k">'+esc(c)+
      '</span><span class="v"><span>available</span></span></div>').join('')+'</div>'+
      '<div id="wsAIOut"></div>',
      [{label:'Propose',primary:true,key:'propose',run:()=>{
          aiPropose($('wsAIIn').value); }},
       {label:t('cancel'),key:'close',run:closeModal}]);
    return true; }

  function aiPropose(text){
    if(!S.project) return null;
    const phrase=String(text||'').trim();
    const bid=S.project.building_id||'bld_0';
    const target=auResolveNlTarget(S.project.model,phrase.split(/\s+/)[1]||phrase,bid);
    const out=$('wsAIOut');
    if(!target.valid){
      const cands=(target.candidates||[]).map(c=>
        '<button class="ws-btn" style="width:100%;margin:3px 0" data-ws-cand="'+esc(c)+
        '">'+esc(c)+'</button>').join('');
      if(out) out.innerHTML='<div class="ws-sec" data-ws-section="AMBIGUOUS">'+
        '<h4>'+esc(target.issues[0]?target.issues[0].code:'INVALID_TARGET')+'</h4>'+
        (cands||'<div class="k">—</div>')+'</div>';
      if(out) Array.prototype.forEach.call(out.querySelectorAll('[data-ws-cand]'),el=>{
        el.onclick=()=>{ select(el.getAttribute('data-ws-cand'));
          if(out) out.innerHTML='<div class="k">selected '+
            esc(el.getAttribute('data-ws-cand'))+'</div>'; }; });
      return target; }
    const cmd={type:'RESIZE_SPACE',target_id:target.target,
      parameters:{w:6,d:4},source:'AI_PROPOSAL'};
    const p=wsAssistantProposeEdit(S.project,null,cmd,'assistant proposal from: '+phrase);
    if(out) out.innerHTML='<div class="ws-sec" data-ws-section="PROPOSAL">'+
      '<h4>PROPOSED_AUTHORING_COMMAND</h4>'+
      '<div class="ws-f"><span class="k">committed</span><span class="v"><span>false'+
      '</span></span></div>'+
      '<div class="ws-f"><span class="k">command</span><span class="v"><span>'+
      esc(cmd.type)+'</span></span></div>'+
      '<div class="ws-f"><span class="k">target</span><span class="v"><span>'+
      esc(target.target)+'</span></span></div>'+
      '<button class="ws-btn pri" style="width:100%;margin-top:8px" data-ws-apply="1">'+
      esc(t('preview'))+'</button></div>';
    if(out) Array.prototype.forEach.call(out.querySelectorAll('[data-ws-apply]'),el=>{
      el.onclick=()=>{ closeModal(); beginPreview(p.proposal.command); }; });
    return p; }

  /* ------------------------------------------ §55-§58 المراجع البصرية */
  function referencePanel(){
    if(!S.presentation) S.presentation=wsPresentationContext(S.project);
    const refs=(S.presentation.references||[]).map(r=>
      '<div class="ws-ref" data-ws-ref="'+esc(r.reference_id)+'">'+
      '<div><b>'+esc(r.kind)+'</b> · '+esc(r.scope)+' · '+esc(r.scope_id||'—')+
      '<br><span class="k">'+esc(r.caption||r.uri)+'</span></div></div>').join('');
    modal(t('refs'),'presentation context · never engineering geometry',
      '<label>kind</label><select id="wsRefKind">'+
      WS_REFERENCE_KINDS.map(k=>'<option>'+esc(k)+'</option>').join('')+'</select>'+
      '<label>scope</label><select id="wsRefScope">'+
      WS_REFERENCE_SCOPES.map(k=>'<option>'+esc(k)+'</option>').join('')+'</select>'+
      '<label>scope id</label><input id="wsRefId" value="'+esc(S.ui.selected_id||'')+'">'+
      '<label>source</label><input id="wsRefUri" placeholder="https://…">'+
      '<label>caption</label><input id="wsRefCap">'+
      '<div class="ws-sec" data-ws-section="REFERENCES"><h4>'+esc(t('refs'))+' ('+
      (S.presentation.references||[]).length+')</h4>'+(refs||'<div class="k">—</div>')+
      '</div>'+
      '<div class="ws-sec"><span class="k" data-ws-note="canonical" lang="en">'+
      esc(S.presentation.note)+'</span></div>',
      [{label:'Attach',primary:true,key:'attach',run:()=>{
          const r=attachReference($('wsRefKind').value,$('wsRefScope').value,
            $('wsRefId').value,$('wsRefUri').value,$('wsRefCap').value);
          if(r.valid){ closeModal(); referencePanel(); }
          else showRejection(r.issues); }},
       {label:t('cancel'),key:'close',run:closeModal}]);
    return S.presentation; }

  function attachReference(kind,scope,scopeId,uri,caption){
    if(!S.presentation) S.presentation=wsPresentationContext(S.project);
    const before=S.project?wsModelHashOf(S.project):null;
    const r=wsAttachReference(S.presentation,kind,scope,scopeId,uri,'user',caption);
    if(r.valid) S.presentation=r.context;
    if(S.project&&wsModelHashOf(S.project)!==before)
      throw new Error('a visual reference changed the engineering model');
    return r; }

  function setVisualIntent(field,value){
    if(!S.presentation) S.presentation=wsPresentationContext(S.project);
    const before=S.project?wsModelHashOf(S.project):null;
    const r=wsSetVisualIntent(S.presentation,field,value);
    if(r.valid) S.presentation=r.context;
    if(S.project&&wsModelHashOf(S.project)!==before)
      throw new Error('visual intent changed the engineering model');
    return r; }

  /* ---------------------------------------------------- §63/§64 لغة - */
  function setLanguage(lang){
    const lg=(WS_LANGUAGES.indexOf(lang)>=0)?lang:'ar';
    /* اللغة قابلة للتبديل قبل فتح أي مشروع: الحالة تُهيّأ عند الحاجة بدل أن
       ترمي الواجهة استثناءً على مستعمل لم يفتح مشروعاً بعد */
    if(!S.ui) S.ui=wsUiStateDefault();
    const keepSel=S.ui.selected_id, keepMode=S.ui.ui_mode, keepPrev=S.preview;
    S.ui.language=lg;
    if(typeof document!=='undefined'&&document.documentElement){
      document.documentElement.setAttribute('dir',
        ACS_WORKSPACE_SPEC.direction[lg]||'ltr');
      document.documentElement.setAttribute('lang',lg); }
    S.ui.selected_id=keepSel; S.ui.ui_mode=keepMode; S.preview=keepPrev;
    /* الشجرة تحمل أسماء مجموعات مترجَمة، فتُعاد صياغتها باللغة الجديدة.
       هذا اشتقاق عرضٍ محض: النموذج الهندسي لا يُمسّ. */
    if(S.project) S.tree=wsProjectTree(S.project,S.arch,S.coordination,lg);
    renderAll();
    return {language:lg,dir:ACS_WORKSPACE_SPEC.direction[lg],
      selection_preserved:S.ui.selected_id===keepSel,
      mode_preserved:S.ui.ui_mode===keepMode,
      preview_preserved:S.preview===keepPrev,
      project_reloaded:false}; }

  /* ------------------------------------------------ §42-§45 المشروع - */
  function createProjectFlow(){
    modal(t('create'),'',
      '<label>1 · name</label><input id="wsNpName" value="مشروع جديد">'+
      '<label>2 · program</label><select id="wsNpType">'+
      '<option value="residential">residential</option>'+
      '<option value="warehouse">warehouse</option>'+
      '<option value="office">office</option></select>'+
      '<label>3 · requirements</label><textarea id="wsNpReq" '+
      'placeholder="اكتب متطلّباتك بلغتك"></textarea>'+
      '<label>4 · site width (m)</label><input id="wsNpW" type="number" value="30">'+
      '<label>4 · site depth (m)</label><input id="wsNpD" type="number" value="24">'+
      '<div id="wsNpStage" class="ws-sec" data-ws-section="STAGES"></div>',
      [{label:'5 · Generate',primary:true,key:'generate',run:()=>{
          generate({name:$('wsNpName').value,type:$('wsNpType').value,
            requirements:$('wsNpReq').value,
            w:Number($('wsNpW').value),d:Number($('wsNpD').value)}); }},
       {label:t('cancel'),key:'cancel',run:closeModal}]);
    return true; }

  function stage(name){
    const el=$('wsNpStage');
    if(el) el.innerHTML+='<div class="ws-f" data-ws-stage="'+esc(name)+
      '"><span class="k">'+esc(name)+'</span><span class="v"><span>done</span></span></div>';
    return name; }

  function generate(input){
    const stages=ACS_WORKSPACE_SPEC.generation_stages;
    stage(stages[0]);
    let model;
    try{
      model=(typeof buildModelFromText==='function')
        ?buildModelFromText(input.requirements||'',input)
        :null; }
    catch(e){ model=null; }
    if(!model) model=fallbackModel(input);
    stage(stages[1]);
    const project=auCreateProject(model,'bld_0','USER',null);
    const integ=auValidateModelIntegrity(project.model,'bld_0');
    stage(stages[2]);
    S.project=project;
    S.ui=S.ui||wsUiStateDefault();
    S.presentation=wsPresentationContext(project);
    S.exported=false;
    rederive();
    stage(stages[3]);
    closeModal(); open(); renderAll();
    toast('PROJECT_LOADED',project.current_revision);
    return {project:project,integrity:integ}; }

  function fallbackModel(input){
    /* نموذج قانوني صغير من مدخلات المستخدم — لا قيمة هندسية مخترعة خارج ما ذُكر */
    const w=Number(input.w)||30, d=Number(input.d)||24;
    const rw=Math.max(3,Math.min(8,Math.floor(w/4)));
    const rd=Math.max(3,Math.min(8,Math.floor(d/4)));
    return {meta:{type:input.type||'residential',name:input.name||'project'},
      wall_h:3,wall_t:0.2,floor_height:3.2,site:{w:w,d:d},
      levels:[{index:0,name:'ground',template:'g'}],
      floors:{g:{rooms:[
        {id:'main',rect:[0,0,rw,rd],doors:[{edge:'N',offset:rw/2,width:0.9}]},
        {id:'second',rect:[rw,0,rw,rd]}]}}}; }

  /* ------------------------------------------------------- §60/§61 - */
  function setLoading(on,text){
    const el=$('wsLoading'); if(!el) return;
    el.textContent=text||'…'; el.classList.toggle('on',!!on); }
  function setDegraded(on,reason){
    S.degraded=!!on;
    const el=$('wsDegraded'); if(!el) return;
    el.classList.toggle('on',!!on);
    const b=$('wsDegradedBody');
    if(b&&reason) b.textContent=String(reason);
    return {degraded:S.degraded,data_accessible:!!S.project}; }

  /* ---------------------------------------------------- §67 اختصارات */
  function keydown(ev){
    if(!S.ready) return null;
    const mod=ev.ctrlKey||ev.metaKey;
    const tag=(ev.target&&ev.target.tagName)?ev.target.tagName.toLowerCase():'';
    if(tag==='input'||tag==='textarea'||tag==='select'){
      if(ev.key==='Escape'){ closeModal(); return 'CANCEL'; }
      return null; }
    if(mod&&(ev.key==='z'||ev.key==='Z')){
      ev.preventDefault();
      if(ev.shiftKey){ redo(); return 'REDO'; }
      undo(); return 'UNDO'; }
    if(ev.key==='Escape'){ if(S.preview) cancelPreview(); else closeModal();
      return 'CANCEL'; }
    if(ev.key==='f'||ev.key==='F'){ fit('FIT_SELECTION'); return 'FIT_SELECTION'; }
    if(ev.key==='e'||ev.key==='E'){ toggleMode(); return 'TOGGLE_EDIT'; }
    if(ev.key==='b'||ev.key==='B'){ togglePane('wsTreePane'); return 'TOGGLE_TREE'; }
    if(ev.key==='i'||ev.key==='I'){ togglePane('wsInspPane'); return 'TOGGLE_INSPECTOR'; }
    if(ev.key==='Delete'||ev.key==='Backspace'){
      if(S.ui.ui_mode==='EDIT'&&S.ui.selected_id) requestDelete();
      return 'REQUEST_DELETE'; }
    return null; }

  function requestDelete(){
    if(!S.project||!S.ui.selected_id) return null;
    const res=auResolveTarget(S.project.model,S.ui.selected_id,
      S.project.building_id||'bld_0');
    const map={SPACE:'DELETE_SPACE',DOOR:'DELETE_DOOR',WINDOW:'DELETE_WINDOW',
      OBJECT:'DELETE_OBJECT',LEVEL:'DELETE_LEVEL'};
    const op=map[res.kind];
    if(!op){ toast('COMMAND_REJECTED','not deletable'); return null; }
    confirmDelete(op,S.ui.selected_id);
    return op; }

  function togglePane(id){ const el=$(id); if(el) el.classList.toggle('on'); }
  function fit(preset){
    const p=(WS_CAMERA_PRESETS.indexOf(preset)>=0)?preset:'HOME';
    if(typeof window!=='undefined'&&window.__ACS_ON_CAMERA)
      try{ window.__ACS_ON_CAMERA(p,S.ui.selected_id); }catch(e){}
    return {preset:p,writes_to_model:false}; }

  /* ------------------------------------------------------- §73 مغادرة */
  function beforeUnload(ev){
    if(S.project&&!S.exported&&(S.project.history||[]).length>1){
      if(ev){ ev.preventDefault(); ev.returnValue=''; }
      return true; }
    return false; }

  /* ------------------------------------------------------------ ربط - */
  function open(){
    const el=$('acsWorkspace'); if(el) el.classList.add('on');
    S.ready=true; return true; }
  function close(){ const el=$('acsWorkspace'); if(el) el.classList.remove('on');
    return true; }

  function bind(){
    if(typeof document==='undefined') return false;
    const on=(id,fn)=>{ const el=$(id); if(el) el.onclick=fn; };
    on('wsBtnTree',()=>togglePane('wsTreePane'));
    on('wsBtnInsp',()=>togglePane('wsInspPane'));
    on('wsBtnMode',toggleMode);
    on('wsBtnUndo',undo);
    on('wsBtnRedo',redo);
    on('wsBtnHistory',historyPanel);
    on('wsBtnIssues',issuePanel);
    on('wsBtnAI',assistantPanel);
    on('wsBtnExport',exportPanel);
    on('wsBtnLang',()=>setLanguage(S.ui.language==='ar'?'en':'ar'));
    const m=$('wsModal');
    if(m) m.onclick=e=>{ if(e.target===m) closeModal(); };
    if(typeof window!=='undefined'){
      window.addEventListener('keydown',keydown);
      window.addEventListener('beforeunload',beforeUnload); }
    return true; }

  function init(project){
    S.ui=wsUiStateDefault();
    if(project){ S.project=project; S.presentation=wsPresentationContext(project);
      rederive(); }
    bind(); renderAll(); S.ready=true;
    return S; }

  function attach(project){
    S.project=project; S.ui=S.ui||wsUiStateDefault();
    S.presentation=wsPresentationContext(project);
    S.exported=true; rederive(); renderAll(); return S; }

  return {init:init,attach:attach,open:open,close:close,state:()=>S,
    ui:()=>S.ui, select:select, setMode:setMode, toggleMode:toggleMode,
    startOperation:startOperation, beginPreview:beginPreview,
    cancelPreview:cancelPreview, commit:doCommit, undo:undo, redo:redo,
    history:historyPanel, diff:showDiff, issues:issuePanel, focusIssue:focusIssue,
    save:saveProject, load:loadProject, exportPanel:exportPanel, doExport:doExport,
    assistant:assistantPanel, aiPropose:aiPropose,
    references:referencePanel, attachReference:attachReference,
    setVisualIntent:setVisualIntent, presentation:()=>S.presentation,
    setLanguage:setLanguage, createProject:createProjectFlow, generate:generate,
    setLoading:setLoading, setDegraded:setDegraded, keydown:keydown,
    requestDelete:requestDelete, fit:fit, beforeUnload:beforeUnload,
    toast:toast, modal:modal, closeModal:closeModal, rederive:rederive,
    render:renderAll, tree:()=>S.tree, issueModel:()=>S.issues,
    project:()=>S.project};
})();

/* ---------------------- واجهة المطوّر لمساحة العمل --------------------- */
if(typeof window!=='undefined'){
  window.ACS = window.ACS || {};
  window.ACS.workspaceSpec   = ()=>_wsCopy(ACS_WORKSPACE_SPEC);
  window.ACS.workspace       = WS;
  window.ACS.projectTree     = (p,a,c,l)=>wsProjectTree(p,a,c,l);
  window.ACS.flattenTree     = (t,e,d,l)=>wsFlattenTree(t,e,d,l);
  window.ACS.inspectorModel  = (p,id,a,v,c,l)=>wsInspectorModel(p,id,a,v,c,l);
  window.ACS.issueCenter     = (p,a,c,r,rr,b)=>wsIssueCenter(p,a,c,r,rr,b);
  window.ACS.issueTargets    = (i)=>wsIssueTargets(i);
  window.ACS.requirementCoverage = (r,l)=>wsRequirementCoverage(r,l);
  window.ACS.availableOperations = (k,l)=>wsAvailableOperations(k,l);
  window.ACS.presentationContext = (p)=>wsPresentationContext(p);
  window.ACS.attachReference = (c,k,s,i,u,pv,cap)=>wsAttachReference(c,k,s,i,u,pv,cap);
  window.ACS.setVisualIntent = (c,f,v)=>wsSetVisualIntent(c,f,v);
  window.ACS.uiStateDefault  = ()=>wsUiStateDefault();
  window.ACS.classifyStateKey= (k)=>wsClassifyStateKey(k);
  window.ACS.assertUiStateExcluded = (p,u)=>wsAssertUiStateExcluded(p,u);
  window.ACS.exportDescriptor= (p,k,s,v,c)=>wsExportDescriptor(p,k,s,v,c);
  window.ACS.assistantClaim  = (k,t,e)=>wsAssistantClaim(k,t,e);
  window.ACS.assistantPropose= (p,ph,c,r)=>wsAssistantProposeEdit(p,ph,c,r);
  window.ACS.workspaceSummary= (p,u,t,i)=>wsWorkspaceSummary(p,u,t,i);
  window.ACS.displayValue    = (v,e,l)=>wsDisplayValue(v,e,l);
  window.ACS.convertDisplay  = (v,u)=>wsConvertDisplay(v,u);
  window.ACS.provenanceLabel = (s,l)=>wsResolveProvenanceLabel(s,l);
}
"""


def _replace(page, begin, end, block, anchor, after_anchor):
    if begin in page and end in page:
        a = page.index(begin)
        b = page.index(end) + len(end)
        tail = page[b:]
        if tail.startswith("\n"):
            tail = tail[1:]
        return page[:a] + block + tail, "replaced"
    i = page.index(anchor)
    if after_anchor:
        i += len(anchor)
        if page[i:i + 1] == "\n":
            i += 1
    return page[:i] + block + page[i:], "injected"


def build():
    with open(SPEC_PATH, "r", encoding="utf-8") as f:
        spec = json.load(f)
    body = BODY.replace("__SPEC__", json.dumps(spec, ensure_ascii=False,
                                               separators=(",", ":")))
    js_block = JS_BEGIN + "\n" + body + "\n" + JS_END + "\n"
    css_block = CSS_BEGIN + "\n" + CSS + "\n" + CSS_END + "\n"
    dom_block = DOM_BEGIN + "\n" + DOM + "\n" + DOM_END + "\n"

    with open(PAGE, "r", encoding="utf-8") as f:
        page = f.read()
    page, a1 = _replace(page, CSS_BEGIN, CSS_END, css_block, CSS_ANCHOR, False)
    page, a2 = _replace(page, DOM_BEGIN, DOM_END, dom_block, DOM_ANCHOR, False)
    page, a3 = _replace(page, JS_BEGIN, JS_END, js_block, JS_ANCHOR, True)
    with open(PAGE, "w", encoding="utf-8") as f:
        f.write(page)
    print("workspace styles %s (%d bytes), dom %s (%d bytes), ui %s (%d bytes)"
          % (a1, len(css_block), a2, len(dom_block), a3, len(js_block)))


if __name__ == "__main__":
    build()
