# -*- coding: utf-8 -*-
"""يحقن طبقة الجودة البصرية (المرحلة 9.1) في public/index.html.

كتلتان بحدّ معلَن بينهما:
1) كتلة كلاسيكية (تُستخرَج للاختبارات): مرآة المواصفة حرفياً + الدوالّ الحتمية
   pq* التي تُقارَن بايت-بايت مع بايثون + لوحة الإعدادات.
2) جسر داخل سكربت الوحدة (module) حيث يعيش THREE والمشهد: يطبّق الإعدادات على
   العرض الحيّ، قابلاً للعكس، ولا يلمس النموذج القانوني إطلاقاً. غياب THREE
   (كما في صندوق البناء) يعيد رفضاً مصنَّفاً PQ_THREE_UNAVAILABLE — لا انهيار.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SPEC_PATH = os.path.join(ROOT, "acs_pbr.json")
PAGE = os.path.join(ROOT, "public", "index.html")

JS_BEGIN = "/* ===== ACS PBR QUALITY (generated by tools/build_pbr_browser.py) ===== */"
JS_END = "/* ===== END ACS PBR QUALITY ===== */"
JS_ANCHOR = "/* ===== END ACS DOCUMENTATION ===== */"

CSS_BEGIN = "/* ===== ACS PBR STYLES (generated) ===== */"
CSS_END = "/* ===== END ACS PBR STYLES ===== */"
CSS_ANCHOR = "</style>"

DOM_BEGIN = "<!-- ===== ACS PBR DOM (generated) ===== -->"
DOM_END = "<!-- ===== END ACS PBR DOM ===== -->"
DOM_ANCHOR = "</body>"

BRIDGE_SENTINEL_A = "/* ===== ACS PBR BRIDGE (module scope) ===== */"
BRIDGE_SENTINEL_B = "/* ===== END ACS PBR BRIDGE ===== */"
BRIDGE_ANCHOR = "function setSun(elev,azi){"
LOOP_OLD = "  renderer.render(scene,camera);\n});"
LOOP_NEW = ("  if(window.__ACS_PQ__&&window.__ACS_PQ__.composer&&"
            "!renderer.xr.isPresenting){window.__ACS_PQ__.composer.render();}"
            "else{renderer.render(scene,camera);}\n});")

CSS = r""".pq-panel{position:fixed;inset-block-end:0;inset-inline-end:0;width:min(96vw,360px);
  max-height:82vh;background:var(--ws-panel);border:1px solid var(--ws-line);
  border-start-start-radius:12px;color:var(--ws-txt);z-index:64;display:none;
  grid-template-rows:auto 1fr auto;
  font:13px/1.5 system-ui,-apple-system,"Segoe UI",Tahoma,sans-serif}
.pq-panel.on{display:grid}
.pq-panel *{box-sizing:border-box;min-width:0}
.pq-head{display:flex;align-items:center;gap:8px;padding:10px 12px;
  border-bottom:1px solid var(--ws-line);min-height:var(--ws-hit)}
.pq-head h3{margin:0;font-size:13px;letter-spacing:.4px;text-transform:uppercase;
  color:var(--ws-dim)}
.pq-body{overflow:auto;padding:10px 12px}
.pq-foot{display:flex;gap:8px;padding:10px 12px;border-top:1px solid var(--ws-line);
  flex-wrap:wrap}
.pq-btn{border:1px solid var(--ws-line);background:var(--ws-panel2);color:var(--ws-txt);
  border-radius:9px;padding:0 14px;min-height:var(--ws-hit);cursor:pointer;font-size:13px}
.pq-btn.pri{background:var(--ws-accent);border-color:var(--ws-accent);color:#06101d}
.pq-field{display:flex;gap:8px;align-items:center;padding:4px 0}
.pq-field label{color:var(--ws-dim);font-size:11px;flex:0 0 108px}
.pq-field select,.pq-field input[type=range]{flex:1;min-height:var(--ws-hit);
  background:var(--ws-panel2);color:var(--ws-txt);border:1px solid var(--ws-line);
  border-radius:7px;padding:0 8px;font-size:12px}
.pq-field input[type=checkbox]{width:20px;height:20px}
.pq-note{color:var(--ws-dim);font-size:11px;margin-top:6px}
.pq-status{font-size:11px;padding:4px 8px;border:1px solid var(--ws-line);
  border-radius:7px;margin-top:8px;overflow-wrap:anywhere}
@media (max-width:520px){.pq-panel{width:100vw}.pq-field label{flex:0 0 84px}}
"""

DOM = r"""<aside class="pq-panel" id="pqPanel" role="dialog" aria-label="Visual quality"
  data-pq="panel">
  <div class="pq-head">
    <h3 id="pqTitle">Visual quality</h3>
    <span style="flex:1"></span>
    <button class="pq-btn" id="pqClose" aria-label="Close visual quality">✕</button>
  </div>
  <div class="pq-body" id="pqBody"></div>
  <div class="pq-foot">
    <button class="pq-btn pri" id="pqApply" data-pq-action="APPLY">Apply</button>
    <button class="pq-btn" id="pqCapture" data-pq-action="CAPTURE">Screenshot</button>
  </div>
</aside>
"""

BODY = r"""
const ACS_PBR_SPEC = __SPEC__;

const PQ_LIMITS = ACS_PBR_SPEC.limits;
const PQ_ISSUES = ACS_PBR_SPEC.issue_codes;
const PQ_BLOCKING = ACS_PBR_SPEC.blocking_issue_codes;
const PQ_MATERIALS = (function(){ const m={};
  ACS_PBR_SPEC.materials.forEach(x=>{ m[x.id]=x; }); return m; })();
const PQ_LIGHTING = ACS_PBR_SPEC.lighting_presets;
const PQ_QUALITY = ACS_PBR_SPEC.quality_profiles;
const PQ_REQ = ACS_PBR_SPEC.quality_requirements;
const PQ_CHAIN = ACS_PBR_SPEC.quality_fallback_chain;
const PQ_SHADOWS = ACS_PBR_SPEC.shadow_tiers;
const PQ_CAMERAS = ACS_PBR_SPEC.camera_presets;
const PQ_ENVS = ACS_PBR_SPEC.environment_modes;
const PQ_MAT_MAP = ACS_PBR_SPEC.engineering_material_map;
const PQ_OVERRIDABLE = ['base_color','roughness','metalness','opacity',
  'transmission','ior','thickness_m','emissive','emissive_intensity',
  'normal_scale','texture_scale_m'];

function _pqQ(v){ return _pyRound(Number(v),6)+0; }
function _pqNum(v){
  if(v===null||v===undefined||typeof v==='boolean') return null;
  const n=Number(v); if(!isFinite(n)) return null; return n; }
function _pqSha16(o){ return sha256Hex(ingestCanonicalJson(o)).slice(0,16); }

function pqIssue(code,severity,elementId,message){
  if(PQ_ISSUES.indexOf(code)<0)
    throw new Error('undeclared pbr issue code: '+code);
  return {code:code,severity:severity,element_id:elementId,message:message,
    blocking:PQ_BLOCKING.indexOf(code)>=0}; }

function pqSafeKey(k){
  if(typeof k!=='string'||!k||k.length>64) return false;
  if(ACS_PBR_SPEC.forbidden_property_keys.indexOf(k)>=0) return false;
  return /^[A-Za-z_][A-Za-z0-9_]*$/.test(k); }

/* ------------------------------------------------------------- الخامات */
function pqMaterial(mid,override){
  if(!(mid in PQ_MATERIALS))
    return {valid:false,material:null,issues:[pqIssue('PQ_INVALID_MATERIAL',
      'ERROR',mid,'presentation material is not declared')]};
  const base=PQ_MATERIALS[mid];
  const issues=[]; const out={}; const prov={};
  PQ_OVERRIDABLE.forEach(k=>{ out[k]=(base[k]===undefined)?null:base[k];
    prov[k]='PRESENTATION_DEFAULT'; });
  const ov=(override&&typeof override==='object')?override:{};
  if(Object.keys(ov).length>Number(PQ_LIMITS.max_override_fields))
    return {valid:false,material:null,issues:[pqIssue('PQ_INVALID_OVERRIDE',
      'ERROR',mid,'too many override fields')]};
  Object.keys(ov).sort(_scmp).forEach(k=>{
    if(!pqSafeKey(k)){
      issues.push(pqIssue('PQ_PROPERTY_REFUSED','WARNING',k,
        'the override key is refused')); return; }
    if(PQ_OVERRIDABLE.indexOf(k)<0){
      issues.push(pqIssue('PQ_INVALID_OVERRIDE','WARNING',k,
        'this field is not visually overridable')); return; }
    const v=ov[k];
    if(k==='base_color'||k==='emissive'){
      if(!(typeof v==='string'&&v.length===7&&v.charAt(0)==='#'
        &&/^[0-9a-fA-F]{6}$/.test(v.slice(1)))){
        issues.push(pqIssue('PQ_INVALID_OVERRIDE','WARNING',k,
          'not a hex colour')); return; }
      out[k]=v.toLowerCase();
    } else {
      const n=_pqNum(v);
      if(n===null||n<0||n>20){
        issues.push(pqIssue('PQ_INVALID_OVERRIDE','WARNING',k,
          'not a finite value in range')); return; }
      out[k]=_pqQ(n); }
    prov[k]='USER_VISUAL_OVERRIDE'; });
  const resolved={};
  Object.keys(base).forEach(k=>{ resolved[k]=base[k]; });
  Object.keys(out).forEach(k=>{ resolved[k]=out[k]; });
  resolved.provenance=prov; resolved.visual_only=true;
  resolved.engineering_authority=false; resolved.writes_to_model=false;
  return {valid:true,material:resolved,issues:issues}; }

function pqMaterialForEngineering(name){
  const mid=(name in PQ_MAT_MAP)?PQ_MAT_MAP[name]:null;
  if(mid===null) return {mapped:false,material_id:null,
    policy:ACS_PBR_SPEC.unmapped_material_policy};
  return {mapped:true,material_id:mid,policy:'MAPPED'}; }

/* ------------------------------------------------------------- الإضاءة */
function pqLighting(preset){
  if(!(preset in PQ_LIGHTING))
    return {valid:false,lighting:null,issues:[pqIssue('PQ_INVALID_PRESET',
      'ERROR',preset,'lighting preset is not declared')]};
  const src=PQ_LIGHTING[preset];
  const cfg={};
  Object.keys(src).forEach(k=>{ cfg[k]=src[k]; });
  cfg.preset=preset;
  cfg.fills=(src.fills||[]).slice(0,Number(PQ_LIMITS.max_fill_lights))
    .map(f=>{ const g={}; Object.keys(f).forEach(k=>{ g[k]=f[k]; });
      g.visual_only=true; return g; });
  cfg.mep_fixture_reused=false; cfg.visual_only=true;
  return {valid:true,lighting:cfg,issues:[]}; }

function pqExposureClamp(v){
  const n=_pqNum(v);
  if(n===null) return {value:null,clamped:false,
    issues:[pqIssue('PQ_INVALID_EXPOSURE','ERROR',v,
      'exposure is not a finite number')]};
  const lo=Number(ACS_PBR_SPEC.exposure_min), hi=Number(ACS_PBR_SPEC.exposure_max);
  const c=Math.min(Math.max(n,lo),hi);
  return {value:_pqQ(c),clamped:c!==n,issues:[]}; }

/* ------------------------------------------------------------- الظلال */
function pqShadowConfig(tier,bounds){
  if(!(tier in PQ_SHADOWS))
    return {valid:false,shadow:null,issues:[pqIssue('PQ_INVALID_PROFILE',
      'ERROR',tier,'shadow tier is not declared')]};
  const t=PQ_SHADOWS[tier];
  const b=(bounds&&typeof bounds==='object')?bounds:{};
  let r=_pqNum(b.radius);
  if(r===null||r<=0) r=25.0;
  const m=Number(ACS_PBR_SPEC.shadow_camera_margin);
  const e=_pqQ(r*m);
  return {valid:true,issues:[],shadow:{tier:tier,map_size:Math.trunc(t.map_size),
    bias:t.bias,normal_bias:t.normal_bias,radius_px:t.radius,
    type:ACS_PBR_SPEC.shadow_type,
    camera:{left:-e,right:e,top:e,bottom:-e,near:0.5,far:_pqQ(4.0*e)},
    bounds_radius_m:_pqQ(r),margin:m,hardcoded_size:false}}; }

/* ------------------------------------------------------------- الجودة */
function pqCapabilitiesNormalise(caps){
  const c=(caps&&typeof caps==='object')?caps:{};
  const mt=_pqNum(c.max_texture_size);
  const pr=_pqNum(c.device_pixel_ratio);
  return {webgl2:!!c.webgl2,
    max_texture_size:mt?Math.trunc(mt):2048,
    device_pixel_ratio:_pqQ(Math.min(pr?pr:1.0,
      Number(PQ_LIMITS.max_pixel_ratio)))}; }

function _pqMeets(profile,caps){
  const req=PQ_REQ[profile];
  if(req.webgl2&&!caps.webgl2) return false;
  return caps.max_texture_size>=Math.trunc(req.min_max_texture_size); }

function pqQuality(profile,caps){
  if(!(profile in PQ_QUALITY))
    return {valid:false,quality:null,issues:[pqIssue('PQ_INVALID_PROFILE',
      'ERROR',profile,'quality profile is not declared')]};
  const c=pqCapabilitiesNormalise(caps);
  const issues=[];
  const chain=PQ_CHAIN.slice();
  const idx=chain.indexOf(profile);
  let effective=null;
  for(let i=idx;i<chain.length;i++){
    if(_pqMeets(chain[i],c)){ effective=chain[i]; break; }
    issues.push(pqIssue('PQ_FALLBACK_APPLIED','INFO',chain[i],
      'capability requirement not met; degrading')); }
  if(effective===null) effective='PERFORMANCE';
  const src=PQ_QUALITY[effective];
  const cfg={};
  Object.keys(src).forEach(k=>{ cfg[k]=src[k]; });
  cfg.requested=profile; cfg.effective=effective;
  cfg.degraded=effective!==profile;
  cfg.pixel_ratio=_pqQ(Math.min(c.device_pixel_ratio,
    Number(cfg.pixel_ratio_max)));
  cfg.auto_max_profile=ACS_PBR_SPEC.auto_max_profile;
  cfg.blank_viewport_allowed=false;
  return {valid:true,quality:cfg,issues:issues}; }

function pqAutoProfile(caps){
  const c=pqCapabilitiesNormalise(caps);
  const cap=ACS_PBR_SPEC.auto_max_profile;
  const chain=PQ_CHAIN.slice();
  for(let i=chain.indexOf(cap);i<chain.length;i++)
    if(_pqMeets(chain[i],c))
      return {profile:chain[i],auto:true,ultra_auto_selected:false};
  return {profile:'PERFORMANCE',auto:true,ultra_auto_selected:false}; }

/* ------------------------------------------------------------ الكاميرا */
function pqCamera(preset,bounds){
  if(!(preset in PQ_CAMERAS))
    return {valid:false,camera:null,issues:[pqIssue('PQ_INVALID_PRESET',
      'ERROR',preset,'camera preset is not declared')]};
  const p=PQ_CAMERAS[preset];
  const b=(bounds&&typeof bounds==='object')?bounds:{};
  const cx=_pqNum(b.cx)||0.0, cy=_pqNum(b.cy)||0.0, cz=_pqNum(b.cz)||0.0;
  let r=_pqNum(b.radius);
  if(r===null||r<=0) r=20.0;
  const fov=Math.min(Math.max(Number(p.fov),Number(ACS_PBR_SPEC.fov_min)),
    Number(ACS_PBR_SPEC.fov_max));
  const az=Number(p.azimuth_deg)*Math.PI/180.0;
  const el=Number(p.elevation_deg)*Math.PI/180.0;
  const d=r*Number(p.distance_factor);
  const eyeH=(p.eye_height_m===undefined)?null:p.eye_height_m;
  const px=cx+d*Math.cos(el)*Math.sin(az);
  const pz=cz+d*Math.cos(el)*Math.cos(az);
  let py=cy+d*Math.sin(el);
  let ty=cy;
  if(p.target==='EYE'&&eyeH!==null){
    const baseY=_pqNum(b.min_y)||0.0;
    py=baseY+Number(eyeH); ty=baseY+Number(eyeH); }
  return {valid:true,issues:[],camera:{preset:preset,fov:_pqQ(fov),
    position:[_pqQ(px),_pqQ(py),_pqQ(pz)],target:[_pqQ(cx),_pqQ(ty),_pqQ(cz)],
    bounds_radius_m:_pqQ(r),deterministic:true,fisheye:false}}; }

/* ------------------------------------------------------------- البيئة */
function pqEnvironment(mode){
  if(!(mode in PQ_ENVS))
    return {valid:false,environment:null,issues:[pqIssue(
      'PQ_INVALID_ENVIRONMENT','ERROR',mode,
      'environment mode is not declared')]};
  const src=PQ_ENVS[mode]; const e={};
  Object.keys(src).forEach(k=>{ e[k]=src[k]; });
  e.mode=mode; e.remote_fetch=false; e.changes_geometry=false;
  return {valid:true,environment:e,issues:[]}; }

/* ------------------------------------------------------------ المسارات */
function pqTexturePathOk(path){
  const pol=ACS_PBR_SPEC.texture_policy;
  if(typeof path!=='string'||!path)
    return {ok:false,issues:[pqIssue('PQ_UNSAFE_ASSET_PATH','ERROR',path,
      'empty asset path')]};
  if(path.length>Number(PQ_LIMITS.max_asset_path_length))
    return {ok:false,issues:[pqIssue('PQ_UNSAFE_ASSET_PATH','ERROR',
      path.slice(0,40),'asset path too long')]};
  if(path.indexOf('://')>=0||path.indexOf('//')===0)
    return {ok:false,issues:[pqIssue('PQ_REMOTE_ASSET_REFUSED','ERROR',
      path.slice(0,40),'remote assets are refused')]};
  if(!(new RegExp(pol.safe_asset_pattern)).test(path))
    return {ok:false,issues:[pqIssue('PQ_UNSAFE_ASSET_PATH','ERROR',
      path.slice(0,40),'path is outside the allowed asset root')]};
  const listed=pol.local_texture_sets.some(
    s=>((s.files||[]).indexOf(path)>=0));
  if(!listed)
    return {ok:false,listed:false,issues:[pqIssue('PQ_UNSAFE_ASSET_PATH',
      'WARNING',path.slice(0,40),
      'path is shaped correctly but not in the declared texture set; '+
      'procedural fallback is used instead')]};
  return {ok:true,listed:true,issues:[]}; }

/* --------------------------------------------------------- الإعداد الكلّي */
function pqConfig(profile,lightingPreset,materialsMode,environmentMode,
  exposure,overrides,caps,bounds){
  const issues=[];
  const q=pqQuality(profile||'BALANCED',caps);
  if(!q.valid) return {valid:false,config:null,issues:q.issues};
  q.issues.forEach(i=>issues.push(i));
  const lp=lightingPreset||'CLEAR_NOON';
  const lg=pqLighting(lp);
  if(!lg.valid) return {valid:false,config:null,issues:lg.issues};
  const mm=materialsMode||ACS_PBR_SPEC.default_materials_mode;
  if(ACS_PBR_SPEC.materials_modes.indexOf(mm)<0)
    return {valid:false,config:null,issues:[pqIssue('PQ_INVALID_MODE','ERROR',
      mm,'materials mode is not declared')]};
  const em=environmentMode||q.quality.environment;
  const ev=pqEnvironment(em);
  if(!ev.valid) return {valid:false,config:null,issues:ev.issues};
  const ex=pqExposureClamp((exposure===null||exposure===undefined)
    ?lg.lighting.exposure:exposure);
  if(ex.value===null) return {valid:false,config:null,issues:ex.issues};
  const sh=pqShadowConfig(q.quality.shadow_tier,bounds);
  sh.issues.forEach(i=>issues.push(i));
  const ovOut={};
  Object.keys(overrides||{}).sort(_scmp).forEach(mid=>{
    if(!(mid in PQ_MATERIALS)){
      issues.push(pqIssue('PQ_INVALID_MATERIAL','WARNING',mid,
        'override for an undeclared material')); return; }
    const r=pqMaterial(mid,(overrides||{})[mid]);
    r.issues.forEach(i=>issues.push(i));
    if(r.valid){
      const rec={};
      PQ_OVERRIDABLE.forEach(k=>{ rec[k]=r.material[k]; });
      rec.provenance=r.material.provenance;
      ovOut[mid]=rec; } });
  const cfg={schema:ACS_PBR_SPEC.schema,version:ACS_PBR_SPEC.version,
    quality:q.quality,lighting:lg.lighting,materials_mode:mm,
    environment:ev.environment,exposure:ex.value,
    exposure_clamped:ex.clamped,shadow:sh.valid?sh.shadow:null,
    material_overrides:ovOut,tone_mapping:ACS_PBR_SPEC.tone_mapping,
    output_color_space:ACS_PBR_SPEC.output_color_space,
    ground_context_enabled:ACS_PBR_SPEC.ground_context.enabled_default,
    writes_to_model:false,visual_only:true};
  cfg.presentation_config_hash=_pqSha16(cfg);
  return {valid:true,config:cfg,issues:issues}; }

function pqCaptureMetadata(cfg,modelHash,widthPx,heightPx,generatedAt){
  const w=_pqNum(widthPx), h=_pqNum(heightPx);
  const mx=Number(ACS_PBR_SPEC.capture.max_dimension_px);
  if(w===null||h===null||w<=0||h<=0||w>mx||h>mx)
    return {valid:false,metadata:null,issues:[pqIssue('PQ_INVALID_RESOLUTION',
      'ERROR',[widthPx,heightPx],'capture resolution is out of range')]};
  const c=cfg||{};
  const md={type:ACS_PBR_SPEC.capture.type,
    camera_preset:(c.camera_preset===undefined)?null:c.camera_preset,
    quality_profile:((c.quality||{}).effective===undefined)?null
      :(c.quality||{}).effective,
    lighting_preset:((c.lighting||{}).preset===undefined)?null
      :(c.lighting||{}).preset,
    materials_mode:(c.materials_mode===undefined)?null:c.materials_mode,
    environment:((c.environment||{}).mode===undefined)?null
      :(c.environment||{}).mode,
    exposure:(c.exposure===undefined)?null:c.exposure,
    model_hash:(modelHash===undefined)?null:modelHash,
    presentation_config_hash:(c.presentation_config_hash===undefined)?null
      :c.presentation_config_hash,
    width_px:Math.trunc(w),height_px:Math.trunc(h),
    generated_at:(generatedAt===undefined)?null:generatedAt,
    is_engineering_evidence:false};
  return {valid:true,metadata:md,issues:[]}; }
"""

PANEL = r"""
/* ===================== لوحة الجودة البصرية (§19) ======================== */
const PQ = (function(){
  const S={lang:'en',profile:'BALANCED',lighting:'CLEAR_NOON',
    materials:'ENGINEERING',environment:'SKY',shadows:true,ao:false,
    exposure:null,last:null,capture:null};
  const $=id=>(typeof document!=='undefined')?document.getElementById(id):null;
  const esc=s=>String(s===null||s===undefined?'':s).replace(/&/g,'&amp;')
    .replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')
    .replace(/'/g,'&#39;');
  function T(k){
    const t=ACS_PBR_SPEC.ui_labels[S.lang]||ACS_PBR_SPEC.ui_labels.en;
    return t[k]||ACS_PBR_SPEC.ui_labels.en[k]||k; }
  function state(){ return S; }
  function open(){ const p=$('pqPanel'); if(p) p.classList.add('on');
    render(); return true; }
  function close(){ const p=$('pqPanel'); if(p) p.classList.remove('on');
    return true; }
  function setLanguage(l){ S.lang=(l==='ar')?'ar':'en';
    const t=$('pqTitle'); if(t) t.textContent=T('panel'); render();
    return S.lang; }
  function currentConfig(caps,bounds){
    return pqConfig(S.profile,S.lighting,S.materials,S.environment,
      S.exposure,{},caps||null,bounds||null); }
  function apply(){
    const caps=(typeof window!=='undefined'&&window.ACS&&window.ACS.pbrCaps)
      ?window.ACS.pbrCaps():null;
    const bounds=(typeof window!=='undefined'&&window.ACS&&window.ACS.pbrBounds)
      ?window.ACS.pbrBounds():null;
    const r=currentConfig(caps,bounds);
    if(!r.valid){ S.last={applied:false,issues:r.issues}; render();
      return S.last; }
    r.config.shadows_enabled=!!S.shadows;
    r.config.ssao_enabled=!!S.ao&&r.config.quality.ssao;
    if(typeof window!=='undefined'&&window.ACS
      &&typeof window.ACS.pbrApply==='function'){
      S.last=window.ACS.pbrApply(r.config);
    } else {
      /* غياب THREE (بيئة الفحص): رفض مصنَّف لا انهيار ولا شاشة فارغة */
      S.last={applied:false,config:r.config,
        issues:[pqIssue('PQ_THREE_UNAVAILABLE','INFO',null,
          'the 3D runtime is not present in this environment; the '+
          'configuration is valid and would apply on the deployed site')]}; }
    render(); return S.last; }
  function capture(){
    if(typeof window!=='undefined'&&window.ACS
      &&typeof window.ACS.pbrCapture==='function'){
      S.capture=window.ACS.pbrCapture({width:1920,height:1080});
    } else {
      S.capture={captured:false,
        issues:[pqIssue('PQ_THREE_UNAVAILABLE','INFO',null,
          'no 3D runtime; nothing to capture here')]}; }
    render(); return S.capture; }
  function sel(id,label,opts,cur){
    return '<div class="pq-field"><label>'+esc(label)+'</label>'+
      '<select id="'+id+'" data-pq-control="'+id+'">'+
      opts.map(o=>'<option value="'+esc(o[0])+'"'+(o[0]===cur?' selected':'')+
        '>'+esc(o[1])+'</option>').join('')+'</select></div>'; }
  function render(){
    const host=$('pqBody'); if(!host) return;
    const p=[];
    p.push(sel('pqQuality',T('quality'),
      [['PERFORMANCE',T('performance')],['BALANCED',T('balanced')],
       ['HIGH',T('high')],['ULTRA',T('ultra')]],S.profile));
    p.push(sel('pqLighting',T('lighting'),
      Object.keys(PQ_LIGHTING).map(k=>[k,k]),S.lighting));
    p.push(sel('pqMaterials',T('materials'),
      [['ENGINEERING',T('engineering')],['REALISTIC',T('realistic')]],
      S.materials));
    p.push(sel('pqEnvironment',T('environment'),
      [['NEUTRAL',T('neutral')],['SKY',T('sky')],['STUDIO',T('studio')]],
      S.environment));
    p.push('<div class="pq-field"><label>'+esc(T('shadows'))+'</label>'+
      '<input type="checkbox" id="pqShadows" data-pq-control="pqShadows"'+
      (S.shadows?' checked':'')+'></div>');
    p.push('<div class="pq-field"><label>'+esc(T('ao'))+'</label>'+
      '<input type="checkbox" id="pqAo" data-pq-control="pqAo"'+
      (S.ao?' checked':'')+'></div>');
    p.push('<div class="pq-field"><label>'+esc(T('exposure'))+'</label>'+
      '<input type="range" id="pqExposure" data-pq-control="pqExposure" '+
      'min="'+ACS_PBR_SPEC.exposure_min+'" max="'+ACS_PBR_SPEC.exposure_max+
      '" step="'+ACS_PBR_SPEC.exposure_step+'" value="'+
      (S.exposure===null?1.0:S.exposure)+'"></div>');
    if(S.last){
      const codes=(S.last.issues||[]).map(i=>i.code).join(', ');
      p.push('<div class="pq-status" data-pq-status="'+
        (S.last.applied?'APPLIED':'NOT_APPLIED')+'">'+
        (S.last.applied?'applied':'not applied')+
        (codes?(' — '+esc(codes)):'')+'</div>'); }
    if(S.capture&&S.capture.metadata)
      p.push('<div class="pq-status" data-pq-capture="1">'+
        esc(S.capture.metadata.type)+' '+S.capture.metadata.width_px+'×'+
        S.capture.metadata.height_px+'</div>');
    p.push('<div class="pq-note">presentation only — the engineering model '+
      'is read-only here and its hash never changes</div>');
    host.innerHTML=p.join('');
    const bind=(id,fn)=>{ const e=$(id); if(e) e.onchange=fn; };
    bind('pqQuality',()=>{ S.profile=$('pqQuality').value; });
    bind('pqLighting',()=>{ S.lighting=$('pqLighting').value; });
    bind('pqMaterials',()=>{ S.materials=$('pqMaterials').value; });
    bind('pqEnvironment',()=>{ S.environment=$('pqEnvironment').value; });
    bind('pqShadows',()=>{ S.shadows=$('pqShadows').checked; });
    bind('pqAo',()=>{ S.ao=$('pqAo').checked; });
    bind('pqExposure',()=>{ S.exposure=Number($('pqExposure').value); }); }
  function init(){
    const c=$('pqClose'); if(c) c.onclick=close;
    const a=$('pqApply'); if(a) a.onclick=()=>{ try{ apply(); }catch(e){} };
    const cp=$('pqCapture'); if(cp) cp.onclick=()=>{ try{ capture(); }catch(e){} };
    return true; }
  if(typeof document!=='undefined'&&document.addEventListener)
    document.addEventListener('DOMContentLoaded',init);
  return {state:state,open:open,close:close,init:init,render:render,
    setLanguage:setLanguage,apply:apply,capture:capture,
    currentConfig:currentConfig};
})();

if(typeof window!=='undefined'){
  window.ACS=window.ACS||{};
  window.ACS.pbr={
    spec:()=>JSON.parse(JSON.stringify(ACS_PBR_SPEC)),
    material:pqMaterial, materialForEngineering:pqMaterialForEngineering,
    lighting:pqLighting, exposureClamp:pqExposureClamp,
    shadowConfig:pqShadowConfig, quality:pqQuality, autoProfile:pqAutoProfile,
    camera:pqCamera, environment:pqEnvironment,
    texturePathOk:pqTexturePathOk, config:pqConfig,
    captureMetadata:pqCaptureMetadata, panel:PQ};
}
"""


def _read(p):
    with open(p, encoding="utf-8") as f:
        return f.read()


def _replace(page, begin, end, block, anchor, after_anchor):
    if begin in page and end in page:
        a = page.index(begin)
        b = page.index(end) + len(end)
        tail = page[b:]
        if tail.startswith("\n"):
            tail = tail[1:]
        return page[:a] + block + tail, "replaced"
    i = page.index(anchor)
    if after_anchor:
        i += len(anchor)
        if page[i:i + 1] == "\n":
            i += 1
    return page[:i] + block + page[i:], "injected"


def build():
    with open(SPEC_PATH, "r", encoding="utf-8") as f:
        spec = json.load(f)
    body = (BODY + PANEL).replace(
        "__SPEC__", json.dumps(spec, ensure_ascii=False,
                               separators=(",", ":")))
    js_block = JS_BEGIN + "\n" + body + "\n" + JS_END + "\n"
    css_block = CSS_BEGIN + "\n" + CSS + "\n" + CSS_END + "\n"
    dom_block = DOM_BEGIN + "\n" + DOM + "\n" + DOM_END + "\n"
    page = _read(PAGE)
    page, a1 = _replace(page, CSS_BEGIN, CSS_END, css_block, CSS_ANCHOR, False)
    page, a2 = _replace(page, DOM_BEGIN, DOM_END, dom_block, DOM_ANCHOR, False)
    page, a3 = _replace(page, JS_BEGIN, JS_END, js_block, JS_ANCHOR, True)

    # الجسر داخل سكربت الوحدة — حيث THREE والمشهد. حقن عديم الأثر عند التكرار
    bridge = _read(os.path.join(HERE, "_pbr_bridge_block.js"))
    bridge_block = BRIDGE_SENTINEL_A + "\n" + bridge + "\n" + BRIDGE_SENTINEL_B + "\n"
    if BRIDGE_SENTINEL_A in page and BRIDGE_SENTINEL_B in page:
        a = page.index(BRIDGE_SENTINEL_A)
        b = page.index(BRIDGE_SENTINEL_B) + len(BRIDGE_SENTINEL_B)
        tail = page[b:]
        if tail.startswith("\n"):
            tail = tail[1:]
        page = page[:a] + bridge_block + tail
        a4 = "replaced"
    else:
        assert page.count(BRIDGE_ANCHOR) == 1, "bridge anchor not unique"
        page = page.replace(BRIDGE_ANCHOR, bridge_block + BRIDGE_ANCHOR)
        a4 = "injected"

    # خطّاف حلقة العرض: مبدّل المركِّب — يعمل فقط حين يوجد مركِّب حيّ
    if "window.__ACS_PQ__&&window.__ACS_PQ__.composer" not in page:
        assert page.count(LOOP_OLD) == 1, "render loop anchor not unique"
        page = page.replace(LOOP_OLD, LOOP_NEW)
        a5 = "hooked"
    else:
        a5 = "already hooked"

    with open(PAGE, "w", encoding="utf-8") as f:
        f.write(page)
    print("pbr styles %s (%d bytes), dom %s (%d bytes), quality %s (%d bytes), "
          "bridge %s, render loop %s"
          % (a1, len(css_block), a2, len(dom_block), a3, len(js_block),
             a4, a5))


if __name__ == "__main__":
    build()
