# -*- coding: utf-8 -*-
"""يحقن محرّك العرض التقديمي ولوحة التصوير في public/index.html بين علامات صريحة.

التشغيل مرّتين يستبدل الكتل ولا يكرّرها. تُحقن الشيفرة بعد كتلة مساحة العمل كي
لا يمحو أي مولّد كتلة الآخر. المواصفة تُنسخ حرفاً بحرف من acs_render.json،
والدوال مرآة حرفية لـ acs_render.py — لا تطبيق ثانٍ ولا منطق مستقلّ.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SPEC_PATH = os.path.join(ROOT, "acs_render.json")
PAGE = os.path.join(ROOT, "public", "index.html")

JS_BEGIN = "/* ===== ACS RENDER ENGINE (generated by tools/build_render_browser.py) ===== */"
JS_END = "/* ===== END ACS RENDER ENGINE ===== */"
JS_ANCHOR = "/* ===== END ACS WORKSPACE UI ===== */"

CSS_BEGIN = "/* ===== ACS RENDER STYLES (generated) ===== */"
CSS_END = "/* ===== END ACS RENDER STYLES ===== */"
CSS_ANCHOR = "</style>"

DOM_BEGIN = "<!-- ===== ACS RENDER DOM (generated) ===== -->"
DOM_END = "<!-- ===== END ACS RENDER DOM ===== -->"
DOM_ANCHOR = "</body>"

CSS = r""".rv-panel{position:fixed;inset-block:0;inset-inline-end:0;width:min(94vw,380px);
  background:var(--ws-panel);border-inline-start:1px solid var(--ws-line);
  color:var(--ws-txt);z-index:60;display:none;grid-template-rows:auto 1fr auto;
  font:13px/1.5 system-ui,-apple-system,"Segoe UI",Tahoma,sans-serif}
.rv-panel.on{display:grid}
.rv-panel *{box-sizing:border-box}
.rv-head{display:flex;align-items:center;gap:8px;padding:10px 12px;
  border-bottom:1px solid var(--ws-line);min-height:var(--ws-hit)}
.rv-head h3{margin:0;font-size:13px;letter-spacing:.4px;text-transform:uppercase;
  color:var(--ws-dim)}
.rv-body{overflow:auto;padding:10px 12px}
.rv-foot{display:flex;gap:8px;padding:10px 12px;border-top:1px solid var(--ws-line);
  flex-wrap:wrap}
.rv-sec{margin:0 0 14px}
.rv-sec h4{margin:0 0 6px;font-size:11px;letter-spacing:.5px;text-transform:uppercase;
  color:var(--ws-dim)}
.rv-row{display:flex;align-items:center;justify-content:space-between;gap:8px;
  padding:3px 0}
.rv-row .k{color:var(--ws-dim);font-size:12px}
.rv-row .v{font-size:12px}
.rv-chips{display:flex;flex-wrap:wrap;gap:6px}
.rv-chip{border:1px solid var(--ws-line);background:var(--ws-panel2);
  color:var(--ws-txt);border-radius:999px;padding:0 12px;min-height:var(--ws-hit);
  display:inline-flex;align-items:center;cursor:pointer;font-size:12px}
.rv-chip.on{border-color:var(--ws-accent);color:var(--ws-accent)}
.rv-btn{border:1px solid var(--ws-line);background:var(--ws-panel2);color:var(--ws-txt);
  border-radius:9px;padding:0 14px;min-height:var(--ws-hit);cursor:pointer;font-size:13px}
.rv-btn.pri{background:var(--ws-accent);border-color:var(--ws-accent);color:#06101d}
.rv-btn[disabled]{opacity:.45;cursor:not-allowed}
.rv-gallery{display:grid;grid-template-columns:repeat(auto-fill,minmax(120px,1fr));gap:8px}
.rv-card{border:1px solid var(--ws-line);border-radius:9px;overflow:hidden;
  background:var(--ws-panel2);padding:6px}
.rv-card .t{font-size:11px;color:var(--ws-dim);word-break:break-all}
.rv-card .f{font-size:10px;margin-top:2px}
.rv-card .f.PASS{color:var(--ws-ok)}
.rv-card .f.WARNING{color:var(--ws-warn)}
.rv-card .f.REJECTED{color:var(--ws-err)}
.rv-card .s{font-size:10px;color:var(--ws-warn)}
.rv-thumb{width:100%;height:64px;background:#0b0e13;border-radius:6px;
  display:flex;align-items:center;justify-content:center;color:var(--ws-dim);
  font-size:10px;overflow:hidden}
.rv-thumb svg{max-width:100%;max-height:100%}
.rv-note{color:var(--ws-dim);font-size:11px;margin-top:8px}
.rv-toggle{display:flex;gap:0;border:1px solid var(--ws-line);border-radius:9px;
  overflow:hidden}
.rv-toggle button{flex:1;min-height:var(--ws-hit);background:transparent;border:0;
  color:var(--ws-txt);cursor:pointer;font-size:12px}
.rv-toggle button.on{background:var(--ws-accent);color:#06101d}
.rv-view{position:fixed;inset:0;background:rgba(4,6,10,.92);z-index:70;display:none;
  align-items:center;justify-content:center;padding:18px}
.rv-view.on{display:flex}
.rv-view .box{max-width:96vw;max-height:92vh;overflow:auto;background:#fff;
  border-radius:10px;padding:8px}
@media (max-width:767px){
  .rv-panel{width:100vw}
  .rv-gallery{grid-template-columns:repeat(auto-fill,minmax(104px,1fr))}
}
"""

DOM = r"""<aside class="rv-panel" id="rvPanel" role="dialog" aria-label="Visualisation"
  aria-modal="false" data-rv="panel">
  <div class="rv-head">
    <h3 id="rvTitle">Visualize</h3>
    <span style="flex:1"></span>
    <button class="rv-btn" id="rvClose" aria-label="Close visualisation">✕</button>
  </div>
  <div class="rv-body" id="rvBody"></div>
  <div class="rv-foot">
    <button class="rv-btn" id="rvPreview" data-rv-action="preview">Preview</button>
    <button class="rv-btn pri" id="rvRender" data-rv-action="render">Render</button>
    <button class="rv-btn" id="rvCompare" data-rv-action="compare">Compare</button>
    <button class="rv-btn" id="rvExport" data-rv-action="export">Export</button>
  </div>
</aside>
<div class="rv-view" id="rvView" role="dialog" aria-label="Render output">
  <div class="box" id="rvViewBox"></div>
</div>
"""

BODY = r"""const ACS_RENDER_SPEC = __SPEC__;
const RD_SCHEMA = ACS_RENDER_SPEC.schema;
const RD_VIEW_TYPES = ACS_RENDER_SPEC.view_types;
const RD_QUALITIES = ACS_RENDER_SPEC.qualities;
const RD_THEMES = ACS_RENDER_SPEC.themes;
const RD_LIGHTING = ACS_RENDER_SPEC.lighting_presets;
const RD_CAMERA_PRESETS = ACS_RENDER_SPEC.camera_presets;
const RD_BUFFER_KINDS = ACS_RENDER_SPEC.control_buffer_kinds;
const RD_SEMANTIC_CLASSES = ACS_RENDER_SPEC.semantic_classes;
const RD_DRIFT_TYPES = ACS_RENDER_SPEC.drift_types;
const RD_FIDELITY = ACS_RENDER_SPEC.fidelity_statuses;
const RD_UNSAFE = ACS_RENDER_SPEC.unsafe_patterns;
const RD_THRESH = ACS_RENDER_SPEC.drift_thresholds;
const RD_MATERIALS = (function(){ const m={};
  ACS_RENDER_SPEC.material_library.forEach(x=>{ m[x.id]=x; }); return m; })();
const _RD_SEM_WALL = RD_SEMANTIC_CLASSES.indexOf('WALL');
const _RD_SEM_OPENING = RD_SEMANTIC_CLASSES.indexOf('OPENING');
const _RD_OPENING_BIAS_M = 0.6;

function _rdQ(v){ return _pyRound(Number(v),6)+0; }
function _rdNum(v){
  if(v===null||v===undefined||typeof v==='boolean') return null;
  const f=Number(v);
  if(!isFinite(f)) return null;
  return f; }
function _rdCopy(v){ return JSON.parse(JSON.stringify(v)); }
function _rdSha16(o){ return sha256Hex(ingestCanonicalJson(o)).slice(0,16); }
function _rdIssue(code,subject,detail,severity){
  return {code:code,severity:severity||'ERROR',subject:subject,detail:detail}; }
const _RD_SAFE_ID=new RegExp(ACS_RENDER_SPEC.safe_id_pattern);
function rdIsSafeId(v){
  /* معرّف مقبول بقائمة سماح لا بقائمة حظر: ما ليس معرّفاً معقولاً يُرفض،
     وافقنا على نمط هجومه أم لم نعرفه بعد */
  return typeof v==='string'&&_RD_SAFE_ID.test(v); }
function rdIsAllowedUri(v){
  /* مصدر مرجع مقبول بمخطّط من قائمة سماح. أي مخطّط آخر مرفوض افتراضاً */
  if(typeof v!=='string'||!v) return false;
  const low=v.trim().toLowerCase();
  if(rdIsUnsafe(low)) return false;
  if(low.indexOf('https:')===0||low.indexOf('http:')===0) return true;
  if(low.indexOf('blob:')===0) return true;
  if(low.indexOf('data:')===0)
    return low.indexOf('data:image/')===0&&low.indexOf(';base64,')>=0
      &&low.split(',')[0].indexOf('svg')<0;
  if(low.split('/')[0].indexOf(':')>=0) return false;
  /* مسار نسبي: يُقبل بقائمة سماح لمحارف المسار، فلا يمرّ نصّ ليس مساراً أصلاً */
  return /^[a-z0-9._~/-]+$/.test(low); }
const _RD_PROSE_MAX=Number(ACS_RENDER_SPEC.visual_intent_max_chars);
const _RD_PROSE_BAD=ACS_RENDER_SPEC.forbidden_prose_chars;
const _RD_PROSE_RE=new RegExp(ACS_RENDER_SPEC.visual_intent_pattern);
function rdIsSafeProse(v){
  /* وصف طراز قصير مقبول بقائمة سماح: حروف عربية وإنجليزية وأرقام ومسافات
     وفواصل وشرطات فقط. ما ليس وصف طراز معقولاً يُرفض، عرفنا نمط هجومه أم لا. */
  if(typeof v!=='string'||v.length>_RD_PROSE_MAX) return false;
  return _RD_PROSE_RE.test(v); }
function rdIsUnsafe(){
  for(let i=0;i<arguments.length;i++){
    const v=arguments[i];
    if(typeof v!=='string') continue;
    const low=v.toLowerCase();
    for(let j=0;j<RD_UNSAFE.length;j++)
      if(low.indexOf(String(RD_UNSAFE[j]).toLowerCase())>=0) return true; }
  return false; }

/* ------------------------------------------------------ طلب العرض (§1) --- */
function rdRenderRequest(project,viewType,options,requestId){
  const o=options||{}, issues=[];
  const vt=(typeof viewType==='string')?viewType.toUpperCase():null;
  if(RD_VIEW_TYPES.indexOf(vt)<0)
    issues.push(_rdIssue('INVALID_VIEW_TYPE',viewType,'unknown view type'));
  const quality=String(o.quality||ACS_RENDER_SPEC.default_quality).toUpperCase();
  if(RD_QUALITIES.indexOf(quality)<0)
    issues.push(_rdIssue('INVALID_QUALITY',o.quality,'unknown quality'));
  const theme=String(o.theme||ACS_RENDER_SPEC.default_theme).toUpperCase();
  if(RD_THEMES.indexOf(theme)<0)
    issues.push(_rdIssue('INVALID_THEME',o.theme,'unknown theme'));
  const lighting=String(o.lighting||ACS_RENDER_SPEC.default_lighting).toUpperCase();
  if(RD_LIGHTING.indexOf(lighting)<0)
    issues.push(_rdIssue('INVALID_LIGHTING',o.lighting,'unknown lighting preset'));
  let refs=Array.isArray(o.reference_ids)?o.reference_ids:[];
  refs=refs.filter(r=>typeof r==='string'||typeof r==='number').map(r=>String(r));
  if(!refs.every(r=>rdIsSafeId(String(r))))
    issues.push(_rdIssue('PAYLOAD_REJECTED','reference_ids',
      'a reference identifier is not a plausible identifier'));
  const res=o.resolution;
  if(res!==null&&res!==undefined){
    if(!Array.isArray(res)||res.length!==2||_rdNum(res[0])===null||_rdNum(res[1])===null
       ||Math.trunc(res[0])<=0||Math.trunc(res[1])<=0)
      issues.push(_rdIssue('INVALID_RESOLUTION',res,
        'resolution must be two positive integers'));
    else if(Math.trunc(res[0])*Math.trunc(res[1])>Number(ACS_RENDER_SPEC.max_render_px))
      issues.push(_rdIssue('INVALID_RESOLUTION',res,
        'resolution exceeds the declared maximum')); }
  const flags=(o.context_flags||ACS_RENDER_SPEC.context_default_enabled)
    .filter(c=>ACS_RENDER_SPEC.context_flags.indexOf(c)>=0);
  const uniq=[]; flags.forEach(c=>{ if(uniq.indexOf(c)<0) uniq.push(c); });
  uniq.sort();
  const req={schema:RD_SCHEMA,request_id:null,
    model_hash:project.model_hash===undefined?null:project.model_hash,
    revision_id:project.current_revision===undefined?null:project.current_revision,
    building_id:project.building_id||'bld_0',
    level_id:o.level_id===undefined?null:o.level_id,
    space_id:o.space_id===undefined?null:o.space_id,
    view_type:vt,camera:o.camera===undefined?null:o.camera,
    quality:(RD_QUALITIES.indexOf(quality)>=0)?quality:null,
    theme:(RD_THEMES.indexOf(theme)>=0)?theme:null,
    lighting:(RD_LIGHTING.indexOf(lighting)>=0)?lighting:null,
    ai_enhancement:!!o.ai_enhancement,reference_ids:refs,
    resolution:(res&&!issues.length)?[Math.trunc(res[0]),Math.trunc(res[1])]:null,
    context_flags:uniq,writes_to_model:false,is_presentation_state:true};
  const pick={};
  ACS_RENDER_SPEC.request_fields.forEach(k=>{ if(k in req) pick[k]=req[k]; });
  req.request_id=requestId||('rreq_'+_rdSha16(pick));
  if(issues.length) return {valid:false,issues:issues,request:null};
  return {valid:true,issues:[],request:req}; }

/* --------------------------------------------------- المواد (§4-§7) ----- */
function rdMaterial(mid){ const m=RD_MATERIALS[mid]; return m?_rdCopy(m):null; }
function rdMaterialLibrary(){ return _rdCopy(ACS_RENDER_SPEC.material_library); }
function _rdSlotFor(kind,obj){
  const k=String(kind).toUpperCase();
  if(k==='WALL'&&obj&&typeof obj==='object'){
    const meta=obj.meta||{};
    if(meta.exterior===true||obj.exterior===true) return 'exterior_wall'; }
  const s=ACS_RENDER_SPEC.kind_slot[k];
  return (s===undefined)?null:s; }
function rdAssignMaterials(scene,theme,overrides){
  let th=String(theme||ACS_RENDER_SPEC.default_theme).toUpperCase();
  if(RD_THEMES.indexOf(th)<0) th=ACS_RENDER_SPEC.default_theme;
  const table=ACS_RENDER_SPEC.theme_material[th];
  const ov=(overrides&&typeof overrides==='object'&&!Array.isArray(overrides))?overrides:{};
  const out=[]; let defs=0;
  (scene.objects||[]).forEach(obj=>{
    const oid=obj.id, slot=_rdSlotFor(obj.kind,obj);
    let chosen=null,source=null;
    if((oid in ov)&&RD_MATERIALS[ov[oid]]){ chosen=ov[oid]; source='USER_VISUAL_OVERRIDE'; }
    else if(slot&&(slot in ov)&&RD_MATERIALS[ov[slot]]){ chosen=ov[slot]; source='USER_VISUAL_OVERRIDE'; }
    else if(slot&&RD_MATERIALS[table[slot]]){ chosen=table[slot]; source='THEME_DEFAULT'; }
    else { chosen='r_default'; source='VISUAL_DEFAULT'; }
    if(source==='THEME_DEFAULT'||source==='VISUAL_DEFAULT') defs++;
    const m=RD_MATERIALS[chosen];
    out.push({object_id:oid===undefined?null:oid,kind:obj.kind===undefined?null:obj.kind,
      slot:slot,material_id:chosen,visual_class:m.visual_class,
      assignment_source:source,
      visual_default_applied:source==='THEME_DEFAULT'||source==='VISUAL_DEFAULT',
      semantic_finish_unchanged:true,visual_only:true}); });
  const used=[]; out.forEach(a=>{ if(used.indexOf(a.material_id)<0) used.push(a.material_id); });
  used.sort();
  return {schema:RD_SCHEMA,theme:th,assignments:out,
    visual_default_applied:defs>0,visual_default_count:defs,materials_used:used,
    writes_to_model:false,
    note:'a visual material describes appearance only; it never implies structural '+
         'strength, fire rating, thermal performance or code compliance'}; }
function rdVisualOverride(overrides,scope,target,materialId,intent){
  const it=intent||'VISUAL_OVERRIDE', issues=[];
  if(ACS_RENDER_SPEC.material_override_scopes.indexOf(scope)<0)
    issues.push(_rdIssue('INVALID_TARGET',scope,'unknown override scope'));
  if(!RD_MATERIALS[materialId])
    issues.push(_rdIssue('INVALID_TARGET',materialId,'unknown visual material'));
  if(rdIsUnsafe(String(target),String(materialId)))
    issues.push(_rdIssue('PAYLOAD_REJECTED','override','an override carried markup'));
  if(it==='PROJECT_SPECIFICATION')
    return {valid:false,applied:false,overrides:_rdCopy(overrides||{}),
      requires_authoring:true,
      issues:[_rdIssue('NOT_IMPLEMENTED','intent',
        'changing the project specification is an authoring command and must go '+
        'through the authoring path')],
      note:'a visual override and a specification change are never merged'};
  if(ACS_RENDER_SPEC.override_kinds.indexOf(it)<0)
    issues.push(_rdIssue('INVALID_TARGET',it,'unknown override intent'));
  if(issues.length)
    return {valid:false,applied:false,overrides:_rdCopy(overrides||{}),
      requires_authoring:false,issues:issues};
  const nw=_rdCopy(overrides||{}); nw[String(target)]=materialId;
  return {valid:true,applied:true,overrides:nw,requires_authoring:false,issues:[],
    intent:'VISUAL_OVERRIDE',writes_to_model:false}; }

/* -------------------------------------------------- الإضاءة (§11-§13) --- */
function rdLighting(preset,orientationDeg){
  const p=(typeof preset==='string')?preset.toUpperCase():null;
  if(RD_LIGHTING.indexOf(p)<0)
    return {valid:false,issues:[_rdIssue('INVALID_LIGHTING',preset,
      'unknown lighting preset')],lighting:null};
  const params=_rdCopy(ACS_RENDER_SPEC.lighting_params[p]);
  const known=_rdNum(orientationDeg)!==null;
  if(known) params.azimuth_deg=_rdQ((_rdNum(orientationDeg)+params.azimuth_deg)%360);
  return {valid:true,issues:[],lighting:{preset:p,params:params,
    sun_mode:known?'PROJECT_ORIENTATION':'VISUAL_PRESET',
    is_solar_analysis:false,environment:ACS_RENDER_SPEC.environment_fallback,
    note:'sun direction from a preset is a presentation choice and is never '+
         'presented as solar analysis'}}; }
function rdEnvironment(quality,hasLocalEnvMap){
  let q=String(quality).toUpperCase();
  if(RD_QUALITIES.indexOf(q)<0) q=ACS_RENDER_SPEC.default_quality;
  const wanted=ACS_RENDER_SPEC.quality_profile[q].env_quality;
  const used=(wanted!=='ENVIRONMENT_MAP'||hasLocalEnvMap)?wanted
    :ACS_RENDER_SPEC.environment_fallback;
  return {requested:wanted,used:used,fell_back:used!==wanted,remote_dependency:false,
    note:'the procedural sky is always available, so a render never fails for want '+
         'of a downloadable asset'}; }
function rdQualityProfile(q,constrained){
  let qq=String(q).toUpperCase();
  if(RD_QUALITIES.indexOf(qq)<0) qq=ACS_RENDER_SPEC.default_quality;
  let prof=_rdCopy(ACS_RENDER_SPEC.quality_profile[qq]);
  prof.quality=qq; prof.degraded=false;
  if(constrained){
    const idx=Math.max(0,RD_QUALITIES.indexOf(qq)-2);
    const low=_rdCopy(ACS_RENDER_SPEC.quality_profile[RD_QUALITIES[idx]]);
    low.quality=RD_QUALITIES[idx]; low.degraded=true; low.degraded_from=qq;
    prof=low; }
  prof.shadow_params=_rdCopy(ACS_RENDER_SPEC.shadow_params[prof.shadow_mode]);
  prof.removes_semantic_geometry=false;
  return prof; }

/* -------------------------------------------------- الكاميرا (§28-§30) -- */
function _rdBounds(scene){
  const b=scene.bounds;
  if(!b||b.length!==6) return null;
  return b.map(Number); }
function _rdClampFov(f){
  const lim=ACS_RENDER_SPEC.fov_limits;
  return _rdQ(Math.min(Math.max(Number(f),lim.min_deg),lim.max_deg)); }
function _rdFitDistance(size,fovDeg,aspect){
  let half=Math.max(size[0],size[1]*aspect,size[2])*0.5;
  if(half<=0) half=1.0;
  const f=(Math.max(1e-6,Number(fovDeg))*Math.PI/180)*0.5;
  return _rdQ((half/Math.tan(f))*Number(ACS_RENDER_SPEC.camera_margin)); }
function rdCameraFor(scene,preset,spaceId,aspect){
  const asp=(aspect===undefined||aspect===null)?1.7777778:aspect;
  const p=(typeof preset==='string')?preset.toUpperCase():null;
  if(RD_CAMERA_PRESETS.indexOf(p)<0)
    return {valid:false,issues:[_rdIssue('INVALID_CAMERA',preset,
      'unknown camera preset')],camera:null};
  const b=_rdBounds(scene);
  if(b===null)
    return {valid:false,issues:[_rdIssue('INVALID_CAMERA','bounds',
      'the scene declares no bounds')],camera:null};
  const cx=_rdQ((b[0]+b[3])/2), cy=_rdQ((b[1]+b[4])/2), cz=_rdQ((b[2]+b[5])/2);
  const sx=_rdQ(b[3]-b[0]), sy=_rdQ(b[4]-b[1]), sz=_rdQ(b[5]-b[2]);
  let cam=null;
  if(p==='INTERIOR_WIDE'||p==='INTERIOR_EYE_LEVEL'){
    let space=null;
    (scene.spaces_index||[]).forEach(s=>{
      if(space) return;
      if(s.space_id===spaceId||s.id===spaceId||s.name===spaceId) space=s; });
    if(space===null)
      return {valid:false,issues:[_rdIssue('INVALID_TARGET',spaceId,
        'no such space in the compiled scene')],camera:null};
    const r=space.rect||[0,0,0,0];
    const clear=Number(ACS_RENDER_SPEC.interior_camera_clearance_m);
    if(Number(r[2])<=clear*2.2||Number(r[3])<=clear*2.2)
      return {valid:false,issues:[_rdIssue('SPACE_TOO_SMALL',spaceId,
        'the space is too small for a safe interior camera; no camera is guessed')],
        camera:null};
    const elev=Number(space._elev||0);
    const eye=_rdQ(elev+Number(ACS_RENDER_SPEC.eye_level_m));
    const lens=_rdCopy(ACS_RENDER_SPEC.lens_presets[
      p==='INTERIOR_WIDE'?'INTERIOR_WIDE':'STREET']);
    cam={preset:p,projection:lens.projection,fov_deg:_rdClampFov(lens.fov_deg),
      position:[_rdQ(Number(r[0])+clear+0.001),eye,_rdQ(Number(r[1])+clear+0.001)],
      target:[_rdQ(Number(r[0])+Number(r[2])-clear),eye,
              _rdQ(Number(r[1])+Number(r[3])-clear)],
      up:[0,1,0],inside_space:space.space_id===undefined?null:space.space_id,
      clearance_m:_rdQ(clear)};
  } else if(p==='TOP'){
    cam={preset:p,projection:'orthographic',fov_deg:0,
      ortho_height:_rdQ(Math.max(sz,sx/asp)*Number(ACS_RENDER_SPEC.camera_margin)),
      position:[cx,_rdQ(b[4]+Math.max(sx,sz)+10),cz],target:[cx,cy,cz],up:[0,0,1]};
  } else {
    const lens=_rdCopy(ACS_RENDER_SPEC.lens_presets[
      p==='STREET_VIEW'?'STREET':'ARCHITECTURAL_EXTERIOR']);
    const fov=_rdClampFov(lens.fov_deg);
    const d=_rdFitDistance([sx,sy,sz],fov,asp);
    let pos;
    if(p==='FRONT_EXTERIOR') pos=[cx,_rdQ(cy+sy*0.35),_rdQ(b[2]-d)];
    else if(p==='REAR_EXTERIOR') pos=[cx,_rdQ(cy+sy*0.35),_rdQ(b[5]+d)];
    else if(p==='FRONT_CORNER') pos=[_rdQ(b[0]-d*0.62),_rdQ(cy+sy*0.45),_rdQ(b[2]-d*0.62)];
    else if(p==='REAR_CORNER') pos=[_rdQ(b[3]+d*0.62),_rdQ(cy+sy*0.45),_rdQ(b[5]+d*0.62)];
    else if(p==='BIRDS_EYE') pos=[_rdQ(cx-d*0.35),_rdQ(b[4]+d*0.85),_rdQ(b[2]-d*0.35)];
    else if(p==='DOLLHOUSE') pos=[_rdQ(cx-d*0.45),_rdQ(b[4]+d*0.55),_rdQ(b[2]-d*0.45)];
    else if(p==='STREET_VIEW') pos=[cx,_rdQ(b[1]+Number(ACS_RENDER_SPEC.eye_level_m)),
                                    _rdQ(b[2]-d*1.15)];
    else pos=[cx,_rdQ(cy+sy*0.35),_rdQ(b[2]-d)];
    cam={preset:p,projection:lens.projection,fov_deg:fov,
      position:[_rdQ(pos[0]),_rdQ(pos[1]),_rdQ(pos[2])],target:[cx,cy,cz],up:[0,1,0],
      fit_distance_m:d}; }
  cam.aspect=_rdQ(asp); cam.near_m=0.05; cam.far_m=4000;
  cam.fit_bounds=b.map(_rdQ);
  cam.is_presentation_state=true; cam.writes_to_model=false;
  cam.camera_id='cam_'+_rdSha16(cam);
  return {valid:true,issues:[],camera:cam}; }

/* --------------------------------------------- تحويلات العرض (§21-§23) -- */
function rdVisualTransform(scene,kind,options){
  const o=options||{};
  const k=(typeof kind==='string')?kind.toUpperCase():null;
  if(ACS_RENDER_SPEC.visual_transforms.indexOf(k)<0)
    return {valid:false,issues:[_rdIssue('INVALID_TARGET',kind,
      'unknown visual transform')],transform:null};
  let hidden=[], offsets={}, plane=null;
  const objs=scene.objects||[];
  if(k==='ROOF_HIDE'){
    hidden=objs.filter(o2=>['ROOF','ROOF_CAP'].indexOf(String(o2.kind).toUpperCase())>=0)
      .map(o2=>o2.id).sort();
  } else if(k==='WALL_CLIP'){
    let cut=_rdNum(o.height_m); if(cut===null) cut=1.2;
    hidden=objs.filter(o2=>['CEILING','ROOF','ROOF_CAP']
      .indexOf(String(o2.kind).toUpperCase())>=0).map(o2=>o2.id).sort();
    plane={axis:'y',offset_m:_rdQ(cut),keep:'BELOW'};
  } else if(k==='LEVEL_ISOLATION'){
    const lv=o.level_index;
    const keep=[];
    objs.forEach(ob=>{ const meta=ob.meta||{};
      const li=(meta.level_index!==undefined)?meta.level_index:ob.level_index;
      if(lv!==null&&lv!==undefined&&li!==null&&li!==undefined
         &&Math.trunc(li)!==Math.trunc(lv)) keep.push(ob.id); });
    hidden=keep.sort();
  } else if(k==='CLIP_PLANE'){
    const ax=String(o.axis||'x').toLowerCase();
    if(ACS_RENDER_SPEC.cut_axes.indexOf(ax)<0)
      return {valid:false,issues:[_rdIssue('INVALID_TARGET',o.axis,'unknown cut axis')],
        transform:null};
    const off=_rdNum(o.offset_m);
    const b=_rdBounds(scene)||[0,0,0,1,1,1];
    const mid={x:(b[0]+b[3])/2,y:(b[1]+b[4])/2,z:(b[2]+b[5])/2}[ax];
    plane={axis:ax,offset_m:_rdQ(off===null?mid:off),
      keep:String(o.keep||'BELOW').toUpperCase()};
  } else if(k==='LEVEL_EXPLODE'){
    let gap=_rdNum(o.gap_m);
    if(gap===null) gap=Number(ACS_RENDER_SPEC.explode_gap_m);
    objs.forEach(ob=>{ const meta=ob.meta||{};
      const li=(meta.level_index!==undefined)?meta.level_index:ob.level_index;
      if(li===null||li===undefined) return;
      offsets[ob.id]=[0,_rdQ(Number(li)*gap),0]; }); }
  return {valid:true,issues:[],transform:{kind:k,hidden_object_ids:hidden,
    clip_plane:plane,display_offsets:offsets,reversible:true,
    duplicates_geometry:false,changes_level_elevation:false,writes_to_model:false,
    note:'a visual transform hides or offsets objects for presentation only; the '+
         'engineering geometry and level elevations are untouched'}}; }

/* ------------------------------------ رسومات ثنائية الأبعاد (§24-§27) --- */
function _rdFv(field,fallback){
  if(field&&typeof field==='object'&&!Array.isArray(field)){
    if(field.value!==null&&field.value!==undefined) return [_rdQ(field.value),'MODEL'];
    if(field.render_fallback!==null&&field.render_fallback!==undefined)
      return [_rdQ(field.render_fallback),'DISPLAY_FALLBACK'];
    return [(fallback===null||fallback===undefined)?null:_rdQ(fallback),'UNKNOWN']; }
  const n=_rdNum(field);
  if(n!==null) return [_rdQ(n),'MODEL'];
  return [(fallback===null||fallback===undefined)?null:_rdQ(fallback),'UNKNOWN']; }
function _rdPlanWalls(arch,levelIndex){
  const out=[];
  (arch.walls||[]).forEach(w=>{
    if(levelIndex!==null&&levelIndex!==undefined&&w.level_index!==null
       &&w.level_index!==undefined&&Math.trunc(w.level_index)!==Math.trunc(levelIndex))
      return;
    const a=w.start,b=w.end;
    if(!a||typeof a!=='object'||!b||typeof b!=='object') return;
    const t=_rdFv(w.thickness_m);
    out.push({id:w.id===undefined?null:w.id,
      x1:_rdQ(a.x===undefined?0:a.x),y1:_rdQ(a.z===undefined?0:a.z),
      x2:_rdQ(b.x===undefined?0:b.x),y2:_rdQ(b.z===undefined?0:b.z),
      thickness_m:t[0],thickness_source:t[1],
      exposure:w.exposure===undefined?null:w.exposure}); });
  out.sort((p,q)=>_scmp(String(p.id),String(q.id)));
  return out; }
function _rdPlanOpenings(arch,levelIndex,kind){
  const out=[];
  (arch.openings||[]).forEach(o=>{
    if(String(o.type||'').toUpperCase()!==kind) return;
    if(levelIndex!==null&&levelIndex!==undefined&&o.level_index!==null
       &&o.level_index!==undefined&&Math.trunc(o.level_index)!==Math.trunc(levelIndex))
      return;
    const ax=String(o.axis||'x').toLowerCase();
    const fixed=_rdNum(o.fixed), u=_rdNum(o.u_center);
    if(fixed===null||u===null) return;
    const x=(ax==='x')?u:fixed, y=(ax==='x')?fixed:u;
    const wv=_rdFv(o.width_m);
    out.push({id:o.id===undefined?null:o.id,x:_rdQ(x),y:_rdQ(y),axis:ax,
      width_m:wv[0],width_source:wv[1],
      edge:o.edge===undefined?null:o.edge,
      space_id:o.space_id===undefined?null:o.space_id,
      host_wall_id:o.host_wall_id===undefined?null:o.host_wall_id}); });
  out.sort((p,q)=>_scmp(String(p.id),String(q.id)));
  return out; }
function _rdPlanExtent(spaces,walls){
  const xs=[],ys=[];
  spaces.forEach(s=>{ const r=s.rect||[0,0,0,0];
    xs.push(Number(r[0]),Number(r[0])+Number(r[2]));
    ys.push(Number(r[1]),Number(r[1])+Number(r[3])); });
  walls.forEach(w=>{ xs.push(w.x1,w.x2); ys.push(w.y1,w.y2); });
  if(!xs.length) return [0,0,1,1];
  return [_rdQ(Math.min.apply(null,xs)),_rdQ(Math.min.apply(null,ys)),
          _rdQ(Math.max.apply(null,xs)),_rdQ(Math.max.apply(null,ys))]; }
function rdPlanDrawing(scene,arch,levelIndex,style,options){
  const o=options||{};
  const st=String(style===undefined?'CLEAN':style).toUpperCase();
  if(ACS_RENDER_SPEC.plan_styles.indexOf(st)<0)
    return {valid:false,issues:[_rdIssue('INVALID_TARGET',style,'unknown plan style')],
      drawing:null};
  const spaces=(scene.spaces_index||[]).filter(s=>
    levelIndex===null||levelIndex===undefined
    ||Math.trunc(s.level_index||0)===Math.trunc(levelIndex));
  const walls=_rdPlanWalls(arch||{},levelIndex);
  const doors=_rdPlanOpenings(arch||{},levelIndex,'DOOR');
  const windows=_rdPlanOpenings(arch||{},levelIndex,'WINDOW');
  const stairs=[];
  (scene.objects||[]).forEach(ob=>{
    if(String(ob.kind).toUpperCase()!=='STAIR') return;
    const g=ob.geometry||{};
    stairs.push({id:ob.id===undefined?null:ob.id,
      x:_rdQ(g.cx===undefined?0:g.cx),y:_rdQ(g.cz===undefined?0:g.cz),
      w:_rdQ(g.ex===undefined?1:g.ex),d:_rdQ(g.ez===undefined?1:g.ez)}); });
  const furniture=[];
  if(o.furniture){
    (scene.objects||[]).forEach(ob=>{
      if(ob.semantic&&String(ob.layer).toUpperCase()==='OBJECT'){
        const g=ob.geometry||{};
        furniture.push({id:ob.id===undefined?null:ob.id,
          kind:ob.kind===undefined?null:ob.kind,
          x:_rdQ(g.cx===undefined?0:g.cx),y:_rdQ(g.cz===undefined?0:g.cz),
          w:_rdQ(g.ex===undefined?0.5:g.ex),d:_rdQ(g.ez===undefined?0.5:g.ez)}); } }); }
  const orientation=_rdNum(o.orientation_deg);
  const dims=spaces.map(s=>{ const r=s.rect||[0,0,0,0];
    const a=_rdNum(s.area_m2);
    return {space_id:s.space_id===undefined?null:s.space_id,
      w_m:_rdQ(r[2]),d_m:_rdQ(r[3]),
      area_m2:_rdQ(a===null?(Number(r[2])*Number(r[3])):a),source:'MODEL'}; });
  const drawing={schema:RD_SCHEMA,kind:'FLOOR_PLAN',style:st,
    level_index:(levelIndex===undefined)?null:levelIndex,units:'m',
    extent:_rdPlanExtent(spaces,walls),
    walls:walls,doors:doors,windows:windows,stairs:stairs,
    spaces:spaces.map(s=>({space_id:s.space_id===undefined?null:s.space_id,
      name:s.name===undefined?null:s.name,
      rect:(s.rect||[0,0,0,0]).map(_rdQ),
      area_m2:_rdQ(_rdNum(s.area_m2)===null?0:_rdNum(s.area_m2))})),
    dimensions:dims,furniture:furniture,
    north_deg:orientation===null?null:_rdQ(orientation),
    north_shown:orientation!==null,
    is_construction_drawing:false,writes_to_model:false,
    note:'a presentation plan derived from the compiled architecture; it is not a '+
         'construction drawing and carries no code annotation'};
  drawing.drawing_id='rdrw_'+_rdSha16(drawing);
  return {valid:true,issues:[],drawing:drawing}; }
function rdElevationDrawing(scene,face,options){
  const f=String(face===undefined?'NORTH':face).toUpperCase();
  if(ACS_RENDER_SPEC.elevation_faces.indexOf(f)<0)
    return {valid:false,issues:[_rdIssue('INVALID_TARGET',face,
      'unknown elevation face')],drawing:null};
  const b=_rdBounds(scene);
  if(b===null)
    return {valid:false,issues:[_rdIssue('INVALID_CAMERA','bounds',
      'the scene declares no bounds')],drawing:null};
  const horiz=(f==='NORTH'||f==='SOUTH')?0:2;
  const shapes=[];
  (scene.objects||[]).forEach(ob=>{
    const g=ob.geometry||{};
    if(g.type!=='box') return;
    const kind=String(ob.kind).toUpperCase();
    if(ob.visual_only) return;
    const c=[_rdNum(g.cx),_rdNum(g.cy),_rdNum(g.cz)];
    const e=[_rdNum(g.ex),_rdNum(g.ey),_rdNum(g.ez)];
    if(c.indexOf(null)>=0||e.indexOf(null)>=0) return;
    shapes.push({id:ob.id===undefined?null:ob.id,kind:kind,
      u:_rdQ(c[horiz]-e[horiz]/2),w:_rdQ(e[horiz]),
      y:_rdQ(c[1]-e[1]/2),h:_rdQ(e[1]),
      depth:_rdQ(horiz===0?c[2]:c[0])}); });
  const front=(f==='NORTH'||f==='WEST');
  shapes.sort((p,q)=>{
    const a=front?p.depth:-p.depth, bb=front?q.depth:-q.depth;
    if(a!==bb) return a<bb?-1:1;
    return _scmp(String(p.id),String(q.id)); });
  let u0,u1,y0,y1;
  if(shapes.length){
    u0=Math.min.apply(null,shapes.map(s=>s.u));
    u1=Math.max.apply(null,shapes.map(s=>s.u+s.w));
    y0=Math.min.apply(null,shapes.map(s=>s.y));
    y1=Math.max.apply(null,shapes.map(s=>s.y+s.h));
  } else { u0=(horiz===0)?b[0]:b[2]; u1=(horiz===0)?b[3]:b[5]; y0=b[1]; y1=b[4]; }
  const drawing={schema:RD_SCHEMA,kind:'ELEVATION',face:f,units:'m',
    extent:[_rdQ(u0),_rdQ(y0),_rdQ(u1),_rdQ(y1)],shapes:shapes,
    opening_count:shapes.filter(s=>s.kind==='DOOR'||s.kind==='WINDOW').length,
    invented_features:0,writes_to_model:false,
    note:'only openings present in the model appear; no facade feature is invented'};
  drawing.drawing_id='rdrw_'+_rdSha16(drawing);
  return {valid:true,issues:[],drawing:drawing}; }
function rdSectionDrawing(scene,axis,offsetM,options){
  const ax=String(axis===undefined?'x':axis).toLowerCase();
  if(ACS_RENDER_SPEC.section_axes.indexOf(ax)<0)
    return {valid:false,issues:[_rdIssue('INVALID_TARGET',axis,'unknown section axis')],
      drawing:null};
  const b=_rdBounds(scene);
  if(b===null)
    return {valid:false,issues:[_rdIssue('INVALID_CAMERA','bounds',
      'the scene declares no bounds')],drawing:null};
  const ai=(ax==='x')?0:2;
  let cut=_rdNum(offsetM);
  if(cut===null) cut=(b[ai]+b[ai+3])/2;
  const horiz=(ax==='x')?2:0;
  const cutShapes=[],beyond=[];
  (scene.objects||[]).forEach(ob=>{
    const g=ob.geometry||{};
    if(g.type!=='box'||ob.visual_only) return;
    const c=[_rdNum(g.cx),_rdNum(g.cy),_rdNum(g.cz)];
    const e=[_rdNum(g.ex),_rdNum(g.ey),_rdNum(g.ez)];
    if(c.indexOf(null)>=0||e.indexOf(null)>=0) return;
    const lo=c[ai]-e[ai]/2, hi=c[ai]+e[ai]/2;
    const rec={id:ob.id===undefined?null:ob.id,kind:String(ob.kind).toUpperCase(),
      u:_rdQ(c[horiz]-e[horiz]/2),w:_rdQ(e[horiz]),
      y:_rdQ(c[1]-e[1]/2),h:_rdQ(e[1])};
    if(lo<=cut&&cut<=hi){ rec.cut=true; cutShapes.push(rec); }
    else { rec.cut=false; beyond.push(rec); } });
  cutShapes.sort((p,q)=>_scmp(String(p.id),String(q.id)));
  beyond.sort((p,q)=>_scmp(String(p.id),String(q.id)));
  const all=cutShapes.concat(beyond);
  let u0,u1,y0,y1;
  if(all.length){
    u0=Math.min.apply(null,all.map(s=>s.u));
    u1=Math.max.apply(null,all.map(s=>s.u+s.w));
    y0=Math.min.apply(null,all.map(s=>s.y));
    y1=Math.max.apply(null,all.map(s=>s.y+s.h));
  } else { u0=b[horiz]; u1=b[horiz+3]; y0=b[1]; y1=b[4]; }
  const levels=[];
  (scene.objects||[]).forEach(ob=>{
    if(String(ob.kind).toUpperCase()!=='SLAB') return;
    const v=_rdNum((ob.geometry||{}).cy);
    const q=_rdQ(v===null?0:v);
    if(levels.indexOf(q)<0) levels.push(q); });
  levels.sort((a,b2)=>a-b2);
  const drawing={schema:RD_SCHEMA,kind:'SECTION',axis:ax,offset_m:_rdQ(cut),units:'m',
    extent:[_rdQ(u0),_rdQ(y0),_rdQ(u1),_rdQ(y1)],
    cut_shapes:cutShapes,beyond_shapes:beyond,cut_count:cutShapes.length,
    levels:levels,writes_to_model:false,
    note:'a section through the compiled scene; nothing is drawn that is not in the model'};
  drawing.drawing_id='rdrw_'+_rdSha16(drawing);
  return {valid:true,issues:[],drawing:drawing}; }

/* ------------------------------------------- مخازن التحكّم (§35-§36) ---- */
function _rdProject(cam,p){
  const px=Number(p[0]),py=Number(p[1]),pz=Number(p[2]);
  const ex=Number(cam.position[0]),ey=Number(cam.position[1]),ez=Number(cam.position[2]);
  const tx=Number(cam.target[0]),ty=Number(cam.target[1]),tz=Number(cam.target[2]);
  let fx=tx-ex,fy=ty-ey,fz=tz-ez;
  const fl=Math.sqrt(fx*fx+fy*fy+fz*fz)||1; fx/=fl; fy/=fl; fz/=fl;
  const ux=0,uy=1,uz=0;
  let rx=fy*uz-fz*uy, ry=fz*ux-fx*uz, rz=fx*uy-fy*ux;
  let rl=Math.sqrt(rx*rx+ry*ry+rz*rz);
  if(rl<1e-9){ rx=1; ry=0; rz=0; rl=1; }
  rx/=rl; ry/=rl; rz/=rl;
  const vx=ry*fz-rz*fy, vy=rz*fx-rx*fz, vz=rx*fy-ry*fx;
  const dx=px-ex,dy=py-ey,dz=pz-ez;
  const cxx=dx*rx+dy*ry+dz*rz;
  const cyy=dx*vx+dy*vy+dz*vz;
  const czz=dx*fx+dy*fy+dz*fz;
  if(cam.projection==='orthographic'){
    let oh=Number(cam.ortho_height||1); if(oh<=0) oh=1;
    return [cxx/((oh*Number(cam.aspect||1))/2), cyy/(oh/2), czz]; }
  if(czz<=0.01) return null;
  const t=Math.tan((Number(cam.fov_deg)*Math.PI/180)/2);
  if(t<=0) return null;
  return [cxx/(czz*t*Number(cam.aspect||1)), cyy/(czz*t), czz]; }
function _rdBoxCorners(g){
  const cx=Number(g.cx),cy=Number(g.cy),cz=Number(g.cz);
  const hx=Number(g.ex)/2,hy=Number(g.ey)/2,hz=Number(g.ez)/2;
  const rot=(Number(g.rot_y||0))*Math.PI/180;
  const ca=Math.cos(rot),sa=Math.sin(rot);
  const pts=[];
  [-1,1].forEach(sxg=>{ [-1,1].forEach(syg=>{ [-1,1].forEach(szg=>{
    const lx=hx*sxg, ly=hy*syg, lz=hz*szg;
    pts.push([cx+(lx*ca+lz*sa), cy+ly, cz+(-lx*sa+lz*ca)]); }); }); });
  return pts; }
function _rdSemanticClass(obj){
  const k=String(obj.kind).toUpperCase();
  if(obj.visual_only) return 'VISUAL_ONLY';
  if(k==='WALL'||k==='EXTERIOR_WALL') return 'WALL';
  if(k==='DOOR'||k==='WINDOW'||k==='OPENING'||k==='GLAZING') return 'OPENING';
  if(k==='SLAB'||k==='FLOOR'||k==='CEILING') return 'SLAB';
  if(k==='ROOF'||k==='ROOF_CAP') return 'ROOF';
  if(k==='STAIR') return 'STAIR';
  if(k==='GROUND'||k==='PAVING'||k==='PARKING') return 'GROUND';
  return 'OBJECT'; }
function rdControlBuffers(scene,camera,width,height,kinds,modelHash){
  /* صفر صريح ليس "غير محدَّد": استعمال || يبتلعه ويستبدله بالافتراضي صامتاً */
  const w=Math.trunc((width===undefined||width===null)
    ?ACS_RENDER_SPEC.buffer_default_px.width:width);
  const h=Math.trunc((height===undefined||height===null)
    ?ACS_RENDER_SPEC.buffer_default_px.height:height);
  if(w<=0||h<=0||w*h>Number(ACS_RENDER_SPEC.buffer_max_px))
    return {valid:false,issues:[_rdIssue('INVALID_RESOLUTION',[w,h],
      'buffer resolution out of range')],buffers:null};
  const want=(kinds||RD_BUFFER_KINDS).filter(k=>RD_BUFFER_KINDS.indexOf(k)>=0);
  if(!want.length)
    return {valid:false,issues:[_rdIssue('BUFFER_MISSING',kinds,
      'no known buffer requested')],buffers:null};
  const n=w*h, INF=1e30;
  const depth=new Array(n).fill(INF), objid=new Array(n).fill(0);
  const roomid=new Array(n).fill(0), sem=new Array(n).fill(0), nrm=new Array(n).fill(0);
  const objNames=[null], roomNames=[null], roomOf={};
  (scene.spaces_index||[]).forEach(s=>{
    if(!(s.space_id in roomOf)){ roomNames.push(s.space_id===undefined?null:s.space_id);
      roomOf[s.space_id]=roomNames.length-1; } });
  (scene.objects||[]).forEach(ob=>{
    const g=ob.geometry||{};
    if(g.type!=='box') return;
    const pts=_rdBoxCorners(g), proj=[];
    for(let i=0;i<pts.length;i++){
      const q=_rdProject(camera,pts[i]);
      if(q===null) return;
      proj.push(q); }
    const xs=proj.map(q=>q[0]), ys=proj.map(q=>q[1]), zs=proj.map(q=>q[2]);
    let x0=Math.floor((Math.min.apply(null,xs)*0.5+0.5)*w);
    let x1=Math.ceil((Math.max.apply(null,xs)*0.5+0.5)*w);
    let y0=Math.floor((0.5-Math.max.apply(null,ys)*0.5)*h);
    let y1=Math.ceil((0.5-Math.min.apply(null,ys)*0.5)*h);
    x0=Math.max(0,x0); x1=Math.min(w,x1); y0=Math.max(0,y0); y1=Math.min(h,y1);
    if(x0>=x1||y0>=y1) return;
    const z=Math.min.apply(null,zs);
    objNames.push(ob.id===undefined?null:ob.id);
    const oi=objNames.length-1;
    const si=RD_SEMANTIC_CLASSES.indexOf(_rdSemanticClass(ob));
    const meta=ob.meta||{};
    const rid=(meta.space_id in roomOf)?roomOf[meta.space_id]:0;
    const ex=Number(g.ex),ey=Number(g.ey),ez=Number(g.ez);
    let ni; if(ey<=ex&&ey<=ez) ni=2; else if(ex<=ez) ni=1; else ni=3;
    for(let yy=y0;yy<y1;yy++){
      const base=yy*w;
      for(let xx=x0;xx<x1;xx++){
        const i=base+xx;
        const near=Math.abs(z-depth[i])<=_RD_OPENING_BIAS_M;
        if(near&&si===_RD_SEM_OPENING&&sem[i]===_RD_SEM_WALL){
          depth[i]=(z<depth[i])?z:depth[i];
          objid[i]=oi; roomid[i]=rid; sem[i]=si; nrm[i]=ni;
        } else if(near&&si===_RD_SEM_WALL&&sem[i]===_RD_SEM_OPENING){
        } else if(z<depth[i]){
          depth[i]=z; objid[i]=oi; roomid[i]=rid; sem[i]=si; nrm[i]=ni; } } } });
  let dmax=0;
  for(let i=0;i<n;i++){ const v=depth[i]; if(v<INF&&v>dmax) dmax=v; }
  const depthOut=new Array(n);
  for(let i=0;i<n;i++){
    const v=depth[i];
    depthOut[i]=(v>=INF)?0:(dmax>0?_pyRound((v/dmax)*65535,0):0); }
  const edge=new Array(n).fill(0);
  for(let yy=0;yy<h;yy++){
    for(let xx=0;xx<w;xx++){
      const i=yy*w+xx, a=objid[i];
      if((xx+1<w&&objid[i+1]!==a)||(yy+1<h&&objid[i+w]!==a)) edge[i]=1; } }
  const all={DEPTH:depthOut,EDGE:edge,NORMAL:nrm,OBJECT_ID:objid,ROOM_ID:roomid,
    SEMANTIC_MASK:sem};
  const made={};
  want.forEach(k=>{ made[k]=all[k]; });
  const out={schema:RD_SCHEMA,width:w,height:h,
    camera_id:camera.camera_id===undefined?null:camera.camera_id,
    projection:camera.projection===undefined?null:camera.projection,
    /* المشهد البصري يبصم النموذج في فضاء أسماء المصرّف، والمشروع يبصمه في
       فضاء التأليف. المخزن يحمل الاثنين صراحةً، ويُثبَّت على البصمة التي
       يمرّرها خطّ الأنابيب كي تُقارَن أشباهٌ بأشباه لا فضاءان مختلفان. */
    model_hash:(modelHash===undefined||modelHash===null)
      ?(scene.model_hash===undefined?null:scene.model_hash):modelHash,
    scene_model_hash:scene.model_hash===undefined?null:scene.model_hash,
    kinds:want.slice(),buffers:made,object_names:objNames,room_names:roomNames,
    semantic_classes:RD_SEMANTIC_CLASSES.slice(),
    rasterised_on:'CPU_DETERMINISTIC',gpu_dependent:false,writes_to_model:false};
  const pick={}; want.forEach(k=>{ pick[k]=made[k]; });
  out.buffer_id='rbuf_'+_rdSha16(pick);
  return {valid:true,issues:[],buffers:out}; }
function rdBuffersAligned(a,b){
  const issues=[];
  if(!a||typeof a!=='object'||!b||typeof b!=='object')
    return {aligned:false,issues:[_rdIssue('BUFFER_MISSING','buffers',
      'a buffer set is missing')]};
  ACS_RENDER_SPEC.buffer_alignment_fields.forEach(f=>{
    if(a[f]!==b[f]) issues.push(_rdIssue('BUFFER_MISALIGNED',f,
      'control buffers disagree on '+f)); });
  return {aligned:issues.length===0,issues:issues}; }

/* -------------------------- سمات الهندسة وكشف الانحراف (§39-§41) -------- */
function rdGeometryFeatures(buffers){
  const b=buffers.buffers;
  const w=Math.trunc(buffers.width), h=Math.trunc(buffers.height);
  const sem=b.SEMANTIC_MASK, obj=b.OBJECT_ID;
  if(sem===undefined||obj===undefined)
    return {valid:false,issues:[_rdIssue('BUFFER_MISSING','SEMANTIC_MASK/OBJECT_ID',
      'feature extraction needs the semantic and object buffers')],features:null};
  const bg=RD_SEMANTIC_CLASSES.indexOf('BACKGROUND');
  const ground=RD_SEMANTIC_CLASSES.indexOf('GROUND');
  const opening=RD_SEMANTIC_CLASSES.indexOf('OPENING');
  const roof=RD_SEMANTIC_CLASSES.indexOf('ROOF');
  const slab=RD_SEMANTIC_CLASSES.indexOf('SLAB');
  const visOnly=RD_SEMANTIC_CLASSES.indexOf('VISUAL_ONLY');
  const sil=new Array(w*h);
  for(let i=0;i<w*h;i++)
    sil[i]=(sem[i]!==bg&&sem[i]!==ground&&sem[i]!==visOnly)?1:0;
  const colsTop=[];
  for(let xx=0;xx<w;xx++){
    let top=null;
    for(let yy=0;yy<h;yy++) if(sil[yy*w+xx]){ top=yy; break; }
    colsTop.push(top===null?-1:top); }
  const xs=[];
  for(let xx=0;xx<w;xx++) if(colsTop[xx]>=0) xs.push(xx);
  let silPx=0; for(let i=0;i<w*h;i++) silPx+=sil[i];
  const footprint={min_x:xs.length?Math.min.apply(null,xs):0,
    max_x:xs.length?Math.max.apply(null,xs):0,area_px:silPx};
  const roofLine=colsTop.slice();
  let roofPx=0; for(let i=0;i<w*h;i++) if(sem[i]===roof) roofPx++;
  const bandsFrom=counts=>{
    const out=[]; let run=null;
    for(let yy=0;yy<h;yy++){
      if(counts[yy]>0&&run===null) run=yy;
      else if(counts[yy]===0&&run!==null){ out.push([run,yy-1]); run=null; } }
    if(run!==null) out.push([run,h-1]);
    return out; };
  const openRows=[],slabRows=[];
  for(let yy=0;yy<h;yy++){
    let a=0,c=0;
    for(let xx=0;xx<w;xx++){
      if(sem[yy*w+xx]===opening) a++;
      if(sem[yy*w+xx]===slab) c++; }
    openRows.push(a); slabRows.push(c); }
  let bands=bandsFrom(openRows), bandBasis='OPENING_ROWS';
  if(!bands.length){ bands=bandsFrom(slabRows); bandBasis='SLAB_ROWS'; }
  const seen=new Array(w*h).fill(0), comps=[];
  for(let start=0;start<w*h;start++){
    if(sem[start]!==opening||seen[start]) continue;
    const stack=[start]; seen[start]=1;
    let minx=start%w,maxx=start%w,miny=Math.floor(start/w),maxy=Math.floor(start/w),size=0;
    while(stack.length){
      const i=stack.pop(); size++;
      const xx=i%w, yy=Math.floor(i/w);
      if(xx<minx) minx=xx; if(xx>maxx) maxx=xx;
      if(yy<miny) miny=yy; if(yy>maxy) maxy=yy;
      const nb=[xx>0?i-1:-1, xx+1<w?i+1:-1, yy>0?i-w:-1, yy+1<h?i+w:-1];
      for(let t=0;t<4;t++){ const j=nb[t];
        if(j>=0&&!seen[j]&&sem[j]===opening){ seen[j]=1; stack.push(j); } } }
    comps.push({cx:Math.trunc((minx+maxx)/2),cy:Math.trunc((miny+maxy)/2),
      w:maxx-minx+1,h:maxy-miny+1,px:size}); }
  comps.sort((a,b2)=>(a.cx!==b2.cx)?a.cx-b2.cx:a.cy-b2.cy);
  let wallPx=0;
  for(let i=0;i<w*h;i++) if(sem[i]===RD_SEMANTIC_CLASSES.indexOf('WALL')) wallPx++;
  const ids=[];
  for(let i=0;i<obj.length;i++){
    const o=obj[i];
    if(o&&buffers.object_names[o]&&ids.indexOf(buffers.object_names[o])<0)
      ids.push(buffers.object_names[o]); }
  ids.sort(_scmp);
  const feats={schema:RD_SCHEMA,width:w,height:h,
    model_hash:buffers.model_hash===undefined?null:buffers.model_hash,
    camera_id:buffers.camera_id===undefined?null:buffers.camera_id,
    silhouette_px:silPx,silhouette_excludes_visual_only:true,
    footprint:footprint,roof_line:roofLine,roof_px:roofPx,
    floor_bands:bands,floor_band_count:bands.length,floor_band_basis:bandBasis,
    openings:comps,opening_count:comps.length,wall_px:wallPx,
    semantic_object_ids:ids};
  feats.feature_id=_rdSha16({silhouette_px:feats.silhouette_px,
    footprint:feats.footprint,floor_band_count:feats.floor_band_count,
    opening_count:feats.opening_count,roof_px:feats.roof_px});
  return {valid:true,issues:[],features:feats}; }
function _rdIou(a,b){
  if(a<=0&&b<=0) return 1;
  const lo=(a<b)?a:b, hi=(a<b)?b:a;
  if(hi<=0) return 0;
  return lo/hi; }
function rdDetectDrift(reference,candidate,requiredSemanticIds){
  const issues=[],drifts=[];
  if(!reference||typeof reference!=='object'||!candidate||typeof candidate!=='object')
    return {valid:false,status:'REJECTED',drifts:[],
      issues:[_rdIssue('BUFFER_MISSING','features','a feature set is missing')],
      writes_to_model:false};
  if(reference.width!==candidate.width||reference.height!==candidate.height)
    issues.push(_rdIssue('BUFFER_MISALIGNED','resolution',
      'the candidate is not at the reference resolution'));
  if(reference.camera_id!==candidate.camera_id)
    issues.push(_rdIssue('BUFFER_MISALIGNED','camera_id',
      'the candidate is not from the reference camera'));
  if(reference.model_hash!==candidate.model_hash)
    issues.push(_rdIssue('MODEL_HASH_MISMATCH','model_hash',
      'the candidate is not pinned to the reference model'));
  const add=(t,detail)=>drifts.push({type:t,
    severity:ACS_RENDER_SPEC.drift_severity[t],detail:detail});
  const rb=Math.trunc(reference.floor_band_count||0);
  const cb=Math.trunc(candidate.floor_band_count||0);
  if(rb!==cb) add('FLOOR_COUNT_DRIFT',
    'the reference shows '+rb+' floor bands, the candidate shows '+cb);
  const ro=Math.trunc(reference.opening_count||0);
  const co=Math.trunc(candidate.opening_count||0);
  if(co>ro) add('WINDOW_ADDED',
    'the candidate shows '+co+' openings, the reference '+ro);
  else if(co<ro) add('WINDOW_REMOVED',
    'the candidate shows '+co+' openings, the reference '+ro);
  else {
    const tol=Math.trunc(RD_THRESH.opening_center_tolerance_px);
    const ra=reference.openings||[], ca=candidate.openings||[];
    for(let i=0;i<Math.min(ra.length,ca.length);i++){
      const dx=Math.abs(Math.trunc(ra[i].cx)-Math.trunc(ca[i].cx));
      const dy=Math.abs(Math.trunc(ra[i].cy)-Math.trunc(ca[i].cy));
      if(dx>tol||dy>tol){
        add('DOOR_MOVED','an opening centre moved '+dx+','+dy+
          ' px (tolerance '+tol+')');
        break; } } }
  const fi=_rdIou(Math.trunc((reference.footprint||{}).area_px||0),
                  Math.trunc((candidate.footprint||{}).area_px||0));
  if(fi<Number(RD_THRESH.footprint_iou_min))
    add('FOOTPRINT_DRIFT','footprint overlap '+_rdFix3(fi)+
      ' is below the declared minimum '+_rdFix3(RD_THRESH.footprint_iou_min));
  const wi=_rdIou(Math.trunc(reference.wall_px||0),Math.trunc(candidate.wall_px||0));
  if(wi<Number(RD_THRESH.wall_layout_iou_min))
    add('WALL_LAYOUT_DRIFT','wall coverage overlap '+_rdFix3(wi)+
      ' is below the declared minimum '+_rdFix3(RD_THRESH.wall_layout_iou_min));
  const rl=reference.roof_line||[], cl=candidate.roof_line||[];
  if(rl.length===cl.length&&rl.length){
    let worst=0;
    for(let i=0;i<rl.length;i++){
      if(rl[i]<0&&cl[i]<0) continue;
      const d=Math.abs(Math.trunc(rl[i])-Math.trunc(cl[i]));
      if(d>worst) worst=d; }
    if(worst>Math.trunc(RD_THRESH.roof_line_tolerance_px))
      add('ROOF_GEOMETRY_DRIFT','the roof line moved '+worst+
        ' px (tolerance '+Math.trunc(RD_THRESH.roof_line_tolerance_px)+')'); }
  if(requiredSemanticIds&&requiredSemanticIds.length){
    const have=candidate.semantic_object_ids||[];
    const missing=requiredSemanticIds.filter(x=>have.indexOf(x)<0).sort(_scmp);
    if(missing.length) add('SEMANTIC_OBJECT_MISSING',
      'requested semantic objects are absent from the candidate: '+
      missing.slice(0,4).join(', ')); }
  const major=drifts.filter(d=>d.severity==='MAJOR');
  const minor=drifts.filter(d=>d.severity==='MINOR');
  let status;
  if(issues.length||major.length>=Math.trunc(RD_THRESH.major_drift_reject_at))
    status='REJECTED';
  else if(minor.length>=Math.trunc(RD_THRESH.minor_drift_warn_at)) status='WARNING';
  else status='PASS';
  return {valid:true,status:status,drifts:drifts,issues:issues,
    major_count:major.length,minor_count:minor.length,
    presented_as_model_faithful:status==='PASS',
    drift_code:(status==='REJECTED')?ACS_RENDER_SPEC.drift_rejected_code:null,
    may_regenerate:status!=='PASS',writes_to_model:false,
    note:'material and detail differences are expected and are not drift; a rejected '+
         'image is never presented as model faithful and no drift result edits the model'}; }
function _rdFix3(v){
  /* %.3f في بايثون تقرّب نصف-إلى-زوجي؛ النصّ يجب أن يتطابق حرفاً بحرف */
  const n=_pyRound(Number(v),3);
  let s=String(n);
  if(s.indexOf('.')<0) s+='.';
  let dec=s.split('.')[1]||'';
  while(dec.length<3) dec+='0';
  return s.split('.')[0]+'.'+dec.slice(0,3); }

/* ------------------------------ حدود الذكاء الاصطناعي (§34-§38) --------- */
function rdAiPromptContract(request,visualIntent,references){
  const refs=(references||[]).filter(r=>r&&typeof r==='object');
  const safe=[];
  refs.forEach(r=>{
    if(!rdIsAllowedUri(String(r.uri||''))) return;
    if(rdIsUnsafe(String(r.caption||''))) return;
    if(!rdIsSafeId(String(r.reference_id||''))) return;
    safe.push({reference_id:r.reference_id===undefined?null:r.reference_id,
      kind:r.kind===undefined?null:r.kind,
      scope:r.scope===undefined?null:r.scope}); });
  const intent={};
  if(visualIntent&&typeof visualIntent==='object')
    Object.keys(visualIntent).sort(_scmp).forEach(k=>{
      if(rdIsSafeProse(visualIntent[k])) intent[k]=visualIntent[k]; });
  return {schema:RD_SCHEMA,
    preserve:ACS_RENDER_SPEC.ai_preserve.slice(),
    may_enhance:ACS_RENDER_SPEC.ai_may_enhance.slice(),
    visual_intent:intent,reference_ids:safe.map(r=>r.reference_id),references:safe,
    view_type:request.view_type===undefined?null:request.view_type,
    theme:request.theme===undefined?null:request.theme,
    lighting:request.lighting===undefined?null:request.lighting,
    text:'Preserve exactly: '+ACS_RENDER_SPEC.ai_preserve.join(', ')+
         '. You may enhance only: '+ACS_RENDER_SPEC.ai_may_enhance.join(', ')+
         '. The supplied control buffers define the geometry; do not depart from them.',
    geometry_control_supplied:null,writes_to_model:false}; }
function rdAiRequest(request,baseRender,buffers,promptContract,provider){
  const issues=[];
  if(!buffers||typeof buffers!=='object'||!buffers.buffers)
    issues.push(_rdIssue('BUFFER_MISSING','control_buffers',
      'control buffers are required before an enhancement request'));
  if(baseRender===null||baseRender===undefined)
    issues.push(_rdIssue('BUFFER_MISSING','base_render',
      'the deterministic base render is required first'));
  if(baseRender&&typeof baseRender==='object'&&buffers&&typeof buffers==='object'){
    if(baseRender.camera_id&&buffers.camera_id&&baseRender.camera_id!==buffers.camera_id)
      issues.push(_rdIssue('BUFFER_MISALIGNED','camera_id',
        'the base render and the control buffers use different cameras'));
    if(baseRender.model_hash&&buffers.model_hash
       &&baseRender.model_hash!==buffers.model_hash)
      issues.push(_rdIssue('MODEL_HASH_MISMATCH','model_hash',
        'the base render and the control buffers are pinned to different models')); }
  const contract=_rdCopy(promptContract||{});
  contract.geometry_control_supplied=!!(buffers&&typeof buffers==='object'
    &&buffers.kinds&&buffers.kinds.length);
  const req={schema:RD_SCHEMA,stage_pipeline:ACS_RENDER_SPEC.pipeline.slice(),
    model_hash:((buffers||{}).model_hash===undefined)?null:buffers.model_hash,
    revision_id:request.revision_id===undefined?null:request.revision_id,
    building_id:request.building_id===undefined?null:request.building_id,
    base_render_id:((baseRender||{}).render_id===undefined)?null:baseRender.render_id,
    camera_id:((buffers||{}).camera_id===undefined)?null:buffers.camera_id,
    control_buffer_id:((buffers||{}).buffer_id===undefined)?null:buffers.buffer_id,
    supplied_buffers:((buffers||{}).kinds||[]).slice(),
    prompt:contract,text_only:!contract.geometry_control_supplied,
    reference_ids:(request.reference_ids||[]).slice(),
    provider:(provider===undefined)?null:provider,
    writes_to_model:false,engineering_authority:false,
    generator_shipped:ACS_RENDER_SPEC.photorealistic_engine_shipped};
  if(issues.length) return {valid:false,issues:issues,request:null};
  return {valid:true,issues:[],request:req}; }
function rdProviderAdapter(providerId,available,timeoutS){
  return {schema:RD_SCHEMA,provider_id:providerId,
    accepts:['base_image','control_buffers','prompt','reference_images'],
    returns:['presentation_image','provider_model','generated_at'],
    timeout_s:Math.trunc(timeoutS===undefined?60:timeoutS),
    available:!!available,requires_secret:true,
    secret_location:ACS_RENDER_SPEC.provider_secret_location,
    secret_in_client:false,secret_in_metadata:false,secret_in_logs:false,
    note:'a provider key lives in the server environment only and never appears in '+
         'client source, render metadata or a log'}; }
function rdAiEnhance(adapter,aiReq,providerResult){
  if(!adapter.available||providerResult===null||providerResult===undefined)
    return {valid:false,used_ai:false,
      issues:[_rdIssue('PROVIDER_UNAVAILABLE',adapter.provider_id,
        'the enhancement provider returned nothing; the deterministic render remains '+
        'the output','WARNING')],
      fallback:'DETERMINISTIC_BASE_RENDER',
      base_render_id:aiReq.base_render_id===undefined?null:aiReq.base_render_id,
      output:null,writes_to_model:false};
  return {valid:true,used_ai:true,issues:[],fallback:null,output:{
    type:ACS_RENDER_SPEC.ai_output_type,
    engineering_authority:ACS_RENDER_SPEC.ai_engineering_authority,
    model_hash:aiReq.model_hash===undefined?null:aiReq.model_hash,
    revision_id:aiReq.revision_id===undefined?null:aiReq.revision_id,
    base_render_id:aiReq.base_render_id===undefined?null:aiReq.base_render_id,
    camera_id:aiReq.camera_id===undefined?null:aiReq.camera_id,
    reference_ids:(aiReq.reference_ids||[]).slice(),
    provider:adapter.provider_id===undefined?null:adapter.provider_id,
    provider_model:providerResult.provider_model===undefined?null
      :providerResult.provider_model,
    generated_at:providerResult.generated_at===undefined?null
      :providerResult.generated_at,
    image_ref:providerResult.image_ref===undefined?null:providerResult.image_ref,
    geometry_fidelity:null,writes_to_model:false},writes_to_model:false}; }

/* ------------------------------------ الناتج والأثر (§57-§58, §61) ------ */
function rdRenderDescriptor(request,camera,kind,options){
  const o=options||{}, k=kind||'DETERMINISTIC_RENDER';
  const d={schema:RD_SCHEMA,render_id:null,kind:k,
    model_hash:request.model_hash===undefined?null:request.model_hash,
    revision_id:request.revision_id===undefined?null:request.revision_id,
    building_id:request.building_id===undefined?null:request.building_id,
    level_id:request.level_id===undefined?null:request.level_id,
    space_id:request.space_id===undefined?null:request.space_id,
    camera:camera?_rdCopy(camera):null,
    camera_id:((camera||{}).camera_id===undefined)?null:camera.camera_id,
    view_type:request.view_type===undefined?null:request.view_type,
    quality:request.quality===undefined?null:request.quality,
    theme:request.theme===undefined?null:request.theme,
    lighting:request.lighting===undefined?null:request.lighting,
    ai_used:k==='AI_ENHANCED_VISUALIZATION',
    ai_provider:o.ai_provider===undefined?null:o.ai_provider,
    ai_provider_model:o.ai_provider_model===undefined?null:o.ai_provider_model,
    reference_ids:(request.reference_ids||[]).slice(),
    generated_at:o.created_at===undefined?null:o.created_at,
    geometry_fidelity:o.geometry_fidelity===undefined?null:o.geometry_fidelity,
    visual_default_applied:!!o.visual_default_applied,
    resolution:o.resolution_rendered===undefined?null:o.resolution_rendered,
    resolution_claimed_rendered:!(o.resolution_rendered===undefined
      ||o.resolution_rendered===null),
    engineering_authority:false,certifies_nothing:true,writes_to_model:false,
    note:'a render is a presentation output pinned to one revision. It certifies '+
         'nothing and is never engineering truth'};
  const pick={};
  ACS_RENDER_SPEC.metadata_fields.forEach(f=>{ if(f in d) pick[f]=d[f]; });
  d.render_id='rnd_'+_rdSha16(pick);
  return d; }
function rdStaleness(render,project){
  const cur=project.current_revision===undefined?null:project.current_revision;
  const ch=project.model_hash===undefined?null:project.model_hash;
  const stale=(render.revision_id!==cur)||(render.model_hash!==ch);
  return {render_id:render.render_id===undefined?null:render.render_id,
    status:stale?'STALE_SOURCE_MODEL':'CURRENT',
    render_revision:render.revision_id===undefined?null:render.revision_id,
    current_revision:cur,auto_deleted:false,auto_repointed:false,
    note:'a render stays associated with the revision it was produced from'}; }
function rdGallery(renders,project){
  const cards=(renders||[]).map(r=>({
    render_id:r.render_id===undefined?null:r.render_id,
    thumbnail:r.thumbnail===undefined?null:r.thumbnail,
    view_type:r.view_type===undefined?null:r.view_type,
    revision_id:r.revision_id===undefined?null:r.revision_id,
    theme:r.theme===undefined?null:r.theme,
    kind:r.kind===undefined?null:r.kind,
    geometry_fidelity:r.geometry_fidelity===undefined?null:r.geometry_fidelity,
    staleness:rdStaleness(r,project).status}));
  cards.sort((a,b)=>_scmp(String(a.render_id),String(b.render_id)));
  return {schema:RD_SCHEMA,cards:cards,count:cards.length,
    persistence:ACS_RENDER_SPEC.gallery_persistence,
    cloud:ACS_RENDER_SPEC.gallery_cloud,
    stale_count:cards.filter(c=>c.staleness==='STALE_SOURCE_MODEL').length,
    writes_to_model:false}; }
function rdVariant(request,name,overrides){
  const flags=request.context_flags||[];
  const v={variant_id:null,name:String(name),
    model_hash:request.model_hash===undefined?null:request.model_hash,
    revision_id:request.revision_id===undefined?null:request.revision_id,
    theme:request.theme===undefined?null:request.theme,
    lighting:request.lighting===undefined?null:request.lighting,
    quality:request.quality===undefined?null:request.quality,
    material_overrides:_rdCopy(overrides||{}),
    decor_enabled:flags.length>0&&flags.indexOf('entourage')>=0,
    landscape_enabled:flags.indexOf('vegetation')>=0,
    entourage_enabled:flags.indexOf('entourage')>=0,
    creates_revision:false,writes_to_model:false};
  v.variant_id='rvar_'+_rdSha16(v);
  return v; }

/* ------------------------------------- فصل العرضي عن الدلالي ------------ */
function rdSeparateVisual(scene){
  const semantic=[],visual=[];
  (scene.objects||[]).forEach(ob=>{
    const rec={id:ob.id===undefined?null:ob.id,
      kind:ob.kind===undefined?null:ob.kind,
      layer:ob.layer===undefined?null:ob.layer};
    if(ob.visual_only){
      const layer=String(ob.layer).toUpperCase();
      rec.tag=(layer==='LANDSCAPE')?ACS_RENDER_SPEC.landscape_tag
        :(layer==='ENTOURAGE')?ACS_RENDER_SPEC.entourage_tag
        :ACS_RENDER_SPEC.decoration_tag;
      visual.push(rec);
    } else semantic.push(rec); });
  semantic.sort((a,b)=>_scmp(String(a.id),String(b.id)));
  visual.sort((a,b)=>_scmp(String(a.id),String(b.id)));
  return {semantic_objects:semantic,semantic_count:semantic.length,
    visual_only_objects:visual,visual_only_count:visual.length,
    counts_are_separate:true,visual_enters_semantic_count:false,
    visual_becomes_site_data:false,
    note:'visual furniture, plants, people and vehicles are presentation objects and '+
         'never enter semantic object counts or site engineering data'}; }
function rdContextEnabled(request,flag){
  return (request.context_flags||[]).indexOf(flag)>=0; }

/* --------------------------------------- إخراج متّجه (§25) -------------- */
function _rdEsc(v){
  return String(v===null||v===undefined?'':v).replace(/&/g,'&amp;')
    .replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')
    .replace(/'/g,'&#39;'); }
function _rdFmt(v){
  const n=_pyRound(Number(v),3)+0;
  if(n===Math.trunc(n)) return String(Math.trunc(n));
  let s=n.toFixed(3);
  s=s.replace(/0+$/,'').replace(/\.$/,'');
  return s; }
const _RD_PLAN_STYLE={
  TECHNICAL:{bg:'#ffffff',wall:'#111111',space:'#f6f6f4',text:'#222222',
    open:'#ffffff',stair:'#dddddd'},
  CLEAN:{bg:'#ffffff',wall:'#2b2b2b',space:'#f2efe9',text:'#3a3a3a',
    open:'#ffffff',stair:'#e3ded3'},
  MONOCHROME:{bg:'#ffffff',wall:'#000000',space:'#ffffff',text:'#000000',
    open:'#ffffff',stair:'#eeeeee'},
  PRESENTATION:{bg:'#12161c',wall:'#e8e6e1',space:'#1d232c',text:'#cfd6de',
    open:'#12161c',stair:'#2b3440'}};
function rdPlanSvg(drawing,options){
  const o=options||{};
  const st=_RD_PLAN_STYLE[drawing.style]||_RD_PLAN_STYLE.CLEAN;
  const pxm=Number(o.px_per_m||34), pad=Number(o.padding_px||46);
  const ex=drawing.extent||[0,0,1,1];
  const wM=Number(ex[2])-Number(ex[0]), hM=Number(ex[3])-Number(ex[1]);
  const W=Math.round(wM*pxm+pad*2), H=Math.round(hM*pxm+pad*2);
  const X=x=>_rdFmt((Number(x)-Number(ex[0]))*pxm+pad);
  const Y=y=>_rdFmt((Number(y)-Number(ex[1]))*pxm+pad);
  const S=v=>_rdFmt(Number(v)*pxm);
  const p=['<svg xmlns="http://www.w3.org/2000/svg" width="'+W+'" height="'+H+
    '" viewBox="0 0 '+W+' '+H+
    '" font-family="system-ui,Segoe UI,Tahoma,sans-serif">',
    '<rect width="'+W+'" height="'+H+'" fill="'+st.bg+'"/>'];
  (drawing.spaces||[]).forEach(s=>{ const r=s.rect||[0,0,0,0];
    p.push('<rect x="'+X(r[0])+'" y="'+Y(r[1])+'" width="'+S(r[2])+'" height="'+
      S(r[3])+'" fill="'+st.space+'" stroke="none" data-space="'+
      _rdEsc(s.space_id)+'"/>'); });
  (drawing.walls||[]).forEach(w=>{
    p.push('<line x1="'+X(w.x1)+'" y1="'+Y(w.y1)+'" x2="'+X(w.x2)+'" y2="'+Y(w.y2)+
      '" stroke="'+st.wall+'" stroke-width="'+
      S(Math.max(0.08,Number(w.thickness_m||0.2)))+
      '" stroke-linecap="square" data-wall="'+_rdEsc(w.id)+'"/>'); });
  (drawing.doors||[]).forEach(d=>{
    const ww=Number(d.width_m||0.9), horiz=String(d.axis)==='x';
    p.push('<rect x="'+X(Number(d.x)-(horiz?ww/2:0.13))+'" y="'+
      Y(Number(d.y)-(horiz?0.13:ww/2))+'" width="'+S(horiz?ww:0.26)+
      '" height="'+S(horiz?0.26:ww)+'" fill="'+st.open+'" stroke="'+st.wall+
      '" stroke-width="1" data-door="'+_rdEsc(d.id)+'"/>'); });
  (drawing.windows||[]).forEach(d=>{
    const ww=Number(d.width_m||1.2), horiz=String(d.axis)==='x';
    p.push('<rect x="'+X(Number(d.x)-(horiz?ww/2:0.09))+'" y="'+
      Y(Number(d.y)-(horiz?0.09:ww/2))+'" width="'+S(horiz?ww:0.18)+
      '" height="'+S(horiz?0.18:ww)+'" fill="'+st.open+
      '" stroke="#4a7d94" stroke-width="1.4" data-window="'+_rdEsc(d.id)+'"/>'); });
  (drawing.stairs||[]).forEach(s=>{
    p.push('<rect x="'+X(Number(s.x)-Number(s.w)/2)+'" y="'+
      Y(Number(s.y)-Number(s.d)/2)+'" width="'+S(s.w)+'" height="'+S(s.d)+
      '" fill="'+st.stair+'" stroke="'+st.wall+'" stroke-width="1" data-stair="'+
      _rdEsc(s.id)+'"/>'); });
  (drawing.furniture||[]).forEach(f=>{
    p.push('<rect x="'+X(Number(f.x)-Number(f.w)/2)+'" y="'+
      Y(Number(f.y)-Number(f.d)/2)+'" width="'+S(f.w)+'" height="'+S(f.d)+
      '" fill="none" stroke="'+st.text+
      '" stroke-width="1" stroke-dasharray="3 2" data-furniture="'+
      _rdEsc(f.id)+'"/>'); });
  (drawing.spaces||[]).forEach(s=>{ const r=s.rect||[0,0,0,0];
    const cx=Number(r[0])+Number(r[2])/2, cy=Number(r[1])+Number(r[3])/2;
    p.push('<text x="'+X(cx)+'" y="'+Y(cy)+'" fill="'+st.text+
      '" font-size="11" text-anchor="middle" data-label="'+_rdEsc(s.space_id)+
      '">'+_rdEsc(s.name||s.space_id)+'</text>');
    p.push('<text x="'+X(cx)+'" y="'+_rdFmt(Number(Y(cy))+13)+'" fill="'+st.text+
      '" font-size="9" text-anchor="middle" opacity="0.75">'+
      _rdFmt(s.area_m2||0)+' m²</text>'); });
  if(drawing.north_shown)
    p.push('<g data-north="1"><circle cx="'+_rdFmt(W-30)+'" cy="26" r="13" fill="none" '+
      'stroke="'+st.text+'"/><text x="'+_rdFmt(W-30)+'" y="30" fill="'+st.text+
      '" font-size="11" text-anchor="middle">N</text></g>');
  p.push('<text x="'+_rdFmt(pad)+'" y="'+_rdFmt(H-14)+'" fill="'+st.text+
    '" font-size="9" opacity="0.7">presentation drawing — not a construction '+
    'drawing</text>');
  p.push('</svg>');
  return p.join('\n'); }
function rdElevationSvg(drawing,options){
  const o=options||{};
  const pxm=Number(o.px_per_m||34), pad=Number(o.padding_px||46);
  const ex=drawing.extent||[0,0,1,1];
  const wM=Number(ex[2])-Number(ex[0]), hM=Number(ex[3])-Number(ex[1]);
  const W=Math.round(wM*pxm+pad*2), H=Math.round(hM*pxm+pad*2);
  const X=x=>_rdFmt((Number(x)-Number(ex[0]))*pxm+pad);
  const Y=y=>_rdFmt(H-pad-(Number(y)-Number(ex[1]))*pxm);
  const S=v=>_rdFmt(Number(v)*pxm);
  const fill={WALL:'#dcd8d0',SLAB:'#c6c2ba',DOOR:'#8a6a44',WINDOW:'#9dc4d6',
    STAIR:'#cfcabf',ROOF_CAP:'#b9b4aa',CEILING:'#d2cec6'};
  const p=['<svg xmlns="http://www.w3.org/2000/svg" width="'+W+'" height="'+H+
    '" viewBox="0 0 '+W+' '+H+
    '" font-family="system-ui,Segoe UI,Tahoma,sans-serif">',
    '<rect width="'+W+'" height="'+H+'" fill="#ffffff"/>'];
  (drawing.shapes||[]).forEach(s=>{
    p.push('<rect x="'+X(s.u)+'" y="'+Y(Number(s.y)+Number(s.h))+'" width="'+S(s.w)+
      '" height="'+S(s.h)+'" fill="'+(fill[s.kind]||'#e2e0db')+
      '" stroke="#3a3a3a" stroke-width="0.6" data-shape="'+_rdEsc(s.id)+
      '" data-kind="'+_rdEsc(s.kind)+'"/>'); });
  p.push('<line x1="'+_rdFmt(pad*0.4)+'" y1="'+Y(0)+'" x2="'+_rdFmt(W-pad*0.4)+
    '" y2="'+Y(0)+'" stroke="#111" stroke-width="1.4"/>');
  p.push('<text x="'+_rdFmt(pad)+'" y="'+_rdFmt(H-14)+
    '" fill="#333" font-size="10">'+_rdEsc(drawing.face)+
    ' elevation — '+Math.trunc(drawing.opening_count||0)+
    ' modelled openings, 0 invented</text>');
  p.push('</svg>');
  return p.join('\n'); }
function rdSectionSvg(drawing,options){
  const o=options||{};
  const pxm=Number(o.px_per_m||34), pad=Number(o.padding_px||46);
  const ex=drawing.extent||[0,0,1,1];
  const wM=Number(ex[2])-Number(ex[0]), hM=Number(ex[3])-Number(ex[1]);
  const W=Math.round(wM*pxm+pad*2), H=Math.round(hM*pxm+pad*2);
  const X=x=>_rdFmt((Number(x)-Number(ex[0]))*pxm+pad);
  const Y=y=>_rdFmt(H-pad-(Number(y)-Number(ex[1]))*pxm);
  const S=v=>_rdFmt(Number(v)*pxm);
  const p=['<svg xmlns="http://www.w3.org/2000/svg" width="'+W+'" height="'+H+
    '" viewBox="0 0 '+W+' '+H+
    '" font-family="system-ui,Segoe UI,Tahoma,sans-serif">',
    '<rect width="'+W+'" height="'+H+'" fill="#ffffff"/>'];
  (drawing.beyond_shapes||[]).forEach(s=>{
    p.push('<rect x="'+X(s.u)+'" y="'+Y(Number(s.y)+Number(s.h))+'" width="'+S(s.w)+
      '" height="'+S(s.h)+'" fill="#eeece8" stroke="#cfcbc4" stroke-width="0.5" '+
      'data-beyond="'+_rdEsc(s.id)+'"/>'); });
  (drawing.cut_shapes||[]).forEach(s=>{
    p.push('<rect x="'+X(s.u)+'" y="'+Y(Number(s.y)+Number(s.h))+'" width="'+S(s.w)+
      '" height="'+S(s.h)+'" fill="#2b2b2b" stroke="#000" stroke-width="0.8" '+
      'data-cut="'+_rdEsc(s.id)+'" data-kind="'+_rdEsc(s.kind)+'"/>'); });
  p.push('<text x="'+_rdFmt(pad)+'" y="'+_rdFmt(H-14)+
    '" fill="#333" font-size="10">section on '+_rdEsc(drawing.axis)+' at '+
    _rdFmt(drawing.offset_m||0)+' m — '+Math.trunc(drawing.cut_count||0)+
    ' cut elements</text>');
  p.push('</svg>');
  return p.join('\n'); }

/* --------------------------------- صورة مخزن تحكّم حتمية ---------------- */
let _RD_CRC_TABLE=null;
function _rdCrc32(data){
  if(_RD_CRC_TABLE===null){
    _RD_CRC_TABLE=[];
    for(let n=0;n<256;n++){ let c=n;
      for(let k=0;k<8;k++) c=(c&1)?(0xEDB88320^(c>>>1)):(c>>>1);
      _RD_CRC_TABLE.push(c>>>0); } }
  let c=0xFFFFFFFF;
  for(let i=0;i<data.length;i++)
    c=(_RD_CRC_TABLE[(c^data[i])&0xFF]^(c>>>8))>>>0;
  return (c^0xFFFFFFFF)>>>0; }
function _rdAdler32(data){
  let a=1,b=0;
  for(let i=0;i<data.length;i++){ a=(a+data[i])%65521; b=(b+a)%65521; }
  return (((b<<16)|a)>>>0); }
function _rdBe32(n){
  return [(n>>>24)&255,(n>>>16)&255,(n>>>8)&255,n&255]; }
function _rdChunk(tag,data){
  const body=[];
  for(let i=0;i<tag.length;i++) body.push(tag.charCodeAt(i));
  for(let i=0;i<data.length;i++) body.push(data[i]);
  return _rdBe32(data.length).concat(body).concat(_rdBe32(_rdCrc32(body))); }
function rdBufferPng(buffers,kind){
  /* كتل zlib مخزَّنة لا مضغوطة عمداً: مستويات الضغط تختلف بين المكتبات،
     وبقاء البايتات متطابقة بين بايثون وجافاسكربت شرطٌ في هذه المرحلة. */
  if((buffers.kinds||[]).indexOf(kind)<0) return null;
  const w=Math.trunc(buffers.width), h=Math.trunc(buffers.height);
  const src=buffers.buffers[kind];
  let mx=0;
  for(let i=0;i<src.length;i++) if(src[i]>mx) mx=src[i];
  const raw=[];
  for(let y=0;y<h;y++){
    raw.push(0);
    const row=y*w;
    for(let x=0;x<w;x++){
      const v=src[row+x];
      raw.push(mx===0?0:(Math.floor((v*255)/mx)&255)); } }
  const z=[0x78,0x01];
  let i=0; const n=raw.length;
  while(i<n){
    const blk=Math.min(65535,n-i);
    z.push((i+blk>=n)?1:0);
    z.push(blk&255,(blk>>8)&255,(~blk)&255,((~blk)>>8)&255);
    for(let j=0;j<blk;j++) z.push(raw[i+j]);
    i+=blk; }
  const ad=_rdAdler32(raw);
  z.push.apply(z,_rdBe32(ad));
  let png=[137,80,78,71,13,10,26,10];
  png=png.concat(_rdChunk('IHDR',_rdBe32(w).concat(_rdBe32(h)).concat([8,0,0,0,0])));
  png=png.concat(_rdChunk('IDAT',z));
  png=png.concat(_rdChunk('IEND',[]));
  return png; }

/* =========================== لوحة التصوير داخل مساحة العمل (§59-§63) ===== */
const RV = (function(){
  const S={project:null,scene:null,arch:null,request:null,camera:null,
           overrides:{},renders:[],current:null,mode:'BASE',
           view:'EXTERIOR',theme:ACS_RENDER_SPEC.default_theme,
           lighting:ACS_RENDER_SPEC.default_lighting,
           quality:ACS_RENDER_SPEC.default_quality,ai:false};
  const $=id=>(typeof document!=='undefined')?document.getElementById(id):null;
  const esc=_rdEsc;
  function attach(project,scene,arch){ S.project=project; S.scene=scene; S.arch=arch;
    return S; }
  function state(){ return S; }
  function open(){ const p=$('rvPanel'); if(p) p.classList.add('on'); render(); return true; }
  function close(){ const p=$('rvPanel'); if(p) p.classList.remove('on'); return true; }
  function set(k,v){
    if(k==='view'&&RD_VIEW_TYPES.indexOf(v)>=0) S.view=v;
    else if(k==='theme'&&RD_THEMES.indexOf(v)>=0) S.theme=v;
    else if(k==='lighting'&&RD_LIGHTING.indexOf(v)>=0) S.lighting=v;
    else if(k==='quality'&&RD_QUALITIES.indexOf(v)>=0) S.quality=v;
    else if(k==='ai') S.ai=!!v;
    render(); return S[k]; }
  function chips(name,list,cur){
    return '<div class="rv-chips" data-rv-group="'+esc(name)+'">'+list.map(v=>
      '<button class="rv-chip'+(v===cur?' on':'')+'" data-rv-set="'+esc(name)+
      '" data-rv-val="'+esc(v)+'">'+esc(v)+'</button>').join('')+'</div>'; }
  function render(){
    const host=$('rvBody'); if(!host) return;
    if(!S.project){ host.innerHTML='<div class="rv-note">No project open</div>'; return; }
    const p=[];
    p.push('<div class="rv-sec" data-rv-section="VIEW"><h4>View</h4>'+
      chips('view',RD_VIEW_TYPES,S.view)+'</div>');
    p.push('<div class="rv-sec" data-rv-section="STYLE"><h4>Style</h4>'+
      chips('theme',RD_THEMES,S.theme)+'</div>');
    p.push('<div class="rv-sec" data-rv-section="LIGHTING"><h4>Lighting</h4>'+
      chips('lighting',RD_LIGHTING,S.lighting)+'</div>');
    p.push('<div class="rv-sec" data-rv-section="QUALITY"><h4>Quality</h4>'+
      chips('quality',RD_QUALITIES,S.quality)+'</div>');
    p.push('<div class="rv-sec" data-rv-section="MATERIALS"><h4>Materials</h4>'+
      '<div class="rv-row"><span class="k">visual override</span><span class="v">'+
      Object.keys(S.overrides).length+'</span></div>'+
      '<div class="rv-note">a visual override changes appearance only; changing the '+
      'project specification goes through the authoring path</div></div>');
    p.push('<div class="rv-sec" data-rv-section="AI_ENHANCEMENT"><h4>AI enhancement</h4>'+
      '<div class="rv-toggle"><button data-rv-set="ai" data-rv-val="" class="'+
      (S.ai?'':'on')+'">Base only</button><button data-rv-set="ai" data-rv-val="1" '+
      'class="'+(S.ai?'on':'')+'">AI enhanced</button></div>'+
      '<div class="rv-note" data-rv="ai-note">'+
      (ACS_RENDER_SPEC.photorealistic_engine_shipped?'':
       'no generator is bundled; without a provider the deterministic render is the '+
       'output')+'</div></div>');
    p.push('<div class="rv-sec" data-rv-section="GALLERY"><h4>Renders ('+
      S.renders.length+')</h4>'+galleryHtml()+'</div>');
    host.innerHTML=p.join('');
    Array.prototype.forEach.call(host.querySelectorAll('[data-rv-set]'),el=>{
      el.onclick=()=>{ const k=el.getAttribute('data-rv-set');
        const v=el.getAttribute('data-rv-val');
        set(k,k==='ai'?!!v:v); }; });
    Array.prototype.forEach.call(host.querySelectorAll('[data-rv-open]'),el=>{
      el.onclick=()=>show(el.getAttribute('data-rv-open')); }); }
  function galleryHtml(){
    if(!S.renders.length) return '<div class="rv-note">No render yet</div>';
    const g=rdGallery(S.renders,S.project);
    return '<div class="rv-gallery">'+g.cards.map(c=>{
      const r=S.renders.filter(x=>x.render_id===c.render_id)[0]||{};
      return '<div class="rv-card" data-rv-render="'+esc(c.render_id)+
        '" data-rv-open="'+esc(c.render_id)+'"><div class="rv-thumb">'+
        (r.svg?r.svg:esc(c.view_type))+'</div><div class="t">'+esc(c.view_type)+
        ' · '+esc(c.theme)+'</div><div class="f '+esc(c.geometry_fidelity||'')+
        '" data-rv-fidelity="'+esc(c.geometry_fidelity||'')+'">'+
        esc(c.kind==='AI_ENHANCED_VISUALIZATION'?'AI':'BASE')+
        (c.geometry_fidelity?(' · '+esc(c.geometry_fidelity)):'')+'</div>'+
        (c.staleness==='STALE_SOURCE_MODEL'
          ?'<div class="s" data-rv-stale="1">STALE_SOURCE_MODEL</div>':'')+
        '</div>'; }).join('')+'</div>'; }
  function buildRequest(){
    const r=rdRenderRequest(S.project,S.view,{theme:S.theme,lighting:S.lighting,
      quality:S.quality,ai_enhancement:S.ai});
    if(r.valid) S.request=r.request;
    return r; }
  function preview(){
    const r=buildRequest();
    if(!r.valid) return r;
    const cam=rdCameraFor(S.scene,cameraForView(S.view));
    if(cam.valid) S.camera=cam.camera;
    return {valid:cam.valid,request:r.request,camera:cam.camera,issues:cam.issues}; }
  function cameraForView(v){
    return {EXTERIOR:'FRONT_CORNER',INTERIOR:'INTERIOR_WIDE',DOLLHOUSE:'DOLLHOUSE',
      CUTAWAY:'FRONT_CORNER',ISOMETRIC:'BIRDS_EYE',TOP:'TOP',FLOOR_PLAN:'TOP',
      SECTION:'FRONT_EXTERIOR',ELEVATION:'FRONT_EXTERIOR',PANORAMA:'STREET_VIEW',
      VR_PREVIEW:'INTERIOR_EYE_LEVEL'}[v]||'FRONT_CORNER'; }
  function doRender(createdAt){
    const before=S.project?S.project.model_hash:null;
    const pv=preview();
    if(!pv.valid) return pv;
    let svg=null;
    if(S.view==='FLOOR_PLAN'){
      const d=rdPlanDrawing(S.scene,S.arch,0,'CLEAN');
      if(d.valid) svg=rdPlanSvg(d.drawing); }
    else if(S.view==='ELEVATION'){
      const d=rdElevationDrawing(S.scene,'NORTH');
      if(d.valid) svg=rdElevationSvg(d.drawing); }
    else if(S.view==='SECTION'){
      const d=rdSectionDrawing(S.scene,'x');
      if(d.valid) svg=rdSectionSvg(d.drawing); }
    const mats=rdAssignMaterials(S.scene,S.theme,S.overrides);
    const desc=rdRenderDescriptor(S.request,S.camera,'DETERMINISTIC_RENDER',
      {created_at:createdAt===undefined?null:createdAt,
       visual_default_applied:mats.visual_default_applied});
    desc.svg=svg;
    S.renders=S.renders.concat([desc]);
    S.current=desc;
    if(S.project&&S.project.model_hash!==before)
      throw new Error('a render changed the engineering model');
    render();
    return {valid:true,render:desc,issues:[]}; }
  function compare(){ S.mode=(S.mode==='BASE')?'AI':'BASE'; render(); return S.mode; }
  function show(id){
    const r=S.renders.filter(x=>x.render_id===id)[0];
    const v=$('rvView'), box=$('rvViewBox');
    if(!v||!box||!r) return null;
    box.innerHTML=r.svg?r.svg:('<div style="padding:20px;color:#333">'+
      esc(r.view_type)+' — deterministic base render requires the 3D runtime</div>');
    v.classList.add('on');
    return r; }
  function hide(){ const v=$('rvView'); if(v) v.classList.remove('on'); return true; }
  function gallery(){ return rdGallery(S.renders,S.project); }
  function renders(){ return S.renders.slice(); }
  function init(){
    const c=$('rvClose'); if(c) c.onclick=close;
    const rb=$('rvRender'); if(rb) rb.onclick=()=>{ try{ doRender(); }catch(e){} };
    const pb=$('rvPreview'); if(pb) pb.onclick=()=>{ preview(); };
    const cb=$('rvCompare'); if(cb) cb.onclick=compare;
    const vb=$('rvView'); if(vb) vb.onclick=e=>{ if(e.target===vb) hide(); };
    return true; }
  if(typeof document!=='undefined'&&document.addEventListener)
    document.addEventListener('DOMContentLoaded',init);
  return {attach:attach,state:state,open:open,close:close,set:set,render:render,
    preview:preview,doRender:doRender,compare:compare,show:show,hide:hide,
    gallery:gallery,renders:renders,init:init,request:()=>S.request,
    camera:()=>S.camera,overrides:()=>S.overrides,mode:()=>S.mode};
})();

if(typeof window!=='undefined'){
  window.ACS=window.ACS||{};
  window.ACS.render={
    spec:()=>_rdCopy(ACS_RENDER_SPEC),
    request:rdRenderRequest, camera:rdCameraFor, materials:rdAssignMaterials,
    override:rdVisualOverride, lighting:rdLighting, environment:rdEnvironment,
    quality:rdQualityProfile, transform:rdVisualTransform,
    plan:rdPlanDrawing, elevation:rdElevationDrawing, section:rdSectionDrawing,
    planSvg:rdPlanSvg, elevationSvg:rdElevationSvg, sectionSvg:rdSectionSvg,
    bufferPng:rdBufferPng,
    buffers:rdControlBuffers, aligned:rdBuffersAligned,
    features:rdGeometryFeatures, drift:rdDetectDrift,
    promptContract:rdAiPromptContract, aiRequest:rdAiRequest,
    provider:rdProviderAdapter, enhance:rdAiEnhance,
    descriptor:rdRenderDescriptor, staleness:rdStaleness, gallery:rdGallery,
    variant:rdVariant, separate:rdSeparateVisual,
    safeId:rdIsSafeId, allowedUri:rdIsAllowedUri, unsafe:rdIsUnsafe,
    safeProse:rdIsSafeProse,
    panel:RV};
}
"""


def _replace(page, begin, end, block, anchor, after_anchor):
    if begin in page and end in page:
        a = page.index(begin)
        b = page.index(end) + len(end)
        tail = page[b:]
        if tail.startswith("\n"):
            tail = tail[1:]
        return page[:a] + block + tail, "replaced"
    i = page.index(anchor)
    if after_anchor:
        i += len(anchor)
        if page[i:i + 1] == "\n":
            i += 1
    return page[:i] + block + page[i:], "injected"


def build():
    with open(SPEC_PATH, "r", encoding="utf-8") as f:
        spec = json.load(f)
    body = BODY.replace("__SPEC__", json.dumps(spec, ensure_ascii=False,
                                               separators=(",", ":")))
    js_block = JS_BEGIN + "\n" + body + "\n" + JS_END + "\n"
    css_block = CSS_BEGIN + "\n" + CSS + "\n" + CSS_END + "\n"
    dom_block = DOM_BEGIN + "\n" + DOM + "\n" + DOM_END + "\n"

    with open(PAGE, "r", encoding="utf-8") as f:
        page = f.read()
    page, a1 = _replace(page, CSS_BEGIN, CSS_END, css_block, CSS_ANCHOR, False)
    page, a2 = _replace(page, DOM_BEGIN, DOM_END, dom_block, DOM_ANCHOR, False)
    page, a3 = _replace(page, JS_BEGIN, JS_END, js_block, JS_ANCHOR, True)
    with open(PAGE, "w", encoding="utf-8") as f:
        f.write(page)
    print("render styles %s (%d bytes), dom %s (%d bytes), engine %s (%d bytes)"
          % (a1, len(css_block), a2, len(dom_block), a3, len(js_block)))


if __name__ == "__main__":
    build()
