# -*- coding: utf-8 -*-
"""يبني نسخة المتصفّح من طبقة زمن التشغيل ويحقنها في public/index.html.

المواصفة القانونية acs_runtime.json تُنسخ حرفياً، والمنطق مرآة سطر بسطر لـ
acs_runtime.py. الحقن عديم الأثر عند التكرار: إن كانت الكتلة موجودة تُستبدل
بالكامل بدل أن تُكرَّر، فلا تنشأ نسخة ثانية غير محكومة.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
IDX = os.path.join(ROOT, 'public', 'index.html')
SPEC_PATH = os.path.join(ROOT, 'acs_runtime.json')

BEGIN = '/* ===== ACS RUNTIME LAYER (generated by tools/build_runtime_browser.py) ===== */'
END = '/* ===== END ACS RUNTIME LAYER ===== */'
ANCHOR = 'const ACS_VISUAL_SPEC = '

JS = r'''
/* ==================================================================
   المرحلة 4 — أساس التجوّل التفاعلي وزمن التشغيل الحتمي (مطابق لـ acs_runtime.py).
   تفاعل للقراءة فقط: زمن التشغيل زائل والنموذج الهندسي غير قابل للتعديل •
   لا محرّك محاكاة ولا فيزياء ولا تمهيد مسارات ولا وكلاء ولا ذكاء اصطناعي •
   لا مسار كتابة عكسي إلى المشهد البصري ولا إلى أي نموذج هندسي.
   ================================================================== */
const ACS_RUNTIME_SPEC = __SPEC__;
const RT_SCHEMA = ACS_RUNTIME_SPEC.schema;
const RT_VERSION = ACS_RUNTIME_SPEC.version;
const RT_COMPILER_VERSION = ACS_RUNTIME_SPEC.compiler_version;
const RT_NAVIGATION_MODES = ACS_RUNTIME_SPEC.navigation_modes;
const RT_NAVIGATION_CONTRACTS = ACS_RUNTIME_SPEC.navigation_contracts;
const RT_DEFAULT_NAV = ACS_RUNTIME_SPEC.default_navigation_mode;
const RT_ORBIT_TARGETS = ACS_RUNTIME_SPEC.orbit_target_kinds;
const RT_CAPSULE_DEFAULTS = ACS_RUNTIME_SPEC.player_capsule_defaults;
const RT_CAPSULE_LIMITS = ACS_RUNTIME_SPEC.player_capsule_limits;
const RT_COLLISION_POLICY = ACS_RUNTIME_SPEC.collision_policy;
const RT_LAYER_POLICY = ACS_RUNTIME_SPEC.layer_default_policy;
const RT_DECORATION_COLLISION = ACS_RUNTIME_SPEC.decoration_collision;
const RT_DECORATION_OPTIONS = ACS_RUNTIME_SPEC.decoration_collision_options;
const RT_PORTAL_STATES = ACS_RUNTIME_SPEC.portal_states;
const RT_DEFAULT_PORTAL_STATE = ACS_RUNTIME_SPEC.default_portal_state;
const RT_EXTERIOR = ACS_RUNTIME_SPEC.exterior_space_id;
const RT_VERTICAL_KINDS = ACS_RUNTIME_SPEC.vertical_connection_kinds;
const RT_ACTIONS = ACS_RUNTIME_SPEC.interaction_actions;
const RT_ACTION_TARGETS = ACS_RUNTIME_SPEC.action_targets;
const RT_CAPABILITIES = ACS_RUNTIME_SPEC.interaction_capabilities;
const RT_VISIBILITY_MODES = ACS_RUNTIME_SPEC.visibility_modes;
const RT_DISCIPLINES = ACS_RUNTIME_SPEC.disciplines;
const RT_MEASUREMENT_TYPES = ACS_RUNTIME_SPEC.measurement_types;
const RT_VALIDATION_CODES = ACS_RUNTIME_SPEC.validation_codes;
const RT_SEVERITIES = ACS_RUNTIME_SPEC.severities;
const RT_CODE_SEVERITY = ACS_RUNTIME_SPEC.code_severity;
const RT_WRITE_INTENTS = ACS_RUNTIME_SPEC.model_write_intents;
const RT_CELL = Number(ACS_RUNTIME_SPEC.spatial_index.cell_size_m);
const RT_MAX_CELLS = Number(ACS_RUNTIME_SPEC.spatial_index.max_cells_per_entry);
const RT_MAX_ABS_COORD = Number(ACS_RUNTIME_SPEC.spatial_index.max_abs_coordinate_m);
const RT_NOT_SPECIFIED = 'NOT_SPECIFIED';
const _RT_EPS = 1e-9;

/* قيمة تعداد صالحة: نصّ فقط. المصفوفات والأرقام والكائنات لا تُكرَه على نصّ،
   كي لا يقبل تطبيق ما يرفضه الآخر. */
function _rtEnum(v){ return (typeof v==='string')?v.toUpperCase():null; }
function _rtQ(v){ const r=_pyRound(Number(v),6); return r===0?0:r; }
function _rtNum(v){ return _snum(v); }
/* صياغة قانونية واحدة عبر اللغتين. الأرقام تُرمَّز برمز موحّد (ingestCanonicalJson)
   لأن بايثون تكتب 14.0 وجافاسكربت تكتب 14 — والبصمة لا تحتمل هذا الفارق. */
function _rtCanon(o){ return ingestCanonicalJson(o); }
function _rtSort(v){ if(Array.isArray(v)) return v.map(_rtSort);
  if(v&&typeof v==='object'){ const o={};
    Object.keys(v).sort(_scmp).forEach(k=>{o[k]=_rtSort(v[k]);}); return o; }
  return v; }
function _rtSha16(o){ return sha256Hex(_rtCanon(o)).slice(0,16); }
/* نسخة عميقة: زمن التشغيل لا يحتفظ بأي مرجع مشترك مع المصدر */
function _rtCopy(v){ return (v&&typeof v==='object')?JSON.parse(JSON.stringify(v)):v; }
function rtSeverityOf(code){
  return Object.prototype.hasOwnProperty.call(RT_CODE_SEVERITY,code)
    ?RT_CODE_SEVERITY[code]:'ERROR'; }
function _rtIssue(code,subject,detail){
  return {code:code,severity:rtSeverityOf(code),
    subject:(subject===null||subject===undefined)?null:String(subject),
    detail:(detail===null||detail===undefined)?null:String(detail),
    writes_to_model:false}; }
function _rtSortIssues(issues){
  return issues.slice().sort((a,b)=>
    (RT_SEVERITIES.indexOf(a.severity)-RT_SEVERITIES.indexOf(b.severity))
    ||_scmp(String(a.code),String(b.code))
    ||_scmp(String(a.subject),String(b.subject))
    ||_scmp(String(a.detail),String(b.detail))); }
function _rtOk(issues,extra){
  const out={valid:issues.length===0,issues:_rtSortIssues(issues),writes_to_model:false};
  Object.keys(extra||{}).forEach(k=>{out[k]=(extra[k]===undefined)?null:extra[k];});
  return out; }

/* ------------------------------------------------------------ هندسة --- */
function _rtObb(cx,cy,cz,ex,ey,ez,rotY){
  return {cx:_rtQ(cx),cy:_rtQ(cy),cz:_rtQ(cz),hx:_rtQ(Math.abs(ex)/2),
    hy:_rtQ(Math.abs(ey)/2),hz:_rtQ(Math.abs(ez)/2),yaw:_rtQ(rotY||0)}; }
function _rtAabbOf(o){
  const ca=Math.abs(Math.cos(o.yaw)), sa=Math.abs(Math.sin(o.yaw));
  const rx=o.hx*ca+o.hz*sa, rz=o.hx*sa+o.hz*ca;
  return [_rtQ(o.cx-rx),_rtQ(o.cy-o.hy),_rtQ(o.cz-rz),
          _rtQ(o.cx+rx),_rtQ(o.cy+o.hy),_rtQ(o.cz+rz)]; }
function _rtAabbOverlap(a,b){
  return !(a[3]<=b[0]+_RT_EPS||b[3]<=a[0]+_RT_EPS||a[4]<=b[1]+_RT_EPS||b[4]<=a[1]+_RT_EPS
         ||a[5]<=b[2]+_RT_EPS||b[5]<=a[2]+_RT_EPS); }
function _rtProj(o,ax,az){ const c=Math.cos(o.yaw), s=Math.sin(o.yaw);
  return Math.abs(c*ax+s*az)*o.hx+Math.abs(-s*ax+c*az)*o.hz; }
function _rtObbOverlap(a,b){
  if(a.cy+a.hy<=b.cy-b.hy+_RT_EPS||b.cy+b.hy<=a.cy-a.hy+_RT_EPS) return false;
  const axes=[];
  [a,b].forEach(o=>{ const c=Math.cos(o.yaw), s=Math.sin(o.yaw);
    axes.push([c,s]); axes.push([-s,c]); });
  const dx=b.cx-a.cx, dz=b.cz-a.cz;
  for(let i=0;i<axes.length;i++){
    const ax=axes[i][0], az=axes[i][1];
    if(Math.abs(dx*ax+dz*az)>=_rtProj(a,ax,az)+_rtProj(b,ax,az)-1e-9) return false; }
  return true; }
function _rtInv(x,z,transform){
  const t=transform||{}, rot=Number(t.rotation_deg)||0;
  const p=t.position||{}, px=Number(p.x)||0, pz=Number(p.z)||0;
  const r=(-rot)*Math.PI/180, ca=Math.cos(r), sa=Math.sin(r);
  const dx=x-px, dz=z-pz;
  return [dx*ca-dz*sa, dx*sa+dz*ca]; }
function _rtFwd(x,z,transform){
  const t=transform||{}, rot=Number(t.rotation_deg)||0;
  const p=t.position||{}, px=Number(p.x)||0, pz=Number(p.z)||0;
  const r=rot*Math.PI/180, ca=Math.cos(r), sa=Math.sin(r);
  return [px+x*ca-z*sa, pz+x*sa+z*ca]; }
function _rtInRect(x,z,rect,tol){
  tol=tol||0;
  return (rect[0]-tol<=x&&x<=rect[0]+rect[2]+tol&&rect[1]-tol<=z&&z<=rect[1]+rect[3]+tol); }

/* سياسة معلنة لكل نوع: لا استنتاج من اسم شبكة ولا من مادة ولا من حجم */
function _rtPolicy(obj,deco){
  const kind=obj.kind, layer=obj.layer;
  let blocking,walkable,basis;
  if(Object.prototype.hasOwnProperty.call(RT_COLLISION_POLICY,kind)){
    blocking=!!RT_COLLISION_POLICY[kind].blocking;
    walkable=!!RT_COLLISION_POLICY[kind].walkable;
    basis='declared_kind_policy';
  } else {
    const d=RT_LAYER_POLICY[layer]||{blocking:false,walkable:false};
    blocking=!!d.blocking; walkable=!!d.walkable; basis='layer_default_policy'; }
  if(obj.visual_only){
    walkable=false;
    if(layer==='FURNITURE'){ blocking=(deco==='BLOCKING'); basis='declared_decoration_policy'; }
    else { blocking=false; basis='visual_only_never_blocking'; } }
  return [blocking,walkable,basis]; }

/* -------------------------------------------- تصريف مشهد زمن التشغيل -- */
function compileRuntimeScene(visualScene,runtimeConfig){
  const issues=[];
  const cfg=(runtimeConfig&&typeof runtimeConfig==='object'&&!Array.isArray(runtimeConfig))
    ?runtimeConfig:{};
  if(runtimeConfig!==null&&runtimeConfig!==undefined
     &&(typeof runtimeConfig!=='object'||Array.isArray(runtimeConfig)))
    issues.push(_rtIssue('RUNTIME_CONFIG_INVALID','runtime_config',
      'configuration must be an object'));
  if(visualScene===null||visualScene===undefined)
    return _rtFailure(issues.concat([_rtIssue('RUNTIME_SOURCE_SCENE_MISSING','visual_scene',
      'no source scene supplied')]));
  if(typeof visualScene!=='object'||!Array.isArray(visualScene.objects)||!visualScene.scene_id)
    return _rtFailure(issues.concat([_rtIssue('RUNTIME_SOURCE_SCENE_INVALID','visual_scene',
      'source scene is not a compiled visual scene')]));
  if(cfg.writes_to_model)
    issues.push(_rtIssue('RUNTIME_MODEL_WRITE_ATTEMPT','runtime_config',
      'writes_to_model may never be requested'));
  const _dc=cfg.decoration_collision;
  let deco=(_dc===null||_dc===undefined||_dc==='')?RT_DECORATION_COLLISION:_rtEnum(_dc);
  if(RT_DECORATION_OPTIONS.indexOf(deco)<0){
    issues.push(_rtIssue('RUNTIME_CONFIG_INVALID','decoration_collision',deco));
    deco=RT_DECORATION_COLLISION; }

  const transform=_rtCopy(visualScene.transform)||{position:{x:0,z:0},rotation_deg:0};
  const src=visualScene.objects||[];
  const spacesSrc=visualScene.spaces_index||[];
  const objects=[], obstacles=[], seen={}, doors=[];
  src.forEach(o=>{
    if(!o||typeof o!=='object'||!o.id||!o.geometry||typeof o.geometry!=='object'){
      issues.push(_rtIssue('RUNTIME_SOURCE_OBJECT_INVALID',
        (o&&typeof o==='object')?o.id:null,'object is missing an id or a geometry'));
      return; }
    const g=o.geometry;
    const vals=['cx','cy','cz','ex','ey','ez'].map(k=>_rtNum(g[k]));
    if(vals.some(v=>v===null)){
      issues.push(_rtIssue('RUNTIME_SOURCE_OBJECT_INVALID',o.id,
        'geometry carries a non-finite or missing value')); return; }
    const rot=_rtNum(g.rot_y);
    if(rot===null){
      issues.push(_rtIssue('RUNTIME_SOURCE_OBJECT_INVALID',o.id,
        'geometry carries a non-finite rotation')); return; }
    const rid='runtime:obj:'+String(o.id);
    if(Object.prototype.hasOwnProperty.call(seen,rid)){
      issues.push(_rtIssue('RUNTIME_ID_DUPLICATE',rid,'duplicate runtime object id')); return; }
    seen[rid]=true;
    const pol=_rtPolicy(o,deco);
    const box=_rtObb(vals[0],vals[1],vals[2],vals[3],vals[4],vals[5],rot);
    const ro={runtime_object_id:rid,
      source_element_id:(o.source_element_id===undefined)?null:o.source_element_id,
      visual_object_id:o.id,kind:(o.kind===undefined)?null:o.kind,
      discipline:(o.layer===undefined)?null:o.layer,
      level_index:(o.level_index===null||o.level_index===undefined)?null:o.level_index,
      space_id:(o.space_id===undefined)?null:o.space_id,
      visual_only:!!o.visual_only,
      visual_class:(o.visual_class===undefined)?null:o.visual_class,
      obb:box,aabb:_rtAabbOf(box),
      collision:{blocking:pol[0],walkable:pol[1],basis:pol[2]},
      interaction:{selectable:true,inspectable:true,focusable:true,measurable:true,
        hideable:true},
      geometry_source:(o.geometry_source===undefined)?null:o.geometry_source,
      source_scene:visualScene.scene_id};
    objects.push(ro);
    if(pol[0]) obstacles.push({obstacle_id:'obstacle:'+String(o.id),runtime_object_id:rid,
      source_element_id:ro.source_element_id,kind:ro.kind,discipline:ro.discipline,
      level_index:ro.level_index,blocking:true,basis:pol[2],
      obb:_rtCopy(box),bounds:_rtCopy(ro.aabb)});
    if(o.kind==='DOOR') doors.push(o); });
  objects.sort((a,b)=>_scmp(String(a.runtime_object_id),String(b.runtime_object_id)));
  obstacles.sort((a,b)=>_scmp(String(a.obstacle_id),String(b.obstacle_id)));

  const rooms=[], surfaces=[];
  spacesSrc.forEach(s=>{
    const rect=Array.isArray(s.rect)?s.rect:null;
    if(!rect||rect.length!==4||rect.some(v=>_rtNum(v)===null)||_rtNum(rect[2])<=0
       ||_rtNum(rect[3])<=0){
      issues.push(_rtIssue('WALKABLE_SURFACE_INVALID',(s||{}).id,
        'space rectangle is missing or not positive')); return; }
    const elev=_rtNum(s._elev);
    if(elev===null){
      issues.push(_rtIssue('WALKABLE_SURFACE_INVALID',s.id,
        'space carries no finite level elevation')); return; }
    let support=null;
    for(let i=0;i<objects.length;i++){ const ro=objects[i];
      if(ro.collision.walkable&&(ro.kind==='SLAB'||ro.kind==='STRUCTURAL_SLAB')
         &&ro.level_index===s.level_index){ support=ro.source_element_id; break; } }
    rooms.push({runtime_room_id:'runtime:room:'+String(s.id),space_id:s.space_id,
      space_instance_id:s.id,name:(s.name===undefined)?null:s.name,
      level_index:s.level_index,rect_local:rect.map(_rtQ),elevation_m:_rtQ(elev),
      area_m2:_rtNum(s.area_m2),source_scene:visualScene.scene_id});
    surfaces.push({surface_id:'walk:space:'+String(s.id),source_element_id:s.id,
      runtime_room_id:'runtime:room:'+String(s.id),space_id:s.space_id,
      level_id:s.level_index,level_index:s.level_index,walkable:true,
      basis:'space_rectangle',rect_local:rect.map(_rtQ),elevation_m:_rtQ(elev),
      support_element_id:support}); });
  rooms.sort((a,b)=>_scmp(String(a.runtime_room_id),String(b.runtime_room_id)));
  surfaces.sort((a,b)=>_scmp(String(a.surface_id),String(b.surface_id)));

  const portals=[], seenP={}, wallById={};
  src.forEach(o=>{ if(o&&typeof o==='object'&&o.kind==='WALL'&&o.source_element_id)
    wallById[o.source_element_id]=o; });
  doors.slice().sort((a,b)=>_scmp(String(a.id),String(b.id))).forEach(d=>{
    const pid='portal:'+String(d.source_element_id||d.id);
    if(Object.prototype.hasOwnProperty.call(seenP,pid)){
      issues.push(_rtIssue('PORTAL_DUPLICATE',pid,'duplicate portal id')); return; }
    seenP[pid]=true;
    const hostId=(d.host_wall_id===undefined)?null:d.host_wall_id;
    const host=wallById[hostId];
    const g=d.geometry;
    const thinX=_rtNum(g.ex)<=_rtNum(g.ez);
    const probe=0.6, wx=_rtNum(g.cx), wz=_rtNum(g.cz);
    const probes=thinX?[[wx-probe,wz],[wx+probe,wz]]:[[wx,wz-probe],[wx,wz+probe]];
    const lvl=(d.level_index===undefined)?null:d.level_index;
    const found=[];
    probes.forEach(pp=>{
      const l=_rtInv(pp[0],pp[1],transform);
      let hit=null;
      for(let i=0;i<rooms.length;i++){ const r=rooms[i];
        if(r.level_index!==lvl) continue;
        if(_rtInRect(l[0],l[1],r.rect_local)){ hit=r.space_id; break; } }
      found.push(hit); });
    const sides=found.filter(f=>f);
    const exteriorHost=!!(host&&host.exposure==='exterior');
    let frm,to,basis,resolved;
    if(sides.length===2&&sides[0]!==sides[1]){
      frm=sides[0]; to=sides[1]; basis='two_space_probe'; resolved=true; }
    else if(sides.length===1&&exteriorHost){
      frm=sides[0]; to=RT_EXTERIOR; basis='one_space_probe_exterior'; resolved=true; }
    else { frm=sides.length?sides[0]:null; to=null; basis='unresolved'; resolved=false; }
    const p={portal_id:pid,
      source_element_id:(d.source_element_id===undefined)?null:d.source_element_id,
      visual_object_id:d.id,host_wall_id:hostId,host_wall_resolved:host!==undefined,
      level_index:lvl,from_space:frm,to_space:to,connectivity_basis:basis,
      connectivity_resolved:resolved,default_state:RT_DEFAULT_PORTAL_STATE,
      aperture:_rtCopy(_rtObb(wx,_rtNum(g.cy),wz,_rtNum(g.ex),_rtNum(g.ey),_rtNum(g.ez),
        _rtNum(g.rot_y))),
      source_scene:visualScene.scene_id,
      note:'a runtime portal derived from a modelled door; the door itself is untouched '+
           'and no access control is implied'};
    if(hostId&&host===undefined)
      issues.push(_rtIssue('PORTAL_REFERENCE_INVALID',pid,
        'host wall '+hostId+' does not resolve in the source scene'));
    portals.push(p); });
  portals.sort((a,b)=>_scmp(String(a.portal_id),String(b.portal_id)));

  const vertical=[];
  objects.forEach(ro=>{ if(RT_VERTICAL_KINDS.indexOf(ro.kind)<0) return;
    vertical.push({vertical_id:'vertical:'+String(ro.source_element_id||ro.visual_object_id),
      source_element_id:ro.source_element_id,kind:ro.kind,bounds:_rtCopy(ro.aabb),
      note:'a modelled vertical connection; no lift or escalator operation is simulated'}); });
  vertical.sort((a,b)=>_scmp(String(a.vertical_id),String(b.vertical_id)));

  const index=_rtBuildIndex(obstacles,surfaces,transform);
  const scene={schema:RT_SCHEMA,version:RT_VERSION,compiler_version:RT_COMPILER_VERSION,
    runtime_id:'runtime:'+String(visualScene.scene_id),
    source_scene:visualScene.scene_id,
    source_signature:_rtSha16({scene:visualScene.scene_id,
      model_hash:(visualScene.model_hash===undefined)?null:visualScene.model_hash,
      objects:src.length}),
    model_hash:(visualScene.model_hash===undefined)?null:visualScene.model_hash,
    building_id:(visualScene.building_id===undefined)?null:visualScene.building_id,
    transform:transform,
    walkability:{surfaces:surfaces,obstacles:obstacles,portals:portals,
      vertical_connections:vertical},
    objects:objects,rooms:rooms,spatial_index:index,
    defaults:{navigation_mode:RT_DEFAULT_NAV,player_capsule:_rtCopy(RT_CAPSULE_DEFAULTS),
      decoration_collision:deco,spawn:{}},
    issues:_rtSortIssues(issues),writes_to_model:false,
    meta:{note:ACS_RUNTIME_SPEC.note,derivation:ACS_RUNTIME_SPEC.derivation_note,
      ephemerality:ACS_RUNTIME_SPEC.ephemerality_note,compliance:'NOT_EVALUATED'}};
  scene.defaults.spawn=_rtDefaultSpawn(scene);
  scene.counts=_rtCounts(scene);
  /* القبول معلن صراحةً: مشهد يحمل خطأ واحداً لا يُقدَّم على أنه صالح. */
  scene.accepted=scene.issues.every(i=>i.severity!=='ERROR');
  return scene; }

function _rtFailure(issues){
  return {schema:RT_SCHEMA,version:RT_VERSION,compiler_version:RT_COMPILER_VERSION,
    runtime_id:null,source_scene:null,source_signature:null,model_hash:null,building_id:null,
    transform:{position:{x:0,z:0},rotation_deg:0},
    walkability:{surfaces:[],obstacles:[],portals:[],vertical_connections:[]},
    objects:[],rooms:[],
    spatial_index:{cell_size_m:RT_CELL,cells:0,entries:0,oversized:0,buckets:{}},
    defaults:{navigation_mode:RT_DEFAULT_NAV,player_capsule:_rtCopy(RT_CAPSULE_DEFAULTS),
      decoration_collision:RT_DECORATION_COLLISION,spawn:{}},
    issues:_rtSortIssues(issues),writes_to_model:false,accepted:false,
    counts:{objects:0,obstacles:0,surfaces:0,portals:0,portals_unresolved:0,rooms:0,
      vertical_connections:0},
    meta:{note:ACS_RUNTIME_SPEC.note,derivation:ACS_RUNTIME_SPEC.derivation_note,
      ephemerality:ACS_RUNTIME_SPEC.ephemerality_note,compliance:'NOT_EVALUATED'}}; }

function _rtCounts(scene){
  const w=scene.walkability;
  return {objects:scene.objects.length,obstacles:w.obstacles.length,
    surfaces:w.surfaces.length,portals:w.portals.length,
    portals_unresolved:w.portals.filter(p=>!p.connectivity_resolved).length,
    rooms:scene.rooms.length,vertical_connections:w.vertical_connections.length,
    visual_only_objects:scene.objects.filter(o=>o.visual_only).length,
    issues:scene.issues.length}; }

/* ------------------------------------------------------ الفهرس المكاني - */
/* صندوق صالح للفهرسة: ستّة أعداد منتهية. غير ذلك لا يُعدّ خلايا إطلاقاً. */
function _rtFiniteBox(aabb){
  if(!Array.isArray(aabb)||aabb.length!==6) return null;
  const v=aabb.map(_rtNum);
  if(v.some(x=>x===null)) return null;
  if(v.some(x=>Math.abs(x)>RT_MAX_ABS_COORD)) return null;
  return v; }
function _rtCells(aabb){
  const b=_rtFiniteBox(aabb);
  if(b===null) return [];
  const out=[];
  for(let ix=Math.floor(b[0]/RT_CELL);ix<=Math.floor(b[3]/RT_CELL);ix++)
    for(let iz=Math.floor(b[2]/RT_CELL);iz<=Math.floor(b[5]/RT_CELL);iz++)
      out.push(ix+'|'+iz);
  return out; }
function _rtCellSpan(aabb){
  const b=_rtFiniteBox(aabb);
  if(b===null) return Infinity;
  const nx=Math.floor(b[3]/RT_CELL)-Math.floor(b[0]/RT_CELL)+1;
  const nz=Math.floor(b[5]/RT_CELL)-Math.floor(b[2]/RT_CELL)+1;
  return nx*nz; }
function _rtSurfaceWorldAabb(s,transform){
  const r=s.rect_local;
  const pts=[_rtFwd(r[0],r[1],transform),_rtFwd(r[0]+r[2],r[1],transform),
             _rtFwd(r[0],r[1]+r[3],transform),_rtFwd(r[0]+r[2],r[1]+r[3],transform)];
  const xs=pts.map(p=>p[0]), zs=pts.map(p=>p[1]);
  return [_rtQ(Math.min.apply(null,xs)),_rtQ(s.elevation_m),_rtQ(Math.min.apply(null,zs)),
          _rtQ(Math.max.apply(null,xs)),_rtQ(s.elevation_m),_rtQ(Math.max.apply(null,zs))]; }
function _rtBuildIndex(obstacles,surfaces,transform){
  const buckets={}, oversized=[], entries=[];
  obstacles.forEach(o=>entries.push([o.obstacle_id,o.bounds]));
  surfaces.forEach(s=>entries.push([s.surface_id,_rtSurfaceWorldAabb(s,transform)]));
  entries.forEach(e=>{
    if(_rtCellSpan(e[1])>RT_MAX_CELLS){ oversized.push(e[0]); return; }
    _rtCells(e[1]).forEach(c=>{ if(!buckets[c]) buckets[c]=[]; buckets[c].push(e[0]); }); });
  const keys=Object.keys(buckets).sort(_scmp);
  const out={};
  keys.forEach(k=>{ out[k]=buckets[k].slice().sort(_scmp); });
  return {cell_size_m:RT_CELL,cells:keys.length,entries:entries.length,
    oversized:oversized.length,oversized_ids:oversized.slice().sort(_scmp),buckets:out}; }
/* مرشّحون من الخلايا التي يلامسها الاستعلام فقط — لا مسح لكل الأجسام */
function queryRuntimeSpatialIndex(runtimeScene,aabb){
  const idx=runtimeScene.spatial_index||{}, buckets=idx.buckets||{};
  const hit={};
  /* صندوق استعلام أوسع من سقف الخلايا المعلن لا يُعدّ خليةً خلية — يُعلَن مسحاً
     كاملاً صراحةً بدل تفجير الذاكرة أو ادّعاء تسريع لم يحدث. */
  const span=_rtCellSpan(aabb);
  const full=!isFinite(span)||span>RT_MAX_CELLS;
  if(full){
    Object.keys(buckets).forEach(c=>{ buckets[c].forEach(id=>{hit[id]=true;}); });
    (idx.oversized_ids||[]).forEach(id=>{hit[id]=true;});
    const allIds=Object.keys(hit).sort(_scmp);
    return {candidate_ids:allIds,candidate_count:allIds.length,scanned_cells:0,
      total_entries:idx.entries||0,full_scan:true}; }
  const cells=_rtCells(aabb);
  cells.forEach(c=>{ (buckets[c]||[]).forEach(id=>{hit[id]=true;}); });
  (idx.oversized_ids||[]).forEach(id=>{hit[id]=true;});
  const ids=Object.keys(hit).sort(_scmp);
  return {candidate_ids:ids,candidate_count:ids.length,scanned_cells:cells.length,
    total_entries:idx.entries||0,full_scan:false}; }

/* ------------------------------------------------------ كبسولة اللاعب -- */
function validateRuntimeCapsule(capsule){
  const issues=[];
  const c=(capsule&&typeof capsule==='object'&&!Array.isArray(capsule))?capsule:{};
  if(capsule!==null&&capsule!==undefined
     &&(typeof capsule!=='object'||Array.isArray(capsule)))
    issues.push(_rtIssue('PLAYER_CAPSULE_INVALID','capsule','capsule must be an object'));
  const r=_rtNum(c.radius_m===undefined?RT_CAPSULE_DEFAULTS.radius_m:c.radius_m);
  const h=_rtNum(c.height_m===undefined?RT_CAPSULE_DEFAULTS.height_m:c.height_m);
  const e=_rtNum(c.eye_height_m===undefined?RT_CAPSULE_DEFAULTS.eye_height_m:c.eye_height_m);
  if(r===null) issues.push(_rtIssue('PLAYER_CAPSULE_INVALID','radius_m','not a finite number'));
  else if(r<=0) issues.push(_rtIssue('PLAYER_CAPSULE_INVALID','radius_m',
    'must be greater than zero'));
  else if(r<RT_CAPSULE_LIMITS.min_radius_m||r>RT_CAPSULE_LIMITS.max_radius_m)
    issues.push(_rtIssue('PLAYER_CAPSULE_INVALID','radius_m','outside the declared limits'));
  if(h===null) issues.push(_rtIssue('PLAYER_CAPSULE_INVALID','height_m','not a finite number'));
  else if(h<=0) issues.push(_rtIssue('PLAYER_CAPSULE_INVALID','height_m',
    'must be greater than zero'));
  else if(h<RT_CAPSULE_LIMITS.min_height_m||h>RT_CAPSULE_LIMITS.max_height_m)
    issues.push(_rtIssue('PLAYER_CAPSULE_INVALID','height_m','outside the declared limits'));
  if(r!==null&&h!==null&&r>0&&h>0&&h<=2*r)
    issues.push(_rtIssue('PLAYER_CAPSULE_INVALID','height_m',
      'height must exceed twice the radius'));
  if(e===null) issues.push(_rtIssue('PLAYER_CAPSULE_INVALID','eye_height_m',
    'not a finite number'));
  else if(e<=0) issues.push(_rtIssue('PLAYER_CAPSULE_INVALID','eye_height_m',
    'must be greater than zero'));
  else if(h!==null&&e>h) issues.push(_rtIssue('PLAYER_CAPSULE_INVALID','eye_height_m',
    'must not exceed the capsule height'));
  const resolved=issues.length?null:{radius_m:_rtQ(r),height_m:_rtQ(h),eye_height_m:_rtQ(e)};
  return _rtOk(issues,{capsule:resolved}); }
function _rtCapsuleBox(position,capsule){
  const r=capsule.radius_m, h=capsule.height_m;
  return _rtObb(position[0],position[1]+h/2,position[2],2*r,h,2*r,0); }

/* --------------------------------------------------------- الملاحة ---- */
function validateRuntimeNavigation(mode,target,runtimeScene){
  const issues=[];
  const m=_rtEnum(mode);
  if(RT_NAVIGATION_MODES.indexOf(m)<0){
    issues.push(_rtIssue('NAVIGATION_MODE_INVALID',mode,'unknown navigation mode'));
    return _rtOk(issues,{mode:null,contract:null}); }
  const contract=_rtCopy(RT_NAVIGATION_CONTRACTS[m]);
  if(contract.targeted&&target!==null&&target!==undefined){
    const tk=_rtEnum((target||{}).kind)||'';
    const tid=(target||{}).id;
    if(RT_ORBIT_TARGETS.indexOf(tk)<0)
      issues.push(_rtIssue('NAVIGATION_TARGET_INVALID',tk||null,
        'target kind is not a declared orbit target'));
    else if(tk!=='BUILDING'&&runtimeScene!==null&&runtimeScene!==undefined){
      if(!_rtTargetExists(runtimeScene,tk,tid))
        issues.push(_rtIssue('NAVIGATION_TARGET_INVALID',tid,
          'target does not resolve in the runtime scene')); } }
  if(!contract.targeted&&target!==null&&target!==undefined)
    issues.push(_rtIssue('NAVIGATION_TARGET_INVALID',(target||{}).id,
      'this navigation mode accepts no target'));
  return _rtOk(issues,{mode:issues.length?null:m,contract:issues.length?null:contract}); }
function _rtTargetExists(scene,kind,tid){
  if(kind==='OBJECT') return (scene.objects||[]).some(o=>o.runtime_object_id===tid
    ||o.visual_object_id===tid||o.source_element_id===tid);
  if(kind==='ROOM') return (scene.rooms||[]).some(r=>r.runtime_room_id===tid
    ||r.space_instance_id===tid||r.space_id===tid);
  if(kind==='FLOOR') return (scene.rooms||[]).some(r=>r.level_index===tid);
  return false; }

/* ------------------------------------------------- الظهور والدخول ----- */
function validateRuntimeSpawn(runtimeScene,position,capsule,levelIndex){
  const issues=[];
  const cap=validateRuntimeCapsule(capsule);
  if(!cap.valid) return _rtOk(cap.issues.concat([_rtIssue('SPAWN_INVALID','capsule',
    'spawn requires a valid capsule')]),{position:null,surface_id:null});
  const c=cap.capsule;
  if(!Array.isArray(position)||position.length!==3||position.some(v=>_rtNum(v)===null)){
    issues.push(_rtIssue('SPAWN_INVALID','position','position must be three finite numbers'));
    return _rtOk(issues,{position:null,surface_id:null}); }
  const p=position.map(_rtNum);
  const surface=_rtSurfaceAt(runtimeScene,p,levelIndex);
  if(surface===null)
    issues.push(_rtIssue('SPAWN_OUTSIDE_WALKABLE_AREA','position',
      'no walkable surface supports this position'));
  const box=_rtCapsuleBox(p,c), boxAabb=_rtAabbOf(box);
  const q=queryRuntimeSpatialIndex(runtimeScene,boxAabb);
  const byId={};
  runtimeScene.walkability.obstacles.forEach(o=>{byId[o.obstacle_id]=o;});
  q.candidate_ids.forEach(eid=>{ const ob=byId[eid];
    if(!ob) return;
    if(_rtAabbOverlap(boxAabb,ob.bounds)&&_rtObbOverlap(box,ob.obb))
      issues.push(_rtIssue('SPAWN_INSIDE_OBSTACLE',ob.obstacle_id,
        'capsule intersects '+ob.kind)); });
  return _rtOk(issues,{position:issues.length?null:[_rtQ(p[0]),_rtQ(p[1]),_rtQ(p[2])],
    surface_id:surface?surface.surface_id:null,candidate_count:q.candidate_ids.length}); }
function _rtSurfaceAt(runtimeScene,p,levelIndex){
  const l=_rtInv(p[0],p[2],runtimeScene.transform);
  let best=null;
  runtimeScene.walkability.surfaces.forEach(s=>{
    if(levelIndex!==null&&levelIndex!==undefined&&s.level_index!==levelIndex) return;
    if(!_rtInRect(l[0],l[1],s.rect_local)) return;
    if(p[1]+1e-6<s.elevation_m-0.05) return;
    if(p[1]-s.elevation_m>3.5) return;
    if(best===null||s.elevation_m>best.elevation_m) best=s; });
  return best; }
function _rtDefaultSpawn(scene){
  const surfaces=scene.walkability.surfaces;
  if(!surfaces.length) return {position:null,surface_id:null,
    basis:'no walkable surface exists in this scene'};
  const s=surfaces.slice().sort((a,b)=>
    ((a.level_index===null?0:a.level_index)-(b.level_index===null?0:b.level_index))
    ||_scmp(String(a.surface_id),String(b.surface_id)))[0];
  const r=s.rect_local;
  const w=_rtFwd(r[0]+r[2]/2,r[1]+r[3]/2,scene.transform);
  return {position:[_rtQ(w[0]),_rtQ(s.elevation_m),_rtQ(w[1])],surface_id:s.surface_id,
    basis:'centre of the first walkable surface'}; }
/* بحث حتميّ عن أقرب موضع صالح — ترتيب ثابت، ولا تحريك لأي هندسة */
function findNearestValidSpawn(runtimeScene,position,capsule,levelIndex,maxRadiusM,stepM){
  const base=validateRuntimeSpawn(runtimeScene,position,capsule,levelIndex);
  if(base.valid) return _rtOk([],{position:base.position,surface_id:base.surface_id,
    moved:false,search_steps:0});
  if(!Array.isArray(position)||position.length!==3||position.some(v=>_rtNum(v)===null))
    return _rtOk([_rtIssue('SPAWN_INVALID','position','position must be three finite numbers')],
      {position:null,surface_id:null,moved:false,search_steps:0});
  const p=position.map(_rtNum);
  let r=_rtNum(maxRadiusM===undefined?6.0:maxRadiusM); if(r===null) r=6.0;
  let st=_rtNum(stepM===undefined?0.5:stepM); if(st===null||st<=0) st=0.5;
  let steps=0, ring=1;
  while(ring*st<=r){
    const offs=[], n=Math.max(8,ring*8);
    for(let k=0;k<n;k++){ const ang=2*Math.PI*k/n;
      offs.push([_rtQ(Math.cos(ang)*ring*st),_rtQ(Math.sin(ang)*ring*st)]); }
    offs.sort((a,b)=>(a[0]-b[0])||(a[1]-b[1]));
    for(let i=0;i<offs.length;i++){
      steps++;
      const cand=[p[0]+offs[i][0],p[1],p[2]+offs[i][1]];
      const res=validateRuntimeSpawn(runtimeScene,cand,capsule,levelIndex);
      if(res.valid) return _rtOk([],{position:res.position,surface_id:res.surface_id,
        moved:true,search_steps:steps}); }
    ring++; }
  return _rtOk([_rtIssue('SPAWN_NO_VALID_POSITION_FOUND','position',
    'no valid position within the search radius')],
    {position:null,surface_id:null,moved:false,search_steps:steps}); }

/* ---------------------------------------------------------- الحركة ---- */
function runtimeMoveQuery(runtimeScene,runtimeState,start,end){
  const issues=[];
  const capIn=(runtimeState||{}).player_capsule||_rtCopy(RT_CAPSULE_DEFAULTS);
  const cv=validateRuntimeCapsule(capIn);
  if(!cv.valid) return _rtOk(cv.issues,{allowed:false,blocked_by:null,
    reason:'invalid capsule'});
  const c=cv.capsule;
  [['start',start],['end',end]].forEach(pair=>{
    if(!Array.isArray(pair[1])||pair[1].length!==3||pair[1].some(v=>_rtNum(v)===null))
      issues.push(_rtIssue('SPAWN_INVALID',pair[0],'point must be three finite numbers')); });
  if(issues.length) return _rtOk(issues,{allowed:false,blocked_by:null,reason:'invalid point'});
  const s=start.map(_rtNum), e=end.map(_rtNum);
  const mode=(runtimeState||{}).navigation_mode||RT_DEFAULT_NAV;
  const contract=RT_NAVIGATION_CONTRACTS[mode]||RT_NAVIGATION_CONTRACTS[RT_DEFAULT_NAV];
  const sweep=_rtSweepBox(s,e,c), sweepAabb=_rtAabbOf(sweep);
  const q=queryRuntimeSpatialIndex(runtimeScene,sweepAabb);
  if(!contract.collision) return _rtOk([],{allowed:true,blocked_by:null,
    reason:'collision disabled by contract',candidate_count:q.candidate_count,mode:mode});
  const portalStates=(runtimeState||{}).portal_states||{};
  const openWalls={};
  runtimeScene.walkability.portals.forEach(p=>{
    const st=Object.prototype.hasOwnProperty.call(portalStates,p.portal_id)
      ?portalStates[p.portal_id]:p.default_state;
    if(st==='OPEN'&&p.host_wall_id){
      if(!openWalls[p.host_wall_id]) openWalls[p.host_wall_id]=[];
      openWalls[p.host_wall_id].push(p); } });
  const byId={};
  runtimeScene.walkability.obstacles.forEach(o=>{byId[o.obstacle_id]=o;});
  for(let i=0;i<q.candidate_ids.length;i++){
    const ob=byId[q.candidate_ids[i]];
    if(!ob) continue;
    if(!_rtAabbOverlap(sweepAabb,ob.bounds)) continue;
    if(!_rtObbOverlap(sweep,ob.obb)) continue;
    if(ob.kind==='WALL'&&openWalls[ob.source_element_id]){
      let passed=null;
      const ps=openWalls[ob.source_element_id];
      for(let j=0;j<ps.length;j++){
        const ap=Object.assign({},ps[j].aperture);
        ap.hx=ap.hx+c.radius_m; ap.hz=ap.hz+c.radius_m;
        if(_rtObbOverlap(sweep,ap)){ passed=ps[j]; break; } }
      if(passed!==null) continue; }
    return _rtOk([],{allowed:false,blocked_by:ob.obstacle_id,blocked_kind:ob.kind,
      reason:'obstacle intersects the swept capsule',candidate_count:q.candidate_count,
      mode:mode}); }
  if(contract.requires_walkable_surface){
    const sup=_rtSurfaceAt(runtimeScene,e,null);
    if(sup===null) return _rtOk([],{allowed:false,blocked_by:null,
      reason:'no walkable surface supports the destination',
      candidate_count:q.candidate_count,mode:mode}); }
  return _rtOk([],{allowed:true,blocked_by:null,reason:'clear',
    candidate_count:q.candidate_count,mode:mode}); }
function _rtSweepBox(s,e,c){
  const lo=[Math.min(s[0],e[0]),Math.min(s[1],e[1]),Math.min(s[2],e[2])];
  const hi=[Math.max(s[0],e[0]),Math.max(s[1],e[1]),Math.max(s[2],e[2])];
  const r=c.radius_m, h=c.height_m;
  return _rtObb((lo[0]+hi[0])/2,(lo[1]+hi[1])/2+h/2,(lo[2]+hi[2])/2,
    (hi[0]-lo[0])+2*r,(hi[1]-lo[1])+h,(hi[2]-lo[2])+2*r,0); }

/* -------------------------------------------------------- حالة التشغيل - */
function createRuntimeState(runtimeScene,navigationMode,capsule,spawn){
  const issues=[];
  let mode=(navigationMode===null||navigationMode===undefined)
    ?(((runtimeScene.defaults||{}).navigation_mode)||RT_DEFAULT_NAV):navigationMode;
  const nv=validateRuntimeNavigation(mode,null,null);
  if(!nv.valid){ issues.push.apply(issues,nv.issues); mode=RT_DEFAULT_NAV; }
  const cv=validateRuntimeCapsule((capsule===null||capsule===undefined)
    ?((runtimeScene.defaults||{}).player_capsule):capsule);
  let cap;
  if(!cv.valid){ issues.push.apply(issues,cv.issues); cap=_rtCopy(RT_CAPSULE_DEFAULTS); }
  else cap=cv.capsule;
  let pos=(spawn===null||spawn===undefined)
    ?(((runtimeScene.defaults||{}).spawn||{}).position):spawn;
  /* الغياب يُكتب null صراحةً: حقل ناقص في جافاسكربت يقابله null في بايثون. */
  if(pos===undefined) pos=null;
  return {schema:RT_SCHEMA,version:RT_VERSION,runtime_id:runtimeScene.runtime_id,
    source_scene:runtimeScene.source_scene,
    camera:{position:_rtCopy(pos),target:null,eye_height_m:cap.eye_height_m,
      orientation_deg:0.0},
    navigation_mode:mode,player_capsule:cap,selection:null,
    visibility:{hidden_object_ids:[],hidden_rooms:[],hidden_levels:[],
      hidden_disciplines:[],isolated:null},
    measurements:[],portal_states:{},simulation_time:0.0,
    issues:_rtSortIssues(issues),writes_to_model:false,
    note:'ephemeral runtime state; it is never written into the visual scene or into any '+
         'canonical engineering model'}; }
function advanceSimulationTime(runtimeState,deltaS){
  const d=_rtNum(deltaS);
  if(d===null||d<0) return _rtOk([_rtIssue('SIMULATION_TIME_INVALID','delta_s',
    'delta must be a finite non-negative number')],
    {simulation_time:runtimeState.simulation_time});
  runtimeState.simulation_time=_rtQ(Number(runtimeState.simulation_time||0)+d);
  return _rtOk([],{simulation_time:runtimeState.simulation_time}); }

/* -------------------------------------------------------- البوّابات --- */
function setPortalState(runtimeState,runtimeScene,portalId,newState){
  const issues=[];
  const st=_rtEnum(newState);
  if(RT_PORTAL_STATES.indexOf(st)<0)
    issues.push(_rtIssue('PORTAL_STATE_INVALID',newState,'unknown portal state'));
  let p=null;
  runtimeScene.walkability.portals.forEach(x=>{ if(x.portal_id===portalId) p=x; });
  if(p===null) issues.push(_rtIssue('PORTAL_REFERENCE_INVALID',portalId,
    'portal does not resolve in the runtime scene'));
  if(issues.length) return _rtOk(issues,{portal_id:portalId,state:null});
  if(!runtimeState.portal_states) runtimeState.portal_states={};
  runtimeState.portal_states[portalId]=st;
  return _rtOk([],{portal_id:portalId,state:st,runtime_only:true}); }
/* رسم اتّصال مشتقّ من البوّابات الصالحة فقط. أساس لا تخطيط مسارات */
function roomConnectivityGraph(runtimeScene){
  const spaces={}, edges=[], unresolved=[];
  (runtimeScene.rooms||[]).forEach(r=>{spaces[r.space_id]=true;});
  runtimeScene.walkability.portals.forEach(p=>{
    if(!p.connectivity_resolved){ unresolved.push({portal_id:p.portal_id,
      from_space:p.from_space,to_space:p.to_space,basis:p.connectivity_basis}); return; }
    if(p.to_space===RT_EXTERIOR) spaces[RT_EXTERIOR]=true;
    edges.push({portal_id:p.portal_id,from:p.from_space,to:p.to_space,
      basis:p.connectivity_basis}); });
  edges.sort((a,b)=>_scmp(String(a.from),String(b.from))||_scmp(String(a.to),String(b.to))
    ||_scmp(String(a.portal_id),String(b.portal_id)));
  unresolved.sort((a,b)=>_scmp(String(a.portal_id),String(b.portal_id)));
  return {spaces:Object.keys(spaces).sort(_scmp),edges:edges,unresolved:unresolved,
    note:'a connectivity foundation only — no route planning, evacuation routing or '+
         'pathfinding exists in this phase'}; }

/* ------------------------------------------------- التحديد والفحص ----- */
function selectRuntimeObject(runtimeState,runtimeScene,targetId){
  const o=_rtFindObject(runtimeScene,targetId);
  if(o===null) return _rtOk([_rtIssue('INTERACTION_TARGET_INVALID',targetId,
    'target does not resolve in the runtime scene')],{selection:null});
  if(!o.interaction.selectable) return _rtOk([_rtIssue('INTERACTION_TARGET_INVALID',targetId,
    'target is not selectable')],{selection:null});
  const sel={runtime_object_id:o.runtime_object_id,source_element_id:o.source_element_id,
    visual_object_id:o.visual_object_id,discipline:o.discipline,kind:o.kind,
    visual_only:o.visual_only};
  runtimeState.selection=sel;
  return _rtOk([],{selection:_rtCopy(sel),runtime_only:true}); }
function deselectRuntimeObject(runtimeState){
  runtimeState.selection=null;
  return _rtOk([],{selection:null,runtime_only:true}); }
/* معرّف صالح: نصّ غير فارغ. المعرّف الغائب لا يطابق حقلاً غائباً أبداً —
   وإلا لطابق targetId=null جسماً بصريّاً لا مصدر هندسي له. */
function _rtIsId(targetId){ return typeof targetId==='string'&&targetId!==''; }
function _rtFindObject(runtimeScene,targetId){
  if(!_rtIsId(targetId)) return null;
  const list=runtimeScene.objects||[];
  for(let i=0;i<list.length;i++){ const o=list[i];
    if(o.runtime_object_id===targetId||o.visual_object_id===targetId
       ||o.source_element_id===targetId) return o; }
  return null; }
function _rtFindRoom(runtimeScene,targetId){
  if(!_rtIsId(targetId)) return null;
  const list=runtimeScene.rooms||[];
  for(let i=0;i<list.length;i++){ const r=list[i];
    if(r.runtime_room_id===targetId||r.space_instance_id===targetId
       ||r.space_id===targetId) return r; }
  return null; }
/* يعرض ما ينصّ عليه المصدر فقط. الغائب يُعلَن NOT_SPECIFIED */
function inspectRuntimeObject(runtimeScene,targetId,visualScene){
  const o=_rtFindObject(runtimeScene,targetId);
  if(o===null){
    const r=_rtFindRoom(runtimeScene,targetId);
    if(r===null) return _rtOk([_rtIssue('INTERACTION_TARGET_INVALID',targetId,
      'target does not resolve in the runtime scene')],{inspection:null});
    return _rtOk([],{inspection:{runtime_room_id:r.runtime_room_id,kind:'ROOM',
      source_element_id:r.space_instance_id,space_id:r.space_id,
      name:(r.name===null||r.name===undefined)?RT_NOT_SPECIFIED:r.name,
      level_index:(r.level_index===null||r.level_index===undefined)?RT_NOT_SPECIFIED
        :r.level_index,
      elevation_m:r.elevation_m,
      area_m2:(r.area_m2===null||r.area_m2===undefined)?RT_NOT_SPECIFIED:r.area_m2,
      width_m:_rtQ(r.rect_local[2]),depth_m:_rtQ(r.rect_local[3]),source_backed:true,
      note:'values are taken from the canonical space record; nothing is invented'},
      runtime_only:true}); }
  let src=null;
  if(visualScene&&typeof visualScene==='object')
    (visualScene.objects||[]).forEach(v=>{ if(v.id===o.visual_object_id) src=v; });
  const box=o.obb;
  const insp={runtime_object_id:o.runtime_object_id,kind:o.kind,discipline:o.discipline,
    source_element_id:o.source_element_id?o.source_element_id:RT_NOT_SPECIFIED,
    visual_object_id:o.visual_object_id,visual_only:o.visual_only,
    visual_class:o.visual_class?o.visual_class:RT_NOT_SPECIFIED,
    level_index:(o.level_index===null||o.level_index===undefined)?RT_NOT_SPECIFIED
      :o.level_index,
    space_id:o.space_id?o.space_id:RT_NOT_SPECIFIED,
    position:[box.cx,box.cy,box.cz],orientation_rad:box.yaw,
    dimensions_m:{width:_rtQ(box.hx*2),height:_rtQ(box.hy*2),depth:_rtQ(box.hz*2)},
    geometry_source:o.geometry_source?o.geometry_source:RT_NOT_SPECIFIED,
    collision:_rtCopy(o.collision),source_backed:!o.visual_only,
    note:'runtime inspection of source-backed values only; an absent property is reported '+
         'NOT_SPECIFIED and never replaced by a plausible default'};
  [['host_wall_id','host_wall_id'],['material','material'],
   ['material_provenance','material_provenance'],['asset_id','asset_id'],
   ['exposure','exposure']].forEach(pair=>{
    const val=(src||{})[pair[1]];
    insp[pair[0]]=(val===null||val===undefined||val==='')?RT_NOT_SPECIFIED:val; });
  if(o.visual_only){ insp.engineering_source=RT_NOT_SPECIFIED;
    insp.visual_metadata_only=true; }
  return _rtOk([],{inspection:insp,runtime_only:true}); }

/* ------------------------------------------------------------ الرؤية -- */
function setRuntimeVisibility(runtimeState,runtimeScene,mode,targetId){
  const issues=[];
  const m=_rtEnum(mode);
  if(RT_VISIBILITY_MODES.indexOf(m)<0){
    issues.push(_rtIssue('VISIBILITY_MODE_INVALID',mode,'unknown visibility mode'));
    return _rtOk(issues,{visibility:null}); }
  if(!runtimeState.visibility) runtimeState.visibility={hidden_object_ids:[],hidden_rooms:[],
    hidden_levels:[],hidden_disciplines:[],isolated:null};
  const vis=runtimeState.visibility;
  if(m==='RESTORE_VISIBILITY'){
    vis.hidden_object_ids=[]; vis.hidden_rooms=[]; vis.hidden_levels=[];
    vis.hidden_disciplines=[]; vis.isolated=null;
    return _rtOk([],{visibility:_rtCopy(vis),runtime_only:true}); }
  if(/OBJECT$/.test(m)){
    const o=_rtFindObject(runtimeScene,targetId);
    if(o===null) issues.push(_rtIssue('VISIBILITY_TARGET_INVALID',targetId,'unknown object'));
    else _rtToggle(vis.hidden_object_ids,o.runtime_object_id,m.indexOf('HIDE')===0);
  } else if(/ROOM$/.test(m)){
    const r=_rtFindRoom(runtimeScene,targetId);
    if(r===null) issues.push(_rtIssue('VISIBILITY_TARGET_INVALID',targetId,'unknown room'));
    else if(m.indexOf('ISOLATE')===0){
      vis.isolated={kind:'ROOM',id:r.runtime_room_id};
      vis.hidden_rooms=runtimeScene.rooms.filter(x=>x.runtime_room_id!==r.runtime_room_id)
        .map(x=>x.runtime_room_id).sort(_scmp); }
    else _rtToggle(vis.hidden_rooms,r.runtime_room_id,m.indexOf('HIDE')===0);
  } else if(/FLOOR$/.test(m)){
    const lv=targetId;
    const levels=Array.from(new Set(runtimeScene.rooms.filter(x=>x.level_index!==null
      &&x.level_index!==undefined).map(x=>x.level_index))).sort((a,b)=>a-b);
    if(levels.indexOf(lv)<0) issues.push(_rtIssue('VISIBILITY_TARGET_INVALID',targetId,
      'unknown level'));
    else if(m.indexOf('ISOLATE')===0){ vis.isolated={kind:'FLOOR',id:lv};
      vis.hidden_levels=levels.filter(x=>x!==lv); }
    else _rtToggle(vis.hidden_levels,lv,m.indexOf('HIDE')===0);
  } else if(/DISCIPLINE$/.test(m)){
    const d=_rtEnum(targetId);
    if(RT_DISCIPLINES.indexOf(d)<0) issues.push(_rtIssue('VISIBILITY_TARGET_INVALID',targetId,
      'unknown discipline'));
    else if(m.indexOf('ISOLATE')===0){
      const present=Array.from(new Set(runtimeScene.objects.filter(o=>o.discipline)
        .map(o=>o.discipline))).sort(_scmp);
      vis.isolated={kind:'DISCIPLINE',id:d};
      vis.hidden_disciplines=present.filter(x=>x!==d); }
    else _rtToggle(vis.hidden_disciplines,d,m.indexOf('HIDE')===0); }
  if(issues.length) return _rtOk(issues,{visibility:_rtCopy(vis)});
  vis.hidden_object_ids=vis.hidden_object_ids.slice().sort(_scmp);
  vis.hidden_rooms=vis.hidden_rooms.slice().sort(_scmp);
  vis.hidden_disciplines=vis.hidden_disciplines.slice().sort(_scmp);
  vis.hidden_levels=vis.hidden_levels.slice().sort((a,b)=>
    _scmp(String(typeof a),String(typeof b))||_scmp(String(a),String(b)));
  return _rtOk([],{visibility:_rtCopy(vis),runtime_only:true}); }
function _rtToggle(lst,value,hide){
  const i=lst.indexOf(value);
  if(hide){ if(i<0) lst.push(value); } else if(i>=0) lst.splice(i,1); }
function restoreRuntimeVisibility(runtimeState,runtimeScene){
  return setRuntimeVisibility(runtimeState,runtimeScene,'RESTORE_VISIBILITY',null); }
function effectiveRuntimeVisibility(runtimeState,runtimeScene){
  const vis=runtimeState.visibility||{};
  const ho={}, hr={}, hl={}, hd={};
  (vis.hidden_object_ids||[]).forEach(x=>{ho[x]=true;});
  (vis.hidden_rooms||[]).forEach(x=>{hr[x]=true;});
  (vis.hidden_levels||[]).forEach(x=>{hl[x]=true;});
  (vis.hidden_disciplines||[]).forEach(x=>{hd[x]=true;});
  const roomSpace={};
  runtimeScene.rooms.forEach(r=>{roomSpace[r.runtime_room_id]=r.space_id;});
  const hiddenSpaces={};
  Object.keys(hr).forEach(r=>{ if(roomSpace[r]) hiddenSpaces[roomSpace[r]]=true; });
  const out=runtimeScene.objects.map(o=>{
    let visible=true;
    if(ho[o.runtime_object_id]) visible=false;
    if(hd[o.discipline]) visible=false;
    if(o.level_index!==null&&o.level_index!==undefined&&hl[o.level_index]) visible=false;
    if(o.space_id&&hiddenSpaces[o.space_id]) visible=false;
    return {runtime_object_id:o.runtime_object_id,visible:visible}; });
  out.sort((a,b)=>_scmp(String(a.runtime_object_id),String(b.runtime_object_id)));
  return {objects:out,hidden_count:out.filter(x=>!x.visible).length,runtime_only:true}; }

/* ------------------------------------------------------------ القياس -- */
function createRuntimeMeasurement(runtimeScene,mtype,opts){
  opts=opts||{};
  const issues=[];
  const t=_rtEnum(mtype);
  if(RT_MEASUREMENT_TYPES.indexOf(t)<0){
    issues.push(_rtIssue('MEASUREMENT_INVALID',mtype,'unknown measurement type'));
    return _rtOk(issues,{measurement:null}); }
  const pt=(name,v)=>{
    if(!Array.isArray(v)||v.length!==3){
      issues.push(_rtIssue('MEASUREMENT_INVALID',name,
        'point must be a vector of three numbers')); return null; }
    const vals=v.map(_rtNum);
    if(vals.some(x=>x===null)){
      issues.push(_rtIssue('MEASUREMENT_INVALID',name,'point carries a non-finite value'));
      return null; }
    return vals; };
  let body=null;
  if(t==='POINT_TO_POINT'){
    const a=pt('start',opts.start), b=pt('end',opts.end);
    if(issues.length) return _rtOk(issues,{measurement:null});
    let sum=0; for(let i=0;i<3;i++) sum+=(b[i]-a[i])*(b[i]-a[i]);
    body={start:a.map(_rtQ),end:b.map(_rtQ),distance_m:_rtQ(Math.sqrt(sum))};
  } else if(t==='OBJECT_WIDTH'||t==='OBJECT_HEIGHT'){
    const o=_rtFindObject(runtimeScene,opts.target_id);
    if(o===null){ issues.push(_rtIssue('MEASUREMENT_TARGET_INVALID',opts.target_id,
      'unknown object')); return _rtOk(issues,{measurement:null}); }
    const d=(t==='OBJECT_WIDTH')?o.obb.hx*2:o.obb.hy*2;
    body={target_id:o.runtime_object_id,source_element_id:o.source_element_id,
      axis:(t==='OBJECT_WIDTH')?'WIDTH':'HEIGHT',distance_m:_rtQ(d)};
  } else if(t==='ROOM_DIMENSION'){
    const r=_rtFindRoom(runtimeScene,opts.target_id);
    if(r===null){ issues.push(_rtIssue('MEASUREMENT_TARGET_INVALID',opts.target_id,
      'unknown room')); return _rtOk(issues,{measurement:null}); }
    body={target_id:r.runtime_room_id,source_element_id:r.space_instance_id,
      width_m:_rtQ(r.rect_local[2]),depth_m:_rtQ(r.rect_local[3]),
      distance_m:_rtQ(Math.max(r.rect_local[2],r.rect_local[3]))};
  } else {
    const a=_rtFindObject(runtimeScene,opts.target_id);
    const b=_rtFindObject(runtimeScene,opts.other_id);
    if(a===null||b===null){
      issues.push(_rtIssue('MEASUREMENT_TARGET_INVALID',
        (a===null)?opts.target_id:opts.other_id,'unknown object'));
      return _rtOk(issues,{measurement:null}); }
    body={target_id:a.runtime_object_id,other_id:b.runtime_object_id,
      source_element_id:a.source_element_id,other_source_element_id:b.source_element_id,
      distance_m:_rtQ(_rtAabbGap(a.aabb,b.aabb))}; }
  if(body.distance_m<0||_rtNum(body.distance_m)===null){
    issues.push(_rtIssue('MEASUREMENT_INVALID',t,'computed distance is not valid'));
    return _rtOk(issues,{measurement:null}); }
  const ident=Object.assign({},body); ident.type=t;
  const m=Object.assign({},body);
  m.measurement_id='measure:'+_rtSha16(ident);
  m.type=t; m.runtime_only=true; m.source_scene=runtimeScene.source_scene;
  m.note='a runtime measurement; it is never a code check, a clearance requirement or a '+
         'compliance statement';
  return _rtOk([],{measurement:m}); }
function _rtAabbGap(a,b){
  const dx=Math.max(0,Math.max(a[0]-b[3],b[0]-a[3]));
  const dy=Math.max(0,Math.max(a[1]-b[4],b[1]-a[4]));
  const dz=Math.max(0,Math.max(a[2]-b[5],b[2]-a[5]));
  return Math.sqrt(dx*dx+dy*dy+dz*dz); }
function validateRuntimeMeasurement(measurement){
  const issues=[];
  if(!measurement||typeof measurement!=='object'||Array.isArray(measurement)){
    issues.push(_rtIssue('MEASUREMENT_INVALID','measurement','must be an object'));
    return _rtOk(issues,{}); }
  if(RT_MEASUREMENT_TYPES.indexOf(measurement.type)<0)
    issues.push(_rtIssue('MEASUREMENT_INVALID',measurement.type,'unknown measurement type'));
  if(measurement.runtime_only!==true)
    issues.push(_rtIssue('MEASUREMENT_INVALID',measurement.measurement_id,
      'runtime_only must be true'));
  const _d=measurement.distance_m;
  if(typeof _d!=='number'||_rtNum(_d)===null||_rtNum(_d)<0)
    issues.push(_rtIssue('MEASUREMENT_INVALID',measurement.measurement_id,
      'distance must be a finite non-negative number'));
  return _rtOk(issues,{}); }
function addRuntimeMeasurement(runtimeState,runtimeScene,mtype,opts){
  const res=createRuntimeMeasurement(runtimeScene,mtype,opts);
  if(res.valid){ if(!runtimeState.measurements) runtimeState.measurements=[];
    runtimeState.measurements.push(_rtCopy(res.measurement)); }
  return res; }

/* ------------------------------------------ التحقّق من الأفعال -------- */
function validateRuntimeAction(action,targetKind,targetId,payload){
  const issues=[];
  const a=_rtEnum(action);
  if(RT_ACTIONS.indexOf(a)<0){
    issues.push(_rtIssue('INTERACTION_ACTION_INVALID',action,'unknown runtime action'));
    return _rtOk(issues,{action:null}); }
  const allowed=RT_ACTION_TARGETS[a];
  const tk=(targetKind===null||targetKind===undefined)?'NONE'
    :(_rtEnum(targetKind)||'');
  if(allowed.indexOf(tk)<0)
    issues.push(_rtIssue('INTERACTION_TARGET_INVALID',targetKind,
      'target kind is not valid for '+a));
  const p=(payload&&typeof payload==='object'&&!Array.isArray(payload))?payload:{};
  Object.keys(p).forEach(key=>{
    const k=String(key).toLowerCase();
    if(RT_WRITE_INTENTS.indexOf(k)>=0||k.indexOf('set_')===0||k.indexOf('write_')===0
       ||k==='geometry'||k==='source_element_id'||k==='vertices'||k==='transform')
      issues.push(_rtIssue('RUNTIME_MODEL_WRITE_ATTEMPT',key,
        'the runtime exposes no model-write path')); });
  if(p.writes_to_model) issues.push(_rtIssue('RUNTIME_MODEL_WRITE_ATTEMPT','writes_to_model',
    'the runtime exposes no model-write path'));
  return _rtOk(issues,{action:issues.length?null:a,target_kind:tk,target_id:targetId}); }

/* ---------------------------------------------------------- التحقّق --- */
function validateRuntimeScene(runtimeScene){
  const issues=(runtimeScene.issues||[]).slice();
  const seen={};
  (runtimeScene.objects||[]).forEach(o=>{
    const rid=o.runtime_object_id;
    if(Object.prototype.hasOwnProperty.call(seen,rid))
      issues.push(_rtIssue('RUNTIME_ID_DUPLICATE',rid,'duplicate runtime object id'));
    seen[rid]=true;
    if(!o.visual_only&&!o.source_element_id)
      issues.push(_rtIssue('RUNTIME_SOURCE_OBJECT_INVALID',rid,
        'a model-derived runtime object must name its source')); });
  const w=runtimeScene.walkability||{};
  (w.surfaces||[]).forEach(s=>{
    const r=s.rect_local;
    if(!r||r.length!==4||_rtNum(r[2])===null||_rtNum(r[3])===null||r[2]<=0||r[3]<=0
       ||_rtNum(s.elevation_m)===null)
      issues.push(_rtIssue('WALKABLE_SURFACE_INVALID',s.surface_id,
        'surface bounds are not valid')); });
  (w.obstacles||[]).forEach(o=>{
    const b=o.bounds;
    if(!b||b.length!==6||b.some(v=>_rtNum(v)===null)||b[3]<b[0]||b[4]<b[1]||b[5]<b[2])
      issues.push(_rtIssue('OBSTACLE_INVALID',o.obstacle_id,
        'obstacle bounds are not valid')); });
  const seenP={}, spaceIds={};
  (runtimeScene.rooms||[]).forEach(r=>{spaceIds[r.space_id]=true;});
  spaceIds[RT_EXTERIOR]=true;
  (w.portals||[]).forEach(p=>{
    if(Object.prototype.hasOwnProperty.call(seenP,p.portal_id))
      issues.push(_rtIssue('PORTAL_DUPLICATE',p.portal_id,'duplicate portal id'));
    seenP[p.portal_id]=true;
    if(RT_PORTAL_STATES.indexOf(p.default_state)<0)
      issues.push(_rtIssue('PORTAL_STATE_INVALID',p.portal_id,
        'unknown default portal state'));
    if(p.connectivity_resolved){
      ['from_space','to_space'].forEach(side=>{
        if(!spaceIds[p[side]])
          issues.push(_rtIssue('PORTAL_SPACE_REFERENCE_INVALID',p.portal_id,
            side+' does not resolve')); });
      if(p.from_space===p.to_space)
        issues.push(_rtIssue('PORTAL_SPACE_REFERENCE_INVALID',p.portal_id,
          'a portal may not connect a space to itself')); } });
  if(runtimeScene.writes_to_model)
    issues.push(_rtIssue('RUNTIME_MODEL_WRITE_ATTEMPT','runtime_scene',
      'writes_to_model must be false'));
  return _rtOk(issues,{}); }
function runtimeRuleInputs(runtimeScene){
  const c=runtimeScene.counts||{};
  return {building:{'runtime.object.count':c.objects||0,
    'runtime.obstacle.count':c.obstacles||0,
    'runtime.walkable_surface.count':c.surfaces||0,
    'runtime.portal.count':c.portals||0,
    'runtime.portal.unresolved_count':c.portals_unresolved||0}}; }
function runtimeSummary(runtimeScene){
  const c=runtimeScene.counts||{}, idx=runtimeScene.spatial_index||{};
  return {compiler_version:RT_COMPILER_VERSION,runtime_id:runtimeScene.runtime_id,
    source_scene:runtimeScene.source_scene,model_hash:runtimeScene.model_hash,
    objects:c.objects||0,obstacles:c.obstacles||0,surfaces:c.surfaces||0,
    rooms:c.rooms||0,portals:c.portals||0,
    portals_unresolved:c.portals_unresolved||0,
    vertical_connections:c.vertical_connections||0,
    spatial_cells:idx.cells||0,issues:(runtimeScene.issues||[]).length,
    engineering_geometry_modified:false,writes_to_model:false,
    compliance:'NOT_EVALUATED',
    note:'deterministic read-only interaction runtime; ephemeral state only, no simulation '+
         'engine, and no write path to any engineering model'}; }
'''


def main():
    with open(SPEC_PATH, encoding='utf-8') as f:
        spec = f.read().rstrip()
    block = BEGIN + '\n' + JS.replace('__SPEC__', spec).strip() + '\n' + END + '\n'
    with open(IDX, encoding='utf-8') as f:
        src = f.read()
    if BEGIN in src:
        a = src.index(BEGIN)
        b = src.index(END) + len(END) + 1
        src = src[:a] + block + src[b:]
        action = 'replaced'
    else:
        if src.count(ANCHOR) != 1:
            print('anchor not unique in index.html', file=sys.stderr)
            return 2
        src = src.replace(ANCHOR, block + ANCHOR, 1)
        action = 'injected'
    with open(IDX, 'w', encoding='utf-8') as f:
        f.write(src)
    print('runtime layer %s: %d bytes' % (action, len(block)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
