# -*- coding: utf-8 -*-
"""يكتب طبقة التبادل مع BIM ولوحة الاستيراد/التصدير في مواضعها بعد التفكيك (F-09):
الشيفرة في public/app/generated/bim.js، والأنماط في public/app/styles/app.css،
والعلامة في public/index.html — لا يكتب المولّد خارج علامتيه.

حدّ معلَن: تحليل STEP وكتابته يبقيان في بايثون. المتصفّح يحمل التمثيل المُوحَّد
للتجهيز وما يُبنى عليه (التصنيف، الوحدات، المعرّفات، الفرق، المقترحات، القِدَم،
تقرير الذهاب والإياب)، وهو ما يُقارَن في اختبار التكافؤ. لا يُدّعى تكافؤ مُحلِّل
في المتصفّح لأنه غير منفَّذ هناك.
"""
import io
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import app_source as APP  # noqa: E402 — التخطيط بعد التفكيك يُعرَف من مصدر واحد

SPEC_PATH = os.path.join(ROOT, "acs_bim.json")
# بعد F-09: الشيفرة في وحدتها، والأنماط في ملفّ الأنماط، والعلامة وحدها بقيت في القشرة.
JS_TARGET = os.path.join(APP.APP, "generated", "bim.js")
CSS_TARGET = os.path.join(APP.APP, "styles", "app.css")
PAGE = os.path.join(APP.PUB, "index.html")

JS_BEGIN = "/* ===== ACS BIM EXCHANGE (generated by tools/build_bim_browser.py) ===== */"
JS_END = "/* ===== END ACS BIM EXCHANGE ===== */"

CSS_BEGIN = "/* ===== ACS BIM STYLES (generated) ===== */"
CSS_END = "/* ===== END ACS BIM STYLES ===== */"

DOM_BEGIN = "<!-- ===== ACS BIM DOM (generated) ===== -->"
DOM_END = "<!-- ===== END ACS BIM DOM ===== -->"

CSS = r""".bx-panel{position:fixed;inset-block:0;inset-inline-start:0;width:min(96vw,440px);
  background:var(--ws-panel);border-inline-end:1px solid var(--ws-line);
  color:var(--ws-txt);z-index:62;display:none;grid-template-rows:auto 1fr auto;
  font:13px/1.5 system-ui,-apple-system,"Segoe UI",Tahoma,sans-serif}
.bx-panel.on{display:grid}
.bx-panel *{box-sizing:border-box;min-width:0}
.bx-head{display:flex;align-items:center;gap:8px;padding:10px 12px;
  border-bottom:1px solid var(--ws-line);min-height:var(--ws-hit)}
.bx-head h3{margin:0;font-size:13px;letter-spacing:.4px;text-transform:uppercase;
  color:var(--ws-dim)}
.bx-body{overflow:auto;padding:10px 12px}
.bx-foot{display:flex;gap:8px;padding:10px 12px;border-top:1px solid var(--ws-line);
  flex-wrap:wrap}
.bx-btn{border:1px solid var(--ws-line);background:var(--ws-panel2);color:var(--ws-txt);
  border-radius:9px;padding:0 14px;min-height:var(--ws-hit);cursor:pointer;font-size:13px}
.bx-btn.pri{background:var(--ws-accent);border-color:var(--ws-accent);color:#06101d}
.bx-btn.ok{border-color:var(--ws-ok);color:var(--ws-ok)}
.bx-btn.no{border-color:var(--ws-err);color:var(--ws-err)}
.bx-btn[disabled]{opacity:.45;cursor:not-allowed}
.bx-sec{margin:0 0 14px}
.bx-sec h4{margin:0 0 6px;font-size:11px;letter-spacing:.5px;text-transform:uppercase;
  color:var(--ws-dim)}
.bx-row{display:flex;align-items:flex-start;justify-content:space-between;gap:10px;
  padding:3px 0}
.bx-row .k{color:var(--ws-dim);font-size:12px;flex:0 0 auto}
.bx-row .v{font-size:12px;text-align:end;overflow-wrap:anywhere;word-break:break-word}
.bx-badge{display:inline-block;border:1px solid var(--ws-line);border-radius:999px;
  padding:0 8px;font-size:10px;margin-inline-start:6px}
.bx-badge.SUPPORTED{border-color:var(--ws-ok);color:var(--ws-ok)}
.bx-badge.PARTIALLY_SUPPORTED{border-color:var(--ws-warn);color:var(--ws-warn)}
.bx-badge.PRESERVED_OPAQUE{border-color:var(--ws-info);color:var(--ws-info)}
.bx-badge.UNSUPPORTED,.bx-badge.REFUSED{border-color:var(--ws-err);color:var(--ws-err)}
.bx-badge.PASS{border-color:var(--ws-ok);color:var(--ws-ok)}
.bx-badge.WARNING{border-color:var(--ws-warn);color:var(--ws-warn)}
.bx-badge.FAIL{border-color:var(--ws-err);color:var(--ws-err)}
.bx-preview{margin:6px 0 0;max-height:220px;overflow:auto}
.bx-line{display:flex;justify-content:space-between;gap:8px;padding:2px 0;
  font-size:12px}
.bx-line .n{overflow-wrap:anywhere;word-break:break-word}
.bx-line .s{color:var(--ws-dim);flex:0 0 auto;font-size:10px}
.bx-item{border:1px solid var(--ws-line);border-radius:9px;padding:8px;margin:0 0 6px;
  background:var(--ws-panel2)}
.bx-item .t{font-size:12px;overflow-wrap:anywhere;word-break:break-word}
.bx-item .c{font-size:11px;color:var(--ws-dim);overflow-wrap:anywhere}
.bx-item .a{display:flex;gap:6px;margin-top:6px;flex-wrap:wrap}
.bx-item .a button{min-height:var(--ws-hit);padding:0 12px;border-radius:8px;
  border:1px solid var(--ws-line);background:transparent;color:inherit;cursor:pointer;
  font-size:12px}
.bx-note{color:var(--ws-dim);font-size:11px;margin-top:8px}
.bx-stage{display:inline-flex;align-items:center;gap:6px;border:1px dashed var(--ws-warn);
  color:var(--ws-warn);border-radius:8px;padding:2px 10px;font-size:11px}
@media (max-width:767px){ .bx-panel{width:100vw} }
"""

DOM = r"""<aside class="bx-panel" id="bxPanel" role="dialog" aria-label="BIM exchange"
  data-bx="panel">
  <div class="bx-head">
    <h3 id="bxTitle">BIM / Exchange</h3>
    <span class="acs-u-11"></span>
    <button class="bx-btn" id="bxClose" aria-label="Close BIM exchange">✕</button>
  </div>
  <div class="bx-body" id="bxBody"></div>
  <div class="bx-foot">
    <button class="bx-btn" id="bxImport" data-bx-action="import">Import BIM</button>
    <button class="bx-btn" id="bxExport" data-bx-action="export">Export BIM</button>
    <button class="bx-btn" id="bxValidate" data-bx-action="validate">Validate</button>
    <button class="bx-btn" id="bxCompare" data-bx-action="compare">Compare</button>
    <button class="bx-btn" id="bxProposals" data-bx-action="proposals">Proposals</button>
    <button class="bx-btn" id="bxRoundtrip" data-bx-action="roundtrip">Round-trip</button>
  </div>
</aside>
"""

BODY = r"""const ACS_BIM_SPEC = __SPEC__;
const BX_SCHEMA = ACS_BIM_SPEC.schema;
const BX_LIMITS = ACS_BIM_SPEC.limits;
const BX_TOL = ACS_BIM_SPEC.tolerances;
const BX_UNSAFE = ACS_BIM_SPEC.unsafe_patterns;
const BX_FORBIDDEN_KEYS = ACS_BIM_SPEC.forbidden_property_keys;
const BX_ISSUE_CODES = ACS_BIM_SPEC.issue_codes;
const BX_BLOCKING = ACS_BIM_SPEC.blocking_issue_codes;
const BX_GUID_ALPHABET = ACS_BIM_SPEC.global_id_alphabet;
const BX_COMMAND_SOURCE = ACS_BIM_SPEC.import_command_source;
const BX_COMMAND_MAP = ACS_BIM_SPEC.import_command_map;
const BX_ENTITY_SUPPORT = (function(){ const m={};
  ACS_BIM_SPEC.entity_support.forEach(e=>{ m[e.entity.toUpperCase()]=e; }); return m; })();
const BX_SAFE_ID = new RegExp(ACS_BIM_SPEC.safe_id_pattern);
const BX_PARSER_VERSION = 'acs-bim-step/1.0.0';
const BX_MAPPER_VERSION = 'acs-bim-map/1.0.0';
/* حدّ معلَن: تحليل STEP وكتابته يجريان في بايثون فقط. المتصفّح يعمل على التمثيل
   المُوحَّد للتجهيز، وهو ما يُقارَن في اختبار التكافؤ. */
const BX_STEP_PARSER_IN_BROWSER = false;

function _bxQ(v){ return _pyRound(Number(v),6)+0; }
function _bxNum(v){
  if(v===null||v===undefined||typeof v==='boolean') return null;
  const f=Number(v); return isFinite(f)?f:null; }
function _bxCopy(v){ return JSON.parse(JSON.stringify(v)); }
function _bxSha16(o){ return sha256Hex(ingestCanonicalJson(o)).slice(0,16); }
function bxIssue(code,severity,entityId,message,blocking){
  const c=(BX_ISSUE_CODES.indexOf(code)>=0)?code:'BIM_INVALID_FILE';
  const sev=severity||'ERROR';
  const b=(blocking===undefined||blocking===null)
    ?(BX_BLOCKING.indexOf(c)>=0&&sev==='ERROR'):!!blocking;
  return {code:c,severity:sev,entity_id:(entityId===undefined)?null:entityId,
    message:message||'',blocking:!!b}; }
function bxIsUnsafe(v){
  if(typeof v!=='string') return false;
  for(let i=0;i<v.length;i++){ const c=v.charCodeAt(i);
    if(c<32&&c!==9) return true; }
  const low=v.toLowerCase();
  for(let i=0;i<BX_UNSAFE.length;i++)
    if(low.indexOf(String(BX_UNSAFE[i]).toLowerCase())>=0) return true;
  return false; }
function bxIsSafeId(v){ return typeof v==='string'&&BX_SAFE_ID.test(v); }
function bxSafeKey(k){
  if(typeof k!=='string'||!k||k.length>255) return false;
  if(BX_FORBIDDEN_KEYS.indexOf(k)>=0) return false;
  return bxIsSafeId(k.split(' ').join('_')); }
function bxSupportOf(t){
  const e=BX_ENTITY_SUPPORT[String(t).toUpperCase()];
  return e?e.support:'UNSUPPORTED'; }
function bxIfcGuid(seed){
  const h=sha256Hex(ingestCanonicalJson(seed)).slice(0,32);
  /* الحساب على ستّ عشرة خانة بستّ عشريّة بلا أعداد كبيرة: نقرأ من اليمين */
  const digits=[]; let hex=h;
  const toBits=[];
  for(let i=0;i<hex.length;i++) {
    const v=parseInt(hex.charAt(i),16);
    for(let b=3;b>=0;b--) toBits.push((v>>b)&1); }
  /* 128 بت: أوّل بتَّين ثم 21 مجموعة من ستّة */
  const take=(from,len)=>{ let n=0; for(let i=0;i<len;i++) n=(n<<1)|toBits[from+i];
    return n; };
  digits.push(take(0,2));
  for(let i=0;i<21;i++) digits.push(take(2+i*6,6));
  return digits.map(d=>BX_GUID_ALPHABET.charAt(d)).join(''); }
function bxLengthFactor(name){
  const f=ACS_BIM_SPEC.length_units[name];
  return (f===undefined)?null:f; }
function bxToMetres(value,unitName){
  const f=bxLengthFactor(unitName), n=_bxNum(value);
  if(f===null) return {valid:false,value:null,
    issues:[bxIssue('BIM_UNIT_UNRESOLVED','ERROR',null,
      'unit '+unitName+' is not declared; it is never guessed')]};
  if(n===null) return {valid:false,value:null,
    issues:[bxIssue('BIM_INVALID_NUMBER','ERROR',null,'value is not a finite number')]};
  return {valid:true,value:_bxQ(n*f),issues:[],converted_once:true}; }

/* ------------------------------------------------- بناء نموذج التبادل --- */
function _bxRooms(model){
  const out=[];
  Object.keys(model.floors||{}).sort(_scmp).forEach(tk=>{
    ((model.floors[tk]||{}).rooms||[]).forEach(r=>out.push([tk,r])); });
  return out; }
function _bxLevels(model){
  return (model.levels||[]).slice().sort((a,b)=>{
    const ai=(a.index===null||a.index===undefined)?1e9:a.index;
    const bi=(b.index===null||b.index===undefined)?1e9:b.index;
    return ai-bi; }); }
function _bxOpening(bid,lv,r,op,j,kind,x,z,w,d,elev){
  const edge=String(op.edge||'N').toUpperCase().slice(0,1);
  const offset=_bxNum(op.offset), width=_bxNum(op.width), height=_bxNum(op.height);
  if(offset===null||width===null) return null;
  let px,pz,ang;
  if(edge==='N'){ px=x+offset; pz=z; ang=0; }
  else if(edge==='S'){ px=x+offset; pz=z+d; ang=0; }
  else if(edge==='W'){ px=x; pz=z+offset; ang=90; }
  else { px=x+w; pz=z+offset; ang=90; }
  const idx=lv.index;
  const sill=_bxNum(op.sill);
  return {canonical_id:bid+'.flr_'+idx+'.'+lv.template+'.'+r.id+'.'+kind+'_'+j,
    level_index:idx,elevation:elev,x:_bxQ(px),z:_bxQ(pz),rotation_deg:_bxQ(ang),
    width:_bxQ(width),height:(height===null)?null:_bxQ(height),
    height_known:height!==null,sill:(sill===null)?null:_bxQ(sill),
    host_wall_id:bid+'.flr_'+idx+'.'+lv.template+'.'+r.id+'.wall_'+edge,
    edge:edge,offset:_bxQ(offset),
    space_id:bid+'.flr_'+idx+'.'+lv.template+'.'+r.id,
    authoring_space_id:lv.template+'.'+r.id}; }

function _bxApplyPolygonExchange(ex,model,levels,bid,scope){
  const byTemplate=new Map();
  _bxRooms(model).forEach(([t,r])=>{if(!byTemplate.has(t))byTemplate.set(t,[]);byTemplate.get(t).push(r);});
  const selected=levels.filter(l=>(byTemplate.get(l.template)||[]).some(r=>'polygon' in r));
  if(!selected.length)return;
  const indices=new Set(selected.map(l=>l.index)),ids=new Map(),sourceOpenings=new Map();
  const key=(i,s)=>JSON.stringify([i,s]);
  selected.forEach(lv=>{
    const idx=lv.index,template=lv.template;
    (byTemplate.get(template)||[]).forEach(room=>{
      if(_pyT(room.shape)||_pyT(room.vertices))throw Error('POLYGON_UNSUPPORTED: conflicting boundary representation');
      const ring=ACS_POLYGON.room_ring(room),aid=template+'.'+room.id;
      const arid=room.space_id||(bid+'.'+aid),sid=bid+'.flr_'+idx+'.'+aid;
      ids.set(key(idx,arid),sid);
      if(scope==='SPACES_ONLY')return;
      [['door','doors'],['window','windows']].forEach(([kind,field])=>{
        (room[field]||[]).forEach((op,j)=>{
          if('polygon' in room){
            const edge=ACS_POLYGON.edge_index(room,op),[a,b]=ACS_POLYGON.edges(ring)[edge];
            const width=op.width,offset=op.offset;
            if([width,offset].some(v=>typeof v!=='number'||!Number.isFinite(v))||width<=0||
               offset-width/2 < -ACS_POLYGON.EPS||offset+width/2 > Math.hypot(b[0]-a[0],b[1]-a[1])+ACS_POLYGON.EPS)
              throw Error('POLYGON_OPENING_INVALID: width and offset must fit the authored edge');
          }
          sourceOpenings.set(sid+'.'+kind+'_'+j,[arid+'.'+kind+'_'+j+'@'+idx,op]);
        });
      });
    });
  });
  const arch=compileArchitecture(model,bid),spaces=new Map();
  arch.spaces.filter(s=>indices.has(s.level_index)).forEach(s=>spaces.set(ids.get(key(s.level_index,s.space_id)),s));
  ex.spaces.forEach(space=>{
    if(indices.has(space.level_index)){
      const derived=spaces.get(space.canonical_id);
      if('polygon' in derived){space.polygon=derived.polygon;space.area_m2=_bxQ(derived.area_m2);}
    }
  });
  const walls=new Map(arch.walls.filter(w=>indices.has(w.level_index)).map(w=>[w.id,w]));
  const elevations=new Map(ex.levels.map(l=>[l.index,l.elevation]));
  if(scope!=='SPACES_ONLY'){
    ex.walls=ex.walls.filter(w=>!indices.has(w.level_index));
    walls.forEach(wall=>{
      const idx=wall.level_index,owners=wall.spaces.map(s=>ids.get(key(idx,s)));
      const height=wall.height_m,thickness=wall.thickness_m.value;
      ex.walls.push({canonical_id:wall.id,level_index:idx,elevation:elevations.get(idx),
        start:[_bxQ(wall.start.x),_bxQ(wall.start.z)],end:[_bxQ(wall.end.x),_bxQ(wall.end.z)],
        height:_bxQ(height.value!==null?height.value:height.render_fallback),
        thickness:thickness!==null?_bxQ(thickness):null,thickness_known:thickness!==null,
        space_id:owners[0],space_ids:owners,shared:wall.shared,edge:null});
    });
  }
  const openings=new Map(arch.openings.map(o=>[o.id,o]));
  ['doors','windows'].forEach(field=>ex[field].forEach(opening=>{
    if(!indices.has(opening.level_index))return;
    const [arid,source]=sourceOpenings.get(opening.canonical_id),derived=openings.get(arid);
    const anchor=derived?archOpeningAnchor(arch,arid):null,host=derived?walls.get(derived.host_wall_id):null;
    if(!derived||derived.host_status!=='resolved'||anchor===null||!host)
      throw Error('POLYGON_OPENING_UNRESOLVED: no canonical host or position');
    opening.x=_bxQ(anchor[0]);opening.z=_bxQ(anchor[1]);opening.host_wall_id=host.id;
    opening.offset=_bxQ(Math.hypot(anchor[0]-host.start.x,anchor[1]-host.start.z));
    opening.rotation_deg=_bxQ(Math.atan2(host.end.z-host.start.z,host.end.x-host.start.x)*180/Math.PI);
    if('edge_index' in source){opening.edge=null;opening.edge_index=source.edge_index;
      opening.source_edge_offset=_bxQ(source.offset);}
  }));
  const slabs=new Map(arch.slabs.filter(s=>indices.has(s.level_index)).map(s=>[s.level_index,s]));
  ex.slabs.forEach(slab=>{
    if(indices.has(slab.level_index)){
      const derived=slabs.get(slab.level_index);
      slab.outline=derived.outline;slab.cells=derived.cells;slab.area_m2=_bxQ(derived.area_m2);
    }
  });
}

function bxBuildExchange(project,options){
  const o=options||{};
  const model=project.model, bid=project.building_id||'bld_0';
  const scope=String(o.scope||'ALL').toUpperCase();
  if(ACS_BIM_SPEC.export_scope_options.indexOf(scope)<0)
    return {valid:false,issues:[bxIssue('BIM_EXPORT_VALIDATION_FAILED','ERROR',null,
      'unknown export scope: '+o.scope)],exchange:null};
  const includeSpaces=(o.include_spaces===undefined)?true:!!o.include_spaces;
  const wanted=(o.levels===undefined)?null:o.levels;
  const wallH=_bxNum(model.wall_h)||3;
  const wallT=_bxNum(model.wall_t);
  const floorH=_bxNum(model.floor_height)||(wallH+0.2);
  const site=model.site||{};
  let levels=_bxLevels(model);
  if(wanted!==null) levels=levels.filter(l=>wanted.indexOf(l.index)>=0);
  const name=(model.meta||{}).name;
  const ex={schema_version:ACS_BIM_SPEC.writable_schemas[0],
    project:{canonical_id:'project',name:name||'Project'},
    site:{canonical_id:'site',name:'Site',
      w:_bxNum(site.w),d:_bxNum(site.d)},
    building:{canonical_id:bid,name:name||bid},
    levels:[],spaces:[],walls:[],slabs:[],doors:[],windows:[],stairs:[],
    unsupported:[],losses:[]};
  const byTemplate={};
  _bxRooms(model).forEach(pr=>{
    (byTemplate[pr[0]]=byTemplate[pr[0]]||[]).push(pr[1]); });
  levels.forEach(lv=>{
    const idx=lv.index;
    const elev=_bxQ((lv.elevation!==null&&lv.elevation!==undefined)
      ?_bxNum(lv.elevation):(Number(idx||0)*floorH));
    ex.levels.push({canonical_id:bid+'.flr_'+idx,
      name:lv.name||('Level '+idx),index:idx,elevation:elev,template:lv.template});
    const rooms=(byTemplate[lv.template]||[]).slice()
      .sort((a,b)=>_scmp(String(a.id),String(b.id)));
    rooms.forEach(r=>{
      const rect=r.rect||[0,0,0,0];
      const x=_bxQ(_bxNum(rect[0])||0), z=_bxQ(_bxNum(rect[1])||0);
      const w=_bxQ(_bxNum(rect[2])||0), d=_bxQ(_bxNum(rect[3])||0);
      const rh=_bxNum(r.height)||wallH;
      const sid=bid+'.flr_'+idx+'.'+lv.template+'.'+r.id;
      const aid=lv.template+'.'+r.id;
      if(includeSpaces&&['ALL','SPACES_ONLY','LEVELS'].indexOf(scope)>=0)
        ex.spaces.push({canonical_id:sid,authoring_id:aid,
          name:r.name||String(r.id),number:String(r.id),level_index:idx,
          elevation:elev,height:_bxQ(rh),footprint:[x,z,w,d],area_m2:_bxQ(w*d)});
      if(scope==='SPACES_ONLY') return;
      [['N',x,z,x+w,z],['S',x,z+d,x+w,z+d],['W',x,z,x,z+d],['E',x+w,z,x+w,z+d]]
        .forEach(e=>{
          ex.walls.push({canonical_id:bid+'.flr_'+idx+'.'+lv.template+'.'+r.id+
              '.wall_'+e[0],
            level_index:idx,elevation:elev,start:[_bxQ(e[1]),_bxQ(e[2])],
            end:[_bxQ(e[3]),_bxQ(e[4])],height:_bxQ(rh),
            thickness:(wallT===null)?null:_bxQ(wallT),
            thickness_known:wallT!==null,space_id:sid,edge:e[0]}); });
      (r.doors||[]).forEach((op,j)=>{
        const rec=_bxOpening(bid,lv,r,op,j,'door',x,z,w,d,elev);
        if(rec) ex.doors.push(rec); });
      (r.windows||[]).forEach((op,j)=>{
        const rec=_bxOpening(bid,lv,r,op,j,'window',x,z,w,d,elev);
        if(rec) ex.windows.push(rec); });
      (r.objects||[]).forEach((ob,j)=>{
        const kind=String(ob.kind||'');
        const oid=bid+'.flr_'+idx+'.'+lv.template+'.obj_'+j;
        if(kind.toLowerCase()==='stairs'||kind.toLowerCase()==='stair')
          ex.stairs.push({canonical_id:oid,level_index:idx,elevation:elev,
            x:_bxQ(x+(_bxNum(ob.x)||0)),z:_bxQ(z+(_bxNum(ob.z)||0)),
            w:_bxQ(_bxNum(ob.w)||1.2),d:_bxQ(_bxNum(ob.d)||2.4),space_id:sid});
        else ex.unsupported.push({canonical_id:oid,kind:kind,space_id:sid,
          reason:'no declared IFC mapping for this object kind'}); }); });
    if(scope!=='SPACES_ONLY'&&scope!=='ENVELOPE_ONLY'){
      const xs=[],zs=[];
      rooms.forEach(r=>{ const rect=r.rect||[0,0,0,0];
        const rx=_bxNum(rect[0])||0, rz=_bxNum(rect[1])||0;
        xs.push(rx,rx+(_bxNum(rect[2])||0)); zs.push(rz,rz+(_bxNum(rect[3])||0)); });
      if(xs.length){
        const mnx=Math.min.apply(null,xs), mxx=Math.max.apply(null,xs);
        const mnz=Math.min.apply(null,zs), mxz=Math.max.apply(null,zs);
        ex.slabs.push({canonical_id:bid+'.flr_'+idx+'.slab',level_index:idx,
          elevation:elev,outline:[_bxQ(mnx),_bxQ(mnz),_bxQ(mxx-mnx),_bxQ(mxz-mnz)],
          thickness:null,thickness_known:false,predefined_type:'FLOOR'}); } } });
  try{_bxApplyPolygonExchange(ex,model,levels,bid,scope);}
  catch(error){return {valid:false,issues:[bxIssue('BIM_EXPORT_VALIDATION_FAILED','ERROR',null,
    error.message)],exchange:null};}
  ex.unsupported.forEach(u=>{ ex.losses.push({entity_id:u.canonical_id,
    type:'UNSUPPORTED_ENTITY',severity:'WARNING',message:u.reason}); });
  if(wallT===null&&ex.walls.length)
    ex.losses.push({entity_id:null,type:'PROPERTY_LOSS',severity:'WARNING',
      message:'wall thickness is not stated in the model and is not invented on export'});
  ex.slabs.forEach(s=>{ ex.losses.push({entity_id:s.canonical_id,type:'PROPERTY_LOSS',
    severity:'INFO',message:'slab thickness is not stated in the model'}); });
  ex.config={scope:scope,include_spaces:!!includeSpaces,
    levels:(wanted===null)?null:wanted.slice().sort((a,b)=>a-b),
    include_external_metadata:(o.include_external_metadata===undefined)
      ?true:!!o.include_external_metadata,
    coordinate_policy:ACS_BIM_SPEC.coordinate_policy,schema:ex.schema_version};
  ex.config_hash=_bxSha16(ex.config);
  ex.model_hash=(project.model_hash===undefined)?null:project.model_hash;
  ex.revision_id=(project.current_revision===undefined)?null:project.current_revision;
  ex.building_id=bid;
  return {valid:true,issues:[],exchange:ex}; }

function bxValidateExchange(ex){
  const issues=[], seen={};
  const groups=['levels','spaces','walls','slabs','doors','windows','stairs'];
  let total=0;
  groups.forEach(g=>{ (ex[g]||[]).forEach(it=>{
    total++;
    const cid=it.canonical_id;
    if(!bxIsSafeId(String(cid)))
      issues.push(bxIssue('BIM_INVALID_IDENTIFIER','ERROR',cid,
        'canonical identifier is not a plausible identifier'));
    if(cid in seen)
      issues.push(bxIssue('BIM_DUPLICATE_ID','ERROR',cid,
        'the same canonical identifier appears twice'));
    seen[cid]=true;
    ['name','number'].forEach(k=>{
      if((k in it)&&bxIsUnsafe(it[k]))
        issues.push(bxIssue('BIM_UNSAFE_STRING','ERROR',cid,
          'an exported name carries an unsafe value')); }); }); });
  if(total>Number(BX_LIMITS.max_objects))
    issues.push(bxIssue('BIM_RESOURCE_LIMIT_EXCEEDED','ERROR',null,
      'object count exceeds the declared maximum'));
  if((ex.levels||[]).length>Number(BX_LIMITS.max_levels))
    issues.push(bxIssue('BIM_RESOURCE_LIMIT_EXCEEDED','ERROR',null,
      'level count exceeds the declared maximum'));
  const wallIds={}; (ex.walls||[]).forEach(w=>{ wallIds[w.canonical_id]=true; });
  ['doors','windows'].forEach(k=>{ (ex[k]||[]).forEach(op=>{
    if(op.host_wall_id&&!wallIds[op.host_wall_id])
      issues.push(bxIssue('BIM_HOST_UNRESOLVED','WARNING',op.canonical_id,
        'the host wall is not part of this export scope')); }); });
  groups.forEach(g=>{ (ex[g]||[]).forEach(it=>{
    Object.keys(it).sort(_scmp).forEach(k=>{
      const v=it[k];
      if(typeof v==='number'&&!isFinite(v))
        issues.push(bxIssue('BIM_INVALID_NUMBER','ERROR',it.canonical_id,
          'a non-finite number reached the exporter')); }); }); });
  return issues; }

function bxExportDescriptor(project,ex,serialised,generatedAt){
  return {export_id:'bimexp_'+_bxSha16({m:ex.model_hash,c:ex.config_hash,
      s:ex.schema_version}),
    model_hash:ex.model_hash,revision_id:ex.revision_id,schema:ex.schema_version,
    object_count:(ex.walls.length+ex.slabs.length+ex.doors.length+ex.windows.length
      +ex.stairs.length+ex.spaces.length),
    level_count:ex.levels.length,space_count:ex.spaces.length,
    wall_count:ex.walls.length,door_count:ex.doors.length,
    window_count:ex.windows.length,slab_count:ex.slabs.length,
    stair_count:ex.stairs.length,
    unsupported_count:ex.unsupported.length,losses:ex.losses,
    warnings:bxValidateExchange(ex).filter(i=>!i.blocking),
    file_hash:(serialised&&serialised.file_hash)||null,
    generator_version:ACS_BIM_SPEC.compiler_version,config_hash:ex.config_hash,
    generated_at:(generatedAt===undefined)?null:generatedAt,
    deterministic_fields:ACS_BIM_SPEC.export_deterministic_fields.slice(),
    non_deterministic_fields:ACS_BIM_SPEC.export_non_deterministic_fields.slice(),
    writes_to_model:false,
    serialised_in_browser:false,
    note:'STEP serialisation runs in the server implementation; the browser builds and '+
         'validates the same exchange model'}; }

/* ------------------------------------------------------- الفرق والمقترحات */
function _bxNear(a,b,tol){
  const na=_bxNum(a), nb=_bxNum(b);
  if(na===null||nb===null) return na===null&&nb===null;
  return Math.abs(na-nb)<=Number(tol); }
function _bxWallKey(x,z,rot,len){
  return [_pyRound(Number(x||0),3),_pyRound(Number(z||0),3),
    _pyRound(((Number(rot||0))%180+180)%180,2),_pyRound(Number(len||0),3)].join('|'); }
function _bxStaged(staging,kind){
  return (staging.entities||[]).filter(e=>e.canonical_kind===kind); }

function bxImportDiff(project,staging,options){
  const before=project.model_hash;
  const built=bxBuildExchange(project,options);
  if(!built.valid) return {valid:false,issues:built.issues,diff:null};
  const ex=built.exchange, diffs=[], tol=BX_TOL;
  const levelElevations=new Map(_bxStaged(staging,'level').map(e=>
    [e.source_entity_id,_bxNum((e.geometry||{}).elevation)]));
  const add=(kind,target,source,field,oldV,newV,basis,severity,loss,aid)=>{
    diffs.push({type:kind,canonical_id:(target===undefined)?null:target,
      authoring_id:(aid===undefined)?null:aid,
      source_entity_id:(source===undefined)?null:source,
      field:(field===undefined)?null:field,
      old_value:(oldV===undefined)?null:oldV,
      proposed_value:(newV===undefined)?null:newV,
      mapping_basis:basis||'UNMATCHED',severity:severity||'INFO',
      loss:(loss===undefined)?null:loss}); };
  [['walls','wall'],['doors','door'],['windows','window'],['spaces','space'],
   ['slabs','slab']].forEach(pair=>{
    const group=pair[0], kind=pair[1], src=new Map(), byGuid=new Map(), sourceKeys=new Map();
    ex[group].forEach(it=>{
      let key;
      if(kind==='wall'){
        const x1=it.start[0],z1=it.start[1],x2=it.end[0],z2=it.end[1];
        key=_bxWallKey(x1,z1,_bxQ(Math.atan2(z2-z1,x2-x1)*180/Math.PI),
          _bxQ(Math.sqrt((x2-x1)*(x2-x1)+(z2-z1)*(z2-z1))));
      } else if(kind==='door'||kind==='window')
        key=[_pyRound(it.x,3),_pyRound(it.z,3)].join('|');
      else if(kind==='space')
        key=[_pyRound(it.footprint[0],3),_pyRound(it.footprint[1],3)].join('|');
      else key=[_pyRound(it.outline[0],3),_pyRound(it.outline[1],3)].join('|');
      key=_pyRound(it.elevation,3)+'|'+key;
      if(!src.has(key))src.set(key,[]);
      src.get(key).push(it);sourceKeys.set(it.canonical_id,key);
      byGuid.set(bxIfcGuid({m:ex.model_hash,id:it.canonical_id,s:staging.bim_schema}),it); });
    const used=new Set(), staged=_bxStaged(staging,kind), gidCounts=new Map();
    staged.forEach(st=>gidCounts.set(st.external_global_id,(gidCounts.get(st.external_global_id)||0)+1));
    staged.forEach(st=>{
      const g=st.geometry||{};
      const elevation=levelElevations.get(st.level_source_id),values=[g.x,g.z,elevation];
      if(kind==='wall')values.push(g.rot_deg,g.length);
      let key=null;
      if(values.every(v=>typeof v==='number'&&Number.isFinite(v))){
        key=kind==='wall'?_bxWallKey(g.x,g.z,g.rot_deg,g.length):
          [_pyRound(g.x,3),_pyRound(g.z,3)].join('|');
        key=_pyRound(elevation,3)+'|'+key;
      }
      const identified=byGuid.get(st.external_global_id);
      let candidates,basis;
      if(identified!==undefined){
        candidates=(gidCounts.get(st.external_global_id)===1&&
          sourceKeys.get(identified.canonical_id)===key&&!used.has(identified.canonical_id))?[identified]:[];
        basis='SOURCE_GLOBAL_ID';
      }else{
        candidates=(src.get(key)||[]).filter(it=>!used.has(it.canonical_id));
        basis='SEMANTIC_AND_GEOMETRY';
      }
      const match=candidates.length===1?candidates[0]:undefined;
      if(match===undefined){ add('OBJECT_ADDED',null,st.source_entity_id,null,null,null,
        'UNMATCHED','WARNING'); return; }
      used.add(match.canonical_id);
      if(kind==='wall'){
        if(!_bxNear(g.height,match.height,tol.dimension_tolerance_m))
          add('OBJECT_RESIZED',match.canonical_id,st.source_entity_id,'height',
            match.height,g.height,basis,'WARNING');
      } else if(kind==='door'||kind==='window'){
        if(!_bxNear(g.width,match.width,tol.dimension_tolerance_m))
          add('OBJECT_RESIZED',match.canonical_id,st.source_entity_id,'width',
            match.width,g.width,basis,'WARNING');
        if(st.host_source_id===null||st.host_source_id===undefined)
          add('HOST_CHANGED',match.canonical_id,st.source_entity_id,'host_wall_id',
            match.host_wall_id,null,'UNMATCHED','WARNING','RELATIONSHIP_LOSS');
      } else if(kind==='space'){
        if(String(st.name)!==String(match.name))
          add('PROPERTY_CHANGED',match.canonical_id,st.source_entity_id,'name',
            match.name,st.name,basis,'INFO',null,match.authoring_id);
        if(!_bxNear((g.w||0)*(g.d||0),match.area_m2,tol.area_tolerance_m2))
          add('OBJECT_RESIZED',match.canonical_id,st.source_entity_id,'area_m2',
            match.area_m2,_bxQ((g.w||0)*(g.d||0)),basis,'WARNING'); } });
    ex[group].slice().sort((a,b)=>_scmp(String(a.canonical_id),
      String(b.canonical_id))).forEach(it=>{
      if(!used.has(it.canonical_id)) add('OBJECT_REMOVED',it.canonical_id,null,null,null,null,
        'UNMATCHED','WARNING'); }); });
  const srcLv={};
  ex.levels.forEach(l=>{ srcLv[_pyRound(_bxQ(l.elevation),3)]=l; });
  _bxStaged(staging,'level').forEach(lv=>{
    const e=_pyRound(_bxQ(lv.geometry.elevation),3);
    if(!(e in srcLv)) add('LEVEL_CHANGED',null,lv.source_entity_id,'elevation',null,e,
      'UNMATCHED','WARNING'); });
  (staging.entities||[]).forEach(e=>{
    if(e.support==='UNSUPPORTED'||e.support==='PRESERVED_OPAQUE')
      add('UNSUPPORTED_EXTERNAL_OBJECT',null,e.source_entity_id,'entity_type',null,
        e.entity_type,'UNMATCHED','INFO','UNSUPPORTED_ENTITY'); });
  const conflicts=bxConflicts(project,staging,ex);
  diffs.sort((a,b)=>{
    const ka=[a.type,String(a.canonical_id),String(a.source_entity_id),
      String(a.field)].join(' ');
    const kb=[b.type,String(b.canonical_id),String(b.source_entity_id),
      String(b.field)].join(' ');
    return _scmp(ka,kb); });
  if(project.model_hash!==before)
    throw new Error('the diff engine changed the project');
  const byType={};
  ACS_BIM_SPEC.diff_types.forEach(t=>{
    byType[t]=diffs.filter(d=>d.type===t).length; });
  return {valid:true,issues:[],diff:{schema:BX_SCHEMA,import_id:staging.import_id,
    target_model_hash:(project.model_hash===undefined)?null:project.model_hash,
    target_revision_id:(project.current_revision===undefined)?null
      :project.current_revision,
    source_file_hash:staging.source.file_hash,entries:diffs,count:diffs.length,
    by_type:byType,conflicts:conflicts,
    blocking_conflicts:conflicts.filter(c=>c.blocking),writes_to_model:false}}; }

function bxConflicts(project,staging,ex){
  const out=[], gids={};
  const add=(cls,subject,msg)=>out.push({conflict:cls,subject:subject,message:msg,
    blocking:ACS_BIM_SPEC.blocking_conflicts.indexOf(cls)>=0});
  (staging.entities||[]).forEach(e=>{
    const g=e.external_global_id;
    if(!g) return;
    if(g in gids) add('DUPLICATE_EXTERNAL_ID',g,
      'the same GlobalId appears more than once');
    gids[g]=e.source_entity_id; });
  if(ACS_BIM_SPEC.readable_schemas.indexOf(staging.bim_schema)<0)
    add('SCHEMA_CONFLICT',staging.bim_schema,'the schema is not readable');
  if(!(staging.units||{}).length) add('UNIT_CONFLICT','length',
    'no length unit was declared');
  (staging.entities||[]).forEach(e=>{
    if((e.canonical_kind==='door'||e.canonical_kind==='window')
       &&e.host_basis==='UNRESOLVED')
      add('HOST_CONFLICT',e.source_entity_id,
        'the opening has no resolvable host wall');
    if((e.world===null||e.world===undefined)
       &&['wall','door','window','space','slab'].indexOf(e.canonical_kind)>=0)
      add('PLACEMENT_CONFLICT',e.source_entity_id,
        'the placement could not be resolved to project world coordinates'); });
  return out; }

function bxImportProposals(diff,staging){
  const props=[], blocked=(diff.blocking_conflicts||[]).length>0;
  diff.entries.forEach(d=>{
    let state;
    if(d.type==='UNSUPPORTED_EXTERNAL_OBJECT') state='BLOCKED';
    else if(blocked) state='BLOCKED';
    else if(d.mapping_basis==='UNMATCHED'
      &&['OBJECT_ADDED','OBJECT_REMOVED','LEVEL_CHANGED'].indexOf(d.type)>=0)
      state='BLOCKED';
    else state='PENDING';
    const p={proposal_id:null,state:state,change_type:d.type,
      canonical_id:d.canonical_id,authoring_id:(d.authoring_id===undefined)?null
        :d.authoring_id,
      source_entity_id:d.source_entity_id,field:d.field,old_value:d.old_value,
      proposed_value:d.proposed_value,mapping_basis:d.mapping_basis,
      severity:d.severity,loss:d.loss,writes_to_model:false,
      blocked_reason:(state==='BLOCKED')
        ?('an unmatched or unsupported change cannot be applied automatically; it '+
          'needs explicit reconciliation'):null};
    p.proposal_id='bimprop_'+_bxSha16({change_type:p.change_type,
      canonical_id:p.canonical_id,source_entity_id:p.source_entity_id,
      field:p.field,proposed_value:p.proposed_value});
    props.push(p); });
  props.sort((a,b)=>_scmp(a.proposal_id,b.proposal_id));
  const byState={};
  ACS_BIM_SPEC.proposal_states.forEach(s=>{
    byState[s]=props.filter(p=>p.state===s).length; });
  return {schema:BX_SCHEMA,import_id:diff.import_id,
    target_model_hash:diff.target_model_hash,
    target_revision_id:diff.target_revision_id,
    proposals:props,count:props.length,by_state:byState,writes_to_model:false,
    note:'no pending proposal writes to the model; acceptance only prepares an '+
         'authoring command.'}; }

function bxSetProposalState(set,proposalId,state){
  if(state!=='ACCEPTED'&&state!=='REJECTED')
    return {valid:false,issues:[bxIssue('BIM_RELATIONSHIP_INVALID','ERROR',proposalId,
      'unknown proposal state')],proposals:set};
  const out=_bxCopy(set); let found=false;
  for(let i=0;i<out.proposals.length;i++){
    const p=out.proposals[i];
    if(p.proposal_id!==proposalId) continue;
    found=true;
    if(p.state==='BLOCKED')
      return {valid:false,issues:[bxIssue('BIM_AMBIGUOUS_MAPPING','ERROR',proposalId,
        'a blocked proposal cannot be accepted or rejected until it is reconciled')],
        proposals:set};
    p.state=state; }
  if(!found) return {valid:false,issues:[bxIssue('BIM_INVALID_REFERENCE','ERROR',
    proposalId,'no such proposal')],proposals:set};
  const byState={};
  ACS_BIM_SPEC.proposal_states.forEach(s=>{
    byState[s]=out.proposals.filter(p=>p.state===s).length; });
  out.by_state=byState;
  return {valid:true,issues:[],proposals:out}; }

function bxImportStaleness(set,project){
  const stale=(set.target_model_hash!==project.model_hash)
    ||(set.target_revision_id!==project.current_revision);
  return {import_id:(set.import_id===undefined)?null:set.import_id,
    status:stale?'STALE_TARGET_MODEL':'CURRENT',
    target_model_hash:(set.target_model_hash===undefined)?null:set.target_model_hash,
    current_model_hash:(project.model_hash===undefined)?null:project.model_hash,
    auto_rebased:false,auto_committed:false,requires_rediff:!!stale,
    note:'a stale import is never rebased or committed automatically.'}; }

function bxExportStaleness(manifest,project){
  const stale=(manifest.model_hash!==project.model_hash)
    ||(manifest.revision_id!==project.current_revision);
  return {export_id:(manifest.export_id===undefined)?null:manifest.export_id,
    status:stale?'STALE_SOURCE_MODEL':'CURRENT',
    export_revision:(manifest.revision_id===undefined)?null:manifest.revision_id,
    current_revision:(project.current_revision===undefined)?null
      :project.current_revision,
    auto_deleted:false,auto_repointed:false}; }

function bxCommandFor(p){
  const ctype=BX_COMMAND_MAP[p.change_type+'.'+p.field];
  if(ctype==='RENAME_SPACE'&&p.authoring_id){
    const v=p.proposed_value;
    if(typeof v!=='string'||bxIsUnsafe(v)) return null;
    return {type:ctype,target_id:p.authoring_id,parameters:{name:v},
      source:BX_COMMAND_SOURCE}; }
  return null; }

function bxCommitImport(project,set,createdAt){
  const st=bxImportStaleness(set,project);
  if(st.status==='STALE_TARGET_MODEL')
    return {valid:false,committed:false,
      issues:[bxIssue('BIM_STALE_TARGET_MODEL','ERROR',set.import_id,
        'the target model moved after staging; re-diff is required before any commit')],
      project:project,state:'STALE_TARGET_MODEL'};
  const accepted=set.proposals.filter(p=>p.state==='ACCEPTED');
  if(!accepted.length)
    return {valid:true,committed:false,issues:[],project:project,state:'PROPOSED',
      note:'nothing was accepted, so nothing is committed'};
  const commands=[], unsupported=[];
  accepted.forEach(p=>{ const c=bxCommandFor(p);
    if(c===null) unsupported.push(p.proposal_id); else commands.push(c); });
  if(!commands.length)
    return {valid:false,committed:false,
      issues:[bxIssue('BIM_AMBIGUOUS_MAPPING','ERROR',null,
        'no accepted proposal maps to an authoring command')],
      project:project,state:'BLOCKED',unsupported_proposals:unsupported};
  const before=project.model_hash, beforeRev=project.current_revision;
  const bid=project.building_id||'bld_0';
  const txn=auValidateTransaction(project,_bxCopy(commands),bid);
  const res=auCommitTransaction(project,_bxCopy(commands),
    {confirm:(txn.transaction||{}).confirmation_digest,acknowledge_warnings:true,
     created_at:(createdAt===undefined)?null:createdAt});
  if(!res.committed)
    return {valid:false,committed:false,
      issues:[bxIssue('BIM_RELATIONSHIP_INVALID','ERROR',null,
        'the authoring path refused the accepted changes')],
      project:project,state:'BLOCKED',authoring_issues:res.issues};
  const np=res.project;
  return {valid:true,committed:true,issues:[],project:np,state:'COMMITTED',
    import_id:set.import_id,previous_model_hash:before,previous_revision:beforeRev,
    new_model_hash:np.model_hash,new_revision:np.current_revision,
    changed_objects:commands.map(c=>c.target_id).sort(_scmp),
    commands:commands,unsupported_proposals:unsupported,via:'AUTHORING_PATH'}; }

function bxAudit(event,payload){
  if(ACS_BIM_SPEC.audit_events.indexOf(event)<0) return null;
  const safe={};
  Object.keys(payload||{}).sort(_scmp).forEach(k=>{
    if(!bxSafeKey(k)) return;
    const v=payload[k];
    if(typeof v==='number'||typeof v==='boolean'||v===null) safe[k]=v;
    else if(typeof v==='string')
      safe[k]=(bxIsSafeId(v)&&v.length<=128)?v:('sha256:'+sha256Hex(v).slice(0,16));
    else safe[k]='sha256:'+_bxSha16(v); });
  return {event:event,fields:safe,records_raw_payload:false,records_secret:false}; }

/* ============================ لوحة التبادل داخل مساحة العمل (§38-§42) ==== */
const BX = (function(){
  const S={project:null,staging:null,diff:null,proposals:null,report:null,
           manifest:null,view:'SUMMARY'};
  const $=id=>(typeof document!=='undefined')?document.getElementById(id):null;
  const esc=s=>String(s===null||s===undefined?'':s).replace(/&/g,'&amp;')
    .replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')
    .replace(/'/g,'&#39;');
  function attach(project){ S.project=project; return S; }
  function state(){ return S; }
  function open(){ const p=$('bxPanel'); if(p) p.classList.add('on'); render();
    return true; }
  function close(){ const p=$('bxPanel'); if(p) p.classList.remove('on'); return true; }
  function loadStaging(staging){
    S.staging=staging; S.diff=null; S.proposals=null; S.view='IMPORT'; render();
    return staging; }
  function exportBim(){
    if(!S.project) return null;
    const before=S.project.model_hash;
    const built=bxBuildExchange(S.project,{});
    if(!built.valid){ S.view='EXPORT'; render(); return built; }
    const issues=bxValidateExchange(built.exchange);
    S.manifest=bxExportDescriptor(S.project,built.exchange,null,null);
    S.manifest.warnings=issues.filter(i=>!i.blocking);
    S.view='EXPORT'; render();
    if(S.project.model_hash!==before)
      throw new Error('an export changed the engineering model');
    return {valid:!issues.some(i=>i.blocking),issues:issues,manifest:S.manifest}; }
  function compare(){
    if(!S.project||!S.staging) return null;
    const before=S.project.model_hash;
    const d=bxImportDiff(S.project,S.staging,{});
    if(d.valid){ S.diff=d.diff; S.proposals=bxImportProposals(d.diff,S.staging); }
    S.view='DIFF'; render();
    if(S.project.model_hash!==before)
      throw new Error('a comparison changed the engineering model');
    return d; }
  function proposals(){ S.view='PROPOSALS'; render(); return S.proposals; }
  function decide(id,state2){
    if(!S.proposals) return null;
    const r=bxSetProposalState(S.proposals,id,state2);
    if(r.valid) S.proposals=r.proposals;
    render(); return r; }
  function commit(createdAt){
    if(!S.project||!S.proposals) return null;
    const r=bxCommitImport(S.project,S.proposals,createdAt);
    if(r.committed) S.project=r.project;
    render(); return r; }
  function roundtrip(report){ S.report=report; S.view='ROUNDTRIP'; render();
    return report; }
  function validate(){
    if(!S.staging) return null;
    S.view='VALIDATE'; render();
    return {issues:S.staging.issues||[],
      blocking:(S.staging.issues||[]).filter(i=>i.blocking)}; }
  function row(k,v,badge){
    return '<div class="bx-row"><span class="k">'+esc(k)+'</span><span class="v">'+
      esc(v)+(badge?('<span class="bx-badge '+esc(badge)+'">'+esc(badge)+'</span>'):'')+
      '</span></div>'; }
  function render(){
    const host=$('bxBody'); if(!host) return;
    if(!S.project){ host.innerHTML='<div class="bx-note">No project open</div>';
      return; }
    const p=[];
    p.push('<div class="bx-sec" data-bx-section="MODEL"><h4>Canonical model</h4>'+
      row('revision',S.project.current_revision)+
      row('model hash',String(S.project.model_hash||'').slice(0,24))+'</div>');
    if(S.staging){
      const st=S.staging, c=st.counts||{};
      p.push('<div class="bx-sec" data-bx-section="IMPORT">'+
        '<h4>Imported file</h4>'+
        '<div class="bx-stage" data-bx="staging-label">'+
        esc(ACS_BIM_SPEC.staging_preview_label)+'</div>'+
        row('file',st.source.file_name||'(name withheld)')+
        row('file hash',String(st.source.file_hash||'').slice(0,24))+
        row('size (bytes)',st.source.byte_length)+
        row('schema',st.bim_schema,st.schema_support)+
        row('unit',((st.units||{}).length||{}).name)+
        row('entities parsed',c.parsed_entities)+
        row('supported',c.supported)+
        row('partially supported',c.partial)+
        row('preserved opaque',c.opaque)+
        row('unsupported',c.unsupported)+
        row('refused',c.refused)+
        row('levels detected',c.levels)+
        row('spaces detected',c.spaces)+
        row('errors',(st.issues||[]).filter(i=>i.severity==='ERROR').length)+
        row('warnings',(st.issues||[]).filter(i=>i.severity==='WARNING').length)+
        row('georeference',(st.georeference||{}).state)+
        row('writes to model',String(st.writes_to_model))+
        /* معاينة ما قُرئ فعلاً: الأسماء الخارجية تُكتب نصّاً مهرَّباً، ولا
           تُستعمل قيمة منها مفتاحاً ولا تفتح عنصراً */
        '<div class="bx-preview">'+
        (st.entities||[]).filter(e=>e.canonical_kind==='space').slice(0,40)
          .map(e=>'<div class="bx-line" data-bx-staged="space">'+
            '<span class="n">'+esc(e.name)+'</span>'+
            '<span class="s">'+esc(e.support)+'</span></div>').join('')+
        '</div>'+
        '<div class="bx-note">'+esc(ACS_BIM_SPEC.staging_preview_note)+'</div></div>');
    }
    if(S.manifest){
      const m=S.manifest;
      p.push('<div class="bx-sec" data-bx-section="EXPORT"><h4>Export</h4>'+
        row('export id',m.export_id)+row('schema',m.schema)+
        row('revision',m.revision_id)+row('objects',m.object_count)+
        row('levels',m.level_count)+row('spaces',m.space_count)+
        row('unsupported',m.unsupported_count)+
        row('losses',(m.losses||[]).length)+
        row('serialised here',String(m.serialised_in_browser))+'</div>');
    }
    if(S.diff){
      const rows=S.diff.entries.slice(0,40).map(d=>
        '<div class="bx-item" data-bx-diff="'+esc(d.type)+'">'+
        '<div class="t">'+esc(_bxDescribe(d))+'</div>'+
        '<div class="c">'+esc(d.mapping_basis)+' · '+esc(d.severity)+
        (d.source_entity_id?(' · '+esc(d.source_entity_id)):'')+'</div></div>').join('');
      p.push('<div class="bx-sec" data-bx-section="DIFF"><h4>Changes ('+
        S.diff.count+')</h4>'+(rows||'<div class="bx-note">No difference</div>')+
        ((S.diff.blocking_conflicts||[]).length
          ?('<div class="bx-note">'+S.diff.blocking_conflicts.length+
            ' blocking conflict(s)</div>'):'')+'</div>');
    }
    if(S.proposals){
      const rows=S.proposals.proposals.slice(0,40).map(pr=>
        '<div class="bx-item" data-bx-proposal="'+esc(pr.proposal_id)+'">'+
        '<div class="t">'+esc(_bxDescribe(pr))+'</div>'+
        '<div class="c">'+esc(pr.state)+' · '+esc(pr.mapping_basis)+'</div>'+
        '<div class="a">'+
        '<button data-bx-accept="'+esc(pr.proposal_id)+'"'+
        (pr.state==='BLOCKED'?' disabled':'')+'>Accept</button>'+
        '<button data-bx-reject="'+esc(pr.proposal_id)+'"'+
        (pr.state==='BLOCKED'?' disabled':'')+'>Reject</button>'+
        '</div></div>').join('');
      p.push('<div class="bx-sec" data-bx-section="PROPOSALS"><h4>Proposals ('+
        S.proposals.count+')</h4>'+(rows||'<div class="bx-note">None</div>')+
        '<div class="bx-note">acceptance only prepares an authoring command; '+
        'nothing is written until an explicit commit</div>'+
        '<button class="bx-btn pri" id="bxCommit" data-bx-action="commit">'+
        'Commit accepted through authoring</button></div>');
    }
    if(S.report){
      const r=S.report;
      p.push('<div class="bx-sec" data-bx-section="ROUNDTRIP"><h4>Round trip</h4>'+
        row('status',r.status,r.status)+
        row('semantic',r.semantic_fidelity)+row('geometry',r.geometry_fidelity)+
        row('relationship',r.relationship_fidelity)+
        row('property',r.property_fidelity)+
        row('losses',(r.losses||[]).length)+
        row('critical losses',r.critical_loss_count)+'</div>');
    }
    host.innerHTML=p.join('');
    Array.prototype.forEach.call(host.querySelectorAll('[data-bx-accept]'),el=>{
      el.onclick=()=>decide(el.getAttribute('data-bx-accept'),'ACCEPTED'); });
    Array.prototype.forEach.call(host.querySelectorAll('[data-bx-reject]'),el=>{
      el.onclick=()=>decide(el.getAttribute('data-bx-reject'),'REJECTED'); });
    const cb=$('bxCommit'); if(cb) cb.onclick=()=>{ try{ commit(); }catch(e){} }; }
  function _bxDescribe(d){
    const id=d.canonical_id||d.source_entity_id||'';
    if(d.change_type==='PROPERTY_CHANGED'||d.type==='PROPERTY_CHANGED')
      return id+' '+(d.field||'')+' '+String(d.old_value)+' → '+
        String(d.proposed_value);
    if(d.change_type==='OBJECT_RESIZED'||d.type==='OBJECT_RESIZED')
      return id+' '+(d.field||'')+' '+String(d.old_value)+' → '+
        String(d.proposed_value);
    if(d.change_type==='UNSUPPORTED_EXTERNAL_OBJECT'
       ||d.type==='UNSUPPORTED_EXTERNAL_OBJECT')
      return 'External '+String(d.proposed_value)+' unsupported';
    return (d.change_type||d.type)+' '+id; }
  function init(){
    const c=$('bxClose'); if(c) c.onclick=close;
    const e=$('bxExport'); if(e) e.onclick=()=>{ try{ exportBim(); }catch(x){} };
    const cm=$('bxCompare'); if(cm) cm.onclick=()=>{ try{ compare(); }catch(x){} };
    const pr=$('bxProposals'); if(pr) pr.onclick=proposals;
    const v=$('bxValidate'); if(v) v.onclick=validate;
    return true; }
  if(typeof document!=='undefined'&&document.addEventListener)
    document.addEventListener('DOMContentLoaded',init);
  return {attach:attach,state:state,open:open,close:close,init:init,render:render,
    loadStaging:loadStaging,exportBim:exportBim,compare:compare,
    proposals:proposals,decide:decide,commit:commit,roundtrip:roundtrip,
    validate:validate,project:()=>S.project,describe:_bxDescribe};
})();

if(typeof window!=='undefined'){
  window.ACS=window.ACS||{};
  window.ACS.bim={
    spec:()=>_bxCopy(ACS_BIM_SPEC),
    buildExchange:bxBuildExchange, validateExchange:bxValidateExchange,
    exportDescriptor:bxExportDescriptor, guid:bxIfcGuid,
    toMetres:bxToMetres, supportOf:bxSupportOf,
    unsafe:bxIsUnsafe, safeId:bxIsSafeId, safeKey:bxSafeKey,
    diff:bxImportDiff, proposals:bxImportProposals,
    setProposalState:bxSetProposalState, commit:bxCommitImport,
    importStaleness:bxImportStaleness, exportStaleness:bxExportStaleness,
    audit:bxAudit, stepParserInBrowser:BX_STEP_PARSER_IN_BROWSER, panel:BX};
}
"""


def _fail(msg):
    raise SystemExit("%s: %s" % (os.path.basename(__file__), msg))


def _read(path):
    if not os.path.exists(path):
        _fail("target file not found: %s\n"
              "  after F-09 the generated blocks live in the modules under "
              "public/app/ (layout: tools/app_source.py).\n"
              "  restore the file (or fix the layout) before regenerating."
              % path)
    with io.open(path, encoding="utf-8") as f:
        return f.read()


def _splice(path, begin, end, block):
    """يستبدل ما بين العلامتين وحدهما ويُبقي كل ما عداهما بايتاً ببايت."""
    src = _read(path)
    nb, ne = src.count(begin), src.count(end)
    if nb != 1 or ne != 1:
        _fail("marker pair not usable in %s: %d opening, %d closing "
              "(each must appear exactly once).\n  opening: %s\n  closing: %s"
              % (path, nb, ne, begin, end))
    a = src.index(begin)
    b = src.index(end) + len(end)
    if b <= a:
        _fail("closing marker precedes opening marker in %s: %s" % (path, end))
    out = src[:a] + block + src[b:]
    if out == src:
        action = "unchanged"
    else:
        with io.open(path, "w", encoding="utf-8") as f:
            f.write(out)
        action = "rewritten"
    print("  %-9s %s  block=%d bytes  file=%d bytes"
          % (action, os.path.relpath(path, ROOT),
             len(block.encode("utf-8")), len(out.encode("utf-8"))))
    return action


def build():
    with open(SPEC_PATH, "r", encoding="utf-8") as f:
        spec = json.load(f)
    body = BODY.replace("__SPEC__", json.dumps(spec, ensure_ascii=False,
                                               separators=(",", ":")))
    js_block = JS_BEGIN + "\n" + body + "\n" + JS_END
    css_block = CSS_BEGIN + "\n" + CSS + "\n" + CSS_END
    dom_block = DOM_BEGIN + "\n" + DOM + "\n" + DOM_END
    print("bim exchange:")
    _splice(CSS_TARGET, CSS_BEGIN, CSS_END, css_block)
    _splice(PAGE, DOM_BEGIN, DOM_END, dom_block)
    _splice(JS_TARGET, JS_BEGIN, JS_END, js_block)


if __name__ == "__main__":
    build()
