# -*- coding: utf-8 -*-
"""يحقن طبقة الجودة البصرية (المرحلة 9.1) في public/index.html.

كتلتان بحدّ معلَن بينهما:
1) كتلة كلاسيكية (تُستخرَج للاختبارات): مرآة المواصفة حرفياً + الدوالّ الحتمية
   pq* التي تُقارَن بايت-بايت مع بايثون + لوحة الإعدادات.
2) جسر داخل سكربت الوحدة (module) حيث يعيش THREE والمشهد: يطبّق الإعدادات على
   العرض الحيّ، قابلاً للعكس، ولا يلمس النموذج القانوني إطلاقاً. غياب THREE
   (كما في صندوق البناء) يعيد رفضاً مصنَّفاً PQ_THREE_UNAVAILABLE — لا انهيار.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SPEC_PATH = os.path.join(ROOT, "acs_pbr.json")
PAGE = os.path.join(ROOT, "public", "index.html")

JS_BEGIN = "/* ===== ACS PBR QUALITY (generated by tools/build_pbr_browser.py) ===== */"
JS_END = "/* ===== END ACS PBR QUALITY ===== */"
JS_ANCHOR = "/* ===== END ACS DOCUMENTATION ===== */"

CSS_BEGIN = "/* ===== ACS PBR STYLES (generated) ===== */"
CSS_END = "/* ===== END ACS PBR STYLES ===== */"
CSS_ANCHOR = "</style>"

DOM_BEGIN = "<!-- ===== ACS PBR DOM (generated) ===== -->"
DOM_END = "<!-- ===== END ACS PBR DOM ===== -->"
DOM_ANCHOR = "</body>"

BRIDGE_SENTINEL_A = "/* ===== ACS PBR BRIDGE (module scope) ===== */"
BRIDGE_SENTINEL_B = "/* ===== END ACS PBR BRIDGE ===== */"
BRIDGE_ANCHOR = "function setSun(elev,azi){"
LOOP_OLD = "  renderer.render(scene,camera);\n});"
LOOP_NEW = ("  if(window.__ACS_PQ__&&window.__ACS_PQ__.composer&&"
            "!renderer.xr.isPresenting){window.__ACS_PQ__.composer.render();}"
            "else{renderer.render(scene,camera);}\n});")

CSS = r""".pq-panel{position:fixed;inset-block-end:0;inset-inline-end:0;width:min(96vw,360px);
  max-height:82vh;background:var(--ws-panel);border:1px solid var(--ws-line);
  border-start-start-radius:12px;color:var(--ws-txt);z-index:64;display:none;
  grid-template-rows:auto 1fr auto;
  font:13px/1.5 system-ui,-apple-system,"Segoe UI",Tahoma,sans-serif}
.pq-panel.on{display:grid}
.pq-panel *{box-sizing:border-box;min-width:0}
.pq-head{display:flex;align-items:center;gap:8px;padding:10px 12px;
  border-bottom:1px solid var(--ws-line);min-height:var(--ws-hit)}
.pq-head h3{margin:0;font-size:13px;letter-spacing:.4px;text-transform:uppercase;
  color:var(--ws-dim)}
.pq-body{overflow:auto;padding:10px 12px}
.pq-foot{display:flex;gap:8px;padding:10px 12px;border-top:1px solid var(--ws-line);
  flex-wrap:wrap}
.pq-btn{border:1px solid var(--ws-line);background:var(--ws-panel2);color:var(--ws-txt);
  border-radius:9px;padding:0 14px;min-height:var(--ws-hit);cursor:pointer;font-size:13px}
.pq-btn.pri{background:var(--ws-accent);border-color:var(--ws-accent);color:#06101d}
.pq-field{display:flex;gap:8px;align-items:center;padding:4px 0}
.pq-field label{color:var(--ws-dim);font-size:11px;flex:0 0 108px}
.pq-field select,.pq-field input[type=range]{flex:1;min-height:var(--ws-hit);
  background:var(--ws-panel2);color:var(--ws-txt);border:1px solid var(--ws-line);
  border-radius:7px;padding:0 8px;font-size:12px}
.pq-field input[type=checkbox]{width:20px;height:20px}
.pq-note{color:var(--ws-dim);font-size:11px;margin-top:6px}
.pq-status{font-size:11px;padding:4px 8px;border:1px solid var(--ws-line);
  border-radius:7px;margin-top:8px;overflow-wrap:anywhere}
@media (max-width:520px){.pq-panel{width:100vw}.pq-field label{flex:0 0 84px}}
"""

DOM = r"""<aside class="pq-panel" id="pqPanel" role="dialog" aria-label="Visual quality"
  data-pq="panel">
  <div class="pq-head">
    <h3 id="pqTitle">Visual quality</h3>
    <span style="flex:1"></span>
    <button class="pq-btn" id="pqClose" aria-label="Close visual quality">✕</button>
  </div>
  <div class="pq-body" id="pqBody"></div>
  <div class="pq-foot">
    <button class="pq-btn pri" id="pqApply" data-pq-action="APPLY">Apply</button>
    <button class="pq-btn" id="pqCapture" data-pq-action="CAPTURE">Screenshot</button>
  </div>
</aside>
"""

BODY = r"""
const ACS_PBR_SPEC = __SPEC__;

const PQ_LIMITS = ACS_PBR_SPEC.limits;
const PQ_ISSUES = ACS_PBR_SPEC.issue_codes;
const PQ_BLOCKING = ACS_PBR_SPEC.blocking_issue_codes;
const PQ_MATERIALS = (function(){ const m={};
  ACS_PBR_SPEC.materials.forEach(x=>{ m[x.id]=x; }); return m; })();
const PQ_LIGHTING = ACS_PBR_SPEC.lighting_presets;
const PQ_QUALITY = ACS_PBR_SPEC.quality_profiles;
const PQ_REQ = ACS_PBR_SPEC.quality_requirements;
const PQ_CHAIN = ACS_PBR_SPEC.quality_fallback_chain;
const PQ_SHADOWS = ACS_PBR_SPEC.shadow_tiers;
const PQ_CAMERAS = ACS_PBR_SPEC.camera_presets;
const PQ_ENVS = ACS_PBR_SPEC.environment_modes;
const PQ_MAT_MAP = ACS_PBR_SPEC.engineering_material_map;
const PQ_OVERRIDABLE = ['base_color','roughness','metalness','opacity',
  'transmission','ior','thickness_m','emissive','emissive_intensity',
  'normal_scale','texture_scale_m'];

function _pqQ(v){ return _pyRound(Number(v),6)+0; }
function _pqNum(v){
  if(v===null||v===undefined||typeof v==='boolean') return null;
  const n=Number(v); if(!isFinite(n)) return null; return n; }
function _pqSha16(o){ return sha256Hex(ingestCanonicalJson(o)).slice(0,16); }

function pqIssue(code,severity,elementId,message){
  if(PQ_ISSUES.indexOf(code)<0)
    throw new Error('undeclared pbr issue code: '+code);
  return {code:code,severity:severity,element_id:elementId,message:message,
    blocking:PQ_BLOCKING.indexOf(code)>=0}; }

function pqSafeKey(k){
  if(typeof k!=='string'||!k||k.length>64) return false;
  if(ACS_PBR_SPEC.forbidden_property_keys.indexOf(k)>=0) return false;
  return /^[A-Za-z_][A-Za-z0-9_]*$/.test(k); }

/* ------------------------------------------------------------- الخامات */
function pqMaterial(mid,override){
  if(!(mid in PQ_MATERIALS))
    return {valid:false,material:null,issues:[pqIssue('PQ_INVALID_MATERIAL',
      'ERROR',mid,'presentation material is not declared')]};
  const base=PQ_MATERIALS[mid];
  const issues=[]; const out={}; const prov={};
  PQ_OVERRIDABLE.forEach(k=>{ out[k]=(base[k]===undefined)?null:base[k];
    prov[k]='PRESENTATION_DEFAULT'; });
  const ov=(override&&typeof override==='object')?override:{};
  if(Object.keys(ov).length>Number(PQ_LIMITS.max_override_fields))
    return {valid:false,material:null,issues:[pqIssue('PQ_INVALID_OVERRIDE',
      'ERROR',mid,'too many override fields')]};
  Object.keys(ov).sort(_scmp).forEach(k=>{
    if(!pqSafeKey(k)){
      issues.push(pqIssue('PQ_PROPERTY_REFUSED','WARNING',k,
        'the override key is refused')); return; }
    if(PQ_OVERRIDABLE.indexOf(k)<0){
      issues.push(pqIssue('PQ_INVALID_OVERRIDE','WARNING',k,
        'this field is not visually overridable')); return; }
    const v=ov[k];
    if(k==='base_color'||k==='emissive'){
      if(!(typeof v==='string'&&v.length===7&&v.charAt(0)==='#'
        &&/^[0-9a-fA-F]{6}$/.test(v.slice(1)))){
        issues.push(pqIssue('PQ_INVALID_OVERRIDE','WARNING',k,
          'not a hex colour')); return; }
      out[k]=v.toLowerCase();
    } else {
      const n=_pqNum(v);
      if(n===null||n<0||n>20){
        issues.push(pqIssue('PQ_INVALID_OVERRIDE','WARNING',k,
          'not a finite value in range')); return; }
      out[k]=_pqQ(n); }
    prov[k]='USER_VISUAL_OVERRIDE'; });
  const resolved={};
  Object.keys(base).forEach(k=>{ resolved[k]=base[k]; });
  Object.keys(out).forEach(k=>{ resolved[k]=out[k]; });
  resolved.provenance=prov; resolved.visual_only=true;
  resolved.engineering_authority=false; resolved.writes_to_model=false;
  return {valid:true,material:resolved,issues:issues}; }

function pqMaterialForEngineering(name){
  const mid=(name in PQ_MAT_MAP)?PQ_MAT_MAP[name]:null;
  if(mid===null) return {mapped:false,material_id:null,
    policy:ACS_PBR_SPEC.unmapped_material_policy};
  return {mapped:true,material_id:mid,policy:'MAPPED'}; }

/* ------------------------------------------------------------- الإضاءة */
function pqLighting(preset){
  if(!(preset in PQ_LIGHTING))
    return {valid:false,lighting:null,issues:[pqIssue('PQ_INVALID_PRESET',
      'ERROR',preset,'lighting preset is not declared')]};
  const src=PQ_LIGHTING[preset];
  const cfg={};
  Object.keys(src).forEach(k=>{ cfg[k]=src[k]; });
  cfg.preset=preset;
  cfg.fills=(src.fills||[]).slice(0,Number(PQ_LIMITS.max_fill_lights))
    .map(f=>{ const g={}; Object.keys(f).forEach(k=>{ g[k]=f[k]; });
      g.visual_only=true; return g; });
  cfg.mep_fixture_reused=false; cfg.visual_only=true;
  return {valid:true,lighting:cfg,issues:[]}; }

function pqExposureClamp(v){
  const n=_pqNum(v);
  if(n===null) return {value:null,clamped:false,
    issues:[pqIssue('PQ_INVALID_EXPOSURE','ERROR',v,
      'exposure is not a finite number')]};
  const lo=Number(ACS_PBR_SPEC.exposure_min), hi=Number(ACS_PBR_SPEC.exposure_max);
  const c=Math.min(Math.max(n,lo),hi);
  return {value:_pqQ(c),clamped:c!==n,issues:[]}; }

/* ------------------------------------------------------------- الظلال */
function pqShadowConfig(tier,bounds){
  if(!(tier in PQ_SHADOWS))
    return {valid:false,shadow:null,issues:[pqIssue('PQ_INVALID_PROFILE',
      'ERROR',tier,'shadow tier is not declared')]};
  const t=PQ_SHADOWS[tier];
  const b=(bounds&&typeof bounds==='object')?bounds:{};
  let r=_pqNum(b.radius);
  if(r===null||r<=0) r=25.0;
  const m=Number(ACS_PBR_SPEC.shadow_camera_margin);
  const e=_pqQ(r*m);
  return {valid:true,issues:[],shadow:{tier:tier,map_size:Math.trunc(t.map_size),
    bias:t.bias,normal_bias:t.normal_bias,radius_px:t.radius,
    type:ACS_PBR_SPEC.shadow_type,
    camera:{left:-e,right:e,top:e,bottom:-e,near:0.5,far:_pqQ(4.0*e)},
    bounds_radius_m:_pqQ(r),margin:m,hardcoded_size:false}}; }

/* ------------------------------------------------------------- الجودة */
function pqCapabilitiesNormalise(caps){
  const c=(caps&&typeof caps==='object')?caps:{};
  const mt=_pqNum(c.max_texture_size);
  const pr=_pqNum(c.device_pixel_ratio);
  return {webgl2:!!c.webgl2,
    max_texture_size:mt?Math.trunc(mt):2048,
    device_pixel_ratio:_pqQ(Math.min(pr?pr:1.0,
      Number(PQ_LIMITS.max_pixel_ratio)))}; }

function _pqMeets(profile,caps){
  const req=PQ_REQ[profile];
  if(req.webgl2&&!caps.webgl2) return false;
  return caps.max_texture_size>=Math.trunc(req.min_max_texture_size); }

function pqQuality(profile,caps){
  if(!(profile in PQ_QUALITY))
    return {valid:false,quality:null,issues:[pqIssue('PQ_INVALID_PROFILE',
      'ERROR',profile,'quality profile is not declared')]};
  const c=pqCapabilitiesNormalise(caps);
  const issues=[];
  const chain=PQ_CHAIN.slice();
  const idx=chain.indexOf(profile);
  let effective=null;
  for(let i=idx;i<chain.length;i++){
    if(_pqMeets(chain[i],c)){ effective=chain[i]; break; }
    issues.push(pqIssue('PQ_FALLBACK_APPLIED','INFO',chain[i],
      'capability requirement not met; degrading')); }
  if(effective===null) effective='PERFORMANCE';
  const src=PQ_QUALITY[effective];
  const cfg={};
  Object.keys(src).forEach(k=>{ cfg[k]=src[k]; });
  cfg.requested=profile; cfg.effective=effective;
  cfg.degraded=effective!==profile;
  cfg.pixel_ratio=_pqQ(Math.min(c.device_pixel_ratio,
    Number(cfg.pixel_ratio_max)));
  cfg.auto_max_profile=ACS_PBR_SPEC.auto_max_profile;
  cfg.blank_viewport_allowed=false;
  return {valid:true,quality:cfg,issues:issues}; }

function pqAutoProfile(caps){
  const c=pqCapabilitiesNormalise(caps);
  const cap=ACS_PBR_SPEC.auto_max_profile;
  const chain=PQ_CHAIN.slice();
  for(let i=chain.indexOf(cap);i<chain.length;i++)
    if(_pqMeets(chain[i],c))
      return {profile:chain[i],auto:true,ultra_auto_selected:false};
  return {profile:'PERFORMANCE',auto:true,ultra_auto_selected:false}; }

/* ------------------------------------------------------------ الكاميرا */
function pqCamera(preset,bounds){
  if(!(preset in PQ_CAMERAS))
    return {valid:false,camera:null,issues:[pqIssue('PQ_INVALID_PRESET',
      'ERROR',preset,'camera preset is not declared')]};
  const p=PQ_CAMERAS[preset];
  const b=(bounds&&typeof bounds==='object')?bounds:{};
  const cx=_pqNum(b.cx)||0.0, cy=_pqNum(b.cy)||0.0, cz=_pqNum(b.cz)||0.0;
  let r=_pqNum(b.radius);
  if(r===null||r<=0) r=20.0;
  const fov=Math.min(Math.max(Number(p.fov),Number(ACS_PBR_SPEC.fov_min)),
    Number(ACS_PBR_SPEC.fov_max));
  const az=Number(p.azimuth_deg)*Math.PI/180.0;
  const el=Number(p.elevation_deg)*Math.PI/180.0;
  const d=r*Number(p.distance_factor);
  const eyeH=(p.eye_height_m===undefined)?null:p.eye_height_m;
  const px=cx+d*Math.cos(el)*Math.sin(az);
  const pz=cz+d*Math.cos(el)*Math.cos(az);
  let py=cy+d*Math.sin(el);
  let ty=cy;
  if(p.target==='EYE'&&eyeH!==null){
    const baseY=_pqNum(b.min_y)||0.0;
    py=baseY+Number(eyeH); ty=baseY+Number(eyeH); }
  return {valid:true,issues:[],camera:{preset:preset,fov:_pqQ(fov),
    position:[_pqQ(px),_pqQ(py),_pqQ(pz)],target:[_pqQ(cx),_pqQ(ty),_pqQ(cz)],
    bounds_radius_m:_pqQ(r),deterministic:true,fisheye:false}}; }

/* ------------------------------------------------------------- البيئة */
function pqEnvironment(mode){
  if(!(mode in PQ_ENVS))
    return {valid:false,environment:null,issues:[pqIssue(
      'PQ_INVALID_ENVIRONMENT','ERROR',mode,
      'environment mode is not declared')]};
  const src=PQ_ENVS[mode]; const e={};
  Object.keys(src).forEach(k=>{ e[k]=src[k]; });
  e.mode=mode; e.remote_fetch=false; e.changes_geometry=false;
  return {valid:true,environment:e,issues:[]}; }

/* ------------------------------------------------------------ المسارات */
function pqTexturePathOk(path){
  const pol=ACS_PBR_SPEC.texture_policy;
  if(typeof path!=='string'||!path)
    return {ok:false,issues:[pqIssue('PQ_UNSAFE_ASSET_PATH','ERROR',path,
      'empty asset path')]};
  if(path.length>Number(PQ_LIMITS.max_asset_path_length))
    return {ok:false,issues:[pqIssue('PQ_UNSAFE_ASSET_PATH','ERROR',
      path.slice(0,40),'asset path too long')]};
  if(path.indexOf('://')>=0||path.indexOf('//')===0)
    return {ok:false,issues:[pqIssue('PQ_REMOTE_ASSET_REFUSED','ERROR',
      path.slice(0,40),'remote assets are refused')]};
  if(!(new RegExp(pol.safe_asset_pattern)).test(path))
    return {ok:false,issues:[pqIssue('PQ_UNSAFE_ASSET_PATH','ERROR',
      path.slice(0,40),'path is outside the allowed asset root')]};
  const listed=pol.local_texture_sets.some(
    s=>((s.files||[]).indexOf(path)>=0));
  if(!listed)
    return {ok:false,listed:false,issues:[pqIssue('PQ_UNSAFE_ASSET_PATH',
      'WARNING',path.slice(0,40),
      'path is shaped correctly but not in the declared texture set; '+
      'procedural fallback is used instead')]};
  return {ok:true,listed:true,issues:[]}; }

/* --------------------------------------------------------- الإعداد الكلّي */
function pqConfig(profile,lightingPreset,materialsMode,environmentMode,
  exposure,overrides,caps,bounds){
  const issues=[];
  const q=pqQuality(profile||'BALANCED',caps);
  if(!q.valid) return {valid:false,config:null,issues:q.issues};
  q.issues.forEach(i=>issues.push(i));
  const lp=lightingPreset||'CLEAR_NOON';
  const lg=pqLighting(lp);
  if(!lg.valid) return {valid:false,config:null,issues:lg.issues};
  const mm=materialsMode||ACS_PBR_SPEC.default_materials_mode;
  if(ACS_PBR_SPEC.materials_modes.indexOf(mm)<0)
    return {valid:false,config:null,issues:[pqIssue('PQ_INVALID_MODE','ERROR',
      mm,'materials mode is not declared')]};
  const em=environmentMode||q.quality.environment;
  const ev=pqEnvironment(em);
  if(!ev.valid) return {valid:false,config:null,issues:ev.issues};
  const ex=pqExposureClamp((exposure===null||exposure===undefined)
    ?lg.lighting.exposure:exposure);
  if(ex.value===null) return {valid:false,config:null,issues:ex.issues};
  const sh=pqShadowConfig(q.quality.shadow_tier,bounds);
  sh.issues.forEach(i=>issues.push(i));
  const ovOut={};
  Object.keys(overrides||{}).sort(_scmp).forEach(mid=>{
    if(!(mid in PQ_MATERIALS)){
      issues.push(pqIssue('PQ_INVALID_MATERIAL','WARNING',mid,
        'override for an undeclared material')); return; }
    const r=pqMaterial(mid,(overrides||{})[mid]);
    r.issues.forEach(i=>issues.push(i));
    if(r.valid){
      const rec={};
      PQ_OVERRIDABLE.forEach(k=>{ rec[k]=r.material[k]; });
      rec.provenance=r.material.provenance;
      ovOut[mid]=rec; } });
  const cfg={schema:ACS_PBR_SPEC.schema,version:ACS_PBR_SPEC.version,
    quality:q.quality,lighting:lg.lighting,materials_mode:mm,
    environment:ev.environment,exposure:ex.value,
    exposure_clamped:ex.clamped,shadow:sh.valid?sh.shadow:null,
    material_overrides:ovOut,tone_mapping:ACS_PBR_SPEC.tone_mapping,
    output_color_space:ACS_PBR_SPEC.output_color_space,
    ground_context_enabled:ACS_PBR_SPEC.ground_context.enabled_default,
    writes_to_model:false,visual_only:true};
  cfg.presentation_config_hash=_pqSha16(cfg);
  return {valid:true,config:cfg,issues:issues}; }

function pqCaptureMetadata(cfg,modelHash,widthPx,heightPx,generatedAt){
  const w=_pqNum(widthPx), h=_pqNum(heightPx);
  const mx=Number(ACS_PBR_SPEC.capture.max_dimension_px);
  if(w===null||h===null||w<=0||h<=0||w>mx||h>mx)
    return {valid:false,metadata:null,issues:[pqIssue('PQ_INVALID_RESOLUTION',
      'ERROR',[widthPx,heightPx],'capture resolution is out of range')]};
  const c=cfg||{};
  const md={type:ACS_PBR_SPEC.capture.type,
    camera_preset:(c.camera_preset===undefined)?null:c.camera_preset,
    quality_profile:((c.quality||{}).effective===undefined)?null
      :(c.quality||{}).effective,
    lighting_preset:((c.lighting||{}).preset===undefined)?null
      :(c.lighting||{}).preset,
    materials_mode:(c.materials_mode===undefined)?null:c.materials_mode,
    environment:((c.environment||{}).mode===undefined)?null
      :(c.environment||{}).mode,
    exposure:(c.exposure===undefined)?null:c.exposure,
    model_hash:(modelHash===undefined)?null:modelHash,
    presentation_config_hash:(c.presentation_config_hash===undefined)?null
      :c.presentation_config_hash,
    width_px:Math.trunc(w),height_px:Math.trunc(h),
    generated_at:(generatedAt===undefined)?null:generatedAt,
    is_engineering_evidence:false};
  return {valid:true,metadata:md,issues:[]}; }

/* ------------------ حدود العرض والقصّ (علاج الشاشة السوداء) ------------- */
const PQ_VB = ACS_PBR_SPEC.viewport_bounds;
const PQ_CLIP = ACS_PBR_SPEC.camera_clip;
const PQ_VIEWPORT_CONTRACT = ACS_PBR_SPEC.viewport_contract_version;

function pqBoundsMember(desc){
  const d=(desc&&typeof desc==='object')?desc:{};
  const name=(typeof d.name==='string')?d.name:'';
  const parents=(d.parent_names||[]).filter(x=>typeof x==='string');
  const flags=(d.user_data&&typeof d.user_data==='object')?d.user_data:{};
  if(!d.is_mesh) return {included:false,reason:'NOT_A_MESH'};
  for(let i=0;i<PQ_VB.excluded_userdata_flags.length;i++){
    const f=PQ_VB.excluded_userdata_flags[i];
    if(flags[f]) return {included:false,reason:'PRESENTATION_FLAG:'+f}; }
  const chain=[name].concat(parents);
  for(let i=0;i<chain.length;i++){
    const n=chain[i];
    if(PQ_VB.excluded_object_names.indexOf(n)>=0)
      return {included:false,reason:'EXCLUDED_NAME:'+n};
    for(let j=0;j<PQ_VB.excluded_name_prefixes.length;j++){
      const pre=PQ_VB.excluded_name_prefixes[j];
      if(n.slice(0,pre.length)===pre)
        return {included:false,reason:'EXCLUDED_PREFIX:'+pre}; } }
  const root=PQ_VB.canonical_root_name, sep=PQ_VB.canonical_tag_separator;
  if(parents.indexOf(root)>=0||name===root)
    return {included:true,reason:'CANONICAL_ROOT'};
  if(name.indexOf(sep)>=0) return {included:true,reason:'CANONICAL_TAG'};
  if(PQ_VB.require_canonical_membership)
    return {included:false,reason:'NOT_CANONICAL_GEOMETRY'};
  return {included:true,reason:'DEFAULT'}; }

function pqBoundsFromDescriptors(objects){
  const mins=[null,null,null], maxs=[null,null,null];
  let used=0;
  (objects||[]).forEach(o=>{
    if(!pqBoundsMember(o).included) return;
    const box=(o&&typeof o==='object')?o.box:null;
    if(!(box&&typeof box==='object'&&Array.isArray(box.min)
      &&Array.isArray(box.max)&&box.min.length===3&&box.max.length===3))
      return;
    for(let i=0;i<3;i++)
      if(_pqNum(box.min[i])===null||_pqNum(box.max[i])===null) return;
    for(let i=0;i<3;i++){
      const a=_pqNum(box.min[i]), b=_pqNum(box.max[i]);
      mins[i]=(mins[i]===null)?a:Math.min(mins[i],a);
      maxs[i]=(maxs[i]===null)?b:Math.max(maxs[i],b); }
    used++; });
  if(!used) return {valid:false,bounds:null,member_count:0,
    issues:[pqIssue('PQ_BOUNDS_UNAVAILABLE','WARNING',null,
      'no canonical geometry is present in the scene')]};
  const size=[maxs[0]-mins[0],maxs[1]-mins[1],maxs[2]-mins[2]];
  return {valid:true,member_count:used,issues:[],bounds:{
    cx:_pqQ((mins[0]+maxs[0])/2.0),cy:_pqQ((mins[1]+maxs[1])/2.0),
    cz:_pqQ((mins[2]+maxs[2])/2.0),min_y:_pqQ(mins[1]),
    size:size.map(_pqQ),
    radius:_pqQ(Math.max(Math.max(size[0],Math.max(size[1],size[2]))/2.0,
      0.5))}}; }

function pqCameraClip(bounds,position){
  const b=(bounds&&typeof bounds==='object')?bounds:{};
  let r=_pqNum(b.radius);
  if(r===null||r<=0) r=20.0;
  const cx=_pqNum(b.cx)||0.0, cy=_pqNum(b.cy)||0.0, cz=_pqNum(b.cz)||0.0;
  const p=(Array.isArray(position)&&position.length===3)?position
    :[cx,cy+r,cz+r*2.0];
  let px=_pqNum(p[0])||0.0, py=_pqNum(p[1])||0.0, pz=_pqNum(p[2])||0.0;
  let dist=Math.sqrt(Math.pow(px-cx,2)+Math.pow(py-cy,2)+Math.pow(pz-cz,2));
  const issues=[];
  const skyLimit=Number(PQ_CLIP.sky_dome_radius_m)
    *Number(PQ_CLIP.max_distance_ratio_of_sky);
  let clamped=false;
  if(dist>skyLimit){
    const k=dist>0?(skyLimit/dist):0.0;
    px=cx+(px-cx)*k; py=cy+(py-cy)*k; pz=cz+(pz-cz)*k;
    dist=skyLimit; clamped=true;
    issues.push(pqIssue('PQ_CAMERA_CLAMPED','INFO',null,
      'camera distance clamped inside the sky dome')); }
  const near=Math.max(Number(PQ_CLIP.near_min),
    Math.min(dist*Number(PQ_CLIP.near_ratio_of_distance),
      Math.max(dist-r*1.5,Number(PQ_CLIP.near_min))));
  const far=Math.min(Math.max(dist+r*Number(PQ_CLIP.far_margin_factor),
    Number(PQ_CLIP.far_min)),Number(PQ_CLIP.far_max));
  return {valid:true,issues:issues,clip:{
    near:_pqQ(near),far:_pqQ(far),distance:_pqQ(dist),
    position:[_pqQ(px),_pqQ(py),_pqQ(pz)],
    clamped:clamped,inside_sky_dome:dist<=skyLimit,
    camera_inside_bounds:dist<=r,
    contains_model:!!(far>dist+r-1e-9
      &&(dist<=r||near<dist-r+1e-9))}}; }

function pqFrustumContains(cam,bounds){
  const c=(cam&&typeof cam==='object')?cam:{};
  const b=(bounds&&typeof bounds==='object')?bounds:{};
  const pos=c.position||[0.0,0.0,0.0], tgt=c.target||[0.0,0.0,0.0];
  const fov=_pqNum(c.fov)||50.0, aspect=_pqNum(c.aspect)||1.6;
  let near=_pqNum(c.near); near=(near===null)?0.05:near;
  let far=_pqNum(c.far); far=(far===null)?1000.0:far;
  const cx=_pqNum(b.cx)||0.0, cy=_pqNum(b.cy)||0.0, cz=_pqNum(b.cz)||0.0;
  let r=_pqNum(b.radius);
  if(r===null||r<=0) r=1.0;
  let fx=tgt[0]-pos[0], fy=tgt[1]-pos[1], fz=tgt[2]-pos[2];
  const flen=Math.sqrt(fx*fx+fy*fy+fz*fz)||1.0;
  fx/=flen; fy/=flen; fz/=flen;
  const vx=cx-pos[0], vy=cy-pos[1], vz=cz-pos[2];
  const depth=vx*fx+vy*fy+vz*fz;
  const dist=Math.sqrt(vx*vx+vy*vy+vz*vz);
  const insideBounds=dist<=r;
  const facing=depth>0||insideBounds;
  const halfV=(Number(fov)*Math.PI/180)/2.0;
  const halfH=Math.atan(Math.tan(halfV)*Number(aspect));
  const lat=Math.sqrt(Math.max(dist*dist-depth*depth,0.0));
  const inNearFar=(depth+r>near)&&(depth-r<far);
  const limitV=Math.abs(depth)*Math.tan(halfV)
    +r/Math.max(Math.cos(halfV),1e-6);
  const limitH=Math.abs(depth)*Math.tan(halfH)
    +r/Math.max(Math.cos(halfH),1e-6);
  let inCone=lat<=Math.max(limitV,limitH);
  let inClip=inNearFar;
  if(insideBounds){ inClip=true; inCone=true; }
  const inside=!!(facing&&inClip&&inCone);
  return {contains:inside,facing:facing,inside_bounds:!!insideBounds,
    depth:_pqQ(depth),
    distance:_pqQ(dist),lateral:_pqQ(lat),near:_pqQ(near),far:_pqQ(far),
    within_clip:!!inClip,within_cone:!!inCone,
    issues:inside?[]:[pqIssue('PQ_MODEL_OUT_OF_FRUSTUM','WARNING',null,
      'the model bounding sphere does not intersect the view frustum')]}; }

function pqMaterialSafe(mat){
  const m=(mat&&typeof mat==='object')?mat:{};
  const reasons=[];
  const col=m.base_color;
  if(!(typeof col==='string'&&col.length===7&&col.charAt(0)==='#'
    &&/^[0-9a-fA-F]{6}$/.test(col.slice(1)))) reasons.push('INVALID_COLOR');
  [['roughness',0.0,1.0],['metalness',0.0,1.0],['opacity',0.0,1.0],
   ['transmission',0.0,1.0]].forEach(t=>{
    const k=t[0];
    if(!(k in m)||m[k]===null) return;   /* غير مضبوط = آمن */
    const v=_pqNum(m[k]);
    if(v===null||v<t[1]||v>t[2])
      reasons.push('INVALID_'+k.toUpperCase()); });
  const op=_pqNum(m.opacity);
  if(m.opacity!==null&&m.opacity!==undefined&&op!==null&&op<=0.0)
    reasons.push('FULLY_TRANSPARENT');
  const safe=reasons.length===0;
  return {safe:safe,reasons:reasons,
    fallback:safe?null:'ENGINEERING_MATERIAL',
    issues:safe?[]:[pqIssue('PQ_MATERIAL_FAIL_OPEN','WARNING',
      (m.id===undefined)?null:m.id,
      'presentation material refused ('+reasons.join(',')
      +'); keeping the engineering material')]}; }

/* ------------------ عقد التحويلات والمحاذاة (المرحلة 9.2) --------------- */
const PQ_TC = ACS_PBR_SPEC.transform_contract;
const PQ_SPACES = PQ_TC.spaces;

function pqLevelBaseY(levelIndex,floorHeight){
  const i=_pqNum(levelIndex), fh=_pqNum(floorHeight);
  if(i===null||fh===null||fh<=0)
    return {valid:false,base_y:null,issues:[pqIssue('ALIGN_LEVEL_MISMATCH',
      'WARNING',String(levelIndex),
      'level index or floor height is not a finite positive number')]};
  return {valid:true,issues:[],base_y:_pqQ(i*fh),space:'BUILDING',
    applied_times:1}; }

function pqResolveTransform(desc){
  const d=(desc&&typeof desc==='object')?desc:{};
  const issues=[];
  const space=d.coordinate_space;
  const sid=(d.source_element_id===undefined)?null:d.source_element_id;
  if(PQ_SPACES.indexOf(space)<0)
    return {resolved:false,world:null,coordinate_space:(space===undefined)
      ?null:space,provenance:'UNRESOLVED',
      issues:[pqIssue('ALIGN_TRANSFORM_UNRESOLVED','WARNING',sid,
        'undeclared coordinate space')]};
  const local=d.local;
  const fin=v=>Array.isArray(v)&&v.length===3
    &&v.every(x=>_pqNum(x)!==null);
  if(!fin(local))
    return {resolved:false,world:null,coordinate_space:space,
      provenance:'UNRESOLVED',
      issues:[pqIssue('ALIGN_TRANSFORM_UNRESOLVED','WARNING',sid,
        'local transform is missing or not finite')]};
  const lx=_pqNum(local[0]), ly=_pqNum(local[1]), lz=_pqNum(local[2]);
  const host=d.host_origin;
  const needsHost=(space==='HOST_LOCAL'||space==='OBJECT_LOCAL');
  let hx=0.0,hy=0.0,hz=0.0;
  if(needsHost){
    if(!fin(host))
      return {resolved:false,world:null,coordinate_space:space,
        provenance:'UNRESOLVED',
        issues:[pqIssue('ALIGN_HOST_NOT_FOUND','WARNING',sid,
          'a HOST_LOCAL transform without a resolvable host origin is '
          +'never placed at the origin')]};
    hx=_pqNum(host[0]); hy=_pqNum(host[1]); hz=_pqNum(host[2]); }
  const lev=(d.level_index===undefined)?null:d.level_index;
  let base=0.0;
  if(lev!==null&&lev!==undefined){
    const r=pqLevelBaseY(lev,d.floor_height);
    if(!r.valid) return {resolved:false,world:null,coordinate_space:space,
      provenance:'UNRESOLVED',issues:r.issues};
    base=r.base_y; }
  if(d.host_origin_includes_level&&lev!==null&&lev!==undefined){
    base=0.0;
    issues.push(pqIssue('ALIGN_DOUBLE_TRANSFORM','INFO',sid,
      'the host origin already carries the level elevation; it was not '
      +'added a second time')); }
  return {resolved:true,world:[_pqQ(hx+lx),_pqQ(hy+ly+base),_pqQ(hz+lz)],
    issues:issues,source_element_id:sid,coordinate_space:space,
    parent_space:(PQ_TC.space_parents[space]===undefined)?null
      :PQ_TC.space_parents[space],
    local:[_pqQ(lx),_pqQ(ly),_pqQ(lz)],
    host_id:(d.host_id===undefined)?null:d.host_id,
    level_id:(d.level_id===undefined)?null:d.level_id,
    level_elevation:_pqQ(base),
    provenance:d.presentation?'PRESENTATION_DERIVED':'CANONICAL',
    level_applied_times:(lev===null||lev===undefined)?0:1,
    host_applied_times:needsHost?1:0}; }

function pqPlateRect(roomRects,siteRect){
  const rects=(roomRects||[]).filter(r=>Array.isArray(r)&&r.length===4
    &&r.every(v=>_pqNum(v)!==null)&&_pqNum(r[2])>0&&_pqNum(r[3])>0);
  if(!rects.length){
    const s=(Array.isArray(siteRect)&&siteRect.length===4)?siteRect:null;
    if(s===null||s.some(v=>_pqNum(v)===null))
      return {valid:false,rect:null,source:'UNRESOLVED',
        issues:[pqIssue('ALIGN_TRANSFORM_UNRESOLVED','WARNING','plate',
          'neither rooms nor a site rectangle are available')]};
    return {valid:true,rect:s.map(v=>_pqQ(_pqNum(v))),
      source:'SITE_FALLBACK',issues:[]}; }
  let x0=Infinity,z0=Infinity,x1=-Infinity,z1=-Infinity;
  rects.forEach(r=>{
    x0=Math.min(x0,_pqNum(r[0])); z0=Math.min(z0,_pqNum(r[1]));
    x1=Math.max(x1,_pqNum(r[0])+_pqNum(r[2]));
    z1=Math.max(z1,_pqNum(r[1])+_pqNum(r[3])); });
  return {valid:true,issues:[],source:'LEVEL_ROOM_UNION',
    rect:[_pqQ(x0),_pqQ(z0),_pqQ(x1-x0),_pqQ(z1-z0)],
    room_count:rects.length}; }

function pqRackBlock(roomRect,rack){
  const rr=(Array.isArray(roomRect)&&roomRect.length===4)?roomRect:null;
  if(rr===null||rr.some(v=>_pqNum(v)===null))
    return {valid:false,block:null,
      issues:[pqIssue('ALIGN_HOST_NOT_FOUND','WARNING','rack',
        'the hosting room rectangle is missing')]};
  const R=(rack&&typeof rack==='object')?rack:{};
  const rx=_pqNum(rr[0]), rz=_pqNum(rr[1]), rw=_pqNum(rr[2]), rd=_pqNum(rr[3]);
  let ox=_pqNum(R.x); ox=(ox===null)?0.0:ox;
  let oz=_pqNum(R.z); oz=(oz===null)?0.0:oz;
  ox=Math.min(Math.max(ox,0.0),rw);
  oz=Math.min(Math.max(oz,0.0),rd);
  const availW=Math.max(rw-ox,0.0), availD=Math.max(rd-oz,0.0);
  let w=_pqNum(R.w), d=_pqNum(R.d);
  w=(w===null||w<=0)?availW:Math.min(w,availW);
  d=(d===null||d<=0)?availD:Math.min(d,availD);
  const issues=[];
  if(availW<=0||availD<=0)
    issues.push(pqIssue('ALIGN_OBJECT_OUTSIDE_HOST','WARNING','rack',
      'the declared rack offset leaves no room extent'));
  return {valid:true,issues:issues,block:{
    x:_pqQ(rx+ox),z:_pqQ(rz+oz),w:_pqQ(w),d:_pqQ(d),
    room_far_x:_pqQ(rx+rw),room_far_z:_pqQ(rz+rd),
    within_room:!!(rx+ox+w<=rx+rw+1e-9&&rz+oz+d<=rz+rd+1e-9),
    offset_applied_times:1}}; }

function pqContainment(childBox,hostBox,tolerance){
  let tol=_pqNum(tolerance);
  if(tol===null) tol=Number(PQ_TC.containment_tolerance_m);
  const ok=b=>(b&&typeof b==='object'
    &&['min','max'].every(k=>Array.isArray(b[k])&&b[k].length===3
      &&b[k].every(v=>_pqNum(v)!==null)));
  if(!(ok(childBox)&&ok(hostBox)))
    return {classification:'UNRESOLVED',overlap:null,
      issues:[pqIssue('ALIGN_TRANSFORM_UNRESOLVED','WARNING',null,
        'a world-space box is missing')]};
  const cmin=childBox.min.map(_pqNum), cmax=childBox.max.map(_pqNum);
  const hmin=hostBox.min.map(_pqNum), hmax=hostBox.max.map(_pqNum);
  let inside=true, disjoint=false;
  for(let i=0;i<3;i++){
    if(!(cmin[i]>=hmin[i]-tol&&cmax[i]<=hmax[i]+tol)) inside=false;
    if(cmin[i]>hmax[i]+tol||cmax[i]<hmin[i]-tol) disjoint=true; }
  const cls=inside?'INSIDE':(disjoint?'OUTSIDE':'INTERSECTING_BOUNDARY');
  const out=[0,1,2].map(i=>_pqQ(Math.max(0.0,
    Math.min(cmax[i],hmax[i])-Math.max(cmin[i],hmin[i]))));
  return {classification:cls,overlap:out,tolerance:_pqQ(tol),
    moved_to_fit:false,
    issues:(cls==='INSIDE'||cls==='INTERSECTING_BOUNDARY')?[]
      :[pqIssue('ALIGN_OBJECT_OUTSIDE_HOST','WARNING',null,
        'the object lies outside its host; it is reported, never '
        +'snapped')]}; }

function pqRoofAlignment(topLevelIndex,floorHeight,roofBaseY,tolerance){
  let tol=_pqNum(tolerance);
  if(tol===null) tol=Number(PQ_TC.roof_tolerance_m);
  const ti=_pqNum(topLevelIndex);
  const exp=pqLevelBaseY((ti===null?0:ti)+1,floorHeight);
  if(!exp.valid) return {aligned:false,expected_y:null,error_m:null,
    issues:exp.issues};
  const got=_pqNum(roofBaseY);
  if(got===null) return {aligned:false,expected_y:exp.base_y,error_m:null,
    issues:[pqIssue('ALIGN_TRANSFORM_UNRESOLVED','WARNING','roof',
      'the roof base elevation is not a finite number')]};
  const err=Math.abs(got-exp.base_y);
  const aligned=err<=tol;
  return {aligned:!!aligned,expected_y:exp.base_y,actual_y:_pqQ(got),
    error_m:_pqQ(err),tolerance:_pqQ(tol),presentation_offset_used:false,
    issues:aligned?[]:[pqIssue('ALIGN_ROOF_DETACHED','WARNING','roof',
      'the roof sits '+err.toFixed(3)+' m from its canonical elevation; it '
      +'is reported, never lowered by a presentation offset')]}; }
"""

PANEL = r"""
/* ===================== لوحة الجودة البصرية (§19) ======================== */
const PQ = (function(){
  const S={lang:'en',profile:'BALANCED',lighting:'CLEAR_NOON',
    materials:'ENGINEERING',environment:'SKY',shadows:true,ao:false,
    exposure:null,last:null,capture:null};
  const $=id=>(typeof document!=='undefined')?document.getElementById(id):null;
  const esc=s=>String(s===null||s===undefined?'':s).replace(/&/g,'&amp;')
    .replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')
    .replace(/'/g,'&#39;');
  function T(k){
    const t=ACS_PBR_SPEC.ui_labels[S.lang]||ACS_PBR_SPEC.ui_labels.en;
    return t[k]||ACS_PBR_SPEC.ui_labels.en[k]||k; }
  function state(){ return S; }
  function open(){ const p=$('pqPanel'); if(p) p.classList.add('on');
    render(); return true; }
  function close(){ const p=$('pqPanel'); if(p) p.classList.remove('on');
    return true; }
  function setLanguage(l){ S.lang=(l==='ar')?'ar':'en';
    const t=$('pqTitle'); if(t) t.textContent=T('panel'); render();
    return S.lang; }
  function currentConfig(caps,bounds){
    return pqConfig(S.profile,S.lighting,S.materials,S.environment,
      S.exposure,{},caps||null,bounds||null); }
  function apply(){
    const caps=(typeof window!=='undefined'&&window.ACS&&window.ACS.pbrCaps)
      ?window.ACS.pbrCaps():null;
    const bounds=(typeof window!=='undefined'&&window.ACS&&window.ACS.pbrBounds)
      ?window.ACS.pbrBounds():null;
    const r=currentConfig(caps,bounds);
    if(!r.valid){ S.last={applied:false,issues:r.issues}; render();
      return S.last; }
    r.config.shadows_enabled=!!S.shadows;
    r.config.ssao_enabled=!!S.ao&&r.config.quality.ssao;
    if(typeof window!=='undefined'&&window.ACS
      &&typeof window.ACS.pbrApply==='function'){
      S.last=window.ACS.pbrApply(r.config);
    } else {
      /* غياب THREE (بيئة الفحص): رفض مصنَّف لا انهيار ولا شاشة فارغة */
      S.last={applied:false,config:r.config,
        issues:[pqIssue('PQ_THREE_UNAVAILABLE','INFO',null,
          'the 3D runtime is not present in this environment; the '+
          'configuration is valid and would apply on the deployed site')]}; }
    render(); return S.last; }
  function capture(){
    if(typeof window!=='undefined'&&window.ACS
      &&typeof window.ACS.pbrCapture==='function'){
      S.capture=window.ACS.pbrCapture({width:1920,height:1080});
    } else {
      S.capture={captured:false,
        issues:[pqIssue('PQ_THREE_UNAVAILABLE','INFO',null,
          'no 3D runtime; nothing to capture here')]}; }
    render(); return S.capture; }
  function sel(id,label,opts,cur){
    return '<div class="pq-field"><label>'+esc(label)+'</label>'+
      '<select id="'+id+'" data-pq-control="'+id+'">'+
      opts.map(o=>'<option value="'+esc(o[0])+'"'+(o[0]===cur?' selected':'')+
        '>'+esc(o[1])+'</option>').join('')+'</select></div>'; }
  function render(){
    const host=$('pqBody'); if(!host) return;
    const p=[];
    p.push(sel('pqQuality',T('quality'),
      [['PERFORMANCE',T('performance')],['BALANCED',T('balanced')],
       ['HIGH',T('high')],['ULTRA',T('ultra')]],S.profile));
    p.push(sel('pqLighting',T('lighting'),
      Object.keys(PQ_LIGHTING).map(k=>[k,k]),S.lighting));
    p.push(sel('pqMaterials',T('materials'),
      [['ENGINEERING',T('engineering')],['REALISTIC',T('realistic')]],
      S.materials));
    p.push(sel('pqEnvironment',T('environment'),
      [['NEUTRAL',T('neutral')],['SKY',T('sky')],['STUDIO',T('studio')]],
      S.environment));
    p.push('<div class="pq-field"><label>'+esc(T('shadows'))+'</label>'+
      '<input type="checkbox" id="pqShadows" data-pq-control="pqShadows"'+
      (S.shadows?' checked':'')+'></div>');
    p.push('<div class="pq-field"><label>'+esc(T('ao'))+'</label>'+
      '<input type="checkbox" id="pqAo" data-pq-control="pqAo"'+
      (S.ao?' checked':'')+'></div>');
    p.push('<div class="pq-field"><label>'+esc(T('exposure'))+'</label>'+
      '<input type="range" id="pqExposure" data-pq-control="pqExposure" '+
      'min="'+ACS_PBR_SPEC.exposure_min+'" max="'+ACS_PBR_SPEC.exposure_max+
      '" step="'+ACS_PBR_SPEC.exposure_step+'" value="'+
      (S.exposure===null?1.0:S.exposure)+'"></div>');
    if(S.last){
      const codes=(S.last.issues||[]).map(i=>i.code).join(', ');
      p.push('<div class="pq-status" data-pq-status="'+
        (S.last.applied?'APPLIED':'NOT_APPLIED')+'">'+
        (S.last.applied?'applied':'not applied')+
        (codes?(' — '+esc(codes)):'')+'</div>'); }
    if(S.capture&&S.capture.metadata)
      p.push('<div class="pq-status" data-pq-capture="1">'+
        esc(S.capture.metadata.type)+' '+S.capture.metadata.width_px+'×'+
        S.capture.metadata.height_px+'</div>');
    p.push('<div class="pq-note">presentation only — the engineering model '+
      'is read-only here and its hash never changes</div>');
    host.innerHTML=p.join('');
    const bind=(id,fn)=>{ const e=$(id); if(e) e.onchange=fn; };
    bind('pqQuality',()=>{ S.profile=$('pqQuality').value; });
    bind('pqLighting',()=>{ S.lighting=$('pqLighting').value; });
    bind('pqMaterials',()=>{ S.materials=$('pqMaterials').value; });
    bind('pqEnvironment',()=>{ S.environment=$('pqEnvironment').value; });
    bind('pqShadows',()=>{ S.shadows=$('pqShadows').checked; });
    bind('pqAo',()=>{ S.ao=$('pqAo').checked; });
    bind('pqExposure',()=>{ S.exposure=Number($('pqExposure').value); }); }
  function init(){
    const c=$('pqClose'); if(c) c.onclick=close;
    const a=$('pqApply'); if(a) a.onclick=()=>{ try{ apply(); }catch(e){} };
    const cp=$('pqCapture'); if(cp) cp.onclick=()=>{ try{ capture(); }catch(e){} };
    return true; }
  if(typeof document!=='undefined'&&document.addEventListener)
    document.addEventListener('DOMContentLoaded',init);
  return {state:state,open:open,close:close,init:init,render:render,
    setLanguage:setLanguage,apply:apply,capture:capture,
    currentConfig:currentConfig};
})();

/* --------- عقد استرداد العرض (مرآة render-recovery/1.0.0) ---------------
   مسار تحميل النموذج الأساسي كان يحسب الحدود بـ Box3().setFromObject(model):
   كل شبكة في مجموعة المبنى بلا فحص صلاحية، وnear/far يبقيان على قيمتَي إنشاء
   الكاميرا (0.05 / 6000) فلا يُعاد ضبطهما عند تحميل نموذج جديد أبداً. فإحداثيّة
   واحدة تالفة بين مئات العناصر المولَّدة تحوّل نصف القطر من ٨٤ م إلى ٥٠ كم
   وتضع الكاميرا على بُعد ١٠٧ كم خلف مستوى قصّ ثابت عند ٦ كم ⇒ إطار أسود
   والواجهة حيّة وعدّادات الطبقات ممتلئة. */
const PQ_RR = ACS_PBR_SPEC.render_recovery;
const PQ_RENDER_RECOVERY_CONTRACT = PQ_RR.version;

function pqElementValid(desc){
  const d=(desc&&typeof desc==='object')?desc:{};
  const box=(d.box&&typeof d.box==='object')?d.box:null;
  if(!(box&&Array.isArray(box.min)&&Array.isArray(box.max)
       &&box.min.length===3&&box.max.length===3))
    return {valid:false,reason:'NO_BOX',extent:null};
  const lo=[],hi=[];
  for(let i=0;i<3;i++){
    const a=_pqNum(box.min[i]), b=_pqNum(box.max[i]);
    if(a===null||b===null) return {valid:false,reason:'NON_FINITE',extent:null};
    lo.push(a); hi.push(b); }
  const size=[hi[0]-lo[0],hi[1]-lo[1],hi[2]-lo[2]];
  if(size.some(v=>v<0)) return {valid:false,reason:'INVERTED_BOX',extent:null};
  const extent=Math.max(size[0],Math.max(size[1],size[2]));
  const far=Math.max(Math.max(Math.abs(lo[0]),Math.abs(lo[1]),Math.abs(lo[2])),
                     Math.max(Math.abs(hi[0]),Math.abs(hi[1]),Math.abs(hi[2])));
  if(extent>PQ_RR.max_element_extent_m)
    return {valid:false,reason:'EXTENT_ABSURD',extent:_pqQ(extent)};
  if(far>PQ_RR.max_coordinate_m)
    return {valid:false,reason:'COORDINATE_ABSURD',extent:_pqQ(extent),
            distance:_pqQ(far)};
  if(extent<PQ_RR.min_element_extent_m)
    return {valid:true,reason:'DEGENERATE_BUT_FINITE',extent:_pqQ(extent),
            degenerate:true};
  return {valid:true,reason:'OK',extent:_pqQ(extent)}; }

function _pqMedian(v){
  const a=v.slice().sort((x,y)=>x-y), n=a.length;
  if(!n) return 0;
  return (n%2)?a[(n-n%2)/2]:(a[n/2-1]+a[n/2])/2; }

function pqRobustBounds(objects){
  const members=[],invalid=[],extents=[];
  (objects||[]).forEach(o=>{
    if(!pqBoundsMember(o).included) return;
    const v=pqElementValid(o);
    if(!v.valid){ invalid.push({name:(o||{}).name,reason:v.reason,
      extent:v.extent===undefined?null:v.extent,
      distance:v.distance===undefined?null:v.distance}); return; }
    members.push(o);
    if(v.extent!==null&&v.extent!==undefined) extents.push(v.extent); });
  const res=pqBoundsFromDescriptors(members);
  const issues=(res.issues||[]).slice();
  const outliers=[];
  if(extents.length){
    const med=_pqMedian(extents);
    if(med>0) members.forEach((o,i)=>{
      if(extents[i]>med*PQ_RR.outlier_extent_ratio)
        outliers.push({name:o.name,extent:extents[i],median:_pqQ(med),
                       ratio:_pqQ(extents[i]/med)}); }); }
  invalid.forEach(x=>issues.push(pqIssue('RENDER_INVALID_ELEMENT','WARNING',
    x.name,'excluded from camera fitting: '+x.reason)));
  outliers.forEach(x=>issues.push(pqIssue('RENDER_BOUNDS_OUTLIER','INFO',x.name,
    'element extent far exceeds the median — kept in bounds, reported for '
    +'inspection (see diagnostics.outliers for the figures)')));
  const out=Object.assign({},res);
  out.issues=issues;
  out.diagnostics={canonical_mesh_count:members.length+invalid.length,
    included_in_bounds:res.member_count||0,
    excluded_invalid_bounds:invalid.length,
    max_element_extent:extents.length?_pqQ(Math.max.apply(null,extents)):null,
    median_element_extent:extents.length?_pqQ(_pqMedian(extents)):null,
    scene_radius:(res.bounds||{}).radius===undefined?null:(res.bounds||{}).radius,
    outliers:outliers.slice(0,16),excluded:invalid.slice(0,16)};
  return out; }

function pqFitDistance(radius,fovDeg,aspect){
  let r=_pqNum(radius); if(r===null||r<=0) r=20;
  let fov=_pqNum(fovDeg); if(fov===null) fov=50;
  fov=Math.min(Math.max(fov,ACS_PBR_SPEC.fov_min),ACS_PBR_SPEC.fov_max);
  let asp=_pqNum(aspect); if(asp===null||asp<=0) asp=1.6;
  const vfov=fov*Math.PI/180;
  const hfov=2*Math.atan(Math.tan(vfov/2)*asp);
  const lim=Math.min(vfov,hfov);
  let d=r/Math.max(Math.sin(lim/2),1e-6);
  d=Math.max(d*PQ_RR.fit_margin,PQ_RR.fit_min_distance_m);
  return _pqQ(d); }

function pqCameraFit(bounds,fovDeg,aspect,azimuthDeg,elevationDeg,attempt){
  const b=(bounds&&typeof bounds==='object')?bounds:{};
  attempt=attempt||0;
  const r=_pqNum(b.radius);
  if(r===null||r<=0) return {valid:false,camera_in_frustum:false,camera:null,
    issues:[pqIssue('PQ_BOUNDS_UNAVAILABLE','WARNING',null,
      'no usable canonical radius — camera cannot be fitted')]};
  const cx=_pqNum(b.cx)||0, cy=_pqNum(b.cy)||0, cz=_pqNum(b.cz)||0;
  const fov=_pqNum(fovDeg)||52, asp=_pqNum(aspect)||1.6;
  let dist=pqFitDistance(r,fov,asp);
  if(attempt>0) dist=_pqQ(dist*Math.pow(PQ_RR.refit_distance_gain,attempt));
  const az=((azimuthDeg===undefined||azimuthDeg===null)?35:azimuthDeg)*Math.PI/180;
  const el=((elevationDeg===undefined||elevationDeg===null)?22:elevationDeg)*Math.PI/180;
  const pos=[cx+dist*Math.cos(el)*Math.cos(az), cy+dist*Math.sin(el),
             cz+dist*Math.cos(el)*Math.sin(az)];
  const clip=pqCameraClip({cx:cx,cy:cy,cz:cz,radius:r},pos);
  const cam={position:clip.clip.position,target:[_pqQ(cx),_pqQ(cy),_pqQ(cz)],
    fov:_pqQ(fov),aspect:_pqQ(asp),near:clip.clip.near,far:clip.clip.far};
  const fr=pqFrustumContains(cam,{cx:cx,cy:cy,cz:cz,radius:r});
  const issues=(clip.issues||[]).concat(fr.issues||[]);
  const ok=!!fr.contains;
  if(!ok&&attempt<PQ_RR.refit_attempts)
    return pqCameraFit(bounds,fovDeg,aspect,azimuthDeg,elevationDeg,attempt+1);
  if(!ok) issues.push(pqIssue('CAMERA_FIT_FAILED','WARNING',null,
    'the model is not inside the frustum after '+PQ_RR.refit_attempts
    +' deterministic re-fit(s)'));
  return {valid:ok,issues:issues,camera:cam,attempt:attempt,
    camera_in_frustum:ok,distance:clip.clip.distance}; }

function pqRecoveryPlan(state){
  const s=(state&&typeof state==='object')?state:{};
  const meshes=_pqNum(s.canonical_meshes)||0, calls=_pqNum(s.draw_calls)||0;
  if(!s.viewport_black) return {needed:false,steps:[],issues:[],
    reason:'VIEWPORT_NOT_BLACK'};
  if(meshes<=0) return {needed:false,steps:[],reason:'NO_CANONICAL_GEOMETRY',
    issues:[pqIssue('PQ_BOUNDS_UNAVAILABLE','WARNING',null,
      'nothing canonical to recover')]};
  if(calls<=0) return {needed:false,steps:[],reason:'NO_DRAW_CALLS',
    issues:[pqIssue('RENDER_BLACK_VIEWPORT','WARNING',null,
      'geometry exists but nothing was drawn')]};
  const steps=[];
  PQ_RR.recovery_steps.forEach(n=>{
    if(n==='DISABLE_COMPOSER'&&!s.composer_active) return;
    if(n==='RESTORE_ENGINEERING_MATERIALS'&&!s.materials_replaced) return;
    steps.push(n); });
  return {needed:true,steps:steps,max_cycles:PQ_RR.max_recovery_cycles,
    reason:'BLACK_WITH_GEOMETRY_AND_DRAW_CALLS',
    issues:[pqIssue('RENDER_BLACK_VIEWPORT','WARNING',null,
      'canonical geometry and draw calls produced a black frame — running one '
      +'recovery cycle')]}; }

if(typeof window!=='undefined'){
  window.ACS=window.ACS||{};
  window.ACS.pbr={
    spec:()=>JSON.parse(JSON.stringify(ACS_PBR_SPEC)),
    material:pqMaterial, materialForEngineering:pqMaterialForEngineering,
    lighting:pqLighting, exposureClamp:pqExposureClamp,
    shadowConfig:pqShadowConfig, quality:pqQuality, autoProfile:pqAutoProfile,
    camera:pqCamera, environment:pqEnvironment,
    texturePathOk:pqTexturePathOk, config:pqConfig,
    captureMetadata:pqCaptureMetadata,
    boundsMember:pqBoundsMember,
    boundsFromDescriptors:pqBoundsFromDescriptors,
    cameraClip:pqCameraClip, frustumContains:pqFrustumContains,
    materialSafe:pqMaterialSafe,
    viewportContract:()=>PQ_VIEWPORT_CONTRACT,
    renderRecoveryContract:()=>PQ_RENDER_RECOVERY_CONTRACT,
    elementValid:pqElementValid, robustBounds:pqRobustBounds,
    fitDistance:pqFitDistance, cameraFit:pqCameraFit,
    recoveryPlan:pqRecoveryPlan,
    levelBaseY:pqLevelBaseY, resolveTransform:pqResolveTransform,
    plateRect:pqPlateRect, rackBlock:pqRackBlock,
    containment:pqContainment, roofAlignment:pqRoofAlignment, panel:PQ};
}
"""


def _read(p):
    with open(p, encoding="utf-8") as f:
        return f.read()


def _replace(page, begin, end, block, anchor, after_anchor):
    if begin in page and end in page:
        a = page.index(begin)
        b = page.index(end) + len(end)
        tail = page[b:]
        if tail.startswith("\n"):
            tail = tail[1:]
        return page[:a] + block + tail, "replaced"
    i = page.index(anchor)
    if after_anchor:
        i += len(anchor)
        if page[i:i + 1] == "\n":
            i += 1
    return page[:i] + block + page[i:], "injected"


def build():
    with open(SPEC_PATH, "r", encoding="utf-8") as f:
        spec = json.load(f)
    body = (BODY + PANEL).replace(
        "__SPEC__", json.dumps(spec, ensure_ascii=False,
                               separators=(",", ":")))
    js_block = JS_BEGIN + "\n" + body + "\n" + JS_END + "\n"
    css_block = CSS_BEGIN + "\n" + CSS + "\n" + CSS_END + "\n"
    dom_block = DOM_BEGIN + "\n" + DOM + "\n" + DOM_END + "\n"
    page = _read(PAGE)
    page, a1 = _replace(page, CSS_BEGIN, CSS_END, css_block, CSS_ANCHOR, False)
    page, a2 = _replace(page, DOM_BEGIN, DOM_END, dom_block, DOM_ANCHOR, False)
    page, a3 = _replace(page, JS_BEGIN, JS_END, js_block, JS_ANCHOR, True)

    # الجسر داخل سكربت الوحدة — حيث THREE والمشهد. حقن عديم الأثر عند التكرار
    bridge = _read(os.path.join(HERE, "_pbr_bridge_block.js"))
    bridge_block = BRIDGE_SENTINEL_A + "\n" + bridge + "\n" + BRIDGE_SENTINEL_B + "\n"
    if BRIDGE_SENTINEL_A in page and BRIDGE_SENTINEL_B in page:
        a = page.index(BRIDGE_SENTINEL_A)
        b = page.index(BRIDGE_SENTINEL_B) + len(BRIDGE_SENTINEL_B)
        tail = page[b:]
        if tail.startswith("\n"):
            tail = tail[1:]
        page = page[:a] + bridge_block + tail
        a4 = "replaced"
    else:
        assert page.count(BRIDGE_ANCHOR) == 1, "bridge anchor not unique"
        page = page.replace(BRIDGE_ANCHOR, bridge_block + BRIDGE_ANCHOR)
        a4 = "injected"

    # خطّاف حلقة العرض: مبدّل المركِّب — يعمل فقط حين يوجد مركِّب حيّ
    if "window.__ACS_PQ__&&window.__ACS_PQ__.composer" not in page:
        assert page.count(LOOP_OLD) == 1, "render loop anchor not unique"
        page = page.replace(LOOP_OLD, LOOP_NEW)
        a5 = "hooked"
    else:
        a5 = "already hooked"

    with open(PAGE, "w", encoding="utf-8") as f:
        f.write(page)
    print("pbr styles %s (%d bytes), dom %s (%d bytes), quality %s (%d bytes), "
          "bridge %s, render loop %s"
          % (a1, len(css_block), a2, len(dom_block), a3, len(js_block),
             a4, a5))


if __name__ == "__main__":
    build()
