# -*- coding: utf-8 -*-
"""حاقن طبقة الأمانة البصرية المعمارية — المرحلة 9.2.

يولّد داخل public/index.html (داخل سكربت الوحدة نفسه):
  1) مرآة جافاسكربت حرفية للطبقة الحتمية acs_archdetail.py فوق المواصفة
     المشحونة ACS_ARCHDETAIL_SPEC (تكافؤ بايت-ببايت).
  2) لوحة «العرض المعماري» (DOM + CSS + منطق) عربي/إنجليزي.
  3) جسر الوحدة الذي يلمس THREE وحده: إطارات النوافذ، تقسيم الواجهة،
     شرائط LED العرضية، المحيط والتنسيق، مكتبة الكائنات العرضية،
     أنماط المقارنة هندسي/PBR/معماري — كله قابل للعكس بلا أثر.

كل الكتل مسوَّرة بعلامات وقابلة لإعادة التوليد بلا تكرار (idempotent).
لا يغيّر هذا الحاقن أي كتلة من مراحل سابقة.
"""
import io
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
PAGE = os.path.join(ROOT, "public", "index.html")
SPEC_PATH = os.path.join(ROOT, "acs_archdetail.json")

JS_BEGIN = "/* ===== ACS ARCH DETAIL (generated by tools/build_archdetail_browser.py) ===== */"
JS_END = "/* ===== END ACS ARCH DETAIL ===== */"
JS_ANCHOR = "/* ===== END ACS PBR QUALITY ===== */"

CSS_BEGIN = "/* ===== ACS ARCH DETAIL STYLES (generated) ===== */"
CSS_END = "/* ===== END ACS ARCH DETAIL STYLES ===== */"
CSS_ANCHOR = "/* ===== END ACS PBR STYLES ===== */"

DOM_BEGIN = "<!-- ===== ACS ARCH DETAIL DOM (generated) ===== -->"
DOM_END = "<!-- ===== END ACS ARCH DETAIL DOM ===== -->"
DOM_ANCHOR = "<!-- ===== END ACS PBR DOM ===== -->"

BRIDGE_A = "/* ===== ACS ARCH DETAIL BRIDGE (module scope) ===== */"
BRIDGE_B = "/* ===== END ACS ARCH DETAIL BRIDGE ===== */"
BRIDGE_ANCHOR = "/* ===== END ACS PBR BRIDGE ===== */"


def _read(p):
    with io.open(p, encoding="utf-8") as f:
        return f.read()


with io.open(SPEC_PATH, encoding="utf-8") as f:
    SPEC = json.load(f)

SPEC_JS = json.dumps(SPEC, ensure_ascii=False, separators=(",", ":"))

BODY = r"""
const ACS_ARCHDETAIL_SPEC = __SPEC__;

const AD_ISSUES = ACS_ARCHDETAIL_SPEC.issue_codes;
const AD_BLOCKING = ACS_ARCHDETAIL_SPEC.blocking_issue_codes;
const AD_MATERIALS = (function(){ const m={};
  ACS_ARCHDETAIL_SPEC.presentation_materials.forEach(x=>{ m[x.id]=x; });
  return m; })();
const AD_PROFILES = ACS_ARCHDETAIL_SPEC.detail_profiles;
const AD_STAGING = ACS_ARCHDETAIL_SPEC.staging_modes;
const AD_CAMERAS = ACS_ARCHDETAIL_SPEC.camera_presets_arch;
const AD_ENVS = ACS_ARCHDETAIL_SPEC.environment_presets;
const AD_LIB = ACS_ARCHDETAIL_SPEC.object_library;
const AD_KEYMAP = ACS_ARCHDETAIL_SPEC.request_interpretation.keyword_map;
const AD_DETAIL_CLASSES = Object.keys(ACS_ARCHDETAIL_SPEC.detail_classes);
const AD_RV = ACS_ARCHDETAIL_SPEC.vehicle_recipes;
const AD_RF = ACS_ARCHDETAIL_SPEC.forklift_recipes;
const AD_RFU = ACS_ARCHDETAIL_SPEC.furniture_recipes;
const AD_RL = ACS_ARCHDETAIL_SPEC.landscape_recipes;

function adIssue(code,severity,elementId,message){
  if(!(code in AD_ISSUES))
    throw new Error('undeclared archdetail issue code: '+code);
  return {code:code,severity:severity,element_id:elementId,message:message,
    blocking:AD_BLOCKING.indexOf(code)>=0}; }

function _adFlags(sourceId,provenance,confidence,reason,context){
  const f={visual_only:true,
    source_element_id:(sourceId===undefined)?null:sourceId,
    provenance:provenance,confidence:confidence,reason:reason};
  if(context) f.presentation_context=true;
  return f; }

/* ------------------------------------------------------ خامات العرض */
function adMaterial(mid,override){
  if(!(mid in AD_MATERIALS))
    return {valid:false,material:null,issues:[adIssue('AD_INVALID_MATERIAL',
      'ERROR',mid,'presentation material is not declared')]};
  const base=AD_MATERIALS[mid];
  const out={}; const prov={}; const issues=[];
  Object.keys(base).sort(_scmp).forEach(k=>{
    out[k]=(base[k]===undefined)?null:base[k];
    if(k==='name_en'||k==='name_ar') return;
    if(PQ_OVERRIDABLE.indexOf(k)>=0) prov[k]='PRESENTATION_DEFAULT'; });
  const ov=(override&&typeof override==='object'
            &&!Array.isArray(override))?override:{};
  const keys=Object.keys(ov).sort(_scmp);
  for(let i=0;i<keys.length;i++){
    const k=keys[i];
    if(!pqSafeKey(k)||PQ_OVERRIDABLE.indexOf(k)<0){
      return {valid:false,material:null,issues:[adIssue(
        'AD_INVALID_MATERIAL','ERROR',mid,'override key refused: '+k)]}; }
    const v=ov[k];
    if(k==='base_color'||k==='emissive'){
      const s=(typeof v==='string')?v:'';
      const ok=(s.length===7&&s.charAt(0)==='#'
        &&/^[0-9a-fA-F]{6}$/.test(s.slice(1)));
      if(!ok) return {valid:false,material:null,issues:[adIssue(
        'AD_INVALID_MATERIAL','ERROR',mid,'invalid color for '+k)]};
      out[k]=s.toLowerCase();
    } else {
      const n=_pqNum(v);
      if(n===null||n<0||n>20)
        return {valid:false,material:null,issues:[adIssue(
          'AD_INVALID_MATERIAL','ERROR',mid,
          'out-of-range override for '+k)]};
      out[k]=_pqQ(n); }
    prov[k]='USER_VISUAL_OVERRIDE'; }
  out.provenance=prov;
  out.is_engineering_truth=false;
  return {valid:true,material:out,issues:issues}; }

function adVariation(modelHash,elementId,materialId){
  const seed=String(modelHash)+'|'+String(elementId)+'|'+String(materialId);
  const h=sha256Hex(seed);
  const rMax=Number(ACS_ARCHDETAIL_SPEC.variation.roughness_jitter_max);
  const aMax=Number(ACS_ARCHDETAIL_SPEC.variation.albedo_jitter_max);
  const nMax=Number(ACS_ARCHDETAIL_SPEC.variation.normal_perturb_max);
  const frac=(a,b)=>parseInt(h.slice(a,b),16)/(Math.pow(16,b-a)-1);
  return {seed:h.slice(0,16),deterministic:true,
    roughness_delta:_pqQ((frac(0,8)*2.0-1.0)*rMax),
    albedo_delta:_pqQ((frac(8,16)*2.0-1.0)*aMax),
    normal_delta:_pqQ(frac(16,24)*nMax)}; }

/* ------------------------------------------------------ ملفات التفصيل */
function adDetailProfile(name,mobile){
  if(!(name in AD_PROFILES))
    return {valid:false,profile:null,issues:[adIssue('AD_INVALID_PROFILE',
      'ERROR',name,'detail profile is not declared')]};
  const issues=[]; let eff=name;
  if(mobile&&(name in ACS_ARCHDETAIL_SPEC.mobile_detail_fallback)){
    eff=ACS_ARCHDETAIL_SPEC.mobile_detail_fallback[name];
    issues.push(adIssue('AD_MOBILE_FALLBACK_APPLIED','INFO',name,
      'constrained device: '+name+' -> '+eff)); }
  const p={};
  Object.keys(AD_PROFILES[eff]).forEach(k=>{ p[k]=AD_PROFILES[eff][k]; });
  p.requested=name; p.effective=eff;
  p.canonical_objects_removed=false; p.blank_viewport_allowed=false;
  return {valid:true,profile:p,issues:issues}; }

function adClassifyDetail(kind){
  return AD_DETAIL_CLASSES.indexOf(kind)>=0?kind:'UNRESOLVED'; }

function adObjectAuthority(obj,contextEnabled){
  const o=(obj&&typeof obj==='object')?obj:{};
  if(o.canonical===true) return 'CANONICAL_OBJECT';
  if(o.requested===true) return 'USER_REQUESTED_OBJECT';
  if(contextEnabled&&o.context===true) return 'PRESENTATION_CONTEXT_OBJECT';
  return 'UNRESOLVED_OBJECT'; }

/* ------------------------------------------------------ تقسيم الواجهة */
function adFacadeZoning(surfaces,request){
  const req=(request&&typeof request==='object')?request:{};
  const primary=(req.primary===undefined)?null:req.primary;
  const accent=(req.accent===undefined)?null:req.accent;
  const issues=[]; const assigns=[];
  const ZM=ACS_ARCHDETAIL_SPEC.facade_zone_materials;
  if(primary!==null&&ZM.indexOf(primary)<0)
    return {valid:false,zones:null,issues:[adIssue('AD_INVALID_MATERIAL',
      'ERROR',primary,'facade zone material is not declared')]};
  if(accent!==null&&ZM.indexOf(accent)<0)
    return {valid:false,zones:null,issues:[adIssue('AD_INVALID_MATERIAL',
      'ERROR',accent,'facade zone material is not declared')]};
  const prim=(surfaces||[]).filter(s=>s&&typeof s==='object'
    &&s.role==='exterior_wall');
  const acc=(surfaces||[]).filter(s=>s&&typeof s==='object'
    &&['parapet','base_course','accent_band'].indexOf(s.role)>=0);
  if(primary){
    prim.forEach(s=>{ assigns.push({
      surface_id:(s.id===undefined)?null:s.id,material:primary,
      detail_class:'REQUESTED_PRESENTATION_DETAIL',
      flags:_adFlags(s.id,'USER_VISUAL_OVERRIDE','HIGH',
        'requested facade appearance')}); });
    if(!prim.length)
      issues.push(adIssue('AD_VISUAL_DETAIL_UNRESOLVED','WARNING',primary,
        'no represented exterior wall surface')); }
  if(accent){
    if(acc.length){
      acc.forEach(s=>{ assigns.push({
        surface_id:(s.id===undefined)?null:s.id,material:accent,
        detail_class:'REQUESTED_PRESENTATION_DETAIL',
        flags:_adFlags(s.id,'USER_VISUAL_OVERRIDE','MEDIUM',
          'requested accent on represented band')}); });
    } else {
      issues.push(adIssue('AD_VISUAL_DETAIL_UNRESOLVED','WARNING',accent,
        'no safe accent zone can be derived; not fabricated')); } }
  return {valid:true,issues:issues,zones:{assignments:assigns,
    invented_walls:false,wall_thickness_changed:false,
    accent_resolved:!!(accent&&acc.length)}}; }

/* --------------------------------------------------- تجميعة النافذة */
function adWindowAssembly(opening,finish){
  const o=(opening&&typeof opening==='object')?opening:{};
  const w=_pqNum(o.width), h=_pqNum(o.height);
  if(w===null||h===null||w<=0||h<=0)
    return {valid:false,assembly:null,issues:[adIssue('AD_INVALID_MODE',
      'ERROR','window','opening width/height missing')]};
  const wa=ACS_ARCHDETAIL_SPEC.window_assembly;
  const fin=finish||wa.default_frame_finish;
  if(!(fin in wa.frame_finishes))
    return {valid:false,assembly:null,issues:[adIssue('AD_INVALID_MODE',
      'ERROR',fin,'frame finish is not declared')]};
  const t=Math.min(Math.max(Math.min(w,h)*wa.frame_thickness_ratio,
    wa.frame_thickness_min_m),wa.frame_thickness_max_m);
  const sill=_pqNum(o.sill);
  return {valid:true,issues:[],assembly:{
    opening:{width:_pqQ(w),height:_pqQ(h),
      sill:_pqQ(sill===null?0.0:sill)},
    opening_size_changed:false,opening_position_changed:false,
    window_count_changed:false,
    detail_class:'DERIVED_PRESENTATION_DETAIL',
    frame:{material:wa.frame_material,finish:fin,
      color:wa.frame_finishes[fin],thickness_m:_pqQ(t),
      depth_m:wa.frame_depth_m,parts:['top','bottom','left','right']},
    glass:{material:'glass_clear',three_material:'physical'},
    sill:{depth_m:wa.sill_depth_m,drop_m:wa.sill_drop_m},
    flags:_adFlags((o.id===undefined)?null:o.id,'PRESENTATION_DEFAULT',
      'HIGH','frame derived from the represented opening')}}; }

function adDoorVisual(door){
  const d=(door&&typeof door==='object')?door:{};
  const ev=d.material||d.kind||'door';
  let cls=(ev in ACS_ARCHDETAIL_SPEC.door_class_evidence_map)
    ?ACS_ARCHDETAIL_SPEC.door_class_evidence_map[ev]:'generic';
  if(d.entrance===true) cls='entrance_door';
  const spec=ACS_ARCHDETAIL_SPEC.door_visual_classes[cls];
  return {valid:true,issues:[],door:{
    visual_class:cls,material:spec.material,glass:!!spec.glass,
    fire_rating_inferred:false,security_rating_inferred:false,
    engineering_material_truth:false,
    detail_class:'DERIVED_PRESENTATION_DETAIL',
    flags:_adFlags((d.id===undefined)?null:d.id,'PRESENTATION_DEFAULT',
      cls!=='generic'?'HIGH':'LOW',
      'visual class mapped from represented evidence')}}; }

function adBalconyVisual(represented,requested){
  if(represented)
    return {status:requested?'ENHANCED':'CANONICAL_GEOMETRY_PRESENT',
      engineering_geometry_created:false,issues:[],
      enhancements:ACS_ARCHDETAIL_SPEC.balcony_rules.enhancements};
  if(requested)
    return {status:'REQUESTED_BUT_NOT_REPRESENTED',
      engineering_geometry_created:false,
      ui_note_en:ACS_ARCHDETAIL_SPEC.balcony_rules.ui_note_en,
      ui_note_ar:ACS_ARCHDETAIL_SPEC.balcony_rules.ui_note_ar,
      issues:[adIssue('AD_BALCONY_NOT_REPRESENTED','WARNING','balcony',
        'requested but not represented in canonical geometry')]};
  return {status:'NOT_REQUESTED',engineering_geometry_created:false,
    issues:[]}; }

function adLed(kind,host){
  const L=ACS_ARCHDETAIL_SPEC.led_lighting;
  if(L.types.indexOf(kind)<0)
    return {valid:false,light:null,issues:[adIssue('AD_INVALID_MODE',
      'ERROR',kind,'led type is not declared')]};
  const h=(host&&typeof host==='object')?host:{};
  if(!h.represented)
    return {valid:false,light:null,issues:[adIssue(
      'AD_HOST_NOT_REPRESENTED','WARNING',kind,
      'no represented host edge for this light')]};
  return {valid:true,issues:[],light:{
    type:kind,visual_only:true,mep_fixture_reused:false,
    creates_electrical_circuit:false,creates_load:false,
    creates_panel_assignment:false,creates_cable_route:false,
    creates_mep_schedule_entry:false,
    emissive_intensity:L.emissive_intensity,
    strip_height_m:L.strip_height_m,strip_depth_m:L.strip_depth_m,
    material:'led_strip',
    detail_class:'REQUESTED_PRESENTATION_DETAIL',
    flags:_adFlags((h.id===undefined)?null:h.id,'USER_VISUAL_OVERRIDE',
      'HIGH','visual-only architectural light on a represented host')}}; }

/* ------------------------------------------------------ التأثيث العرضي */
function adStagingPlan(mode,requestedObjects,canonicalObjects){
  if(!(mode in AD_STAGING))
    return {valid:false,plan:null,issues:[adIssue('AD_INVALID_MODE',
      'ERROR',mode,'staging mode is not declared')]};
  const req=(requestedObjects||[]).filter(o=>o&&typeof o==='object');
  const can=(canonicalObjects||[]).filter(o=>o&&typeof o==='object');
  const improve=can.map(o=>({kind:(o.kind===undefined)?null:o.kind,
      id:(o.id===undefined)?null:o.id,authority:'CANONICAL_OBJECT'}))
    .concat(mode!=='STAGING_OFF'
      ?req.map(o=>({kind:(o.kind===undefined)?null:o.kind,
        id:(o.id===undefined)?null:o.id,
        authority:'USER_REQUESTED_OBJECT'})):[]);
  let additions=[];
  if(mode==='STAGING_PRESENTATION_DEFAULT')
    additions=['sofa','dining_table','bed'].map(k=>({
      kind:k,authority:'PRESENTATION_CONTEXT_OBJECT',
      flags:_adFlags(null,'PRESENTATION_DEFAULT','LOW',
        'presentation staging default',true),
      enters_bim:false,enters_quantities:false,
      enters_engineering_exports:false,
      enters_documentation_schedules:false}));
  return {valid:true,issues:[],plan:{mode:mode,improve:improve,
    additions:additions,silent_population:false,
    canonical_object_count_changed:false}}; }

function _adCategory(kind){
  const cats=Object.keys(AD_LIB).sort(_scmp);
  for(let i=0;i<cats.length;i++)
    if(AD_LIB[cats[i]].indexOf(kind)>=0) return cats[i];
  return null; }

function _adExpand(parts){
  const out=[];
  parts.forEach(p=>{
    if(p.indexOf(':')>=0){ const a=p.split(':');
      for(let i=0;i<parseInt(a[1],10);i++) out.push(a[0]); }
    else out.push(p); });
  return out; }

function adObjectRecipe(kind,dims,canonicalDims,variant){
  const issues=[];
  const cat=_adCategory(kind);
  if(cat===null)
    return {valid:false,recipe:null,issues:[adIssue(
      'AD_INVALID_OBJECT_KIND','ERROR',kind,
      'object kind is not in the presentation library')]};
  let parts,def,recipeId;
  const vmap={forklift:'COUNTERBALANCE_FORKLIFT',
    reach_truck:'REACH_TRUCK',pallet_jack:'PALLET_JACK',
    order_picker:'ORDER_PICKER',stacker:'STACKER'};
  if(kind==='forklift'||['reach_truck','pallet_jack','order_picker',
      'stacker'].indexOf(kind)>=0){
    let v=variant||vmap[kind];
    if(!(v in AD_RF)) v='GENERIC_FORKLIFT_PRESENTATION';
    parts=_adExpand(AD_RF[v].parts); def=AD_RF[v].dims_m; recipeId=v;
  } else if(kind in AD_RV){
    parts=_adExpand(AD_RV[kind].parts); def=AD_RV[kind].dims_m;
    recipeId=kind;
  } else if(kind in AD_RL){
    parts=_adExpand(AD_RL[kind].parts); def=[2.4,2.4,4.5]; recipeId=kind;
  } else if(kind in AD_RFU){
    parts=_adExpand(AD_RFU[kind]); def=[1.0,1.0,1.0]; recipeId=kind;
  } else { parts=['box']; def=[0.8,0.8,0.8]; recipeId='generic_'+kind; }
  const dimsOk=v=>Array.isArray(v)&&v.length===3
    &&v.every(x=>_pqNum(x)!==null&&_pqNum(x)>0);
  let use,source;
  if(dimsOk(canonicalDims)){
    use=canonicalDims.map(x=>_pqQ(_pqNum(x))); source='CANONICAL';
  } else if(dimsOk(dims)){
    use=dims.map(x=>_pqQ(_pqNum(x))); source='USER';
  } else {
    use=def.map(x=>_pqQ(x)); source='PRESENTATION_DEFAULT';
    issues.push(adIssue('AD_PRESENTATION_DEFAULT_DIMENSIONS','INFO',kind,
      'default dimensions are a presentation fallback, not engineering '
      +'measurements')); }
  let forbidden={};
  if(cat==='vehicles')
    ACS_ARCHDETAIL_SPEC.vehicle_invention_forbidden.forEach(k=>{
      forbidden[k]=false; });
  if(recipeId in AD_RF){ forbidden={};
    ACS_ARCHDETAIL_SPEC.forklift_inference_forbidden.forEach(k=>{
      forbidden[k]=false; }); }
  return {valid:true,issues:issues,recipe:{
    kind:kind,category:cat,recipe_id:recipeId,parts:parts,dims_m:use,
    dims_source:source,invented_attributes:forbidden,
    instanced:ACS_ARCHDETAIL_SPEC.instancing.instanced_classes
      .indexOf(kind)>=0,
    visual_only:true}}; }

function adPlacement(obj){
  const o=(obj&&typeof obj==='object')?obj:{};
  const p3=v=>v.slice(0,3).map(x=>{ const n=_pqNum(x);
    return _pqQ(n===null?0.0:n); });
  if(Array.isArray(o.canonical_pos)&&o.canonical_pos.length>=2)
    return {resolved:true,source:'CANONICAL',
      position:p3(o.canonical_pos),issues:[]};
  if(Array.isArray(o.user_pos)&&o.user_pos.length>=2)
    return {resolved:true,source:'USER',position:p3(o.user_pos),issues:[]};
  const z=o.zone;
  if(z&&typeof z==='object'&&['x','z','w','d'].every(k=>
      _pqNum(z[k])!==null)){
    const zx=_pqNum(z.x),zz=_pqNum(z.z),zw=_pqNum(z.w),zd=_pqNum(z.d);
    const i=Math.trunc(_pqNum(o.index)||0);
    const n=Math.max(1,Math.trunc(_pqNum(o.of)||1));
    return {resolved:true,source:'ZONE_DETERMINISTIC',
      position:[_pqQ(zx+zw*(i+0.5)/n),0.0,_pqQ(zz+zd*0.5)],issues:[]}; }
  return {resolved:false,source:'UNRESOLVED',position:null,
    issues:[adIssue('AD_PLACEMENT_UNRESOLVED','WARNING',
      (o.kind===undefined)?null:o.kind,
      'no safe placement can be derived; not fabricated')]}; }

function adVehiclesToBays(countRequested,bays){
  const n=Math.max(0,Math.trunc(_pqNum(countRequested)||0));
  const valid=(bays||[]).filter(b=>b&&typeof b==='object'
    &&b.id!==null&&b.id!==undefined);
  const placed=[];
  for(let i=0;i<Math.min(n,valid.length);i++)
    placed.push({bay_id:valid[i].id,kind:'car',
      authority:'USER_REQUESTED_OBJECT',
      status:'APPLIED_TO_CANONICAL_PARKING'});
  const issues=[];
  if(n>valid.length)
    issues.push(adIssue('AD_PARKING_NOT_RESOLVED','WARNING','cars',
      n+' requested, '+valid.length+' represented bays'));
  return {placed:placed,requested:n,represented_bays:valid.length,
    unplaced:Math.max(0,n-valid.length),issues:issues}; }

function adParking(requested,baysCount){
  const b=Math.max(0,Math.trunc(_pqNum(baysCount)||0));
  if(b>0)
    return {status:requested?'APPLIED_TO_CANONICAL_PARKING'
      :'CANONICAL_GEOMETRY_PRESENT',bays:b,invented_count:false,issues:[]};
  if(requested)
    return {status:'REQUESTED_NOT_GEOMETRICALLY_RESOLVED',bays:0,
      invented_count:false,
      issues:[adIssue('AD_PARKING_NOT_RESOLVED','WARNING','parking',
        'requested but no represented bays')]};
  return {status:'NOT_REQUESTED',bays:0,invented_count:false,issues:[]}; }

function adKitchenLayout(requestedText,canonicalLayout){
  if(ACS_ARCHDETAIL_SPEC.kitchen_layouts.indexOf(canonicalLayout)>=0)
    return {layout:canonicalLayout,source:'CANONICAL',issues:[]};
  if(requestedText)
    return {layout:null,source:'UNRESOLVED',
      issues:[adIssue('AD_KITCHEN_LAYOUT_UNRESOLVED','WARNING','kitchen',
        'ambiguous request; no canonical layout selected')]};
  return {layout:null,source:'NOT_REQUESTED',issues:[]}; }

/* ------------------------------------------------------ البيئة والكاميرا */
function adEnvironment(preset){
  if(!(preset in AD_ENVS))
    return {valid:false,environment:null,issues:[adIssue(
      'AD_INVALID_ENVIRONMENT','ERROR',preset,
      'environment preset is not declared')]};
  const e=AD_ENVS[preset];
  const base=pqEnvironment(e.base_mode);
  if(!base.valid) return base;
  const env={};
  Object.keys(base.environment).forEach(k=>{ env[k]=base.environment[k]; });
  env.arch_preset=preset; env.sun_tint=e.sun_tint;
  env.runtime_cdn=false; env.remote_hdri=false;
  return {valid:true,environment:env,issues:[]}; }

function adCamera(preset,bounds){
  if(preset in PQ_CAMERAS) return pqCamera(preset,bounds);
  if(!(preset in AD_CAMERAS))
    return {valid:false,camera:null,issues:[adIssue('AD_INVALID_CAMERA',
      'ERROR',preset,'camera preset is not declared')]};
  const p=AD_CAMERAS[preset];
  const b=(bounds&&typeof bounds==='object')?bounds:{};
  const cx=_pqNum(b.cx)||0.0, cy=_pqNum(b.cy)||0.0, cz=_pqNum(b.cz)||0.0;
  let r=_pqNum(b.radius);
  if(r===null||r<=0) r=20.0;
  const fov=Math.min(Math.max(Number(p.fov),
    Number(ACS_PBR_SPEC.fov_min)),Number(ACS_PBR_SPEC.fov_max));
  const az=Number(p.azimuth_deg)*Math.PI/180;
  const el=Number(p.elevation_deg)*Math.PI/180;
  const d=r*Number(p.distance_factor);
  let px=cx+d*Math.cos(el)*Math.sin(az);
  let pz=cz+d*Math.cos(el)*Math.cos(az);
  let py=cy+d*Math.sin(el);
  let ty=cy;
  if(p.target==='EYE'&&p.eye_height_m!==undefined&&p.eye_height_m!==null){
    const baseY=_pqNum(b.min_y)||0.0;
    py=baseY+Number(p.eye_height_m); ty=baseY+Number(p.eye_height_m); }
  return {valid:true,issues:[],camera:{preset:preset,fov:_pqQ(fov),
    position:[_pqQ(px),_pqQ(py),_pqQ(pz)],
    target:[_pqQ(cx),_pqQ(ty),_pqQ(cz)],
    bounds_radius_m:_pqQ(r),deterministic:true,fisheye:false}}; }

function adAutoPresentation(meta){
  const m=(meta&&typeof meta==='object')?meta:{};
  const table=ACS_ARCHDETAIL_SPEC.auto_presentation;
  let pick;
  if(m.indoor===true) pick=table.interior_mode;
  else {
    const t=(m.type in table.by_building_type)?m.type:'generic';
    pick=table.by_building_type[t]; }
  const q=pqAutoProfile((m.caps===undefined)?null:m.caps);
  return {valid:true,issues:[],auto:{
    camera_preset:pick.camera,lighting_preset:pick.lighting,
    environment:pick.environment,detail_profile:pick.detail,
    quality_profile:q.profile,ultra_auto_selected:false,
    materials_mode:'REALISTIC',engineering_geometry_changed:false}}; }

/* --------------------------------------------------- تفسير الطلبات */
function adInterpret(text){
  const s=(text===null||text===undefined)?'':String(text);
  const low=s.toLowerCase();
  const found=[]; const seen={};
  AD_KEYMAP.forEach(entry=>{
    const keys=entry.keys_ar.concat(entry.keys_en);
    let hit=null;
    const ordered=keys.slice().sort((a,b)=>b.length-a.length);
    for(let i=0;i<ordered.length;i++){
      if(low.indexOf(ordered[i].toLowerCase())>=0){ hit=ordered[i]; break; } }
    if(hit===null) return;
    if(entry.intent in seen) return;
    seen[entry.intent]=true;
    found.push({intent:entry.intent,
      value:(entry.value===undefined)?null:entry.value,
      classification:entry['class'],matched:hit}); });
  return {text_len:s.length,intents:found,
    engineering_permission_granted:false}; }

/* ------------------------------------------------------ التشخيص */
function adDiagnostic(requests,modelSummary){
  const ms=(modelSummary&&typeof modelSummary==='object')?modelSummary:{};
  const feats=[]; const issues=[];
  const objs={requested_objects:[],canonical_objects:[],
    presentation_objects:[],unresolved_objects:[],
    presentation_default_objects:[]};
  (requests||[]).forEach(r=>{
    const it=r.intent, cls=r.classification;
    if(cls==='REQUIRES_ENGINEERING_CHANGE'){
      feats.push({feature:it,status:'REQUIRES_ENGINEERING_CHANGE'});
      issues.push(adIssue('AD_REQUIRES_ENGINEERING_CHANGE','WARNING',it,
        'outside the presentation authority'));
      return; }
    if(cls==='UNSUPPORTED'){
      feats.push({feature:it,status:'UNRESOLVED'});
      issues.push(adIssue('AD_REQUEST_UNSUPPORTED','WARNING',it,
        'not supported by the presentation layer'));
      return; }
    if(it==='facade_material'){
      const ok=!!ms.exterior_walls;
      feats.push({feature:it,status:ok?'APPLIED':'UNRESOLVED'});
    } else if(it==='facade_accent'){
      const ok=!!ms.accent_band;
      feats.push({feature:it,status:ok?'APPLIED':'UNRESOLVED'});
      if(!ok) issues.push(adIssue('AD_VISUAL_DETAIL_UNRESOLVED','WARNING',
        it,'no safe accent zone'));
    } else if(it==='glass_appearance'){
      const ok=!!ms.windows;
      feats.push({feature:it,status:ok?'APPLIED':'UNRESOLVED'});
    } else if(it==='led_lighting'){
      const ok=!!(ms.exterior_walls||ms.balcony);
      feats.push({feature:it,
        status:ok?'VISUAL_ONLY_APPLIED':'UNRESOLVED'});
    } else if(it==='balcony_presence'){
      const b=adBalconyVisual(!!ms.balcony,true);
      feats.push({feature:it,status:b.status});
      b.issues.forEach(x=>issues.push(x));
    } else if(it==='parking'){
      const pk=adParking(true,
        (ms.parking_bays===undefined)?null:ms.parking_bays);
      feats.push({feature:it,status:pk.status});
      pk.issues.forEach(x=>issues.push(x));
    } else if(it==='landscape'){
      feats.push({feature:it,status:'PRESENTATION_CONTEXT'});
    } else if(it==='kitchen_layout'){
      const k=adKitchenLayout(true,
        (ms.kitchen_layout===undefined)?null:ms.kitchen_layout);
      feats.push({feature:it,status:k.layout?'APPLIED':'UNRESOLVED'});
      k.issues.forEach(x=>issues.push(x));
    } else {
      feats.push({feature:it,status:'UNRESOLVED'});
      issues.push(adIssue('AD_REQUEST_UNSUPPORTED','WARNING',it,
        'unhandled intent')); } });
  (ms.objects||[]).forEach(o=>{
    const a=adObjectAuthority(o,!!ms.context_enabled);
    const rec={kind:(o.kind===undefined)?null:o.kind,
      count:o.count||1,authority:a};
    if(a==='CANONICAL_OBJECT') objs.canonical_objects.push(rec);
    else if(a==='USER_REQUESTED_OBJECT') objs.requested_objects.push(rec);
    else if(a==='PRESENTATION_CONTEXT_OBJECT')
      objs.presentation_objects.push(rec);
    else { objs.unresolved_objects.push(rec);
      issues.push(adIssue('AD_OBJECT_UNRESOLVED','WARNING',
        (o.kind===undefined)?null:o.kind,
        'object authority cannot be resolved')); } });
  const REP=['APPLIED','ENHANCED','CANONICAL_GEOMETRY_PRESENT',
    'VISUAL_ONLY_APPLIED','APPLIED_TO_CANONICAL_PARKING'];
  const UNR=['UNRESOLVED','REQUESTED_NOT_GEOMETRICALLY_RESOLVED',
    'REQUESTED_BUT_NOT_REPRESENTED'];
  const d={requested_visual_features:feats.map(f=>f.feature),
    features:feats,
    represented_visual_features:feats.filter(f=>REP.indexOf(f.status)>=0)
      .map(f=>f.feature),
    unresolved_visual_features:feats.filter(f=>UNR.indexOf(f.status)>=0)
      .map(f=>f.feature),
    engineering_change_required:feats
      .filter(f=>f.status==='REQUIRES_ENGINEERING_CHANGE')
      .map(f=>f.feature),
    presentation_defaults_used:feats
      .filter(f=>f.status==='PRESENTATION_CONTEXT').map(f=>f.feature),
    silently_dropped:[]};
  Object.keys(objs).forEach(k=>{ d[k]=objs[k]; });
  return {valid:true,diagnostic:d,issues:issues}; }

function adCoverage(diag){
  const d=((diag||{}).diagnostic)||{};
  const req=(d.requested_visual_features||[]).length;
  const rep=(d.represented_visual_features||[]).length;
  const unr=(d.unresolved_visual_features||[]).length;
  const eng=(d.engineering_change_required||[]).length;
  return {name:'VISUAL_REQUEST_COVERAGE',
    requested:req,represented:rep,unresolved:unr,
    requires_engineering_change:eng,
    coverage_ratio:req?_pqQ(rep/req):null,
    is_engineering_completeness:false,has_compliance_meaning:false}; }

/* ------------------------------------------------------ الإعداد الكامل */
function adConfig(detail,facadeMode,contextMode,stagingMode,cameraPreset,
    environmentPreset,caps,mobile,requests,modelSummary){
  let issues=[];
  const dp=adDetailProfile(
    detail||ACS_ARCHDETAIL_SPEC.default_detail_profile,mobile);
  if(!dp.valid) return {valid:false,config:null,issues:dp.issues};
  issues=issues.concat(dp.issues);
  const fm=facadeMode||'ENGINEERING';
  if(['ENGINEERING','REQUESTED','REALISTIC'].indexOf(fm)<0)
    return {valid:false,config:null,issues:[adIssue('AD_INVALID_MODE',
      'ERROR',fm,'facade mode is not declared')]};
  const cm=contextMode||'NONE';
  if(['NONE','NEUTRAL','SITE','LANDSCAPE'].indexOf(cm)<0)
    return {valid:false,config:null,issues:[adIssue('AD_INVALID_MODE',
      'ERROR',cm,'context mode is not declared')]};
  const sm=stagingMode||ACS_ARCHDETAIL_SPEC.default_staging_mode;
  if(!(sm in AD_STAGING))
    return {valid:false,config:null,issues:[adIssue('AD_INVALID_MODE',
      'ERROR',sm,'staging mode is not declared')]};
  const ev=adEnvironment(environmentPreset||'NEUTRAL_STUDIO');
  if(!ev.valid) return {valid:false,config:null,issues:ev.issues};
  const cam=cameraPreset||'EXTERIOR_HERO_CORNER';
  if(!(cam in PQ_CAMERAS)&&!(cam in AD_CAMERAS))
    return {valid:false,config:null,issues:[adIssue('AD_INVALID_CAMERA',
      'ERROR',cam,'camera preset is not declared')]};
  const diag=adDiagnostic(requests||[],modelSummary||{});
  issues=issues.concat(diag.issues);
  const cov=adCoverage(diag);
  const cfg={schema:ACS_ARCHDETAIL_SPEC.schema,
    version:ACS_ARCHDETAIL_SPEC.version,
    presentation_layer_version:
      ACS_ARCHDETAIL_SPEC.presentation_layer_version,
    detail:dp.profile,facade_mode:fm,context_mode:cm,staging_mode:sm,
    camera_preset:cam,environment:ev.environment,
    diagnostic:diag.diagnostic,visual_request_coverage:cov,
    writes_to_model:false,visual_only:true,
    canonical_object_count_changed:false};
  cfg.presentation_config_hash=_pqSha16(cfg);
  return {valid:true,config:cfg,issues:issues}; }

function adCaptureMetadata(pbrCfg,adCfg,modelHash,revision,widthPx,
    heightPx,generatedAt){
  const base=pqCaptureMetadata(pbrCfg,modelHash,widthPx,heightPx,
    (generatedAt===undefined)?null:generatedAt);
  if(!base.valid) return base;
  const md={};
  Object.keys(base.metadata).forEach(k=>{ md[k]=base.metadata[k]; });
  const a=adCfg||{};
  md.revision=(revision===undefined)?null:revision;
  md.presentation_layer_version=
    ACS_ARCHDETAIL_SPEC.presentation_layer_version;
  md.architectural_detail_level=((a.detail||{}).effective===undefined)
    ?null:(a.detail||{}).effective;
  md.context_mode=(a.context_mode===undefined)?null:a.context_mode;
  md.staging_mode=(a.staging_mode===undefined)?null:a.staging_mode;
  md.visual_request_coverage=(a.visual_request_coverage===undefined)
    ?null:a.visual_request_coverage;
  md.is_engineering_evidence=false;
  return {valid:true,metadata:md,issues:base.issues}; }
"""

PANEL = r"""
/* ===== لوحة العرض المعماري (المرحلة 9.2) ===== */
const AD=(function(){
  const S={lang:'ar',detail:'DETAIL_STANDARD',facade:'ENGINEERING',
    context:'NONE',staging:'STAGING_REQUESTED_ONLY',camera:'AUTO',
    requestText:'',last:null,inited:false};
  const L=()=>ACS_ARCHDETAIL_SPEC.ui_labels[S.lang];
  const $=id=>document.getElementById(id);
  const CAMS={AUTO:null,HERO:'EXTERIOR_HERO_CORNER',
    STREET:'EXTERIOR_STREET_LEVEL',AERIAL:'EXTERIOR_AERIAL',
    INTERIOR:'INTERIOR_LIVING'};
  function opt(sel,pairs,val){
    sel.innerHTML='';
    pairs.forEach(p=>{ const o=document.createElement('option');
      o.value=p[0]; o.textContent=p[1]; sel.appendChild(o); });
    sel.value=val; }
  function render(){
    const t=L();
    $('adTitle').textContent=t.panel;
    $('adReadonly').textContent=t.readonly;
    $('adCompareLbl').textContent=t.compare;
    $('adDetailLbl').textContent=t.detail;
    $('adFacadeLbl').textContent=t.facade;
    $('adContextLbl').textContent=t.context;
    $('adStagingLbl').textContent=t.staging;
    $('adCameraLbl').textContent=t.camera;
    $('adDiagLbl').textContent=t.diagnostic;
    opt($('adDetail'),[['DETAIL_OFF',t.off],['DETAIL_STANDARD',t.standard],
      ['DETAIL_HIGH',t.high]],S.detail);
    opt($('adFacade'),[['ENGINEERING',t.engineering],
      ['REQUESTED',t.requested],['REALISTIC',t.realistic]],S.facade);
    opt($('adContext'),[['NONE',t.none],['NEUTRAL',t.neutral],
      ['SITE',t.site],['LANDSCAPE',t.landscape]],S.context);
    opt($('adStaging'),[['STAGING_OFF',t.off],
      ['STAGING_REQUESTED_ONLY',t.requested_only],
      ['STAGING_PRESENTATION_DEFAULT',t.presentation]],S.staging);
    opt($('adCamera'),[['AUTO',t.auto],['HERO',t.hero],['STREET',t.street],
      ['AERIAL',t.aerial],['INTERIOR',t.interior]],S.camera); }
  function currentConfig(){
    const req=adInterpret(S.requestText).intents;
    const cam=(S.camera==='AUTO')
      ?adAutoPresentation((typeof window!=='undefined'&&window.ACS
          &&window.ACS.adModelMeta)?window.ACS.adModelMeta():null)
        .auto.camera_preset
      :CAMS[S.camera];
    return adConfig(S.detail,S.facade,S.context,S.staging,cam,
      null,null,false,req,
      (typeof window!=='undefined'&&window.ACS&&window.ACS.adModelSummary)
        ?window.ACS.adModelSummary():null); }
  function apply(){
    const r=currentConfig();
    if(!r.valid){ S.last={applied:false,issues:r.issues,config:null};
      status(); return S.last; }
    if(typeof window!=='undefined'&&window.ACS
        &&typeof window.ACS.adApply==='function'){
      S.last=window.ACS.adApply(r.config);
    } else {
      S.last={applied:false,config:r.config,
        issues:[adIssue('AD_THREE_UNAVAILABLE','ERROR','archdetail',
          'no 3D runtime in this environment; configuration produced, '
          +'nothing rendered')]}; }
    status(); diag(r.config); return S.last; }
  function status(){
    const el=$('adStatus'); if(!el) return;
    const ok=S.last&&S.last.applied!==false;
    el.setAttribute('data-ad-status',ok?'APPLIED':'NOT_APPLIED');
    el.textContent=ok?'✓':((S.last&&S.last.issues&&S.last.issues.length)
      ?S.last.issues[0].code:'—'); }
  function diag(cfg){
    const el=$('adDiagOut'); if(!el||!cfg) return;
    if(!$('adDiagnostic').checked){ el.textContent=''; return; }
    const d=cfg.diagnostic, c=cfg.visual_request_coverage;
    const rows=(d.features||[]).map(f=>f.feature+' → '+f.status);
    el.textContent=rows.join('\n')
      +(rows.length?'\n':'')+c.name+': '+c.represented+'/'+c.requested; }
  function compare(mode){
    if(typeof window!=='undefined'&&window.ACS
        &&typeof window.ACS.adMode==='function')
      return window.ACS.adMode(mode);
    return {applied:false,mode:mode,
      issues:[adIssue('AD_THREE_UNAVAILABLE','ERROR','compare',
        'no 3D runtime in this environment')]}; }
  function init(){
    if(S.inited) return; S.inited=true;
    ['adDetail','adFacade','adContext','adStaging','adCamera']
      .forEach(id=>{ const el=$(id); if(!el) return;
        el.onchange=()=>{ S[{adDetail:'detail',adFacade:'facade',
          adContext:'context',adStaging:'staging',adCamera:'camera'}[id]]
          =el.value; }; });
    $('adApplyBtn').onclick=apply;
    $('adCompareE').onclick=()=>compare('ENGINEERING');
    $('adCompareP').onclick=()=>compare('PBR');
    $('adCompareA').onclick=()=>compare('ARCHITECTURAL');
    $('adClose').onclick=close;
    render(); }
  function open(){ init(); $('adPanel').classList.add('on'); }
  function close(){ $('adPanel').classList.remove('on'); }
  function setLanguage(l){
    if(l==='ar'||l==='en'){ S.lang=l; if(S.inited) render(); } }
  function setRequestText(t){ S.requestText=String(t||''); }
  return {open:open,close:close,init:init,apply:apply,
    setLanguage:setLanguage,setRequestText:setRequestText,
    currentConfig:currentConfig,compare:compare,
    state:()=>({lang:S.lang,detail:S.detail,facade:S.facade,
      context:S.context,staging:S.staging,camera:S.camera}),
    last:()=>S.last};
})();

if(typeof window!=='undefined'){
  window.ACS=window.ACS||{};
  window.ACS.archdetail={
    spec:()=>JSON.parse(JSON.stringify(ACS_ARCHDETAIL_SPEC)),
    material:adMaterial,variation:adVariation,
    detailProfile:adDetailProfile,classifyDetail:adClassifyDetail,
    objectAuthority:adObjectAuthority,facadeZoning:adFacadeZoning,
    windowAssembly:adWindowAssembly,doorVisual:adDoorVisual,
    balconyVisual:adBalconyVisual,led:adLed,stagingPlan:adStagingPlan,
    objectRecipe:adObjectRecipe,placement:adPlacement,
    vehiclesToBays:adVehiclesToBays,parking:adParking,
    kitchenLayout:adKitchenLayout,environment:adEnvironment,
    camera:adCamera,autoPresentation:adAutoPresentation,
    interpret:adInterpret,diagnostic:adDiagnostic,coverage:adCoverage,
    config:adConfig,captureMetadata:adCaptureMetadata,panel:AD};
}
"""

CSS = r"""
#adPanel{position:fixed;left:12px;bottom:12px;z-index:60;display:none;
  background:#10141c;color:#dfe5ee;border:1px solid #2a3242;
  border-radius:10px;padding:10px 12px;width:270px;max-height:72vh;
  overflow:auto;font:12px/1.5 system-ui,sans-serif;direction:rtl}
#adPanel.on{display:block}
#adPanel .ad-h{display:flex;justify-content:space-between;
  align-items:center;margin-bottom:6px;font-weight:700}
#adPanel label{display:block;margin:6px 0 2px;color:#9fb0c8}
#adPanel select{width:100%;background:#1a2230;color:#dfe5ee;
  border:1px solid #2a3242;border-radius:6px;padding:4px}
#adPanel .ad-note{color:#7d8aa0;margin-top:8px;font-size:11px}
#adPanel .ad-row{display:flex;gap:6px;margin-top:8px}
#adPanel button{background:#233047;color:#dfe5ee;border:0;
  border-radius:6px;padding:5px 10px;cursor:pointer;flex:1}
#adPanel #adStatus{margin-inline-start:6px;color:#8fd18f}
#adPanel #adDiagOut{white-space:pre-wrap;color:#b9c6da;margin-top:6px;
  font-size:11px}
"""

DOM = r"""
<div id="adPanel" data-ad="panel">
  <div class="ad-h"><span id="adTitle"></span>
    <button id="adClose" style="flex:0 0 auto">×</button></div>
  <label id="adDetailLbl"></label><select id="adDetail"></select>
  <label id="adFacadeLbl"></label><select id="adFacade"></select>
  <label id="adContextLbl"></label><select id="adContext"></select>
  <label id="adStagingLbl"></label><select id="adStaging"></select>
  <label id="adCameraLbl"></label><select id="adCamera"></select>
  <label><input type="checkbox" id="adDiagnostic">
    <span id="adDiagLbl"></span></label>
  <div class="ad-row"><button id="adApplyBtn">✓</button>
    <span id="adStatus" data-ad-status="NOT_APPLIED">—</span></div>
  <div class="ad-row"><span id="adCompareLbl"></span></div>
  <div class="ad-row">
    <button id="adCompareE" data-ad-compare="ENGINEERING">E</button>
    <button id="adCompareP" data-ad-compare="PBR">P</button>
    <button id="adCompareA" data-ad-compare="ARCHITECTURAL">A</button></div>
  <div id="adDiagOut"></div>
  <div class="ad-note" id="adReadonly"></div>
</div>
"""


def _replace(page, begin, end, block, anchor, after_anchor):
    if begin in page and end in page:
        a = page.index(begin)
        b = page.index(end) + len(end)
        tail = page[b:]
        if tail.startswith("\n"):
            tail = tail[1:]
        return page[:a] + block + tail, "replaced"
    if anchor not in page:
        raise SystemExit("anchor not found: %s" % anchor)
    i = page.index(anchor)
    if after_anchor:
        i += len(anchor)
        return page[:i] + "\n" + block + page[i:], "inserted"
    return page[:i] + block + "\n" + page[i:], "inserted"


def main():
    page = _read(PAGE)
    body = BODY.replace("__SPEC__", SPEC_JS)
    js_block = JS_BEGIN + "\n" + body + "\n" + PANEL + "\n" + JS_END + "\n"
    css_block = CSS_BEGIN + "\n" + CSS + "\n" + CSS_END + "\n"
    dom_block = DOM_BEGIN + "\n" + DOM + "\n" + DOM_END + "\n"

    page, a1 = _replace(page, CSS_BEGIN, CSS_END, css_block, CSS_ANCHOR, True)
    page, a2 = _replace(page, DOM_BEGIN, DOM_END, dom_block, DOM_ANCHOR, True)
    page, a3 = _replace(page, JS_BEGIN, JS_END, js_block, JS_ANCHOR, True)

    bridge = _read(os.path.join(HERE, "_archdetail_bridge_block.js"))
    bridge_block = BRIDGE_A + "\n" + bridge + "\n" + BRIDGE_B + "\n"
    if BRIDGE_A in page and BRIDGE_B in page:
        a = page.index(BRIDGE_A)
        b = page.index(BRIDGE_B) + len(BRIDGE_B)
        tail = page[b:]
        if tail.startswith("\n"):
            tail = tail[1:]
        page = page[:a] + bridge_block + tail
        a4 = "replaced"
    else:
        if BRIDGE_ANCHOR not in page:
            raise SystemExit("bridge anchor not found")
        i = page.index(BRIDGE_ANCHOR) + len(BRIDGE_ANCHOR)
        page = page[:i] + "\n" + bridge_block + page[i:]
        a4 = "inserted"

    for m in (JS_BEGIN, JS_END, CSS_BEGIN, CSS_END, DOM_BEGIN, DOM_END,
              BRIDGE_A, BRIDGE_B):
        if page.count(m) != 1:
            raise SystemExit("marker not unique after injection: %s" % m)

    with io.open(PAGE, "w", encoding="utf-8") as f:
        f.write(page)
    print("archdetail browser layer: css=%s dom=%s js=%s bridge=%s"
          % (a1, a2, a3, a4))


if __name__ == "__main__":
    main()
