/* ============================================================================
   tools/frontend_analyze.js — تحليل نطاق الوحدة الضخمة قبل تفكيكها (F-09).
   لا يعدّل شيئاً. يقرأ نصّ الوحدة، ويقسّمه إلى مقاطع عند حدود الكتل المولَّدة،
   ثمّ يحسب لكل مقطع — بمحلّل نحويّ حقيقي لا بتعبير نمطي —:
     • التصريحات على المستوى الأعلى (ما يُصدِّره)
     • المعرّفات الحرّة (ما يحتاج استيراده)
   المخرج JSON يُستعمل لتوليد قوائم import/export ميكانيكياً، فلا يُخمَّن ربط.

   المحلّل: حزمة Babel المضمّنة في playwright (لا شبكة، لا تثبيت).
   ============================================================================ */
'use strict';
const fs = require('fs');
const path = require('path');
const ROOT = path.resolve(__dirname, '..');
const B = require(path.join(ROOT, 'node_modules', 'playwright', 'lib',
                            'transform', 'babelBundle.js'));

function readIndex(file) {
  return fs.readFileSync(file || path.join(ROOT, 'public', 'index.html'), 'utf8');
}

/* حدود عنصر <script type="module"> — لا نعتمد على تعبير نمطي على كامل الملفّ،
   لأن داخل الوحدة سلاسل تحتوي "</script" حرفياً (قوائم رموز ممنوعة). */
function moduleBody(html) {
  const open = html.indexOf('<script type="module">');
  if (open < 0) return null;
  const bodyStart = html.indexOf('\n', open) + 1;
  const end = html.indexOf('\n</script>', bodyStart);
  return { start: bodyStart, end, code: html.slice(bodyStart, end) };
}

/* الكتل المولَّدة داخل الوحدة: اسمها وحدودها */
function generatedBlocks(code) {
  const out = [];
  const re = /\/\* ===== (?!END )(ACS [A-Za-z0-9 \-_.]+?)\s*(?:\((?:generated by )?([^)]*)\))?\s*=====/g;
  let m;
  while ((m = re.exec(code))) {
    const name = m[1].trim();
    const endMark = '/* ===== END ' + name + ' ===== */';
    const endAt = code.indexOf(endMark, m.index);
    if (endAt < 0) continue;
    out.push({ name, generator: (m[2] || '').trim() || null,
               start: m.index, end: endAt + endMark.length });
  }
  out.sort((a, b) => a.start - b.start);
  /* أزل المتداخل (كتلة داخل كتلة) */
  const flat = [];
  for (const b of out) {
    if (flat.length && b.start < flat[flat.length - 1].end) continue;
    flat.push(b);
  }
  return flat;
}

function segments(code) {
  const blocks = generatedBlocks(code);
  const segs = [];
  let cur = 0;
  for (const b of blocks) {
    if (b.start > cur) segs.push({ kind: 'handwritten', name: 'hand_' + segs.length,
                                   start: cur, end: b.start });
    segs.push({ kind: 'generated', name: b.name, generator: b.generator,
                start: b.start, end: b.end });
    cur = b.end;
  }
  if (cur < code.length) segs.push({ kind: 'handwritten', name: 'hand_' + segs.length,
                                     start: cur, end: code.length });
  return segs.filter(s => code.slice(s.start, s.end).trim().length > 0);
}

/* التصريحات العليا والمعرّفات الحرّة لمقطع — بتحليل نحويّ */
function analyse(src, label) {
  let ast;
  try {
    /* توقيع playwright: babelParse(code, filename, isModule) */
    ast = B.babelParse(src,
      String(label).replace(/[^A-Za-z0-9_.-]/g, '_') + '.js', true);
  } catch (e) {
    return { label, parse_error: String(e.message).slice(0, 240) };
  }
  const declared = [];
  const imported = [];
  let programScope = null;
  B.traverse(ast, {
    Program(p) {
      programScope = p.scope;
      p.stop();
    }
  });
  /* أعِد المرور لجمع الارتباطات بعد بناء النطاق */
  let globals = [];
  B.traverse(ast, {
    Program(p) {
      const b = p.scope.bindings;
      for (const k of Object.keys(b)) {
        if (b[k].kind === 'module') imported.push(k); else declared.push(k);
      }
      globals = Object.keys(p.scope.globals || {});
      p.stop();
    }
  });
  /* هل يُستعمل أي معرّف حرّ وقت تقييم الوحدة (خارج أي دالّة)؟ ذلك وحده ما
     يجعل الدورة بين وحدات ES خطرة (TDZ). الاستعمال داخل دالّة آمن. */
  const topLevelUse = {};
  const written = {};
  const G = new Set(globals);
  B.traverse(ast, {
    ReferencedIdentifier(p) {
      const n = p.node.name;
      if (!G.has(n)) return;
      if (p.getFunctionParent()) return;               /* داخل دالّة: آمن */
      topLevelUse[n] = (topLevelUse[n] || 0) + 1;
    },
    AssignmentExpression(p) {
      const left = p.node.left;
      if (left && left.type === 'Identifier' && G.has(left.name))
        written[left.name] = (written[left.name] || 0) + 1;
    },
    UpdateExpression(p) {
      const a = p.node.argument;
      if (a && a.type === 'Identifier' && G.has(a.name))
        written[a.name] = (written[a.name] || 0) + 1;
    }
  });
  return { label, declared: declared.sort(), imported: imported.sort(),
           free: globals.sort(),
           free_at_evaluation_time: Object.keys(topLevelUse).sort(),
           free_written: Object.keys(written).sort(),
           bytes: Buffer.byteLength(src, 'utf8'),
           lines: src.split('\n').length };
}

/* أسماء بيئة المتصفّح المسموح أن تبقى حرّة */
const BROWSER_GLOBALS = new Set(String(fs.readFileSync(
  path.join(__dirname, 'frontend_globals.txt'), 'utf8')).split('\n')
  .map(s => s.trim()).filter(s => s && !s.startsWith('#')));

function main() {
  const file = process.argv[2];
  const html = readIndex(file);
  const mod = moduleBody(html);
  if (!mod) { console.error('no module script found'); process.exit(2); }
  const segs = segments(mod.code);
  const result = { module_bytes: Buffer.byteLength(mod.code, 'utf8'),
                   segments: [] };
  const declaredSoFar = new Set();
  for (const s of segs) {
    const src = mod.code.slice(s.start, s.end);
    const a = analyse(src, s.name);
    a.kind = s.kind;
    a.generator = s.generator || null;
    if (!a.parse_error) {
      a.needs_from_earlier = a.free.filter(n => declaredSoFar.has(n)).sort();
      a.unresolved = a.free.filter(n => !declaredSoFar.has(n)
                                        && !BROWSER_GLOBALS.has(n)).sort();
      a.declared.forEach(n => declaredSoFar.add(n));
      a.imported.forEach(n => declaredSoFar.add(n));
    }
    result.segments.push(a);
  }
  const out = process.env.ACS_ANALYSIS
    || path.join(ROOT, 'tests', 'performance', 'frontend_analysis.json');
  fs.mkdirSync(path.dirname(out), { recursive: true });
  fs.writeFileSync(out, JSON.stringify(result, null, 1) + '\n');
  for (const s of result.segments) {
    if (s.parse_error) { console.log('  PARSE ERROR %s: %s', s.label, s.parse_error); continue; }
    console.log([s.label.padEnd(28), String(s.kind).padEnd(11),
                 String(s.bytes).padStart(8) + 'B',
                 'decl=' + String(s.declared.length).padEnd(4),
                 'free=' + String(s.free.length).padEnd(4),
                 'earlier=' + String(s.needs_from_earlier.length).padEnd(4),
                 'unresolved=' + s.unresolved.length,
                 'evalTimeFree=' + s.free_at_evaluation_time.length].join('  '));
    if (s.unresolved.length) console.log('       unresolved: ' + s.unresolved.join(', '));
    if (s.free_at_evaluation_time.length)
      console.log('       used at evaluation time: ' + s.free_at_evaluation_time.join(', '));
    if (s.free_written && s.free_written.length)
      console.log('       ASSIGNED (mutable across segments): ' + s.free_written.join(', '));
  }
  console.log('analysis ->', out);
}

module.exports = { readIndex, moduleBody, generatedBlocks, segments, analyse };
if (require.main === module) main();
